/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *__fastcall xreg_open(unsigned int a1, __off_t a2);
int __fastcall xreg_close(int a1, int a2, int a3);
int __fastcall xregr(unsigned int a1);
int __fastcall xdummy_regw(unsigned int a1, unsigned int a2);
int __fastcall xregw(int result, unsigned int a2);
int __fastcall xreg_wait(int result, unsigned int a2, unsigned int a3);
// int open(const char *file, int oflag, ...);
// int printf(const char *format, ...);
// void *mmap(void *addr, size_t len, int prot, int flags, int fd, __off_t offset);
// int munmap(void *addr, size_t len);
// int *_errno_location(void);
// char *strerror(int errnum);
// int fprintf(FILE *stream, const char *format, ...);
// void exit(int status);
// int close(int fd);

//-------------------------------------------------------------------------
// Data declarations

int dev_fd; // weak
int reg_base; // weak
// extern struct _IO_FILE *stderr;


//----- (00000004) --------------------------------------------------------
void *__fastcall xreg_open(unsigned int a1, __off_t a2)
{
  unsigned int v2; // r4
  int fd; // r0
  void *result; // r0
  __off_t v5; // [sp+4h] [bp-14h]

  v5 = a2;
  v2 = a1;
  fd = open("/dev/mem", 2050);
  dev_fd = fd;
  if ( fd < 0 )
    return (void *)printf("open(/dev/mem) failed.[%x]", v2);
  result = mmap(0, 0x20000u, 3, 1, fd, v5);
  reg_base = (int)result;
  return result;
}
// 230: using guessed type int dev_fd;
// 234: using guessed type int reg_base;

//----- (0000009C) --------------------------------------------------------
int __fastcall xreg_close(int a1, int a2, int a3)
{
  FILE *stream; // ST0C_4
  int v4; // r4
  int *v5; // r0
  char *v6; // r0
  int result; // r0
  int v8; // [sp+8h] [bp-10h]

  v8 = a3;
  if ( munmap((void *)reg_base, 0x20000u) == -1 )
  {
    stream = (FILE *)stderr;
    v4 = *_errno_location();
    v5 = _errno_location();
    v6 = strerror(*v5);
    fprintf(stream, "Error at line %d, file %s (%d) [%s]\n", 48, "devreg.cpp", v4, v6, v8);
    exit(1);
  }
  result = dev_fd;
  if ( dev_fd )
    result = close(dev_fd);
  return result;
}
// 230: using guessed type int dev_fd;
// 234: using guessed type int reg_base;

//----- (00000158) --------------------------------------------------------
int __fastcall xregr(unsigned int a1)
{
  return *(_DWORD *)(reg_base + a1);
}
// 234: using guessed type int reg_base;

//----- (0000017C) --------------------------------------------------------
int __fastcall xdummy_regw(unsigned int a1, unsigned int a2)
{
  return printf("%04X,%08X\n", a1, a2);
}

//----- (000001A0) --------------------------------------------------------
int __fastcall xregw(int result, unsigned int a2)
{
  *(_DWORD *)(reg_base + result) = a2;
  return result;
}
// 234: using guessed type int reg_base;

//----- (000001C4) --------------------------------------------------------
int __fastcall xreg_wait(int result, unsigned int a2, unsigned int a3)
{
  int v3; // r12

  v3 = 0;
  while ( 1 )
  {
    ++v3;
    if ( (*(_DWORD *)(reg_base + result) & a2) == a3 )
      break;
    if ( v3 == 899 )
      return printf("\n# wait time out: %02X:%02X v:%02X loop:%d\n", result);
  }
  return result;
}
// 234: using guessed type int reg_base;

// ALL OK, 6 function(s) have been successfully decompiled
