/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

ncnn::Mat *__fastcall ncnn::Mat::~Mat(ncnn::Mat *this);
int __fastcall nna_get_buffer_viraddr(unsigned int a1);
int __fastcall nna_setup_buffer(unsigned int, int, unsigned __int64, int, int); // idb
int __fastcall nna_fd_set_ceil_width(int a1);
int __fastcall nna_fd_set_runonly(int a1);
int __fastcall nna_hd_set_size(int a1, int a2);
int __fastcall nna_fd_set_factor(int a1, float a2);
int __fastcall nna_fd_set_minface(int a1);
int __fastcall nna_fd_set_threshold(int *a1, int *a2);
int __fastcall nna_hd_set_threshold(int a1, int a2);
int __fastcall nna_fd_set_fixedpoint(int *a1);
int __fastcall nna_hd_set_fixedpoint(int *a1);
void *__fastcall nna_img_cut_c1(unsigned __int8 *a1, int a2, int a3, ncnn *this, unsigned __int8 *a5, unsigned __int8 *a6, int a7, int a8, int a9);
int __fastcall nna_img_resize_c1(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); // weak
int __fastcall nna_resize_once(unsigned int a1, int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10);
void __fastcall nna_resize_cpu(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
void **__fastcall std::_Vector_base<Bbox,std::allocator<Bbox>>::~_Vector_base(void **a1);
int __fastcall nna_fd_run(int a1, signed int a2, signed int a3, int a4, int a5);
int __fastcall nna_hd_run_mini(int a1, int a2, int a3, int a4, int a5);
int __fastcall nna_ypr_run(int a1, int a2, int a3, int a4, int a5);
void **__fastcall FDNET::~FDNET(FDNET *this);
int GLOBAL__sub_I_fd_lib_cpp();
// void free(void *ptr);
// _DWORD __cdecl FDNET::GetBuffer_VirAddr(FDNET *__hidden this, unsigned int); weak
// int puts(const char *s);
// _DWORD __cdecl FDNET::SetBuffer(FDNET *__hidden this, unsigned int, unsigned __int64, int); idb
// _DWORD __cdecl FDNET::SetCeilImageWidth(FDNET *__hidden this, int); weak
// _DWORD __cdecl FDNET::SetRunOnly(FDNET *__hidden this, int); weak
// _DWORD __cdecl FDNET::SetHdSize(FDNET *__hidden this, int, int); weak
// _DWORD __cdecl FDNET::SetFactor(FDNET *__hidden this, float); weak
// _DWORD __cdecl FDNET::SetMinFace(FDNET *__hidden this, int); weak
// _DWORD __cdecl FDNET::SetThreshold(FDNET *__hidden this, float *, float *); idb
// _DWORD __cdecl FDNET::SetHdThreshold(FDNET *__hidden this, float, float); weak
// _DWORD __cdecl FDNET::SetFdFixedPoint(FDNET *__hidden this, int *); weak
// _DWORD __cdecl FDNET::SetHdFixedPoint(FDNET *__hidden this, int *); weak
// void *memcpy(void *dest, const void *src, size_t n);
// _DWORD __cdecl ncnn::copy_cut_border_c1(ncnn *__hidden this, const unsigned __int8 *, int, int, unsigned __int8 *, int, int, int, int); idb
// int __fastcall nna_resize(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// void *malloc(size_t size);
// int __cdecl xramcpy(_DWORD, _DWORD); weak
// void __cdecl operator delete(void *); idb
// int printf(const char *format, ...);
// int __fastcall FDNET::NNA_FD_RUN_IMG(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall FDNET::NNA_HD_RUN_IMG_MINI(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall FDNET::NNA_HD_RUN_IMG(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// _DWORD std::ios_base::Init::Init(std::ios_base::Init *__hidden this); idb
// int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD); weak
// _DWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN std::__ioinit; // weak
int fdnet; // weak
int dword_C14; // weak
int dword_C18; // weak
int dword_C1C; // weak
int dword_C20; // weak
int dword_C24; // weak
int dword_C28; // weak
int dword_C2C; // weak
int dword_C30; // weak
_UNKNOWN unk_67EE0; // weak
_UNKNOWN unk_67EEC; // weak
_UNKNOWN unk_67EF0; // weak
_UNKNOWN unk_67EF4; // weak
_UNKNOWN unk_67EF8; // weak
_UNKNOWN unk_67EFC; // weak
_UNKNOWN unk_67F00; // weak
int dword_67F04; // weak
int dword_67F1C; // weak
int dword_67F20; // weak
_UNKNOWN unk_67F24; // weak
_UNKNOWN unk_67F28; // weak
_UNKNOWN unk_67F2C; // weak
_UNKNOWN unk_67F30; // weak
_UNKNOWN unk_67F34; // weak
_UNKNOWN unk_67F38; // weak
_UNKNOWN unk_67F3C; // weak
_UNKNOWN unk_67F40; // weak
_UNKNOWN unk_67F44; // weak
int dword_67F48; // weak
int dword_67F4C; // weak
int dword_67F50; // weak
int dword_67F54; // weak
_UNKNOWN unk_67F58; // weak
int dword_67F64; // weak
int dword_67F68; // weak
int dword_67F6C; // weak
int nna_img; // weak
int dword_67F74; // weak
int dword_67F78; // weak
int dword_67F7C; // weak
int dword_67F80; // weak
int dword_67F84; // weak
int dword_67F88; // weak
// extern _UNKNOWN _dso_handle; weak


//----- (00000004) --------------------------------------------------------
ncnn::Mat *__fastcall ncnn::Mat::~Mat(ncnn::Mat *this)
{
  unsigned int *v1; // r3
  ncnn::Mat *v2; // r4
  unsigned int v3; // r2
  int v4; // r3

  v1 = (unsigned int *)*((_DWORD *)this + 2);
  v2 = this;
  if ( v1 )
  {
    __dmb(0xBu);
    do
      v3 = __ldrex(v1);
    while ( __strex(v3 - 1, v1) );
    __dmb(0xBu);
    if ( v3 == 1 )
    {
      v4 = *((_DWORD *)this + 1);
      if ( v4 )
        free(*(void **)(v4 - 4));
    }
  }
  return v2;
}

//----- (00000074) --------------------------------------------------------
int __fastcall nna_get_buffer_viraddr(unsigned int a1)
{
  return FDNET::GetBuffer_VirAddr((FDNET *)&fdnet, a1);
}
// C10: using guessed type int fdnet;
// 67FC8: using guessed type _DWORD __cdecl FDNET::GetBuffer_VirAddr(FDNET *__hidden this, unsigned int);

//----- (000000B0) --------------------------------------------------------
int __fastcall nna_setup_buffer(unsigned int a1, int a2, unsigned __int64 a3, int a4, int a5)
{
  unsigned int v5; // r6
  unsigned __int64 v6; // r8

  v5 = a1;
  v6 = a3;
  if ( a4 < 0x200000 )
    puts("\n#!!! buffer size at least 2MB ");
  return FDNET::SetBuffer((FDNET *)&fdnet, v5, v6, a4);
}
// C10: using guessed type int fdnet;

//----- (00000124) --------------------------------------------------------
int __fastcall nna_fd_set_ceil_width(int a1)
{
  return FDNET::SetCeilImageWidth((FDNET *)&fdnet, a1);
}
// C10: using guessed type int fdnet;
// 67FD8: using guessed type _DWORD __cdecl FDNET::SetCeilImageWidth(FDNET *__hidden this, int);

//----- (00000160) --------------------------------------------------------
int __fastcall nna_fd_set_runonly(int a1)
{
  return FDNET::SetRunOnly((FDNET *)&fdnet, a1);
}
// C10: using guessed type int fdnet;
// 67FDC: using guessed type _DWORD __cdecl FDNET::SetRunOnly(FDNET *__hidden this, int);

//----- (0000019C) --------------------------------------------------------
int __fastcall nna_hd_set_size(int a1, int a2)
{
  return FDNET::SetHdSize((FDNET *)&fdnet, a1, a2);
}
// C10: using guessed type int fdnet;
// 67FE0: using guessed type _DWORD __cdecl FDNET::SetHdSize(FDNET *__hidden this, int, int);

//----- (000001DC) --------------------------------------------------------
int __fastcall nna_fd_set_factor(int a1, float a2)
{
  return FDNET::SetFactor((FDNET *)&fdnet, a2);
}
// C10: using guessed type int fdnet;
// 67FE4: using guessed type _DWORD __cdecl FDNET::SetFactor(FDNET *__hidden this, float);

//----- (00000228) --------------------------------------------------------
int __fastcall nna_fd_set_minface(int a1)
{
  return FDNET::SetMinFace((FDNET *)&fdnet, a1);
}
// C10: using guessed type int fdnet;
// 67FE8: using guessed type _DWORD __cdecl FDNET::SetMinFace(FDNET *__hidden this, int);

//----- (00000264) --------------------------------------------------------
int __fastcall nna_fd_set_threshold(int *a1, int *a2)
{
  int v2; // r3
  float v3; // s15
  float *v4; // lr
  float v6[3]; // [sp+8h] [bp-28h]
  float v7; // [sp+14h] [bp-1Ch]

  v2 = 0;
  do
  {
    v3 = (float)a2[v2];
    v6[v2] = (float)a1[v2] / 100.0;
    v4 = (float *)((char *)&v7 + v2 * 4);
    ++v2;
    *v4 = v3 / 100.0;
  }
  while ( v2 != 3 );
  return FDNET::SetThreshold((FDNET *)&fdnet, v6, &v7);
}
// C10: using guessed type int fdnet;
// 264: using guessed type float var_28[3];

//----- (000002F8) --------------------------------------------------------
int __fastcall nna_hd_set_threshold(int a1, int a2)
{
  return FDNET::SetHdThreshold((FDNET *)&fdnet, *(float *)&a2, COERCE_FLOAT(ncnn::Mat::~Mat));
}
// C10: using guessed type int fdnet;
// 67FF0: using guessed type _DWORD __cdecl FDNET::SetHdThreshold(FDNET *__hidden this, float, float);

//----- (00000350) --------------------------------------------------------
int __fastcall nna_fd_set_fixedpoint(int *a1)
{
  return FDNET::SetFdFixedPoint((FDNET *)&fdnet, a1);
}
// C10: using guessed type int fdnet;
// 67FF4: using guessed type _DWORD __cdecl FDNET::SetFdFixedPoint(FDNET *__hidden this, int *);

//----- (0000038C) --------------------------------------------------------
int __fastcall nna_hd_set_fixedpoint(int *a1)
{
  return FDNET::SetHdFixedPoint((FDNET *)&fdnet, a1);
}
// C10: using guessed type int fdnet;
// 67FF8: using guessed type _DWORD __cdecl FDNET::SetHdFixedPoint(FDNET *__hidden this, int *);

//----- (000003D8) --------------------------------------------------------
void *__fastcall nna_img_cut_c1(unsigned __int8 *a1, int a2, int a3, ncnn *this, unsigned __int8 *a5, unsigned __int8 *a6, int a7, int a8, int a9)
{
  int v9; // r12
  void *result; // r0

  v9 = a3 - a8 - 1;
  if ( &a6[v9 - 1 + (_DWORD)a5 + a2 - a7] )
    result = (void *)ncnn::copy_cut_border_c1(
                       (ncnn *)a1,
                       (const unsigned __int8 *)a2,
                       a3,
                       (int)this,
                       a6,
                       v9,
                       (int)a5,
                       a2 - a7 - 1,
                       a9);
  else
    result = memcpy((void *)this, a1, a2 * a3);
  return result;
}

//----- (00000454) --------------------------------------------------------
int __fastcall nna_resize_once(unsigned int a1, int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10)
{
  int v11; // [sp+10h] [bp-18h]

  return nna_resize(a1, a2, a3, a4, a5, a6, &v11, 1, a7, a8, a9, a10);
}
// 6800C: using guessed type int __fastcall nna_resize(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (000004B4) --------------------------------------------------------
void __fastcall nna_resize_cpu(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v8; // r6
  int v9; // r4
  void *v10; // r9
  ncnn *v11; // r8
  unsigned __int8 *v12; // r7
  int v13; // r5
  int v14; // r10
  int v15; // r11
  int v16; // ST14_4
  int v17; // ST10_4
  int v18; // [sp+1Ch] [bp-44h]
  int v19; // [sp+20h] [bp-40h]

  v8 = a1;
  v18 = a2;
  v19 = a3;
  v9 = a7;
  v10 = malloc(0x1FA400u);
  v11 = (ncnn *)malloc(0x1FA400u);
  v12 = (unsigned __int8 *)malloc(0x1FA400u);
  xramcpy(v12, (signed int)v12 >> 31);
  v13 = 0;
  while ( 1 )
  {
    v9 += 16;
    if ( v13 >= a8 )
      break;
    v14 = *(_DWORD *)(v9 - 16);
    ++v13;
    v15 = *(_DWORD *)(v9 - 12);
    v16 = *(_DWORD *)(v9 - 4);
    nna_img_cut_c1(
      v12,
      a5,
      a6,
      v11,
      *(unsigned __int8 **)(v9 - 16),
      *(unsigned __int8 **)(v9 - 12),
      *(_DWORD *)(v9 - 8),
      *(_DWORD *)(v9 - 4),
      *(_DWORD *)(v9 - 8));
    nna_img_resize_c1(v11, v17 - v14 + 1, v16 - v15 + 1, v10, v18, v19);
    xramcpy(v8, 0);
    v8 += v19 * v18;
  }
  free(v10);
  free((void *)v11);
  free(v12);
}
// 444: using guessed type int __fastcall nna_img_resize_c1(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 68014: using guessed type int __cdecl xramcpy(_DWORD, _DWORD);

//----- (00000640) --------------------------------------------------------
void **__fastcall std::_Vector_base<Bbox,std::allocator<Bbox>>::~_Vector_base(void **a1)
{
  void **v1; // r4
  void *v2; // r0

  v1 = a1;
  v2 = *a1;
  if ( v2 )
    operator delete(v2);
  return v1;
}

//----- (0000066C) --------------------------------------------------------
int __fastcall nna_fd_run(int a1, signed int a2, signed int a3, int a4, int a5)
{
  int v5; // r4
  int v6; // r3
  int v7; // r0
  int i; // r2
  _BOOL4 v9; // r1
  int v10; // r4
  int v12; // [sp+14h] [bp-24h]
  int v13; // [sp+18h] [bp-20h]
  int v14; // [sp+1Ch] [bp-1Ch]

  v5 = a4;
  v12 = 0;
  v13 = 0;
  v14 = 0;
  if ( a3 <= 1080 && a2 <= 1920 )
  {
    FDNET::NNA_FD_RUN_IMG(&fdnet, a1, a2, a3, &v12);
    v6 = v5;
    v7 = v13;
    v10 = 0;
    for ( i = v12; ; *(_DWORD *)(v6 - 4) = *(_DWORD *)(i - 64) )
    {
      v6 += 20;
      v9 = v10 > a5;
      if ( v7 == i )
        v9 = 1;
      i += 80;
      if ( v9 )
        break;
      ++v10;
      *(_DWORD *)(v6 - 20) = (signed int)(float)(*(float *)(i - 80) * 100.0);
      *(_DWORD *)(v6 - 16) = *(_DWORD *)(i - 76);
      *(_DWORD *)(v6 - 12) = *(_DWORD *)(i - 72);
      *(_DWORD *)(v6 - 8) = *(_DWORD *)(i - 68);
    }
  }
  else
  {
    printf("\n ---FD img [%4d %4d]");
    v10 = 0;
  }
  std::_Vector_base<Bbox,std::allocator<Bbox>>::~_Vector_base((void **)&v12);
  return v10;
}
// C10: using guessed type int fdnet;
// 68024: using guessed type int __fastcall FDNET::NNA_FD_RUN_IMG(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (000007A0) --------------------------------------------------------
int __fastcall nna_hd_run_mini(int a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4
  int v6; // r3
  int v7; // r0
  int v8; // r4
  int i; // r2
  unsigned int v10; // r1
  unsigned int v11; // r1
  int v13; // [sp+14h] [bp-1Ch]
  int v14; // [sp+18h] [bp-18h]
  int v15; // [sp+1Ch] [bp-14h]

  v5 = a4;
  v13 = 0;
  v14 = 0;
  v15 = 0;
  FDNET::NNA_HD_RUN_IMG_MINI(&fdnet, a1, a2, a3, &v13);
  v6 = v5;
  v7 = v14;
  v8 = 0;
  for ( i = v13; ; *(_DWORD *)(v6 - 4) = *(_DWORD *)(i - 64) )
  {
    v6 += 20;
    v10 = __clz(v7 - i);
    i += 80;
    v11 = v10 >> 5;
    if ( v8 > a5 )
      v11 |= 1u;
    if ( v11 )
      break;
    ++v8;
    *(_DWORD *)(v6 - 20) = (signed int)(float)(*(float *)(i - 80) * 100.0);
    *(_DWORD *)(v6 - 16) = *(_DWORD *)(i - 76);
    *(_DWORD *)(v6 - 12) = *(_DWORD *)(i - 72);
    *(_DWORD *)(v6 - 8) = *(_DWORD *)(i - 68);
  }
  std::_Vector_base<Bbox,std::allocator<Bbox>>::~_Vector_base((void **)&v13);
  return v8;
}
// C10: using guessed type int fdnet;
// 68030: using guessed type int __fastcall FDNET::NNA_HD_RUN_IMG_MINI(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (000008AC) --------------------------------------------------------
int __fastcall nna_ypr_run(int a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4
  int v6; // r3
  int v7; // r0
  int v8; // r4
  int i; // r2
  unsigned int v10; // r1
  unsigned int v11; // r1
  int v13; // [sp+14h] [bp-1Ch]
  int v14; // [sp+18h] [bp-18h]
  int v15; // [sp+1Ch] [bp-14h]

  v5 = a4;
  v13 = 0;
  v14 = 0;
  v15 = 0;
  FDNET::NNA_HD_RUN_IMG(&fdnet, a1, a2, a3, &v13);
  v6 = v5;
  v7 = v14;
  v8 = 0;
  for ( i = v13; ; *(_DWORD *)(v6 - 4) = *(_DWORD *)(i - 64) )
  {
    v6 += 20;
    v10 = __clz(v7 - i);
    i += 80;
    v11 = v10 >> 5;
    if ( v8 > a5 )
      v11 |= 1u;
    if ( v11 )
      break;
    ++v8;
    *(_DWORD *)(v6 - 20) = (signed int)(float)(*(float *)(i - 80) * 100.0);
    *(_DWORD *)(v6 - 16) = *(_DWORD *)(i - 76);
    *(_DWORD *)(v6 - 12) = *(_DWORD *)(i - 72);
    *(_DWORD *)(v6 - 8) = *(_DWORD *)(i - 68);
  }
  std::_Vector_base<Bbox,std::allocator<Bbox>>::~_Vector_base((void **)&v13);
  return v8;
}
// C10: using guessed type int fdnet;
// 68034: using guessed type int __fastcall FDNET::NNA_HD_RUN_IMG(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (000009C8) --------------------------------------------------------
void **__fastcall FDNET::~FDNET(FDNET *this)
{
  void **v1; // r4

  v1 = (void **)this;
  std::_Vector_base<Bbox,std::allocator<Bbox>>::~_Vector_base((void **)this + 6);
  std::_Vector_base<Bbox,std::allocator<Bbox>>::~_Vector_base(v1 + 3);
  std::_Vector_base<Bbox,std::allocator<Bbox>>::~_Vector_base(v1);
  return v1;
}

//----- (000009FC) --------------------------------------------------------
int GLOBAL__sub_I_fd_lib_cpp()
{
  std::ios_base::Init::Init((std::ios_base::Init *)&std::__ioinit);
  _aeabi_atexit(&std::__ioinit, &std::ios_base::Init::~Init, &_dso_handle);
  fdnet = 0;
  dword_C14 = 0;
  qmemcpy(&unk_67EE0, "fff?333?333?", 12);
  dword_C18 = 0;
  dword_C1C = 0;
  dword_C20 = 0;
  unk_67EEC = *(_DWORD *)"";
  unk_67EF0 = 1124007936;
  unk_67EF4 = 1124007936;
  dword_C24 = 0;
  dword_C28 = 0;
  dword_C2C = 0;
  unk_67EF8 = 1006632960;
  unk_67EFC = 1006632960;
  unk_67F00 = 1006632960;
  dword_C30 = 0;
  dword_67F04 = 12;
  dword_67F1C = 192;
  dword_67F20 = 108;
  unk_67F24 = 4;
  unk_67F28 = 8;
  unk_67F2C = 4;
  unk_67F30 = 9;
  unk_67F34 = 4;
  unk_67F38 = 9;
  unk_67F3C = 9;
  unk_67F40 = 3;
  unk_67F44 = -1;
  dword_67F48 = -1;
  dword_67F4C = 1;
  dword_67F50 = 1;
  dword_67F54 = 120;
  qmemcpy(&unk_67F58, "fff?333?333?", 12);
  dword_67F64 = 1061997773;
  dword_67F68 = 1058642330;
  dword_67F6C = 1045220557;
  _aeabi_atexit(&fdnet, FDNET::~FDNET, &_dso_handle);
  nna_img = 0;
  dword_67F74 = 0;
  dword_67F78 = 0;
  dword_67F7C = 0;
  dword_67F80 = 0;
  dword_67F84 = 0;
  dword_67F88 = 0;
  return _aeabi_atexit(&nna_img, ncnn::Mat::~Mat, &_dso_handle);
}
// C10: using guessed type int fdnet;
// C14: using guessed type int dword_C14;
// C18: using guessed type int dword_C18;
// C1C: using guessed type int dword_C1C;
// C20: using guessed type int dword_C20;
// C24: using guessed type int dword_C24;
// C28: using guessed type int dword_C28;
// C2C: using guessed type int dword_C2C;
// C30: using guessed type int dword_C30;
// 67F04: using guessed type int dword_67F04;
// 67F1C: using guessed type int dword_67F1C;
// 67F20: using guessed type int dword_67F20;
// 67F48: using guessed type int dword_67F48;
// 67F4C: using guessed type int dword_67F4C;
// 67F50: using guessed type int dword_67F50;
// 67F54: using guessed type int dword_67F54;
// 67F64: using guessed type int dword_67F64;
// 67F68: using guessed type int dword_67F68;
// 67F6C: using guessed type int dword_67F6C;
// 67F70: using guessed type int nna_img;
// 67F74: using guessed type int dword_67F74;
// 67F78: using guessed type int dword_67F78;
// 67F7C: using guessed type int dword_67F7C;
// 67F80: using guessed type int dword_67F80;
// 67F84: using guessed type int dword_67F84;
// 67F88: using guessed type int dword_67F88;
// 6803C: using guessed type int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD);
// 68044: using guessed type _DWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this);

// ALL OK, 21 function(s) have been successfully decompiled
