/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *__fastcall ncnn::fastMalloc(ncnn *this, unsigned int a2);
_DWORD *__fastcall ncnn::copy_make_border_image(_DWORD *result, _DWORD *a2, int a3, int a4, int a5);
_DWORD *__fastcall ncnn::copy_cut_border_image(_DWORD *result, _DWORD *a2, int a3, int a4);
void __fastcall ncnn::Mat::release(ncnn::Mat *this);
ncnn::Mat *__fastcall ncnn::Mat::operator=(ncnn::Mat *this, ncnn::Mat *a2);
void __fastcall ncnn::Mat::create(ncnn::Mat *this, int a2);
void __fastcall ncnn::Mat::create(ncnn::Mat *this, int a2, int a3);
void __fastcall ncnn::Mat::create(ncnn::Mat *this, int a2, int a3, int a4);
void __fastcall ncnn::resize_bilinear_image(ncnn *this, const ncnn::Mat *a2, ncnn::Mat *a3, int a4, int a5);
bool __fastcall ncnn::Mat::empty(ncnn::Mat *this);
int __fastcall ncnn::Mat::channel(int result, int a2, int a3);
int __fastcall ncnn::Mat::substract_mean_normalize(int result, const float *a2, const float *a3);
ncnn::Mat *__fastcall ncnn::Mat::from_float16(ncnn::Mat *this, const unsigned __int16 *a2, int a3);
void __fastcall ncnn::copy_make_border(ncnn *this, const ncnn::Mat *a2, ncnn::Mat *a3, int a4, int a5, int a6, int a7, int a8, float a9);
void __fastcall ncnn::copy_cut_border(ncnn *this, const ncnn::Mat *a2, ncnn::Mat *a3, int a4, int a5, int a6, int a7);
void __fastcall ncnn::resize_bilinear(ncnn *this, const ncnn::Mat *a2, ncnn::Mat *a3, int a4, int a5);
// void *malloc(size_t size);
// void *memcpy(void *dest, const void *src, size_t n);
// void free(void *ptr);
// _DWORD __cdecl operator new[](unsigned int); idb
// int _cxa_throw_bad_array_new_length(void); weak
// void __cdecl operator delete[](void *); idb


//----- (00000004) --------------------------------------------------------
void *__fastcall ncnn::fastMalloc(ncnn *this, unsigned int a2)
{
  void *result; // r0

  result = malloc((size_t)this + 20);
  if ( result )
  {
    *(_DWORD *)((((unsigned int)result + 19) & 0xFFFFFFF0) - 4) = result;
    result = (void *)(((unsigned int)result + 19) & 0xFFFFFFF0);
  }
  return result;
}

//----- (00000034) --------------------------------------------------------
_DWORD *__fastcall ncnn::copy_make_border_image(_DWORD *result, _DWORD *a2, int a3, int a4, int a5)
{
  int v5; // s0
  int v6; // r7
  int v7; // r11
  _DWORD *v8; // r6
  _DWORD *v9; // r5
  int v10; // r3
  int v11; // r4
  _DWORD *v12; // r2
  int v13; // r9
  int k; // r1
  int v15; // r10
  int v16; // r8
  int v17; // r4
  _DWORD *v18; // r2
  int l; // r3
  signed int v20; // r2
  int v21; // r2
  _DWORD *v22; // r1
  int v23; // r3
  int v24; // t1
  _DWORD *v25; // r2
  _DWORD *v26; // r2
  int m; // r3
  int v28; // r8
  _DWORD *v29; // r9
  int v30; // r10
  int i; // r3
  _DWORD *v32; // r2
  int v33; // r3
  signed int v34; // r2
  _DWORD *v35; // r1
  int v36; // r3
  int v37; // r2
  int v38; // t1
  _DWORD *v39; // r1
  int v40; // r9
  int v41; // r4
  _DWORD *v42; // r2
  int v43; // r3
  signed int v44; // r2
  _DWORD *v45; // r1
  int v46; // r3
  int v47; // r2
  int v48; // t1
  _DWORD *j; // r1
  int v50; // r2
  _DWORD *v51; // r6
  int v52; // r10
  _DWORD *v53; // r2
  int v54; // r3
  signed int v55; // r2
  int v56; // r2
  _DWORD *v57; // r1
  int v58; // r3
  int v59; // t1
  _DWORD *v60; // r1
  int v61; // [sp+4h] [bp-4Ch]
  int v62; // [sp+8h] [bp-48h]
  int v63; // [sp+Ch] [bp-44h]
  int v64; // [sp+10h] [bp-40h]
  int v65; // [sp+14h] [bp-3Ch]
  int v66; // [sp+18h] [bp-38h]

  v6 = a4;
  v7 = a2[3];
  v8 = (_DWORD *)result[1];
  v9 = result;
  v10 = a5;
  v61 = a3;
  v11 = a2[1];
  v66 = a2[4];
  if ( a5 )
  {
    if ( a5 == 1 )
    {
      v28 = v6 & ~(v6 >> 31);
      v29 = (_DWORD *)a2[1];
      v64 = 4 * v6;
      v30 = v28 - v6;
      v62 = 4 * v7;
      v65 = 4 * v28;
      for ( i = 0; ; i = v63 + 1 )
      {
        v63 = i;
        if ( i >= v61 )
          break;
        v32 = v29;
        v33 = 0;
        while ( v33 < v6 )
        {
          ++v33;
          *v32 = *v8;
          ++v32;
        }
        v34 = v9[3];
        if ( v34 > 11 )
        {
          result = memcpy(&v29[v64 / 4u], v8, 4 * v34);
          v36 = v28 + v9[3];
        }
        else
        {
          result = &v8[v30];
          v35 = &v29[v65 / 4u];
          v36 = v6 & ~(v6 >> 31);
          v37 = v6 + v34;
          while ( v36 < v37 )
          {
            v38 = *result;
            ++result;
            ++v36;
            *v35 = v38;
            ++v35;
          }
        }
        v39 = &v29[v36];
        while ( v36 < v7 )
        {
          ++v36;
          *v39 = v8[v9[3] - 1];
          ++v39;
        }
        v29 = (_DWORD *)((char *)v29 + v62);
      }
      v40 = v61 & ~(v61 >> 31);
      v41 = v11 + v62 * v40;
      while ( v40 < v61 + v9[4] )
      {
        v42 = (_DWORD *)v41;
        v43 = 0;
        while ( v43 < v6 )
        {
          ++v43;
          *v42 = *v8;
          ++v42;
        }
        v44 = v9[3];
        if ( v44 > 11 )
        {
          result = memcpy((void *)(v41 + v64), v8, 4 * v44);
          v46 = v28 + v9[3];
        }
        else
        {
          result = &v8[v30];
          v45 = (_DWORD *)(v41 + v65);
          v46 = v6 & ~(v6 >> 31);
          v47 = v6 + v44;
          while ( v46 < v47 )
          {
            v48 = *result;
            ++result;
            ++v46;
            *v45 = v48;
            ++v45;
          }
        }
        for ( j = (_DWORD *)(v41 + 4 * v46); ; ++j )
        {
          v50 = v9[3];
          if ( v46 >= v7 )
            break;
          ++v46;
          *j = v8[v50 - 1];
        }
        ++v40;
        v8 += v50;
        v41 += v62;
      }
      v51 = &v8[-v9[3]];
      v52 = (int)&v51[v30];
      while ( v40 < v66 )
      {
        v53 = (_DWORD *)v41;
        v54 = 0;
        while ( v54 < v6 )
        {
          ++v54;
          *v53 = *v51;
          ++v53;
        }
        v55 = v9[3];
        if ( v55 > 11 )
        {
          result = memcpy((void *)(v41 + v64), v51, 4 * v55);
          v58 = v28 + v9[3];
        }
        else
        {
          result = (_DWORD *)v52;
          v56 = v6 + v55;
          v57 = (_DWORD *)(v41 + v65);
          v58 = v6 & ~(v6 >> 31);
          while ( v58 < v56 )
          {
            v59 = *result;
            ++result;
            ++v58;
            *v57 = v59;
            ++v57;
          }
        }
        v60 = (_DWORD *)(v41 + 4 * v58);
        while ( v58 < v7 )
        {
          ++v58;
          *v60 = v51[v9[3] - 1];
          ++v60;
        }
        ++v40;
        v41 += v62;
      }
    }
  }
  else
  {
    v12 = (_DWORD *)a2[1];
    v13 = 4 * v7;
    while ( v10 < v61 )
    {
      result = v12;
      for ( k = 0; k < v7; ++k )
      {
        *result = v5;
        ++result;
      }
      v12 = (_DWORD *)((char *)v12 + v13);
      ++v10;
    }
    v15 = v6 & ~(v6 >> 31);
    v16 = v61 & ~(v61 >> 31);
    v17 = v11 + v13 * v16;
    while ( v16 < v61 + v9[4] )
    {
      v18 = (_DWORD *)v17;
      for ( l = 0; l < v6; ++l )
      {
        *v18 = v5;
        ++v18;
      }
      v20 = v9[3];
      if ( v20 > 11 )
      {
        result = memcpy((void *)(v17 + 4 * v6), v8, 4 * v20);
        v23 = v15 + v9[3];
      }
      else
      {
        v21 = v6 + v20;
        result = &v8[v15 - v6];
        v22 = (_DWORD *)(v17 + 4 * v15);
        v23 = v6 & ~(v6 >> 31);
        while ( v23 < v21 )
        {
          v24 = *result;
          ++result;
          ++v23;
          *v22 = v24;
          ++v22;
        }
      }
      v25 = (_DWORD *)(v17 + 4 * v23);
      while ( v23 < v7 )
      {
        *v25 = v5;
        ++v25;
        ++v23;
      }
      ++v16;
      v17 += v13;
      v8 += v9[3];
    }
    while ( v16 < v66 )
    {
      v26 = (_DWORD *)v17;
      for ( m = 0; m < v7; ++m )
      {
        *v26 = v5;
        ++v26;
      }
      v17 += v13;
      ++v16;
    }
  }
  return result;
}

//----- (00000444) --------------------------------------------------------
_DWORD *__fastcall ncnn::copy_cut_border_image(_DWORD *result, _DWORD *a2, int a3, int a4)
{
  _DWORD *v4; // r7
  int v5; // r6
  signed int v6; // r8
  int v7; // r9
  char *v8; // r4
  char *v9; // r5
  void **v10; // r1
  _DWORD *v11; // r2
  signed int v12; // r3
  _DWORD *v13; // t1

  v4 = result;
  v5 = 0;
  v6 = a2[3];
  v7 = a2[4];
  v8 = (char *)(result[1] + 4 * (a4 + result[3] * a3));
  v9 = (char *)a2[1];
  while ( v5 < v7 )
  {
    if ( v6 > 11 )
    {
      result = memcpy(v9, v8, 4 * v6);
    }
    else
    {
      v10 = (void **)v8;
      v11 = v9;
      v12 = 0;
      while ( v12 < v6 )
      {
        v13 = *v10;
        ++v10;
        result = v13;
        ++v12;
        *v11 = v13;
        ++v11;
      }
    }
    ++v5;
    v9 += 4 * v6;
    v8 += 4 * v4[3];
  }
  return result;
}

//----- (000004D4) --------------------------------------------------------
void __fastcall ncnn::Mat::release(ncnn::Mat *this)
{
  unsigned int *v1; // r3
  ncnn::Mat *v2; // r4
  unsigned int v3; // r2
  int v4; // r3

  v1 = (unsigned int *)*((_DWORD *)this + 2);
  v2 = this;
  if ( v1 )
  {
    __dmb(0xBu);
    do
      v3 = __ldrex(v1);
    while ( __strex(v3 - 1, v1) );
    __dmb(0xBu);
    if ( v3 == 1 )
    {
      v4 = *((_DWORD *)this + 1);
      if ( v4 )
        free(*(void **)(v4 - 4));
    }
  }
  *(_DWORD *)v2 = 0;
  *((_DWORD *)v2 + 1) = 0;
  *((_DWORD *)v2 + 3) = 0;
  *((_DWORD *)v2 + 4) = 0;
  *((_DWORD *)v2 + 5) = 0;
  *((_DWORD *)v2 + 6) = 0;
  *((_DWORD *)v2 + 2) = 0;
}

//----- (00000550) --------------------------------------------------------
ncnn::Mat *__fastcall ncnn::Mat::operator=(ncnn::Mat *this, ncnn::Mat *a2)
{
  ncnn::Mat *v2; // r4
  unsigned int *v3; // r3
  ncnn::Mat *v4; // r5
  unsigned int v5; // r2

  v2 = this;
  if ( this != a2 )
  {
    v3 = (unsigned int *)*((_DWORD *)a2 + 2);
    v4 = a2;
    if ( v3 )
    {
      __dmb(0xBu);
      do
        v5 = __ldrex(v3);
      while ( __strex(v5 + 1, v3) );
      __dmb(0xBu);
    }
    ncnn::Mat::release(this);
    *(_DWORD *)v2 = *(_DWORD *)v4;
    *((_DWORD *)v2 + 1) = *((_DWORD *)v4 + 1);
    *((_DWORD *)v2 + 2) = *((_DWORD *)v4 + 2);
    *((_DWORD *)v2 + 3) = *((_DWORD *)v4 + 3);
    *((_DWORD *)v2 + 4) = *((_DWORD *)v4 + 4);
    *((_DWORD *)v2 + 5) = *((_DWORD *)v4 + 5);
    *((_DWORD *)v2 + 6) = *((_DWORD *)v4 + 6);
  }
  return v2;
}

//----- (000005E0) --------------------------------------------------------
void __fastcall ncnn::Mat::create(ncnn::Mat *this, int a2)
{
  int v2; // r5
  ncnn::Mat *v3; // r4
  unsigned int v4; // r1
  _DWORD *v5; // r0

  v2 = a2;
  v3 = this;
  ncnn::Mat::release(this);
  *(_DWORD *)v3 = 1;
  *((_DWORD *)v3 + 3) = v2;
  *((_DWORD *)v3 + 4) = 1;
  *((_DWORD *)v3 + 5) = 1;
  *((_DWORD *)v3 + 6) = v2;
  if ( v2 )
  {
    v5 = ncnn::fastMalloc((ncnn *)(4 * v2 + 4), v4);
    *((_DWORD *)v3 + 1) = v5;
    *((_DWORD *)v3 + 2) = &v5[v2];
    v5[v2] = 1;
  }
}

//----- (0000063C) --------------------------------------------------------
void __fastcall ncnn::Mat::create(ncnn::Mat *this, int a2, int a3)
{
  ncnn::Mat *v3; // r5
  int v4; // r6
  int v5; // r4
  unsigned int v6; // r1
  int v7; // r4
  _DWORD *v8; // r0

  v3 = this;
  v4 = a2;
  v5 = a3;
  ncnn::Mat::release(this);
  *((_DWORD *)v3 + 4) = v5;
  v7 = v5 * v4;
  *(_DWORD *)v3 = 2;
  *((_DWORD *)v3 + 3) = v4;
  *((_DWORD *)v3 + 5) = 1;
  *((_DWORD *)v3 + 6) = v7;
  if ( v7 )
  {
    v8 = ncnn::fastMalloc((ncnn *)(4 * v7 + 4), v6);
    *((_DWORD *)v3 + 1) = v8;
    *((_DWORD *)v3 + 2) = &v8[v7];
    v8[v7] = 1;
  }
}

//----- (000006A4) --------------------------------------------------------
void __fastcall ncnn::Mat::create(ncnn::Mat *this, int a2, int a3, int a4)
{
  ncnn::Mat *v4; // r5
  int v5; // r6
  int v6; // r7
  int v7; // r4
  unsigned int v8; // r1
  unsigned int v9; // r3
  int v10; // r6
  _DWORD *v11; // r0

  v4 = this;
  v5 = a4;
  v6 = a2;
  v7 = a3;
  ncnn::Mat::release(this);
  *((_DWORD *)v4 + 5) = v5;
  *(_DWORD *)v4 = 3;
  *((_DWORD *)v4 + 3) = v6;
  *((_DWORD *)v4 + 4) = v7;
  v9 = ((unsigned int)(4 * v7 * v6 + 15) >> 2) & 0x3FFFFFFC;
  v10 = v9 * v5;
  *((_DWORD *)v4 + 6) = v9;
  if ( v10 )
  {
    v11 = ncnn::fastMalloc((ncnn *)(4 * v10 + 4), v8);
    *((_DWORD *)v4 + 1) = v11;
    *((_DWORD *)v4 + 2) = &v11[v10];
    v11[v10] = 1;
  }
}

//----- (00000720) --------------------------------------------------------
void __fastcall ncnn::resize_bilinear_image(ncnn *this, const ncnn::Mat *a2, ncnn::Mat *a3, int a4, int a5)
{
  ncnn *v5; // r6
  char *v6; // r8
  char *v7; // r9
  float v8; // s17
  signed int v9; // s15
  unsigned int v10; // r0
  float v11; // s16
  int v12; // r4
  _DWORD *v13; // r5
  int v14; // r2
  signed int v15; // r3
  int v16; // r9
  int v17; // r0
  float v18; // s13
  float v19; // s15
  float v20; // s13
  int v21; // r1
  bool v22; // nf
  unsigned __int8 v23; // vf
  int v24; // r2
  signed int v25; // r3
  int v26; // r0
  float v27; // s13
  float v28; // s15
  float v29; // s13
  int v30; // r1
  bool v31; // nf
  unsigned __int8 v32; // vf
  int v33; // r11
  int v34; // r1
  int v35; // r3
  int v36; // r0
  int v37; // lr
  int v38; // r12
  int v39; // r2
  int v40; // r9
  float *v41; // r10
  int v42; // r2
  signed int v43; // r8
  int v44; // lr
  int v45; // r9
  float *v46; // r10
  signed int v47; // lr
  int v48; // r2
  float v49; // s15
  float v50; // s13
  int v51; // r2
  float *v52; // r8
  float v53; // s13
  float *v54; // r2
  float v55; // s12
  float *v56; // r12
  float v57; // s15
  float v58; // s14
  int v59; // [sp+4h] [bp-8Ch]
  int v60; // [sp+8h] [bp-88h]
  int v61; // [sp+Ch] [bp-84h]
  int v62; // [sp+10h] [bp-80h]
  float *v63; // [sp+14h] [bp-7Ch]
  const ncnn::Mat *v64; // [sp+18h] [bp-78h]
  int v65; // [sp+20h] [bp-70h]
  int v66; // [sp+24h] [bp-6Ch]
  int v67; // [sp+28h] [bp-68h]
  int v68; // [sp+2Ch] [bp-64h]
  int v69; // [sp+30h] [bp-60h]
  int v70; // [sp+44h] [bp-4Ch]
  int v71; // [sp+48h] [bp-48h]
  int v72; // [sp+4Ch] [bp-44h]

  v5 = this;
  v6 = (char *)a3 + a4;
  v7 = (char *)a3 + 2 * (_DWORD)a3 + a4;
  v8 = (float)*((signed int *)this + 3) / (float)(signed int)a3;
  v9 = *((_DWORD *)this + 4);
  v10 = (unsigned int)&v7[2 * a4];
  v64 = a2;
  v59 = a4;
  v11 = (float)v9 / (float)a4;
  if ( v10 > 0x1FFFFFFE )
    _cxa_throw_bad_array_new_length();
  v12 = (int)a3;
  v13 = (_DWORD *)operator new[](4 * v10);
  v62 = (int)&v13[v12];
  v14 = (int)&v13[(_DWORD)v6];
  v60 = (int)&v13[(_DWORD)v6];
  v15 = 0;
  v16 = (int)&v13[(_DWORD)v7];
  while ( v15 < v12 )
  {
    v14 += 8;
    v17 = *((_DWORD *)v5 + 3);
    v18 = (float)((float)((float)v15 + 0.5) * v8) - 0.5;
    v19 = v18;
    LODWORD(v20) = (signed int)v18;
    v21 = LODWORD(v20);
    v23 = __OFSUB__(LODWORD(v20), v17 - 1);
    v22 = LODWORD(v20) - (v17 - 1) < 0;
    if ( SLODWORD(v20) < v17 - 1 )
      v20 = (float)SLODWORD(v20);
    else
      v21 = v17 - 2;
    if ( !(v22 ^ v23) )
      v19 = 1.0;
    v13[v15++] = v21;
    if ( v22 ^ v23 )
      v19 = v19 - v20;
    *(float *)(v14 - 4) = v19;
    *(float *)(v14 - 8) = 1.0 - v19;
  }
  v24 = v16;
  v25 = 0;
  while ( v25 < v59 )
  {
    v24 += 8;
    v26 = *((_DWORD *)v5 + 4);
    v27 = (float)((float)((float)v25 + 0.5) * v11) - 0.5;
    v28 = v27;
    LODWORD(v29) = (signed int)v27;
    v30 = LODWORD(v29);
    v32 = __OFSUB__(LODWORD(v29), v26 - 1);
    v31 = LODWORD(v29) - (v26 - 1) < 0;
    if ( SLODWORD(v29) < v26 - 1 )
      v29 = (float)SLODWORD(v29);
    else
      v30 = v26 - 2;
    if ( !(v31 ^ v32) )
      v28 = 1.0;
    if ( v31 ^ v32 )
      v28 = v28 - v29;
    *(_DWORD *)(v62 + 4 * v25++) = v30;
    *(float *)(v24 - 4) = v28;
    *(float *)(v24 - 8) = 1.0 - v28;
  }
  v67 = 0;
  v68 = 0;
  v69 = 0;
  ncnn::Mat::create((ncnn::Mat *)&v67, v12 + 1);
  v70 = 0;
  v71 = 0;
  v72 = 0;
  v33 = v16 + 8;
  ncnn::Mat::create((ncnn::Mat *)&v70, v12 + 1);
  v34 = v68;
  v35 = 0;
  v36 = v71;
  v37 = -1;
  while ( v35 < v59 )
  {
    v38 = *(_DWORD *)(v62 + 4 * v35);
    v39 = *((_DWORD *)v5 + 3);
    v61 = *((_DWORD *)v5 + 1);
    if ( v37 == v38 )
    {
      v40 = v60;
      v41 = (float *)v34;
      v42 = 4 * (v39 + v38 * v39);
      v43 = 0;
      while ( 1 )
      {
        v40 += 8;
        if ( v43 >= v12 )
          break;
        v44 = v13[v43++];
        *v41 = (float)(*(float *)(v40 - 4) * *(float *)(v61 + v42 + 4 * v44 + 4))
             + (float)(*(float *)(v40 - 8) * *(float *)(v61 + v42 + 4 * v44));
        ++v41;
      }
      v51 = v34;
      v34 = v36;
      v36 = v51;
    }
    else
    {
      v45 = v60;
      v46 = (float *)v36;
      v47 = 0;
      v66 = 4 * v39 * v38;
      v65 = 4 * (v39 + v39 * v38);
      v63 = (float *)v34;
      while ( 1 )
      {
        v45 += 8;
        if ( v47 >= v12 )
          break;
        v48 = v13[v47++];
        v48 *= 4;
        v49 = *(float *)(v45 - 4);
        v50 = *(float *)(v45 - 8);
        *v63 = (float)(v49 * *(float *)(v61 + v48 + v66 + 4)) + (float)(v50 * *(float *)(v61 + v48 + v66));
        ++v63;
        *v46 = (float)(v49 * *(float *)(v61 + v48 + v65 + 4)) + (float)(v50 * *(float *)(v61 + v48 + v65));
        ++v46;
      }
    }
    v37 = v38 + 1;
    v52 = (float *)v34;
    v53 = *(float *)(v33 - 8);
    v54 = (float *)(*((_DWORD *)v64 + 1) + 4 * *((_DWORD *)v64 + 3) * v35);
    v55 = *(float *)(v33 - 4);
    v56 = (float *)v36;
    while ( v56 != (float *)(v36 + 4 * v12) )
    {
      v57 = *v56;
      ++v56;
      v58 = *v52;
      ++v52;
      *v54 = (float)(v55 * v57) + (float)(v53 * v58);
      ++v54;
    }
    ++v35;
    v33 += 8;
  }
  operator delete[](v13);
  ncnn::Mat::release((ncnn::Mat *)&v70);
  ncnn::Mat::release((ncnn::Mat *)&v67);
}
// 1100: using guessed type int _cxa_throw_bad_array_new_length(void);

//----- (00000A94) --------------------------------------------------------
bool __fastcall ncnn::Mat::empty(ncnn::Mat *this)
{
  _BOOL4 result; // r0

  if ( *((_DWORD *)this + 1) )
    result = *((_DWORD *)this + 5) * *((_DWORD *)this + 6) == 0;
  else
    result = 1;
  return result;
}

//----- (00000ACC) --------------------------------------------------------
int __fastcall ncnn::Mat::channel(int result, int a2, int a3)
{
  int v3; // r12
  int v4; // lr
  int v5; // r2

  v3 = *(_DWORD *)(a2 + 16);
  v4 = *(_DWORD *)(a2 + 12);
  v5 = *(_DWORD *)(a2 + 4) + *(_DWORD *)(a2 + 24) * 4 * a3;
  *(_DWORD *)(result + 16) = v3;
  *(_DWORD *)result = 2;
  *(_DWORD *)(result + 4) = v5;
  *(_DWORD *)(result + 12) = v4;
  *(_DWORD *)(result + 8) = 0;
  *(_DWORD *)(result + 20) = 1;
  *(_DWORD *)(result + 24) = v3 * v4;
  return result;
}

//----- (00000B20) --------------------------------------------------------
int __fastcall ncnn::Mat::substract_mean_normalize(int result, const float *a2, const float *a3)
{
  unsigned int v3; // r5
  int v4; // r12
  int v5; // lr
  int v6; // r4
  int i; // r2
  float v8; // s14
  float *v9; // r3
  int v10; // r12
  unsigned int v11; // r4
  int v12; // r3
  int v13; // r4
  int j; // r3
  float v15; // s14
  float *v16; // r1
  int v17; // r12
  int v18; // r5
  float v19; // s13
  float v20; // s14
  float *v21; // r12
  int v22; // r4

  v3 = (unsigned int)a2;
  if ( a2 )
    v3 = 1;
  if ( a3 )
    v4 = 0;
  else
    v4 = v3 & 1;
  v5 = *(_DWORD *)(result + 16) * *(_DWORD *)(result + 12);
  if ( v4 )
  {
    v6 = *(_DWORD *)(result + 20);
    for ( i = 0; i < v6; ++i )
    {
      v8 = *a2;
      ++a2;
      v9 = (float *)(*(_DWORD *)(result + 4) + i * 4 * *(_DWORD *)(result + 24));
      v10 = v5;
      while ( v10 > 0 )
      {
        --v10;
        *v9 = *v9 - v8;
        ++v9;
      }
    }
  }
  else
  {
    v11 = (unsigned int)a3;
    if ( a3 )
      v11 = 1;
    if ( a2 )
      v12 = 0;
    else
      v12 = v11 & 1;
    if ( v12 )
    {
      v13 = *(_DWORD *)(result + 20);
      for ( j = 0; j < v13; ++j )
      {
        v15 = *a3;
        ++a3;
        v16 = (float *)(*(_DWORD *)(result + 4) + j * 4 * *(_DWORD *)(result + 24));
        v17 = v5;
        while ( v17 > 0 )
        {
          --v17;
          *v16 = *v16 * v15;
          ++v16;
        }
      }
    }
    else if ( v3 & v11 )
    {
      v18 = *(_DWORD *)(result + 20);
      while ( v12 < v18 )
      {
        v19 = *a2;
        ++a2;
        v20 = *a3;
        ++a3;
        v21 = (float *)(*(_DWORD *)(result + 4) + v12 * 4 * *(_DWORD *)(result + 24));
        v22 = v5;
        while ( v22 > 0 )
        {
          --v22;
          *v21 = (float)(*v21 - v19) * v20;
          ++v21;
        }
        ++v12;
      }
    }
  }
  return result;
}

//----- (00000C5C) --------------------------------------------------------
ncnn::Mat *__fastcall ncnn::Mat::from_float16(ncnn::Mat *this, const unsigned __int16 *a2, int a3)
{
  ncnn::Mat *v3; // r4
  const unsigned __int16 *v4; // r6
  int v5; // r5
  int *v6; // r12
  int v7; // r1
  unsigned int v8; // t1
  int v9; // r6
  unsigned int v10; // r2
  int v11; // r0
  int v12; // r3
  bool v13; // zf
  int v14; // r0

  v3 = this;
  *(_DWORD *)this = 0;
  v4 = a2;
  *((_DWORD *)this + 1) = 0;
  *((_DWORD *)this + 2) = 0;
  v5 = a3;
  ncnn::Mat::create(this, a3);
  if ( !ncnn::Mat::empty(v3) )
  {
    v6 = (int *)*((_DWORD *)v3 + 1);
    v7 = (int)(v4 - 1);
    while ( v5 > 0 )
    {
      v8 = *(unsigned __int16 *)(v7 + 2);
      v7 += 2;
      v9 = (v8 >> 10) & 0x1F;
      v10 = v8 >> 15;
      v11 = v8 & 0x3FF;
      if ( v9 )
      {
        v13 = v9 == 31;
        v14 = v11 << 13;
        if ( v9 != 31 )
          v9 += 112;
        if ( v13 )
          v12 = (v10 << 31) | v14 | 0x7F800000;
        else
          v12 = (v10 << 31) | v14 | (v9 << 23);
      }
      else if ( v11 )
      {
        while ( 1 )
        {
          v13 = (v11 & 0x200) == 0;
          LOWORD(v11) = 2 * v11;
          if ( !v13 )
            break;
          ++v9;
        }
        v12 = (v10 << 31) | ((112 - v9) << 23) | ((v11 & 0x3FE) << 13);
      }
      else
      {
        v12 = v10 << 31;
      }
      *v6 = v12;
      ++v6;
      --v5;
    }
  }
  return v3;
}

//----- (00000D40) --------------------------------------------------------
void __fastcall ncnn::copy_make_border(ncnn *this, const ncnn::Mat *a2, ncnn::Mat *a3, int a4, int a5, int a6, int a7, int a8, float a9)
{
  ncnn *v9; // r6
  int v10; // r0
  char *v11; // r12
  ncnn::Mat *v12; // r9
  ncnn::Mat *v13; // r5
  int v14; // r1
  char *v15; // r2
  bool v16; // zf
  int v17; // r11
  int v18; // r4
  int v19; // r2
  char v20; // [sp+8h] [bp-68h]
  char v21; // [sp+24h] [bp-4Ch]

  v9 = this;
  v10 = *((_DWORD *)this + 3);
  v11 = (char *)*((_DWORD *)v9 + 4);
  v12 = a3;
  v13 = a2;
  v14 = v10 + a5 + a6;
  v15 = (char *)a3 + (_DWORD)v11 + a4;
  v16 = v11 == v15;
  if ( v11 == v15 )
    v16 = v10 == v14;
  if ( v16 )
  {
    ncnn::Mat::operator=(v13, v9);
  }
  else if ( *(_DWORD *)v9 == 2 )
  {
    ncnn::Mat::create(v13, v14, (int)v15);
    if ( !ncnn::Mat::empty(v13) )
      ncnn::copy_make_border_image(v9, v13, (int)v12, a5, a7);
  }
  else if ( *(_DWORD *)v9 == 3 )
  {
    v17 = *((_DWORD *)v9 + 5);
    ncnn::Mat::create(v13, v14, (int)v15, *((_DWORD *)v9 + 5));
    v18 = ncnn::Mat::empty(v13);
    if ( !v18 )
    {
      while ( v18 < v17 )
      {
        ncnn::Mat::channel((int)&v20, (int)v9, v18);
        v19 = v18++;
        ncnn::Mat::channel((int)&v21, (int)v13, v19);
        ncnn::copy_make_border_image(&v20, &v21, (int)v12, a5, a7);
        ncnn::Mat::release((ncnn::Mat *)&v21);
        ncnn::Mat::release((ncnn::Mat *)&v20);
      }
    }
  }
}

//----- (00000E84) --------------------------------------------------------
void __fastcall ncnn::copy_cut_border(ncnn *this, const ncnn::Mat *a2, ncnn::Mat *a3, int a4, int a5, int a6, int a7)
{
  ncnn *v7; // r6
  ncnn::Mat *v8; // r7
  int v9; // r0
  ncnn::Mat *v10; // r5
  int v11; // r12
  int v12; // r1
  int v13; // r2
  bool v14; // zf
  int v15; // r9
  int v16; // r4
  int v17; // r2
  int v18; // [sp+0h] [bp-60h]
  char v19; // [sp+1Ch] [bp-44h]

  v7 = this;
  v8 = a3;
  v9 = *((_DWORD *)this + 3);
  v10 = a2;
  v11 = *((_DWORD *)v7 + 4);
  v12 = v9 - a5 - a6;
  v13 = v11 - (_DWORD)a3 - a4;
  v14 = v11 == v13;
  if ( v11 == v13 )
    v14 = v9 == v12;
  if ( v14 )
  {
    ncnn::Mat::operator=(v10, v7);
  }
  else if ( *(_DWORD *)v7 == 2 )
  {
    ncnn::Mat::create(v10, v12, v13);
    if ( !ncnn::Mat::empty(v10) )
      ncnn::copy_cut_border_image(v7, v10, (int)v8, a5);
  }
  else if ( *(_DWORD *)v7 == 3 )
  {
    v15 = *((_DWORD *)v7 + 5);
    ncnn::Mat::create(v10, v12, v13, *((_DWORD *)v7 + 5));
    v16 = ncnn::Mat::empty(v10);
    if ( !v16 )
    {
      while ( v16 < v15 )
      {
        ncnn::Mat::channel((int)&v18, (int)v7, v16);
        v17 = v16++;
        ncnn::Mat::channel((int)&v19, (int)v10, v17);
        ncnn::copy_cut_border_image(&v18, &v19, (int)v8, a5);
        ncnn::Mat::release((ncnn::Mat *)&v19);
        ncnn::Mat::release((ncnn::Mat *)&v18);
      }
    }
  }
}

//----- (00000FA4) --------------------------------------------------------
void __fastcall ncnn::resize_bilinear(ncnn *this, const ncnn::Mat *a2, ncnn::Mat *a3, int a4, int a5)
{
  int v5; // r8
  ncnn *v6; // r5
  const ncnn::Mat *v7; // r6
  ncnn::Mat *v8; // r7
  int v9; // r10
  int v10; // r4
  int v11; // [sp+0h] [bp-60h]
  char v12; // [sp+1Ch] [bp-44h]

  v5 = a4;
  v6 = this;
  v7 = a2;
  v8 = a3;
  if ( *((ncnn::Mat **)this + 3) != a3 || *((_DWORD *)this + 4) != a4 )
  {
    if ( *(_DWORD *)this == 2 )
    {
      ncnn::Mat::create(a2, (int)a3, a4);
      if ( !ncnn::Mat::empty(v7) )
        ncnn::resize_bilinear_image(v6, v7, v8, v5, v11);
    }
    else if ( *(_DWORD *)this == 3 )
    {
      v9 = *((_DWORD *)this + 5);
      ncnn::Mat::create(a2, (int)a3, a4, *((_DWORD *)this + 5));
      v10 = ncnn::Mat::empty(v7);
      if ( !v10 )
      {
        while ( v10 < v9 )
        {
          ncnn::Mat::channel((int)&v11, (int)v6, v10);
          ncnn::Mat::channel((int)&v12, (int)v7, v10);
          ncnn::resize_bilinear_image((ncnn *)&v11, (const ncnn::Mat *)&v12, v8, v5, v11);
          ++v10;
          ncnn::Mat::release((ncnn::Mat *)&v12);
          ncnn::Mat::release((ncnn::Mat *)&v11);
        }
      }
    }
  }
  else
  {
    ncnn::Mat::operator=(a2, this);
  }
}

// ALL OK, 16 function(s) have been successfully decompiled
