/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *__fastcall ncnn::fastMalloc(ncnn *this, unsigned int a2);
void __fastcall ncnn::Mat::release(ncnn::Mat *this);
ncnn::Mat *__fastcall ncnn::Mat::operator=(ncnn::Mat *this, ncnn::Mat *a2);
ncnn::Mat *__fastcall ncnn::Mat::Mat(ncnn::Mat *this, int a2);
ncnn::Mat *__fastcall ncnn::Mat::Mat(ncnn::Mat *this, int a2, int a3, int a4);
bool __fastcall ncnn::Mat::empty(ncnn::Mat *this);
int __fastcall ncnn::Mat::channel(int result, int a2, int a3);
void __fastcall ncnn::resize_bilinear_c3(ncnn *this, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7);
int __fastcall ncnn::copy_cut_border_c1(int result, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7, int a8, int a9);
int __fastcall ncnn::copy_cut_border_c3(int result, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7, int a8, int a9);
void __fastcall ncnn::resize_bilinear_c1(ncnn *this, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7);
void __fastcall ncnn::resize_bilinear_c4(ncnn *this, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7);
ncnn::Mat *__fastcall ncnn::Mat::from_pixels(ncnn::Mat *this, const unsigned __int8 *a2, int a3, int a4, int a5);
ncnn::Mat *__fastcall ncnn::Mat::from_pixels_resize(ncnn::Mat *this, const unsigned __int8 *a2, int a3, int a4, int a5, int a6, int a7);
int __fastcall ncnn::Mat::to_pixels(int result, unsigned __int8 *a2, int a3);
void __fastcall ncnn::Mat::to_pixels_resize(ncnn::Mat *this, unsigned __int8 *a2, int a3, int a4, int a5);
// void *malloc(size_t size);
// void free(void *ptr);
// _DWORD __cdecl operator new[](unsigned int); idb
// int _cxa_throw_bad_array_new_length(void); weak
// void __cdecl operator delete[](void *); idb
// void *memcpy(void *dest, const void *src, size_t n);


//----- (00000004) --------------------------------------------------------
void *__fastcall ncnn::fastMalloc(ncnn *this, unsigned int a2)
{
  void *result; // r0

  result = malloc((size_t)this + 20);
  if ( result )
  {
    *(_DWORD *)((((unsigned int)result + 19) & 0xFFFFFFF0) - 4) = result;
    result = (void *)(((unsigned int)result + 19) & 0xFFFFFFF0);
  }
  return result;
}

//----- (00000034) --------------------------------------------------------
void __fastcall ncnn::Mat::release(ncnn::Mat *this)
{
  unsigned int *v1; // r3
  ncnn::Mat *v2; // r4
  unsigned int v3; // r2
  int v4; // r3

  v1 = (unsigned int *)*((_DWORD *)this + 2);
  v2 = this;
  if ( v1 )
  {
    __dmb(0xBu);
    do
      v3 = __ldrex(v1);
    while ( __strex(v3 - 1, v1) );
    __dmb(0xBu);
    if ( v3 == 1 )
    {
      v4 = *((_DWORD *)this + 1);
      if ( v4 )
        free(*(void **)(v4 - 4));
    }
  }
  *(_DWORD *)v2 = 0;
  *((_DWORD *)v2 + 1) = 0;
  *((_DWORD *)v2 + 3) = 0;
  *((_DWORD *)v2 + 4) = 0;
  *((_DWORD *)v2 + 5) = 0;
  *((_DWORD *)v2 + 6) = 0;
  *((_DWORD *)v2 + 2) = 0;
}

//----- (000000B0) --------------------------------------------------------
ncnn::Mat *__fastcall ncnn::Mat::operator=(ncnn::Mat *this, ncnn::Mat *a2)
{
  ncnn::Mat *v2; // r4
  unsigned int *v3; // r3
  ncnn::Mat *v4; // r5
  unsigned int v5; // r2

  v2 = this;
  if ( this != a2 )
  {
    v3 = (unsigned int *)*((_DWORD *)a2 + 2);
    v4 = a2;
    if ( v3 )
    {
      __dmb(0xBu);
      do
        v5 = __ldrex(v3);
      while ( __strex(v5 + 1, v3) );
      __dmb(0xBu);
    }
    ncnn::Mat::release(this);
    *(_DWORD *)v2 = *(_DWORD *)v4;
    *((_DWORD *)v2 + 1) = *((_DWORD *)v4 + 1);
    *((_DWORD *)v2 + 2) = *((_DWORD *)v4 + 2);
    *((_DWORD *)v2 + 3) = *((_DWORD *)v4 + 3);
    *((_DWORD *)v2 + 4) = *((_DWORD *)v4 + 4);
    *((_DWORD *)v2 + 5) = *((_DWORD *)v4 + 5);
    *((_DWORD *)v2 + 6) = *((_DWORD *)v4 + 6);
  }
  return v2;
}

//----- (00000140) --------------------------------------------------------
ncnn::Mat *__fastcall ncnn::Mat::Mat(ncnn::Mat *this, int a2)
{
  int v2; // r5
  ncnn::Mat *v3; // r4
  unsigned int v4; // r1
  _DWORD *v5; // r0

  v2 = a2;
  *(_DWORD *)this = 0;
  v3 = this;
  *((_DWORD *)this + 1) = 0;
  *((_DWORD *)this + 2) = 0;
  ncnn::Mat::release(this);
  *(_DWORD *)v3 = 1;
  *((_DWORD *)v3 + 3) = v2;
  *((_DWORD *)v3 + 4) = 1;
  *((_DWORD *)v3 + 5) = 1;
  *((_DWORD *)v3 + 6) = v2;
  if ( v2 )
  {
    v5 = ncnn::fastMalloc((ncnn *)(4 * v2 + 4), v4);
    *((_DWORD *)v3 + 1) = v5;
    *((_DWORD *)v3 + 2) = &v5[v2];
    v5[v2] = 1;
  }
  return v3;
}

//----- (000001B0) --------------------------------------------------------
ncnn::Mat *__fastcall ncnn::Mat::Mat(ncnn::Mat *this, int a2, int a3, int a4)
{
  int v4; // r6
  ncnn::Mat *v5; // r5
  int v6; // r7
  int v7; // r4
  unsigned int v8; // r1
  unsigned int v9; // r3
  int v10; // r6
  _DWORD *v11; // r0

  v4 = a4;
  v5 = this;
  *(_DWORD *)this = 0;
  v6 = a2;
  *((_DWORD *)this + 1) = 0;
  v7 = a3;
  *((_DWORD *)this + 2) = 0;
  ncnn::Mat::release(this);
  *((_DWORD *)v5 + 5) = v4;
  *(_DWORD *)v5 = 3;
  *((_DWORD *)v5 + 3) = v6;
  *((_DWORD *)v5 + 4) = v7;
  v9 = ((unsigned int)(4 * v7 * v6 + 15) >> 2) & 0x3FFFFFFC;
  v10 = v9 * v4;
  *((_DWORD *)v5 + 6) = v9;
  if ( v10 )
  {
    v11 = ncnn::fastMalloc((ncnn *)(4 * v10 + 4), v8);
    *((_DWORD *)v5 + 1) = v11;
    *((_DWORD *)v5 + 2) = &v11[v10];
    v11[v10] = 1;
  }
  return v5;
}

//----- (00000240) --------------------------------------------------------
bool __fastcall ncnn::Mat::empty(ncnn::Mat *this)
{
  _BOOL4 result; // r0

  if ( *((_DWORD *)this + 1) )
    result = *((_DWORD *)this + 5) * *((_DWORD *)this + 6) == 0;
  else
    result = 1;
  return result;
}

//----- (00000278) --------------------------------------------------------
int __fastcall ncnn::Mat::channel(int result, int a2, int a3)
{
  int v3; // r12
  int v4; // lr
  int v5; // r2

  v3 = *(_DWORD *)(a2 + 16);
  v4 = *(_DWORD *)(a2 + 12);
  v5 = *(_DWORD *)(a2 + 4) + *(_DWORD *)(a2 + 24) * 4 * a3;
  *(_DWORD *)(result + 16) = v3;
  *(_DWORD *)result = 2;
  *(_DWORD *)(result + 4) = v5;
  *(_DWORD *)(result + 12) = v4;
  *(_DWORD *)(result + 8) = 0;
  *(_DWORD *)(result + 20) = 1;
  *(_DWORD *)(result + 24) = v3 * v4;
  return result;
}

//----- (000002CC) --------------------------------------------------------
void __fastcall ncnn::resize_bilinear_c3(ncnn *this, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7)
{
  int v7; // r6
  int v8; // r5
  ncnn *v9; // r9
  double v10; // d9
  double v11; // d17
  unsigned __int8 *v12; // r7
  unsigned __int8 *v13; // r4
  _DWORD *v14; // r10
  int v15; // r12
  int v16; // r2
  int v17; // r4
  signed int v18; // r3
  float v19; // s15
  float v20; // s14
  int v21; // r1
  bool v22; // nf
  unsigned __int8 v23; // vf
  float v24; // s14
  float v25; // s15
  float v26; // s13
  float v27; // s14
  int *v28; // r1
  int v29; // r1
  float v30; // s14
  int *v31; // r1
  int v32; // r12
  int v33; // r2
  int v34; // r3
  int v35; // r6
  float v36; // s15
  float v37; // s14
  signed int v38; // r1
  bool v39; // nf
  unsigned __int8 v40; // vf
  float v41; // s14
  float v42; // s15
  float v43; // s13
  float v44; // s14
  int *v45; // r1
  int v46; // r1
  float v47; // s14
  int *v48; // r1
  int v49; // r12
  int v50; // r1
  int v51; // r7
  int v52; // r2
  signed int v53; // lr
  int v54; // r4
  int v55; // r12
  __int16 v56; // r5
  unsigned __int8 *v57; // r0
  __int16 v58; // r3
  int v59; // r0
  int v60; // r4
  signed int v61; // r8
  int v62; // lr
  __int16 v63; // r2
  __int16 v64; // r3
  unsigned __int8 *v65; // r12
  int v66; // r3
  int v67; // lr
  __int16 *v68; // r0
  __int16 v69; // r6
  __int16 v70; // r5
  __int16 *v71; // r4
  __int16 v72; // r3
  __int16 v73; // t1
  __int16 v74; // t1
  const unsigned __int8 *v75; // [sp+4h] [bp-ACh]
  int v76; // [sp+8h] [bp-A8h]
  int v77; // [sp+Ch] [bp-A4h]
  int v78; // [sp+10h] [bp-A0h]
  int v79; // [sp+14h] [bp-9Ch]
  int v80; // [sp+18h] [bp-98h]
  int v81; // [sp+1Ch] [bp-94h]
  int v82; // [sp+24h] [bp-8Ch]
  int v83; // [sp+28h] [bp-88h]
  signed int v84; // [sp+3Ch] [bp-74h]
  int v85; // [sp+40h] [bp-70h]
  int v86; // [sp+44h] [bp-6Ch]
  int v87; // [sp+5Ch] [bp-54h]
  int v88; // [sp+60h] [bp-50h]

  v7 = a3;
  v8 = a4;
  v9 = this;
  v75 = a2;
  v10 = (double)(signed int)a2 / (double)(signed int)a5;
  v11 = (double)a3;
  v12 = &a5[a6];
  v13 = &a5[a6 + (_DWORD)a5];
  if ( (unsigned int)&v13[a6] > 0x1FFFFFFE )
    _cxa_throw_bad_array_new_length();
  v14 = (_DWORD *)operator new[](4 * (_DWORD)&v13[a6]);
  v15 = (int)(v75 - 1);
  v82 = (int)&v14[(_DWORD)a5];
  v16 = (int)&v14[(_DWORD)v12];
  v17 = (int)&v14[(_DWORD)v13];
  v81 = (int)&v14[(_DWORD)v12];
  v18 = 0;
  while ( v18 < (signed int)a5 )
  {
    v85 = -32768;
    v16 += 4;
    v87 = 0x7FFF;
    v19 = (float)((float)v18 + 0.5) * v10 - 0.5;
    LODWORD(v20) = (signed int)v19;
    v21 = (signed int)v19;
    v23 = __OFSUB__((signed int)v19, v15);
    v22 = (signed int)v19 - v15 < 0;
    if ( (signed int)v19 < v15 )
      v20 = (float)SLODWORD(v20);
    else
      v21 = (int)(v75 - 2);
    if ( (signed int)v19 >= v15 )
      v19 = 1.0;
    v14[v18++] = 3 * v21;
    if ( v22 ^ v23 )
      v19 = v19 - v20;
    v24 = 1.0 - v19;
    v25 = v19 * 2048.0;
    v26 = v24 * 2048.0;
    if ( (float)(v24 * 2048.0) >= 0.0 )
      v27 = 0.5;
    else
      v27 = -0.5;
    v84 = (signed int)(float)(v27 + v26);
    if ( (v84 + 0x8000 < 0) ^ __OFADD__(v84, 0x8000) )
      v28 = &v85;
    else
      v28 = &v84;
    if ( *v28 >= 0x8000 )
      v28 = &v87;
    v29 = *v28;
    v85 = -32768;
    *(_WORD *)(v16 - 4) = v29;
    if ( v25 >= 0.0 )
      v30 = 0.5;
    else
      v30 = -0.5;
    v87 = 0x7FFF;
    v84 = (signed int)(float)(v30 + v25);
    if ( (v84 + 0x8000 < 0) ^ __OFADD__(v84, 0x8000) )
      v31 = &v85;
    else
      v31 = &v84;
    if ( *v31 >= 0x8000 )
      v31 = &v87;
    *(_WORD *)(v16 - 2) = *v31;
  }
  v32 = v7 - 1;
  v33 = v17;
  v34 = 0;
  v35 = v7 - 2;
  while ( v34 < a6 )
  {
    v33 += 4;
    v85 = -32768;
    v36 = (float)((float)v34 + 0.5) * (v11 / (double)a6) - 0.5;
    LODWORD(v37) = (signed int)v36;
    v38 = (signed int)v36;
    v40 = __OFSUB__((signed int)v36, v32);
    v39 = (signed int)v36 - v32 < 0;
    if ( (signed int)v36 < v32 )
      v37 = (float)SLODWORD(v37);
    else
      v38 = v35;
    if ( (signed int)v36 >= v32 )
      v36 = 1.0;
    *(_DWORD *)(v82 + 4 * v34) = 3 * v38;
    if ( v39 ^ v40 )
      v36 = v36 - v37;
    ++v34;
    v87 = 0x7FFF;
    v41 = 1.0 - v36;
    v42 = v36 * 2048.0;
    v43 = v41 * 2048.0;
    if ( (float)(v41 * 2048.0) >= 0.0 )
      v44 = 0.5;
    else
      v44 = -0.5;
    v84 = (signed int)(float)(v44 + v43);
    if ( (v84 + 0x8000 < 0) ^ __OFADD__(v84, 0x8000) )
      v45 = &v85;
    else
      v45 = &v84;
    if ( *v45 >= 0x8000 )
      v45 = &v87;
    v46 = *v45;
    v85 = -32768;
    *(_WORD *)(v33 - 4) = v46;
    if ( v42 >= 0.0 )
      v47 = 0.5;
    else
      v47 = -0.5;
    v87 = 0x7FFF;
    v84 = (signed int)(float)(v47 + v42);
    if ( (v84 + 0x8000 < 0) ^ __OFADD__(v84, 0x8000) )
      v48 = &v85;
    else
      v48 = &v84;
    if ( *v48 >= 0x8000 )
      v48 = &v87;
    *(_WORD *)(v33 - 2) = *v48;
  }
  ncnn::Mat::Mat((ncnn::Mat *)&v85, (3 * (signed int)a5 >> 1) + 3);
  ncnn::Mat::Mat((ncnn::Mat *)&v87, (3 * (signed int)a5 >> 1) + 3);
  v49 = -1;
  v50 = v88;
  v76 = v86;
  v79 = v17 + 4;
  v80 = v8 - 1;
  v77 = 0;
  while ( a6 > v77 )
  {
    v51 = *(_DWORD *)(v82 + 4 * v77);
    if ( v49 == v51 )
    {
      v52 = v76;
      v53 = 0;
      v54 = v81;
      while ( 1 )
      {
        v54 += 4;
        v52 += 6;
        if ( v53 >= (signed int)a5 )
          break;
        v55 = v14[v53++];
        v56 = *(_WORD *)(v54 - 2);
        v57 = (unsigned __int8 *)v9 + (_DWORD)v75 * (v51 + 3) + v55;
        v58 = *(_WORD *)(v54 - 4);
        *(_WORD *)(v52 - 6) = (v58 * *v57 + v57[3] * v56) >> 4;
        *(_WORD *)(v52 - 4) = (v58 * v57[1] + v57[4] * v56) >> 4;
        *(_WORD *)(v52 - 2) = (v58 * v57[2] + v57[5] * v56) >> 4;
      }
      v66 = v76;
      v76 = v50;
      v50 = v66;
    }
    else
    {
      v59 = v50;
      v60 = v76;
      v61 = 0;
      v83 = v51 * (_DWORD)v75;
      v78 = v81;
      while ( 1 )
      {
        v60 += 6;
        v59 += 6;
        v78 += 4;
        if ( v61 >= (signed int)a5 )
          break;
        v62 = v14[v61++];
        v63 = *(_WORD *)(v78 - 2);
        v64 = *(_WORD *)(v78 - 4);
        *(_WORD *)(v60 - 6) = (v64 * *((unsigned __int8 *)v9 + v83 + v62)
                             + *((unsigned __int8 *)v9 + v83 + v62 + 3) * v63) >> 4;
        *(_WORD *)(v60 - 4) = (v64 * *((unsigned __int8 *)v9 + v83 + v62 + 1)
                             + *((unsigned __int8 *)v9 + v83 + v62 + 4) * v63) >> 4;
        v65 = (unsigned __int8 *)v9 + 3 * (_DWORD)v75 + v51 * (_DWORD)v75 + v62;
        *(_WORD *)(v60 - 2) = (v64 * *((unsigned __int8 *)v9 + v83 + v62 + 2)
                             + *((unsigned __int8 *)v9 + v83 + v62 + 5) * v63) >> 4;
        *(_WORD *)(v59 - 6) = (v64 * *v65 + v65[3] * v63) >> 4;
        *(_WORD *)(v59 - 4) = (v64 * v65[1] + v65[4] * v63) >> 4;
        *(_WORD *)(v59 - 2) = (v64 * v65[2] + v65[5] * v63) >> 4;
      }
    }
    v49 = v51 + 1;
    v67 = v80;
    v68 = (__int16 *)v50;
    v69 = *(_WORD *)(v79 - 4);
    v70 = *(_WORD *)(v79 - 2);
    v71 = (__int16 *)v76;
    while ( v68 != (__int16 *)(v50 + 6 * (_DWORD)a5) )
    {
      v73 = *v68;
      ++v68;
      v72 = v73;
      v74 = *v71;
      ++v71;
      *(_BYTE *)(v67++ + 1) = ((v72 * v70 >> 16) + (v74 * v69 >> 16) + 2) >> 2;
    }
    ++v77;
    v79 += 4;
    v80 += 3 * (_DWORD)a5;
  }
  operator delete[](v14);
  ncnn::Mat::release((ncnn::Mat *)&v87);
  ncnn::Mat::release((ncnn::Mat *)&v85);
}
// 23F0: using guessed type int _cxa_throw_bad_array_new_length(void);

//----- (000008A0) --------------------------------------------------------
int __fastcall ncnn::copy_cut_border_c1(int result, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7, int a8, int a9)
{
  const unsigned __int8 *v9; // r7
  char *v10; // r9
  signed int v11; // r5
  int v12; // r8
  bool v13; // zf
  signed int v14; // r4
  int v15; // r6
  signed int i; // r3

  v9 = a2;
  v10 = (char *)a4;
  v11 = (signed int)&a2[-a7 - a8];
  v12 = a3 - (_DWORD)a5 - a6;
  v13 = a2 == (const unsigned __int8 *)v11;
  if ( a2 == (const unsigned __int8 *)v11 )
    v13 = a3 == v12;
  v14 = v13 != 0;
  if ( !v13 )
  {
    v15 = result + a7 + (_DWORD)a5 * (_DWORD)a2;
    while ( v14 < v12 )
    {
      if ( v11 > 11 )
      {
        result = (int)memcpy(v10, (const void *)v15, v11);
      }
      else
      {
        for ( i = 0; i < v11; ++i )
          v10[i] = *(_BYTE *)(v15 + i);
      }
      v10 += v11;
      ++v14;
      v15 += (int)v9;
    }
  }
  return result;
}

//----- (00000940) --------------------------------------------------------
int __fastcall ncnn::copy_cut_border_c3(int result, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7, int a8, int a9)
{
  char *v9; // r9
  const unsigned __int8 *v10; // r6
  int v11; // r8
  bool v12; // zf
  signed int v13; // r4
  int v14; // r5
  int v15; // r10
  char *v16; // r7
  int i; // r3

  v9 = (char *)a4;
  v10 = &a2[-a7 - a8];
  v11 = a3 - (_DWORD)a5 - a6;
  v12 = a2 == v10;
  if ( a2 == v10 )
    v12 = a3 == v11;
  v13 = v12 != 0;
  if ( !v12 )
  {
    v14 = 3 * (_DWORD)a2;
    v15 = 3 * (_DWORD)v10;
    v16 = (char *)(result + a7 + 3 * (_DWORD)a2 * (_DWORD)a5);
    while ( v13 < v11 )
    {
      if ( (signed int)v10 > 11 )
      {
        result = (int)memcpy(v9, v16, 3 * (_DWORD)v10);
      }
      else
      {
        for ( i = 0; i < v15; ++i )
          v9[i] = v16[i];
      }
      v9 += v15;
      ++v13;
      v16 += v14;
    }
  }
  return result;
}

//----- (000009E4) --------------------------------------------------------
void __fastcall ncnn::resize_bilinear_c1(ncnn *this, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7)
{
  int v7; // r7
  ncnn *v8; // r8
  double v9; // d9
  unsigned __int8 *v10; // r6
  unsigned __int8 *v11; // r4
  double v12; // d8
  int v13; // r5
  _DWORD *v14; // r11
  int v15; // r12
  int v16; // r2
  int v17; // r4
  signed int v18; // r3
  float v19; // s15
  float v20; // s14
  int v21; // r1
  bool v22; // nf
  unsigned __int8 v23; // vf
  float v24; // s14
  float v25; // s15
  float v26; // s13
  float v27; // s14
  int *v28; // r1
  int v29; // r1
  float v30; // s14
  int *v31; // r1
  int v32; // r12
  int v33; // r2
  int v34; // r3
  int v35; // r5
  float v36; // s15
  float v37; // s14
  signed int v38; // r1
  bool v39; // nf
  unsigned __int8 v40; // vf
  float v41; // s14
  float v42; // s15
  float v43; // s13
  float v44; // s14
  int *v45; // r1
  int v46; // r1
  float v47; // s14
  int *v48; // r1
  int v49; // lr
  int v50; // r12
  int v51; // r1
  int v52; // r4
  int v53; // r3
  int v54; // r12
  signed int v55; // r0
  int v56; // r5
  int v57; // r6
  signed int v58; // r5
  int v59; // r0
  __int16 v60; // r9
  __int16 v61; // r2
  int v62; // r3
  int v63; // r4
  __int16 *v64; // r0
  __int16 v65; // r7
  __int16 *v66; // r5
  __int16 v67; // r6
  __int16 v68; // r3
  __int16 v69; // t1
  __int16 v70; // t1
  const unsigned __int8 *v71; // [sp+4h] [bp-A4h]
  int v72; // [sp+8h] [bp-A0h]
  int v73; // [sp+Ch] [bp-9Ch]
  int v74; // [sp+10h] [bp-98h]
  int v75; // [sp+14h] [bp-94h]
  int v76; // [sp+18h] [bp-90h]
  int v77; // [sp+20h] [bp-88h]
  int i; // [sp+24h] [bp-84h]
  signed int v79; // [sp+34h] [bp-74h]
  int v80; // [sp+38h] [bp-70h]
  int v81; // [sp+3Ch] [bp-6Ch]
  int v82; // [sp+54h] [bp-54h]
  int v83; // [sp+58h] [bp-50h]

  v7 = a4;
  v8 = this;
  v71 = a2;
  v9 = (double)(signed int)a2 / (double)(signed int)a5;
  v10 = &a5[a6];
  v11 = &a5[a6 + (_DWORD)a5];
  v12 = (double)a3 / (double)a6;
  if ( (unsigned int)&v11[a6] > 0x1FFFFFFE )
    _cxa_throw_bad_array_new_length();
  v13 = a3;
  v14 = (_DWORD *)operator new[](4 * (_DWORD)&v11[a6]);
  v76 = (int)&v14[(_DWORD)a5];
  v15 = (int)(v71 - 1);
  v16 = (int)&v14[(_DWORD)v10];
  v17 = (int)&v14[(_DWORD)v11];
  v75 = (int)&v14[(_DWORD)v10];
  v18 = 0;
  while ( v18 < (signed int)a5 )
  {
    v80 = -32768;
    v16 += 4;
    v82 = 0x7FFF;
    v19 = (float)((float)v18 + 0.5) * v9 - 0.5;
    LODWORD(v20) = (signed int)v19;
    v21 = (signed int)v19;
    v23 = __OFSUB__((signed int)v19, v15);
    v22 = (signed int)v19 - v15 < 0;
    if ( (signed int)v19 < v15 )
      v20 = (float)SLODWORD(v20);
    else
      v21 = (int)(v71 - 2);
    if ( (signed int)v19 >= v15 )
      v19 = 1.0;
    v14[v18++] = v21;
    if ( v22 ^ v23 )
      v19 = v19 - v20;
    v24 = 1.0 - v19;
    v25 = v19 * 2048.0;
    v26 = v24 * 2048.0;
    if ( (float)(v24 * 2048.0) >= 0.0 )
      v27 = 0.5;
    else
      v27 = -0.5;
    v79 = (signed int)(float)(v27 + v26);
    if ( (v79 + 0x8000 < 0) ^ __OFADD__(v79, 0x8000) )
      v28 = &v80;
    else
      v28 = &v79;
    if ( *v28 >= 0x8000 )
      v28 = &v82;
    v29 = *v28;
    v80 = -32768;
    *(_WORD *)(v16 - 4) = v29;
    if ( v25 >= 0.0 )
      v30 = 0.5;
    else
      v30 = -0.5;
    v82 = 0x7FFF;
    v79 = (signed int)(float)(v30 + v25);
    if ( (v79 + 0x8000 < 0) ^ __OFADD__(v79, 0x8000) )
      v31 = &v80;
    else
      v31 = &v79;
    if ( *v31 >= 0x8000 )
      v31 = &v82;
    *(_WORD *)(v16 - 2) = *v31;
  }
  v32 = v13 - 1;
  v33 = v17;
  v34 = 0;
  v35 = v13 - 2;
  while ( v34 < a6 )
  {
    v33 += 4;
    v80 = -32768;
    v36 = (float)((float)v34 + 0.5) * v12 - 0.5;
    LODWORD(v37) = (signed int)v36;
    v38 = (signed int)v36;
    v40 = __OFSUB__((signed int)v36, v32);
    v39 = (signed int)v36 - v32 < 0;
    if ( (signed int)v36 < v32 )
      v37 = (float)SLODWORD(v37);
    else
      v38 = v35;
    if ( (signed int)v36 >= v32 )
      v36 = 1.0;
    *(_DWORD *)(v76 + 4 * v34) = v38;
    v82 = 0x7FFF;
    ++v34;
    if ( v39 ^ v40 )
      v36 = v36 - v37;
    v41 = 1.0 - v36;
    v42 = v36 * 2048.0;
    v43 = v41 * 2048.0;
    if ( (float)(v41 * 2048.0) >= 0.0 )
      v44 = 0.5;
    else
      v44 = -0.5;
    v79 = (signed int)(float)(v44 + v43);
    if ( (v79 + 0x8000 < 0) ^ __OFADD__(v79, 0x8000) )
      v45 = &v80;
    else
      v45 = &v79;
    if ( *v45 >= 0x8000 )
      v45 = &v82;
    v46 = *v45;
    v80 = -32768;
    *(_WORD *)(v33 - 4) = v46;
    if ( v42 >= 0.0 )
      v47 = 0.5;
    else
      v47 = -0.5;
    v82 = 0x7FFF;
    v79 = (signed int)(float)(v47 + v42);
    if ( (v79 + 0x8000 < 0) ^ __OFADD__(v79, 0x8000) )
      v48 = &v80;
    else
      v48 = &v79;
    if ( *v48 >= 0x8000 )
      v48 = &v82;
    *(_WORD *)(v33 - 2) = *v48;
  }
  ncnn::Mat::Mat((ncnn::Mat *)&v80, ((signed int)a5 >> 1) + 1);
  ncnn::Mat::Mat((ncnn::Mat *)&v82, ((signed int)a5 >> 1) + 1);
  v49 = v81;
  v73 = v17 + 4;
  v74 = v7 - 1;
  v50 = -1;
  v51 = v83;
  v72 = 0;
  while ( a6 > v72 )
  {
    v52 = *(_DWORD *)(v76 + 4 * v72);
    v53 = v49 - 2;
    if ( v50 == v52 )
    {
      v54 = v75;
      v55 = 0;
      while ( 1 )
      {
        v54 += 4;
        if ( v55 >= (signed int)a5 )
          break;
        v56 = v14[v55++];
        *(_WORD *)(v53 + 2) = (*(signed __int16 *)(v54 - 4) * (unsigned __int8)v71[v52 * (_DWORD)v71 + v56 + (_DWORD)v8]
                             + (unsigned __int8)v71[v52 * (_DWORD)v71 + 1 + v56 + (_DWORD)v8]
                             * *(signed __int16 *)(v54 - 2)) >> 4;
        v53 += 2;
      }
      v62 = v49;
      v49 = v51;
      v51 = v62;
    }
    else
    {
      v57 = v75;
      v58 = 0;
      v77 = v49 - 2;
      for ( i = v51 - 2; ; i += 2 )
      {
        v57 += 4;
        if ( v58 >= (signed int)a5 )
          break;
        v59 = v14[v58++];
        v60 = *(_WORD *)(v57 - 2);
        v61 = *(_WORD *)(v57 - 4);
        *(_WORD *)(v77 + 2) = (v61 * *((unsigned __int8 *)v8 + v52 * (_DWORD)v71 + v59)
                             + *((unsigned __int8 *)v8 + v52 * (_DWORD)v71 + v59 + 1) * v60) >> 4;
        *(_WORD *)(i + 2) = (v61 * (unsigned __int8)v71[v52 * (_DWORD)v71 + v59 + (_DWORD)v8]
                           + (unsigned __int8)v71[v52 * (_DWORD)v71 + 1 + v59 + (_DWORD)v8] * v60) >> 4;
        v77 += 2;
      }
    }
    v50 = v52 + 1;
    v63 = v74;
    v64 = (__int16 *)v51;
    v65 = *(_WORD *)(v73 - 4);
    v66 = (__int16 *)v49;
    v67 = *(_WORD *)(v73 - 2);
    while ( v64 != (__int16 *)(v51 + 2 * (_DWORD)a5) )
    {
      v69 = *v64;
      ++v64;
      v68 = v69;
      v70 = *v66;
      ++v66;
      *(_BYTE *)(v63++ + 1) = ((v68 * v67 >> 16) + (v70 * v65 >> 16) + 2) >> 2;
    }
    ++v72;
    v73 += 4;
    v74 += (int)a5;
  }
  operator delete[](v14);
  ncnn::Mat::release((ncnn::Mat *)&v82);
  ncnn::Mat::release((ncnn::Mat *)&v80);
}
// 23F0: using guessed type int _cxa_throw_bad_array_new_length(void);

//----- (00000ED8) --------------------------------------------------------
void __fastcall ncnn::resize_bilinear_c4(ncnn *this, const unsigned __int8 *a2, int a3, int a4, unsigned __int8 *a5, int a6, int a7)
{
  int v7; // r6
  ncnn *v8; // r9
  double v9; // d9
  unsigned __int8 *v10; // r8
  unsigned __int8 *v11; // r5
  double v12; // d8
  int v13; // r7
  _DWORD *v14; // r4
  int v15; // r12
  int v16; // r2
  int v17; // r5
  signed int v18; // r3
  float v19; // s15
  float v20; // s14
  int v21; // r1
  bool v22; // nf
  unsigned __int8 v23; // vf
  float v24; // s14
  float v25; // s15
  float v26; // s13
  float v27; // s14
  int *v28; // r1
  int v29; // r1
  float v30; // s14
  int *v31; // r1
  int v32; // r12
  int v33; // r2
  int v34; // r3
  int v35; // r7
  float v36; // s15
  float v37; // s14
  signed int v38; // r1
  bool v39; // nf
  unsigned __int8 v40; // vf
  float v41; // s14
  float v42; // s15
  float v43; // s13
  float v44; // s14
  int *v45; // r1
  int v46; // r1
  float v47; // s14
  int *v48; // r1
  int v49; // r0
  int v50; // r7
  int v51; // r1
  signed int v52; // r12
  int v53; // r5
  int v54; // r0
  __int16 v55; // lr
  unsigned __int8 *v56; // r2
  __int16 v57; // r3
  signed int v58; // r8
  int v59; // lr
  int v60; // r12
  int v61; // r3
  int v62; // r5
  int v63; // r6
  __int16 v64; // r2
  __int16 v65; // r3
  unsigned __int8 *v66; // r1
  int v67; // r3
  __int16 v68; // r6
  __int16 v69; // r5
  int v70; // r12
  __int16 *v71; // r1
  __int16 *v72; // lr
  __int16 v73; // r3
  __int16 v74; // t1
  __int16 v75; // t1
  const unsigned __int8 *v76; // [sp+0h] [bp-B0h]
  int v77; // [sp+4h] [bp-ACh]
  int v78; // [sp+8h] [bp-A8h]
  int v79; // [sp+Ch] [bp-A4h]
  int v80; // [sp+10h] [bp-A0h]
  int v81; // [sp+14h] [bp-9Ch]
  int v82; // [sp+18h] [bp-98h]
  int v83; // [sp+1Ch] [bp-94h]
  int v84; // [sp+20h] [bp-90h]
  int v85; // [sp+24h] [bp-8Ch]
  signed int v86; // [sp+3Ch] [bp-74h]
  int v87; // [sp+40h] [bp-70h]
  int v88; // [sp+44h] [bp-6Ch]
  int v89; // [sp+5Ch] [bp-54h]
  int v90; // [sp+60h] [bp-50h]

  v7 = a4;
  v8 = this;
  v76 = a2;
  v9 = (double)(signed int)a2 / (double)(signed int)a5;
  v10 = &a5[a6];
  v11 = &a5[a6 + (_DWORD)a5];
  v12 = (double)a3 / (double)a6;
  if ( (unsigned int)&v11[a6] > 0x1FFFFFFE )
    _cxa_throw_bad_array_new_length();
  v13 = a3;
  v14 = (_DWORD *)operator new[](4 * (_DWORD)&v11[a6]);
  v84 = (int)&v14[(_DWORD)a5];
  v15 = (int)(v76 - 1);
  v16 = (int)&v14[(_DWORD)v10];
  v17 = (int)&v14[(_DWORD)v11];
  v83 = (int)&v14[(_DWORD)v10];
  v18 = 0;
  while ( v18 < (signed int)a5 )
  {
    v87 = -32768;
    v16 += 4;
    v89 = 0x7FFF;
    v19 = (float)((float)v18 + 0.5) * v9 - 0.5;
    LODWORD(v20) = (signed int)v19;
    v21 = (signed int)v19;
    v23 = __OFSUB__((signed int)v19, v15);
    v22 = (signed int)v19 - v15 < 0;
    if ( (signed int)v19 < v15 )
      v20 = (float)SLODWORD(v20);
    else
      v21 = (int)(v76 - 2);
    if ( (signed int)v19 >= v15 )
      v19 = 1.0;
    v14[v18++] = 4 * v21;
    if ( v22 ^ v23 )
      v19 = v19 - v20;
    v24 = 1.0 - v19;
    v25 = v19 * 2048.0;
    v26 = v24 * 2048.0;
    if ( (float)(v24 * 2048.0) >= 0.0 )
      v27 = 0.5;
    else
      v27 = -0.5;
    v86 = (signed int)(float)(v27 + v26);
    if ( (v86 + 0x8000 < 0) ^ __OFADD__(v86, 0x8000) )
      v28 = &v87;
    else
      v28 = &v86;
    if ( *v28 >= 0x8000 )
      v28 = &v89;
    v29 = *v28;
    v87 = -32768;
    *(_WORD *)(v16 - 4) = v29;
    if ( v25 >= 0.0 )
      v30 = 0.5;
    else
      v30 = -0.5;
    v89 = 0x7FFF;
    v86 = (signed int)(float)(v30 + v25);
    if ( (v86 + 0x8000 < 0) ^ __OFADD__(v86, 0x8000) )
      v31 = &v87;
    else
      v31 = &v86;
    if ( *v31 >= 0x8000 )
      v31 = &v89;
    *(_WORD *)(v16 - 2) = *v31;
  }
  v32 = v13 - 1;
  v33 = v17;
  v34 = 0;
  v35 = v13 - 2;
  while ( v34 < a6 )
  {
    v33 += 4;
    v87 = -32768;
    v36 = (float)((float)v34 + 0.5) * v12 - 0.5;
    LODWORD(v37) = (signed int)v36;
    v38 = (signed int)v36;
    v40 = __OFSUB__((signed int)v36, v32);
    v39 = (signed int)v36 - v32 < 0;
    if ( (signed int)v36 < v32 )
      v37 = (float)SLODWORD(v37);
    else
      v38 = v35;
    if ( (signed int)v36 >= v32 )
      v36 = 1.0;
    *(_DWORD *)(v84 + 4 * v34) = 4 * v38;
    if ( v39 ^ v40 )
      v36 = v36 - v37;
    ++v34;
    v89 = 0x7FFF;
    v41 = 1.0 - v36;
    v42 = v36 * 2048.0;
    v43 = v41 * 2048.0;
    if ( (float)(v41 * 2048.0) >= 0.0 )
      v44 = 0.5;
    else
      v44 = -0.5;
    v86 = (signed int)(float)(v44 + v43);
    if ( (v86 + 0x8000 < 0) ^ __OFADD__(v86, 0x8000) )
      v45 = &v87;
    else
      v45 = &v86;
    if ( *v45 >= 0x8000 )
      v45 = &v89;
    v46 = *v45;
    v87 = -32768;
    *(_WORD *)(v33 - 4) = v46;
    if ( v42 >= 0.0 )
      v47 = 0.5;
    else
      v47 = -0.5;
    v89 = 0x7FFF;
    v86 = (signed int)(float)(v47 + v42);
    if ( (v86 + 0x8000 < 0) ^ __OFADD__(v86, 0x8000) )
      v48 = &v87;
    else
      v48 = &v86;
    if ( *v48 >= 0x8000 )
      v48 = &v89;
    *(_WORD *)(v33 - 2) = *v48;
  }
  ncnn::Mat::Mat((ncnn::Mat *)&v87, (4 * (signed int)a5 >> 1) + 4);
  ncnn::Mat::Mat((ncnn::Mat *)&v89, (4 * (signed int)a5 >> 1) + 4);
  v49 = -1;
  v77 = v88;
  v78 = v90;
  v81 = v17 + 4;
  v82 = v7 - 1;
  v79 = 0;
  while ( a6 > v79 )
  {
    v50 = *(_DWORD *)(v84 + 4 * v79);
    if ( v49 == v50 )
    {
      v51 = v77;
      v52 = 0;
      v53 = v83;
      while ( 1 )
      {
        v53 += 4;
        v51 += 8;
        if ( v52 >= (signed int)a5 )
          break;
        v54 = v14[v52++];
        v55 = *(_WORD *)(v53 - 2);
        v56 = (unsigned __int8 *)v8 + (_DWORD)v76 * (v50 + 4) + v54;
        v57 = *(_WORD *)(v53 - 4);
        *(_WORD *)(v51 - 8) = (v57 * *v56 + v56[4] * v55) >> 4;
        *(_WORD *)(v51 - 6) = (v57 * v56[1] + v56[5] * v55) >> 4;
        *(_WORD *)(v51 - 4) = (v57 * v56[2] + v56[6] * v55) >> 4;
        *(_WORD *)(v51 - 2) = (v57 * v56[3] + v56[7] * v55) >> 4;
      }
      v67 = v77;
      v77 = v78;
      v78 = v67;
    }
    else
    {
      v58 = 0;
      v59 = v77;
      v60 = v78;
      v85 = v50 * (_DWORD)v76;
      v80 = v83;
      while ( 1 )
      {
        v59 += 8;
        v60 += 8;
        v61 = v80 + 4;
        v80 += 4;
        if ( v58 >= (signed int)a5 )
          break;
        v62 = v14[v58++];
        v63 = v85 + v62;
        v64 = *(_WORD *)(v80 - 2);
        v65 = *(_WORD *)(v61 - 4);
        *(_WORD *)(v59 - 8) = (v65 * *((unsigned __int8 *)v8 + v85 + v62)
                             + *((unsigned __int8 *)v8 + v85 + v62 + 4) * v64) >> 4;
        *(_WORD *)(v59 - 6) = (v65 * *((unsigned __int8 *)v8 + v63 + 1) + *((unsigned __int8 *)v8 + v63 + 5) * v64) >> 4;
        v66 = (unsigned __int8 *)v8 + 4 * (_DWORD)v76 + v50 * (_DWORD)v76 + v62;
        *(_WORD *)(v59 - 4) = (v65 * *((unsigned __int8 *)v8 + v63 + 2) + *((unsigned __int8 *)v8 + v63 + 6) * v64) >> 4;
        *(_WORD *)(v59 - 2) = (v65 * *((unsigned __int8 *)v8 + v63 + 3) + *((unsigned __int8 *)v8 + v63 + 7) * v64) >> 4;
        *(_WORD *)(v60 - 8) = (v65 * *v66 + v66[4] * v64) >> 4;
        *(_WORD *)(v60 - 6) = (v65 * v66[1] + v66[5] * v64) >> 4;
        *(_WORD *)(v60 - 4) = (v65 * v66[2] + v66[6] * v64) >> 4;
        *(_WORD *)(v60 - 2) = (v65 * v66[3] + v66[7] * v64) >> 4;
      }
    }
    v49 = v50 + 1;
    v68 = *(_WORD *)(v81 - 4);
    v69 = *(_WORD *)(v81 - 2);
    v70 = v82;
    v71 = (__int16 *)v78;
    v72 = (__int16 *)v77;
    while ( v71 != (__int16 *)(v78 + 8 * (_DWORD)a5) )
    {
      v74 = *v71;
      ++v71;
      v73 = v74;
      v75 = *v72;
      ++v72;
      *(_BYTE *)(v70++ + 1) = ((v73 * v69 >> 16) + (v75 * v68 >> 16) + 2) >> 2;
    }
    ++v79;
    v81 += 4;
    v82 += 4 * (_DWORD)a5;
  }
  operator delete[](v14);
  ncnn::Mat::release((ncnn::Mat *)&v89);
  ncnn::Mat::release((ncnn::Mat *)&v87);
}
// 23F0: using guessed type int _cxa_throw_bad_array_new_length(void);

//----- (000014E0) --------------------------------------------------------
ncnn::Mat *__fastcall ncnn::Mat::from_pixels(ncnn::Mat *this, const unsigned __int8 *a2, int a3, int a4, int a5)
{
  int v5; // r5
  ncnn::Mat *v6; // r6
  const unsigned __int8 *v7; // r4
  bool v8; // zf
  float *v9; // r10
  float *v10; // r9
  int v11; // r5
  float *v12; // r11
  int v13; // r5
  float *i; // r0
  int v15; // r5
  float *j; // r0
  float *v17; // r10
  float *v18; // r9
  int v19; // r5
  float *v20; // r11
  int v21; // r3
  unsigned int v22; // t1
  float *v23; // r10
  float *v24; // r9
  int v25; // r5
  float *v26; // r11
  float *v27; // r10
  float *v28; // r9
  int v29; // r5
  float *v30; // r11
  int v31; // r5
  float *k; // r0
  float *v33; // r10
  float *v34; // r9
  int v35; // r5
  float *v36; // r11
  float *v37; // r1
  int v38; // r3
  int v39; // r5
  unsigned int v40; // t1
  float *v41; // r10
  float *v42; // r9
  int v43; // r5
  int v44; // ST04_4
  float *v45; // r11
  float *v46; // r3
  char v48; // [sp+Ch] [bp-44h]
  float *v49; // [sp+10h] [bp-40h]

  v5 = a4;
  v6 = this;
  v7 = a2;
  if ( (unsigned int)a3 >> 16 << 16 )
  {
    v8 = a3 == 65538;
    if ( a3 != 65538 )
      v8 = a3 == 131073;
    if ( !v8 )
    {
      if ( a3 == 262145 )
      {
        ncnn::Mat::Mat(this, a4, a5, 1);
        if ( !ncnn::Mat::empty(v6) )
        {
          v13 = a5 * v5;
          for ( i = (float *)*((_DWORD *)v6 + 1); ; ++i )
          {
            v7 += 3;
            if ( v13 <= 0 )
              break;
            --v13;
            *i = (float)((29 * *(v7 - 1) + 77 * *(v7 - 3) + 150 * *(v7 - 2)) >> 8);
          }
        }
        return v6;
      }
      if ( a3 == 262146 )
      {
        ncnn::Mat::Mat(this, a4, a5, 1);
        if ( !ncnn::Mat::empty(v6) )
        {
          v15 = a5 * v5;
          for ( j = (float *)*((_DWORD *)v6 + 1); ; ++j )
          {
            v7 += 3;
            if ( v15 <= 0 )
              break;
            --v15;
            *j = (float)((29 * *(v7 - 3) + 77 * *(v7 - 1) + 150 * *(v7 - 2)) >> 8);
          }
        }
        return v6;
      }
      if ( !((a3 - 65540) & 0xFFFEFFFF) )
      {
        ncnn::Mat::Mat(this, a4, a5, 3);
        if ( !ncnn::Mat::empty(v6) )
        {
          ncnn::Mat::channel((int)&v48, (int)v6, 0);
          v17 = v49;
          ncnn::Mat::release((ncnn::Mat *)&v48);
          ncnn::Mat::channel((int)&v48, (int)v6, 1);
          v18 = v49;
          ncnn::Mat::release((ncnn::Mat *)&v48);
          v19 = a5 * v5 - 1;
          ncnn::Mat::channel((int)&v48, (int)v6, 2);
          v20 = v49;
          ncnn::Mat::release((ncnn::Mat *)&v48);
          v21 = (int)(v7 - 1);
          while ( (signed int)&v7[v19 - v21] > 0 )
          {
            *v17 = (float)*(unsigned __int8 *)(v21 + 1);
            ++v17;
            *v18 = (float)*(unsigned __int8 *)(v21 + 1);
            ++v18;
            v22 = *(unsigned __int8 *)(v21++ + 1);
            *v20 = (float)v22;
            ++v20;
          }
        }
        return v6;
      }
      switch ( a3 )
      {
        case 65544:
          ncnn::Mat::Mat(this, a4, a5, 3);
          if ( !ncnn::Mat::empty(v6) )
          {
            ncnn::Mat::channel((int)&v48, (int)v6, 0);
            v23 = v49;
            ncnn::Mat::release((ncnn::Mat *)&v48);
            ncnn::Mat::channel((int)&v48, (int)v6, 1);
            v24 = v49;
            ncnn::Mat::release((ncnn::Mat *)&v48);
            ncnn::Mat::channel((int)&v48, (int)v6, 2);
            v25 = a5 * v5;
            v26 = v49;
            ncnn::Mat::release((ncnn::Mat *)&v48);
            while ( 1 )
            {
              v7 += 4;
              if ( v25 <= 0 )
                break;
              --v25;
              *v23 = (float)*(v7 - 4);
              ++v23;
              *v24 = (float)*(v7 - 3);
              ++v24;
              *v26 = (float)*(v7 - 2);
              ++v26;
            }
          }
          return v6;
        case 131080:
          ncnn::Mat::Mat(this, a4, a5, 3);
          if ( !ncnn::Mat::empty(v6) )
          {
            ncnn::Mat::channel((int)&v48, (int)v6, 0);
            v27 = v49;
            ncnn::Mat::release((ncnn::Mat *)&v48);
            ncnn::Mat::channel((int)&v48, (int)v6, 1);
            v28 = v49;
            ncnn::Mat::release((ncnn::Mat *)&v48);
            ncnn::Mat::channel((int)&v48, (int)v6, 2);
            v29 = a5 * v5;
            v30 = v49;
            ncnn::Mat::release((ncnn::Mat *)&v48);
            while ( 1 )
            {
              v7 += 4;
              if ( v29 <= 0 )
                break;
              --v29;
              *v27 = (float)*(v7 - 2);
              ++v27;
              *v28 = (float)*(v7 - 3);
              ++v28;
              *v30 = (float)*(v7 - 4);
              ++v30;
            }
          }
          return v6;
        case 262152:
          ncnn::Mat::Mat(this, a4, a5, 1);
          if ( !ncnn::Mat::empty(v6) )
          {
            v31 = a5 * v5;
            for ( k = (float *)*((_DWORD *)v6 + 1); ; ++k )
            {
              v7 += 4;
              if ( v31 <= 0 )
                break;
              --v31;
              *k = (float)((29 * *(v7 - 2) + 77 * *(v7 - 4) + 150 * *(v7 - 3)) >> 8);
            }
          }
          return v6;
      }
LABEL_55:
      *(_DWORD *)this = 0;
      *((_DWORD *)this + 1) = 0;
      *((_DWORD *)this + 2) = 0;
      *((_DWORD *)this + 3) = 0;
      *((_DWORD *)this + 4) = 0;
      *((_DWORD *)this + 5) = 0;
      *((_DWORD *)this + 6) = 0;
      return v6;
    }
    ncnn::Mat::Mat(this, a4, a5, 3);
    if ( !ncnn::Mat::empty(v6) )
    {
      ncnn::Mat::channel((int)&v48, (int)v6, 0);
      v9 = v49;
      ncnn::Mat::release((ncnn::Mat *)&v48);
      ncnn::Mat::channel((int)&v48, (int)v6, 1);
      v10 = v49;
      ncnn::Mat::release((ncnn::Mat *)&v48);
      ncnn::Mat::channel((int)&v48, (int)v6, 2);
      v11 = a5 * v5;
      v12 = v49;
      ncnn::Mat::release((ncnn::Mat *)&v48);
      while ( 1 )
      {
        v7 += 3;
        if ( v11 <= 0 )
          break;
        --v11;
        *v9 = (float)*(v7 - 1);
        ++v9;
        *v10 = (float)*(v7 - 2);
        ++v10;
        *v12 = (float)*(v7 - 3);
        ++v12;
      }
    }
  }
  else if ( (unsigned int)(a3 - 1) > 1 )
  {
    if ( a3 == 4 )
    {
      ncnn::Mat::Mat(this, a4, a5, 1);
      if ( !ncnn::Mat::empty(v6) )
      {
        v37 = (float *)*((_DWORD *)v6 + 1);
        v38 = (int)(v7 - 1);
        v39 = a5 * v5 - 1;
        while ( (signed int)&v7[v39 - v38] > 0 )
        {
          v40 = *(unsigned __int8 *)(v38++ + 1);
          *v37 = (float)v40;
          ++v37;
        }
      }
    }
    else
    {
      if ( a3 != 8 )
        goto LABEL_55;
      ncnn::Mat::Mat(this, a4, a5, 4);
      if ( !ncnn::Mat::empty(v6) )
      {
        ncnn::Mat::channel((int)&v48, (int)v6, 0);
        v41 = v49;
        ncnn::Mat::release((ncnn::Mat *)&v48);
        ncnn::Mat::channel((int)&v48, (int)v6, 1);
        v42 = v49;
        ncnn::Mat::release((ncnn::Mat *)&v48);
        ncnn::Mat::channel((int)&v48, (int)v6, 2);
        v43 = a5 * v5;
        v44 = (int)v49;
        ncnn::Mat::release((ncnn::Mat *)&v48);
        ncnn::Mat::channel((int)&v48, (int)v6, 3);
        v45 = v49;
        ncnn::Mat::release((ncnn::Mat *)&v48);
        v46 = (float *)v44;
        while ( 1 )
        {
          v7 += 4;
          if ( v43 <= 0 )
            break;
          --v43;
          *v41 = (float)*(v7 - 4);
          ++v41;
          *v42 = (float)*(v7 - 3);
          ++v42;
          *v46 = (float)*(v7 - 2);
          ++v46;
          *v45 = (float)*(v7 - 1);
          ++v45;
        }
      }
    }
  }
  else
  {
    ncnn::Mat::Mat(this, a4, a5, 3);
    if ( !ncnn::Mat::empty(v6) )
    {
      ncnn::Mat::channel((int)&v48, (int)v6, 0);
      v33 = v49;
      ncnn::Mat::release((ncnn::Mat *)&v48);
      ncnn::Mat::channel((int)&v48, (int)v6, 1);
      v34 = v49;
      ncnn::Mat::release((ncnn::Mat *)&v48);
      ncnn::Mat::channel((int)&v48, (int)v6, 2);
      v35 = a5 * v5;
      v36 = v49;
      ncnn::Mat::release((ncnn::Mat *)&v48);
      while ( 1 )
      {
        v7 += 3;
        if ( v35 <= 0 )
          break;
        --v35;
        *v33 = (float)*(v7 - 3);
        ++v33;
        *v34 = (float)*(v7 - 2);
        ++v34;
        *v36 = (float)*(v7 - 1);
        ++v36;
      }
    }
  }
  return v6;
}

//----- (00001C20) --------------------------------------------------------
ncnn::Mat *__fastcall ncnn::Mat::from_pixels_resize(ncnn::Mat *this, const unsigned __int8 *a2, int a3, int a4, int a5, int a6, int a7)
{
  ncnn::Mat *v7; // r6
  bool v8; // zf
  const unsigned __int8 *v10; // r9
  int v11; // r10
  ncnn *v12; // r11
  char *v13; // r7
  unsigned int *v14; // r3
  unsigned int v15; // r2
  int v16; // [sp+8h] [bp-A0h]
  unsigned __int8 *v17; // [sp+Ch] [bp-9Ch]
  int v18; // [sp+10h] [bp-98h]
  int v19; // [sp+14h] [bp-94h]
  unsigned int *v20; // [sp+18h] [bp-90h]
  int v21; // [sp+1Ch] [bp-8Ch]
  int v22; // [sp+20h] [bp-88h]
  int v23; // [sp+24h] [bp-84h]
  int v24; // [sp+28h] [bp-80h]
  char v25; // [sp+2Ch] [bp-7Ch]
  char v26; // [sp+48h] [bp-60h]
  char v27; // [sp+64h] [bp-44h]

  v7 = this;
  v8 = a4 == a6;
  if ( a4 == a6 )
    v8 = a5 == a7;
  if ( v8 )
  {
    ncnn::Mat::from_pixels(this, a2, a3, a4, a5);
    return v7;
  }
  v18 = 0;
  v10 = (const unsigned __int8 *)a4;
  v19 = 0;
  v20 = 0;
  v11 = a3;
  v21 = 0;
  v22 = 0;
  v23 = 0;
  v12 = (ncnn *)a2;
  v24 = 0;
  if ( (unsigned int)(unsigned __int16)a3 - 1 > 1 )
  {
    if ( (unsigned __int16)a3 == 4 )
    {
      v17 = (unsigned __int8 *)operator new[](a7 * a6);
      ncnn::resize_bilinear_c1(v12, v10, a5, (int)v17, (unsigned __int8 *)a6, a7, v16);
      v13 = &v26;
    }
    else
    {
      if ( (unsigned __int16)a3 != 8 )
        goto LABEL_14;
      v17 = (unsigned __int8 *)operator new[](4 * a7 * a6);
      ncnn::resize_bilinear_c4(v12, v10, a5, (int)v17, (unsigned __int8 *)a6, a7, v16);
      v13 = &v27;
    }
  }
  else
  {
    v17 = (unsigned __int8 *)operator new[](3 * a7 * a6);
    ncnn::resize_bilinear_c3(v12, v10, a5, (int)v17, (unsigned __int8 *)a6, a7, v16);
    v13 = &v25;
  }
  ncnn::Mat::from_pixels((ncnn::Mat *)v13, v17, v11, a6, a7);
  ncnn::Mat::operator=((ncnn::Mat *)&v18, (ncnn::Mat *)v13);
  ncnn::Mat::release((ncnn::Mat *)v13);
  operator delete[](v17);
LABEL_14:
  *(_DWORD *)v7 = v18;
  *((_DWORD *)v7 + 1) = v19;
  v14 = v20;
  *((_DWORD *)v7 + 2) = v20;
  if ( v14 )
  {
    __dmb(0xBu);
    do
      v15 = __ldrex(v14);
    while ( __strex(v15 + 1, v14) );
    __dmb(0xBu);
  }
  *((_DWORD *)v7 + 3) = v21;
  *((_DWORD *)v7 + 4) = v22;
  *((_DWORD *)v7 + 5) = v23;
  *((_DWORD *)v7 + 6) = v24;
  ncnn::Mat::release((ncnn::Mat *)&v18);
  return v7;
}

//----- (00001E04) --------------------------------------------------------
int __fastcall ncnn::Mat::to_pixels(int result, unsigned __int8 *a2, int a3)
{
  int v3; // r6
  unsigned __int8 *v4; // r4
  bool v5; // zf
  unsigned __int8 *v6; // r4
  int v7; // r7
  int v8; // r8
  int v9; // r9
  float *v10; // r12
  float *v11; // r1
  int v12; // r3
  float v13; // s15
  int *v14; // r2
  float v15; // s15
  int *v16; // r2
  float v17; // s15
  int *v18; // r2
  unsigned __int8 *v19; // r4
  float *v20; // r10
  float *v21; // r9
  float *v22; // r8
  int v23; // r3
  float v24; // s15
  int *v25; // r2
  float v26; // s15
  int *v27; // r2
  float v28; // s15
  int *v29; // r2
  unsigned __int8 *v30; // r2
  float *v31; // r12
  int v32; // r1
  float v33; // s15
  int *v34; // r3
  unsigned __int8 *v35; // r4
  float *v36; // r11
  float *v37; // r10
  float *v38; // r9
  float *v39; // r8
  int v40; // r3
  float v41; // s15
  int *v42; // r2
  float v43; // s15
  int *v44; // r2
  float v45; // s15
  int *v46; // r2
  float v47; // s15
  int *v48; // r2
  int v49; // [sp+4h] [bp-4Ch]
  int v50; // [sp+8h] [bp-48h]
  signed int v51; // [sp+Ch] [bp-44h]
  float *v52; // [sp+10h] [bp-40h]

  v3 = result;
  v4 = a2;
  if ( (unsigned int)a3 >> 16 << 16 )
  {
    v5 = a3 == 65538;
    if ( a3 != 65538 )
      v5 = a3 == 131073;
    if ( v5 )
    {
      v6 = a2 + 3;
      ncnn::Mat::channel((int)&v51, result, 0);
      v7 = (int)v52;
      ncnn::Mat::release((ncnn::Mat *)&v51);
      ncnn::Mat::channel((int)&v51, v3, 1);
      v8 = (int)v52;
      ncnn::Mat::release((ncnn::Mat *)&v51);
      ncnn::Mat::channel((int)&v51, v3, 2);
      v9 = (int)v52;
      ncnn::Mat::release((ncnn::Mat *)&v51);
      result = v8;
      v10 = (float *)v7;
      v11 = (float *)v9;
      v12 = *(_DWORD *)(v3 + 16) * *(_DWORD *)(v3 + 12);
      while ( v12 > 0 )
      {
        v13 = *v10;
        ++v10;
        --v12;
        v50 = 0;
        v6 += 3;
        v49 = 255;
        v51 = (signed int)v13;
        if ( (signed int)v13 < 0 )
          v14 = &v50;
        else
          v14 = &v51;
        if ( *v14 >= 256 )
          v14 = &v49;
        *(v6 - 4) = *v14;
        v15 = *(float *)result;
        result += 4;
        v51 = (signed int)v15;
        if ( (signed int)v15 < 0 )
          v16 = &v50;
        else
          v16 = &v51;
        if ( *v16 >= 256 )
          v16 = &v49;
        *(v6 - 5) = *v16;
        v17 = *v11;
        ++v11;
        v51 = (signed int)v17;
        if ( (signed int)v17 < 0 )
          v18 = &v50;
        else
          v18 = &v51;
        if ( *v18 >= 256 )
          v18 = &v49;
        *(v6 - 6) = *v18;
      }
    }
  }
  else if ( (unsigned int)(a3 - 1) > 1 )
  {
    if ( a3 == 4 )
    {
      v30 = a2;
      v31 = *(float **)(result + 4);
      v32 = *(_DWORD *)(result + 16) * *(_DWORD *)(result + 12);
      while ( (signed int)&v4[v32 - (_DWORD)v30] > 0 )
      {
        v33 = *v31;
        ++v31;
        v50 = 0;
        v49 = 255;
        v51 = (signed int)v33;
        if ( (signed int)v33 < 0 )
          v34 = &v50;
        else
          v34 = &v51;
        result = *v34;
        if ( *v34 >= 256 )
          v34 = &v49;
        *v30++ = *v34;
      }
    }
    else if ( a3 == 8 )
    {
      v35 = a2 + 4;
      ncnn::Mat::channel((int)&v51, result, 0);
      v36 = v52;
      ncnn::Mat::release((ncnn::Mat *)&v51);
      ncnn::Mat::channel((int)&v51, v3, 1);
      v37 = v52;
      ncnn::Mat::release((ncnn::Mat *)&v51);
      ncnn::Mat::channel((int)&v51, v3, 2);
      v38 = v52;
      ncnn::Mat::release((ncnn::Mat *)&v51);
      ncnn::Mat::channel((int)&v51, v3, 3);
      v39 = v52;
      ncnn::Mat::release((ncnn::Mat *)&v51);
      result = 255;
      v40 = *(_DWORD *)(v3 + 16) * *(_DWORD *)(v3 + 12);
      while ( v40 > 0 )
      {
        v41 = *v36;
        ++v36;
        --v40;
        v50 = 0;
        v35 += 4;
        v49 = 255;
        v51 = (signed int)v41;
        if ( (signed int)v41 < 0 )
          v42 = &v50;
        else
          v42 = &v51;
        if ( *v42 >= 256 )
          v42 = &v49;
        *(v35 - 8) = *v42;
        v43 = *v37;
        ++v37;
        v51 = (signed int)v43;
        if ( (signed int)v43 < 0 )
          v44 = &v50;
        else
          v44 = &v51;
        if ( *v44 >= 256 )
          v44 = &v49;
        *(v35 - 7) = *v44;
        v45 = *v38;
        ++v38;
        v51 = (signed int)v45;
        if ( (signed int)v45 < 0 )
          v46 = &v50;
        else
          v46 = &v51;
        if ( *v46 >= 256 )
          v46 = &v49;
        *(v35 - 6) = *v46;
        v47 = *v39;
        ++v39;
        v51 = (signed int)v47;
        if ( (signed int)v47 < 0 )
          v48 = &v50;
        else
          v48 = &v51;
        if ( *v48 >= 256 )
          v48 = &v49;
        *(v35 - 5) = *v48;
      }
    }
  }
  else
  {
    v19 = a2 + 3;
    ncnn::Mat::channel((int)&v51, result, (unsigned int)a3 >> 16 << 16);
    v20 = v52;
    ncnn::Mat::release((ncnn::Mat *)&v51);
    ncnn::Mat::channel((int)&v51, v3, 1);
    v21 = v52;
    ncnn::Mat::release((ncnn::Mat *)&v51);
    ncnn::Mat::channel((int)&v51, v3, 2);
    v22 = v52;
    ncnn::Mat::release((ncnn::Mat *)&v51);
    result = 255;
    v23 = *(_DWORD *)(v3 + 16) * *(_DWORD *)(v3 + 12);
    while ( v23 > 0 )
    {
      v24 = *v20;
      ++v20;
      --v23;
      v50 = 0;
      v19 += 3;
      v49 = 255;
      v51 = (signed int)v24;
      if ( (signed int)v24 < 0 )
        v25 = &v50;
      else
        v25 = &v51;
      if ( *v25 >= 256 )
        v25 = &v49;
      *(v19 - 6) = *v25;
      v26 = *v21;
      ++v21;
      v51 = (signed int)v26;
      if ( (signed int)v26 < 0 )
        v27 = &v50;
      else
        v27 = &v51;
      if ( *v27 >= 256 )
        v27 = &v49;
      *(v19 - 5) = *v27;
      v28 = *v22;
      ++v22;
      v51 = (signed int)v28;
      if ( (signed int)v28 < 0 )
        v29 = &v50;
      else
        v29 = &v51;
      if ( *v29 >= 256 )
        v29 = &v49;
      *(v19 - 4) = *v29;
    }
  }
  return result;
}

//----- (0000229C) --------------------------------------------------------
void __fastcall ncnn::Mat::to_pixels_resize(ncnn::Mat *this, unsigned __int8 *a2, int a3, int a4, int a5)
{
  int v5; // r12
  ncnn::Mat *v6; // r4
  unsigned __int8 *v7; // r7
  int v8; // r5
  unsigned __int8 *v9; // r6
  unsigned __int8 *v10; // r9
  int v11; // [sp+8h] [bp-20h]

  v5 = *((_DWORD *)this + 3);
  v11 = a3;
  v6 = this;
  v7 = a2;
  v8 = a3;
  if ( v5 == a4 && *((_DWORD *)this + 4) == a5 )
  {
    ncnn::Mat::to_pixels((int)this, a2, a3);
    return;
  }
  v9 = (unsigned __int8 *)a4;
  if ( (unsigned int)a3 >> 16 << 16 )
    a3 >>= 16;
  if ( (unsigned int)(a3 - 1) <= 1 )
  {
    v10 = (unsigned __int8 *)operator new[](3 * *((_DWORD *)this + 4) * v5);
    ncnn::Mat::to_pixels((int)v6, v10, v8);
    ncnn::resize_bilinear_c3(
      (ncnn *)v10,
      *((const unsigned __int8 **)v6 + 3),
      *((_DWORD *)v6 + 4),
      (int)v7,
      v9,
      a5,
      v11);
LABEL_8:
    operator delete[](v10);
    return;
  }
  if ( a3 == 4 )
  {
    v10 = (unsigned __int8 *)operator new[](*((_DWORD *)this + 4) * v5);
    ncnn::Mat::to_pixels((int)v6, v10, v8);
    ncnn::resize_bilinear_c1(
      (ncnn *)v10,
      *((const unsigned __int8 **)v6 + 3),
      *((_DWORD *)v6 + 4),
      (int)v7,
      v9,
      a5,
      v11);
    goto LABEL_8;
  }
  if ( a3 == 8 )
  {
    v10 = (unsigned __int8 *)operator new[](4 * *((_DWORD *)this + 4) * v5);
    ncnn::Mat::to_pixels((int)v6, v10, v8);
    ncnn::resize_bilinear_c4(
      (ncnn *)v10,
      *((const unsigned __int8 **)v6 + 3),
      *((_DWORD *)v6 + 4),
      (int)v7,
      v9,
      a5,
      v11);
    goto LABEL_8;
  }
}

// ALL OK, 16 function(s) have been successfully decompiled
