/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall nna_load_op(char *a1);
int __fastcall nna_load_op2(char *a1);
int __fastcall dump_engine(_DWORD *a1);
void *nna_get_engine(void);
signed int __fastcall nna_init_engine(unsigned int a1, unsigned int a2, unsigned int a3);
char *__fastcall nna_get_op(int a1);
unsigned int __fastcall nna_get_fm_addr(unsigned int a1);
unsigned int __fastcall nna_get_wt_addr(unsigned int a1);
unsigned int __fastcall nna_get_bs_addr(unsigned int a1);
// FILE *fopen(const char *filename, const char *modes);
// int printf(const char *format, ...);
// int fseek(FILE *stream, int off, int whence);
// int ftell(FILE *stream);
// size_t fread(void *ptr, size_t size, size_t n, FILE *stream);
// int fclose(FILE *stream);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN g_nna_op; // weak
_UNKNOWN unk_80C; // weak
_UNKNOWN g_nna_engine; // weak
_UNKNOWN unk_F8C; // weak
_UNKNOWN unk_F90; // weak
int dword_F94 = 1610612736; // weak
int dword_F98 = 1342177280; // weak
int dword_F9C = 1526726656; // weak
char byte_FA8 = '\0'; // weak
char byte_FA9 = '\0'; // weak
char byte_FAA = '\0'; // weak
char byte_FAB = '\0'; // weak
char byte_FAC = '\0'; // weak
char byte_FAD = '\0'; // weak
char byte_FAE = '\0'; // weak
int dword_FB0 = 0; // weak
char byte_FB4 = '\0'; // weak
char algn_FB5[11] = { '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0' }; // weak
int dword_FC0 = 0; // weak
char byte_FC8 = '\0'; // weak
char byte_FC9 = '\0'; // weak
char byte_FCA = '\0'; // weak
char byte_FCB = '\0'; // weak
char byte_FCC = '\0'; // weak
char byte_FCD = '\0'; // weak
char byte_FCE = '\0'; // weak
int dword_FD0 = 0; // weak
char byte_FD4 = '\0'; // weak
char algn_FD5[11] = { '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0' }; // weak
int dword_FE0 = 0; // weak


//----- (00000004) --------------------------------------------------------
int __fastcall nna_load_op(char *a1)
{
  char *v1; // r5
  FILE *v2; // r0
  FILE *v3; // r4
  char *v4; // r1
  int v5; // r5

  v1 = a1;
  v2 = fopen(a1, "rb");
  v3 = v2;
  if ( v2 )
  {
    fseek(v2, 0, 2);
    v5 = ftell(v3);
    fseek(v3, 0, 0);
    fread(&g_nna_op, 0x47Cu, 1u, v3);
    fclose(v3);
  }
  else
  {
    v4 = v1;
    v5 = 0;
    printf("\n#!!!open file %s fail", v4);
  }
  return v5;
}

//----- (000000A0) --------------------------------------------------------
int __fastcall nna_load_op2(char *a1)
{
  char *v1; // r6
  FILE *v2; // r0
  FILE *v3; // r4
  int v4; // r5
  size_t v6; // r0

  v1 = a1;
  v2 = fopen(a1, "rb");
  v3 = v2;
  if ( v2 )
  {
    fseek(v2, 0, 2);
    v4 = ftell(v3);
    fseek(v3, 0, 0);
    v6 = fread(&unk_80C, 0x47Cu, 1u, v3);
    printf("\n# load op file :%s [%d]", v1, v6);
    fclose(v3);
  }
  else
  {
    v4 = 0;
    printf("\n#!!!open file %s fail", v1);
  }
  return v4;
}

//----- (0000016C) --------------------------------------------------------
int __fastcall dump_engine(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n ENGINE ------------- :");
  printf("\n status               :%d", *v1);
  printf("\n group_id             :%d", v1[1]);
  printf("\n base_nna             :%x", v1[2]);
  printf("\n base_fm              :%x", v1[3]);
  printf("\n base_wt              :%x", v1[4]);
  return printf("\n base_bs              :%x", v1[5]);
}

//----- (0000020C) --------------------------------------------------------
void *nna_get_engine(void)
{
  return &g_nna_engine;
}

//----- (00000244) --------------------------------------------------------
signed int __fastcall nna_init_engine(unsigned int a1, unsigned int a2, unsigned int a3)
{
  signed int result; // r0

  dword_F9C = a3;
  dword_F94 = a1;
  result = 1;
  dword_FC0 = (int)&g_nna_op;
  dword_F98 = a2;
  byte_FA8 = 0;
  unk_F8C = 0;
  unk_F90 = 2147483648;
  byte_FA9 = 0;
  byte_FAA = 0;
  byte_FAB = 0;
  byte_FAC = 0;
  byte_FAD = 0;
  byte_FAE = 0;
  dword_FB0 = -1;
  byte_FB4 = 0;
  *(_QWORD *)&algn_FB5[3] = 0LL;
  byte_FC8 = 1;
  byte_FC9 = 0;
  byte_FCA = 0;
  byte_FCB = 0;
  byte_FCC = 0;
  byte_FCD = 0;
  byte_FCE = 0;
  dword_FD0 = -1;
  byte_FD4 = 0;
  *(_QWORD *)&algn_FD5[3] = 0LL;
  dword_FE0 = (int)&unk_80C;
  return result;
}
// F94: using guessed type int dword_F94;
// F98: using guessed type int dword_F98;
// F9C: using guessed type int dword_F9C;
// FA8: using guessed type char byte_FA8;
// FA9: using guessed type char byte_FA9;
// FAA: using guessed type char byte_FAA;
// FAB: using guessed type char byte_FAB;
// FAC: using guessed type char byte_FAC;
// FAD: using guessed type char byte_FAD;
// FAE: using guessed type char byte_FAE;
// FB0: using guessed type int dword_FB0;
// FB4: using guessed type char byte_FB4;
// FC0: using guessed type int dword_FC0;
// FC8: using guessed type char byte_FC8;
// FC9: using guessed type char byte_FC9;
// FCA: using guessed type char byte_FCA;
// FCB: using guessed type char byte_FCB;
// FCC: using guessed type char byte_FCC;
// FCD: using guessed type char byte_FCD;
// FCE: using guessed type char byte_FCE;
// FD0: using guessed type int dword_FD0;
// FD4: using guessed type char byte_FD4;
// FE0: using guessed type int dword_FE0;

//----- (00000300) --------------------------------------------------------
char *__fastcall nna_get_op(int a1)
{
  return (char *)&g_nna_op + 1148 * a1;
}

//----- (00000324) --------------------------------------------------------
unsigned int __fastcall nna_get_fm_addr(unsigned int a1)
{
  return a1 + *((_DWORD *)nna_get_engine() + 3);
}

//----- (00000348) --------------------------------------------------------
unsigned int __fastcall nna_get_wt_addr(unsigned int a1)
{
  return a1 + *((_DWORD *)nna_get_engine() + 4);
}

//----- (0000036C) --------------------------------------------------------
unsigned int __fastcall nna_get_bs_addr(unsigned int a1)
{
  return a1 + *((_DWORD *)nna_get_engine() + 5);
}

// ALL OK, 9 function(s) have been successfully decompiled
