/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall fill_dummy_bias_cfg(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall fill_dummy_bias_x1(int a1, int a2, int a3, int a4, int a5, int a6, int a7);
int __fastcall fill_dummy_bias_x2(int a1, int a2);
int __fastcall fill_dummy_pool(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
int __fastcall fill_dummy_conv(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10);
int __fastcall nna_conv_act_dummy(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20);
int __fastcall nna_conv_act_pool_dummy(unsigned int a1, unsigned int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24);
int __fastcall nna_inner_product_dummy(unsigned int a1, unsigned int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14);
// int printf(const char *format, ...);
// _DWORD __cdecl nna_conv_get_entry_per_slice(int, int, int, int); idb
// _DWORD __cdecl nna_conv_get_output_w(int, int, int, int, int); idb
// _DWORD __cdecl nna_conv_get_output_h(int, int, int, int, int); idb

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN g_dummy_reg; // weak
_UNKNOWN unk_8AE; // weak
_UNKNOWN unk_8B0; // weak
_UNKNOWN unk_8B2; // weak
_UNKNOWN unk_8B4; // weak
_UNKNOWN unk_8B8; // weak
_UNKNOWN unk_8BC; // weak
_UNKNOWN unk_8BF; // weak
_UNKNOWN unk_8C0; // weak
_UNKNOWN unk_8C1; // weak
_UNKNOWN unk_8C2; // weak
_UNKNOWN unk_8C3; // weak
_UNKNOWN unk_8C4; // weak
_UNKNOWN unk_8C8; // weak
__int16 word_8CC; // weak
__int16 word_8CE; // weak
__int16 word_8D0; // weak
int dword_8D4; // weak
int dword_8D8; // weak
char byte_8DC; // weak
char algn_8DD[3]; // weak
char byte_8E0; // weak
char byte_8E1; // weak
char byte_8E2; // weak
char byte_8E4; // weak
_UNKNOWN unk_8E8; // weak
_UNKNOWN unk_8EA; // weak
_UNKNOWN unk_8EC; // weak
_UNKNOWN unk_8F0; // weak
_UNKNOWN unk_8F4; // weak
_UNKNOWN unk_8F8; // weak
_UNKNOWN unk_8F9; // weak
_UNKNOWN unk_8FA; // weak
_UNKNOWN unk_8FB; // weak
_UNKNOWN LC0; // weak


//----- (00000004) --------------------------------------------------------
int __fastcall fill_dummy_bias_cfg(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v8; // r8
  int v9; // r5
  int v10; // r7
  int result; // r0

  v8 = a3;
  v9 = a1;
  v10 = a2;
  result = printf("\n# fill_dummy_bias_cfg  %3d %3d %3d  %d %d %d  %d %d  ", &LC0, a1, a2, a3, a4, a5, a6, a7, a8);
  word_8CC = v9 - 1;
  word_8CE = v10 - 1;
  word_8D0 = v8 - 1;
  if ( a8 )
  {
    dword_8D4 = 8 * v9;
    dword_8D8 = 8 * v9 * v10;
  }
  else
  {
    result = nna_conv_get_entry_per_slice(v9, v10, v8, 0) - 1;
    dword_8D4 = result;
    dword_8D8 = 31;
  }
  byte_8E4 = a6;
  byte_8DC = byte_8DC & 0xEF | 16 * (a8 & 1);
  return result;
}
// 8CC: using guessed type __int16 word_8CC;
// 8CE: using guessed type __int16 word_8CE;
// 8D0: using guessed type __int16 word_8D0;
// 8D4: using guessed type int dword_8D4;
// 8D8: using guessed type int dword_8D8;
// 8DC: using guessed type char byte_8DC;
// 8E4: using guessed type char byte_8E4;

//----- (000000F8) --------------------------------------------------------
int __fastcall fill_dummy_bias_x1(int a1, int a2, int a3, int a4, int a5, int a6, int a7)
{
  int v7; // r5
  int v8; // r10
  int v9; // r4
  int v10; // r8
  char v11; // r7
  int result; // r0
  unsigned int v13; // r8

  v7 = a4;
  v8 = a1;
  v9 = a6;
  v10 = a2;
  v11 = a3;
  result = printf("\n# fill_dummy_bias_x1  %d %d %d  %d %d %d %d  ", a1, a2, a3, a4, a5, a6, a7);
  if ( v8 )
    v9 = 1;
  if ( v8 )
    v10 = v9;
  v13 = __clz(v10);
  if ( v8 )
    v7 = v9;
  byte_8DC = ((byte_8DC & 0xFE | (v13 >> 5) & 1) & 0xFD | 2 * (v7 == 0)) & 0xF7 | 8 * (v9 == 0);
  byte_8E0 = v11;
  byte_8E1 = a5;
  return result;
}
// 8DC: using guessed type char byte_8DC;
// 8E0: using guessed type char byte_8E0;
// 8E1: using guessed type char byte_8E1;

//----- (000001B0) --------------------------------------------------------
int __fastcall fill_dummy_bias_x2(int a1, int a2)
{
  char v2; // r4
  int v3; // r6
  int result; // r0

  v2 = a2;
  v3 = a1;
  result = printf("\n# fill_dummy_bias_x2  %d %d  ", a1, a2);
  if ( v3 )
    v2 = 0;
  byte_8DC = byte_8DC & 0xFB | 4 * (v2 & 1);
  byte_8E2 = 0;
  return result;
}
// 8DC: using guessed type char byte_8DC;
// 8E2: using guessed type char byte_8E2;

//----- (00000218) --------------------------------------------------------
int __fastcall fill_dummy_pool(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  int v8; // r6
  int v9; // r9
  int v10; // r8
  int v11; // r7
  int v12; // ST24_4
  int v13; // r7
  int result; // r0
  int v15; // r3
  int v16; // [sp+18h] [bp-40h]
  int v17; // [sp+1Ch] [bp-3Ch]

  v8 = a4;
  v9 = a3;
  v10 = a1 + 2 * a6 - a4;
  v11 = a2 + 2 * a6 - a4;
  v16 = (a5 + v10 - 1) / a5 + 1;
  v12 = (a5 + v11 - 1) / a5;
  v17 = v12 + 1;
  v13 = v11 % a5 + a6;
  result = printf("\n# fill_dummy_pool  %3d %3d %3d  %d %d %d  %d %d ", a1, a2, a3, a4, a5, a6, a7, a8);
  byte_8DC |= 0x20u;
  unk_8E8 = (a5 + v10 - 1) / a5;
  unk_8EA = v12;
  unk_8EC = v9 - 1;
  if ( a8 )
  {
    unk_8F0 = 8 * v16;
    v15 = 8 * v16 * v17;
  }
  else
  {
    result = nna_conv_get_entry_per_slice(v16, v17, v9, 0) - 1;
    v15 = 31;
    unk_8F0 = result;
  }
  unk_8F4 = v15;
  unk_8F8 = (unk_8F8 & 0xF | 16 * (((v8 - 1) << 28 >> 28) & 0xF)) & 0xF0 | ((v8 - 1) << 28 >> 28) & 0xF;
  unk_8FA = (unk_8FA & 0xF0 | (a6 << 28 >> 28) & 0xF) & 0xF | 16 * ((a6 << 28 >> 28) & 0xF);
  unk_8FB = (unk_8FB & 0xF | 16 * (v13 & 0xF)) & 0xF0 | (v10 % a5 + a6) & 0xF;
  unk_8F9 = (unk_8F9 & 0xF0 | ((a5 - 1) << 28 >> 28) & 0xF) & 0xF | 16 * (((a5 - 1) << 28 >> 28) & 0xF);
  return result;
}
// 8DC: using guessed type char byte_8DC;

//----- (000003D0) --------------------------------------------------------
int __fastcall fill_dummy_conv(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10)
{
  int v10; // r11
  int v11; // r4
  int v12; // r5
  int v13; // r7
  int v14; // r9
  int v15; // r0
  int v16; // r2
  int v17; // r7
  int v18; // r2
  unsigned int v19; // r3
  int result; // r0
  unsigned int v21; // r3
  unsigned int v22; // r3
  int v23; // r3
  int v24; // [sp+2Ch] [bp-2Ch]

  v10 = a4;
  v11 = a1;
  v12 = a2;
  v13 = a3;
  printf("\n# fill_dummy_conv  %3d %3d %3d  %2d %d %d %d %d  %d %d ", a1, a2, a3, a4, a5, a6, a7, a8, a9, a10);
  v24 = nna_conv_get_output_w(v11, a5, a6, a7, a8);
  v14 = nna_conv_get_output_h(v12, a5, a6, a7, a8);
  g_dummy_reg = v11 - 1;
  unk_8AE = v12 - 1;
  unk_8B0 = v13 - 1;
  v15 = nna_conv_get_entry_per_slice(v11, v12, v13, a9);
  v16 = v13 * (unsigned __int16)a5 * (unsigned __int16)a5;
  v17 = (unsigned __int16)a5 * v13;
  if ( a9 )
    unk_8B4 = v11;
  v18 = v16 - 1;
  v19 = unk_8BC & 0xFF000000 | v18 & 0xFFFFFF;
  if ( a9 )
    LOBYTE(v18) = -2;
  unk_8BC = v19;
  result = v15 - 1;
  v21 = v19 >> 24;
  if ( a9 )
    v22 = v21 & 0xFFFFFF3F | ((v18 & 3) << 6);
  else
    LOBYTE(v22) = 0;
  if ( a9 )
    LOBYTE(v22) = v22 & 0xC0;
  unk_8BF = v22;
  v23 = ((unsigned __int16)a5 - 1) << 28 >> 28;
  unk_8C0 = unk_8C0 & 0xF0 | v23 & 0xF;
  unk_8C1 = unk_8C1 & 0xF0 | v23 & 0xF;
  unk_8C2 = a8 & 0xF;
  unk_8C3 = a8 & 0xF;
  if ( !a9 )
    v11 *= 8;
  if ( !a9 )
    unk_8B4 = v11;
  unk_8B2 = result;
  algn_8DD[0] &= 0xFCu;
  unk_8B8 = v11 * v12;
  unk_8C4 = v10 * (unsigned __int16)a5 * v17;
  unk_8C8 = v14 * v24 - 1;
  byte_8DC = (byte_8DC & 0x7F | ((a9 & 1) << 7)) & 0xBF | ((a10 & 1) << 6);
  return result;
}
// 8DC: using guessed type char byte_8DC;

//----- (000005B8) --------------------------------------------------------
int __fastcall nna_conv_act_dummy(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20)
{
  int v20; // r11
  int v21; // r0
  int v22; // r1
  int v23; // r0
  int result; // r0

  fill_dummy_conv(a7, a8, a9, a10, a11, a12, a13, a14, a18, a20);
  v20 = nna_conv_get_output_w(a7, a11, a12, a13, a14);
  v21 = nna_conv_get_output_h(a8, a11, a12, a13, a14);
  fill_dummy_bias_cfg(v20, v21, a10, 0, (unsigned __int16)a5 >> 8, (unsigned __int8)a5, a18, a19);
  if ( a15 )
    fill_dummy_bias_x1(0, 0, BYTE1(a6), 0, (unsigned __int8)a6, 1, 0);
  else
    fill_dummy_bias_x1(1, 0, BYTE1(a6), 0, (unsigned __int8)a6, 1, 0);
  if ( a16 )
  {
    v22 = 1;
    v23 = 0;
  }
  else
  {
    v22 = 0;
    v23 = 1;
  }
  result = fill_dummy_bias_x2(v23, v22);
  byte_8DC &= 0xDFu;
  return result;
}
// 8DC: using guessed type char byte_8DC;

//----- (00000700) --------------------------------------------------------
int __fastcall nna_conv_act_pool_dummy(unsigned int a1, unsigned int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24)
{
  int v24; // r11
  int v25; // r1

  nna_conv_act_dummy(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a22, 0, a24);
  v24 = nna_conv_get_output_w(a7, a11, a12, a13, a14);
  v25 = nna_conv_get_output_h(a8, a11, a12, a13, a14);
  return fill_dummy_pool(v24, v25, a10, a19, a20, a21, a22, a23);
}

//----- (0000081C) --------------------------------------------------------
int __fastcall nna_inner_product_dummy(unsigned int a1, unsigned int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14)
{
  return nna_conv_act_dummy(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, 1, 1, 1, 0, a11, 0, 0, a12, a13, a14);
}

// ALL OK, 8 function(s) have been successfully decompiled
