/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall nna_net_hd_run(unsigned int a1, int a2, int a3);
int __fastcall nna_net_hd_init(int a1, int a2, int a3);
int __fastcall nna_net_hd(unsigned __int8 *a1, int a2, int a3, int a4);
int __fastcall nna_net_hd_post(char *a1, char *a2);
unsigned int nna_net_hd_get_score_size(void);
unsigned int nna_net_hd_get_location_size(void);
int nna_net_hd_get_score_w(void);
int nna_net_hd_get_score_h(void);
int nna_net_hd_get_score_c(void);
int nna_net_hd_get_score_fixpoint(void);
int nna_net_hd_get_location_fixpoint(void);
int nna_net_hd_case(void);
int __fastcall nna_hd_ddr_run(unsigned int a1, unsigned int a2, int a3, int a4, unsigned int a5);
int GLOBAL__sub_I_nna_hd_cpp();
// int __fastcall nna_net_init(_DWORD); weak
// int __fastcall nna_net_load_hyper(_DWORD); weak
// int __fastcall xramcpy(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int printf(const char *format, ...);
// int __fastcall nna_net_forward(_DWORD); weak
// int __fastcall nna_net_load_data(_DWORD); weak
// int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD); weak
// int __fastcall nna_load_ram(_DWORD, _DWORD); weak
// int __fastcall nna_net_load_quant(_DWORD); weak
// int __fastcall nna_net_dump(_DWORD); weak
// _DWORD std::ios_base::Init::Init(std::ios_base::Init *__hidden this); idb
// int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD); weak
// _DWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_8; // weak
_UNKNOWN loc_4C; // weak
_UNKNOWN loc_50; // weak
_UNKNOWN loc_54; // weak
_UNKNOWN std::__ioinit; // weak
_UNKNOWN unk_984; // weak
_UNKNOWN unk_990; // weak
_UNKNOWN unk_994; // weak
_UNKNOWN unk_998; // weak
_UNKNOWN unk_AA0; // weak
_UNKNOWN unk_AAC; // weak
_UNKNOWN unk_AB0; // weak
_UNKNOWN unk_AB4; // weak
void *hd_info = &unk_6468; // weak
int dword_8718 = 1610612736; // weak
int *off_8720 = &hd_io_data; // weak
void *off_8728 = &hd_layer; // weak
// extern _UNKNOWN _dso_handle; weak


//----- (00000004) --------------------------------------------------------
int __fastcall nna_net_hd_run(unsigned int a1, int a2, int a3)
{
  int v3; // r6
  signed __int64 v4; // d8
  void *v5; // r3
  int v6; // r5
  signed __int64 v7; // d8
  int v8; // r10

  v3 = a3;
  v4 = vdup_n_s32(a1).n64_i64[0];
  v5 = off_8728;
  v6 = a2;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)off_8728) = a2;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)v5) = a3;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v5) = 1;
  nna_net_init(&hd_info);
  nna_net_load_hyper(&hd_info);
  v7 = vshrd_n_s64(v4, 0x20u);
  v8 = *off_8720;
  *(_DWORD *)((char *)&loc_8 + (_DWORD)off_8720) = v3 * v6;
  xramcpy(v8, 0, v7, HIDWORD(v7), v3 * v6, 1);
  printf("\n### +++nna_net_hd_run[%3d %3d %3d] target:%x target2:%x file_sz:%d\n", v6, v3, 1, v8, 0, v7, v3 * v6);
  return nna_net_forward(&hd_info);
}
// 8700: using guessed type void *hd_info;
// 8720: using guessed type int *off_8720;
// 8728: using guessed type void *off_8728;
// 87F0: using guessed type int __fastcall nna_net_init(_DWORD);
// 87F4: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// 87F8: using guessed type int __fastcall xramcpy(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 8800: using guessed type int __fastcall nna_net_forward(_DWORD);

//----- (000000E0) --------------------------------------------------------
int __fastcall nna_net_hd_init(int a1, int a2, int a3)
{
  void *v3; // r3

  v3 = off_8728;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)off_8728) = a1;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)v3) = a2;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v3) = a3;
  return nna_net_init(&hd_info);
}
// 8700: using guessed type void *hd_info;
// 8728: using guessed type void *off_8728;
// 87F0: using guessed type int __fastcall nna_net_init(_DWORD);

//----- (0000011C) --------------------------------------------------------
int __fastcall nna_net_hd(unsigned __int8 *a1, int a2, int a3, int a4)
{
  int v4; // r7
  int v5; // ST1C_4
  int v6; // r6
  int v7; // r8
  signed __int64 v8; // d8
  void *v9; // r3
  int v10; // r10

  v4 = a3;
  v5 = a4;
  v6 = a2;
  v7 = a3 * a2;
  v8 = vshrd_n_s64(vdup_n_s32((unsigned int)a1).n64_i64[0], 0x20u);
  v9 = off_8728;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)off_8728) = a2;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)v9) = a3;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v9) = 1;
  nna_net_init(&hd_info);
  nna_net_load_hyper(&hd_info);
  nna_net_load_data(&hd_info);
  v10 = *off_8720;
  *(_DWORD *)((char *)&loc_8 + (_DWORD)off_8720) = v7;
  xramcpy(v10, 0, v8, HIDWORD(v8), v7, 1);
  printf("\n### +++nna_net_hd[%3d %3d %3d] target:%x target2:%x file_sz:%d\n", v6, v4, v5, v10, 0, v8, v7);
  return nna_net_forward(&hd_info);
}
// 8700: using guessed type void *hd_info;
// 8720: using guessed type int *off_8720;
// 8728: using guessed type void *off_8728;
// 87F0: using guessed type int __fastcall nna_net_init(_DWORD);
// 87F4: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// 87F8: using guessed type int __fastcall xramcpy(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 8800: using guessed type int __fastcall nna_net_forward(_DWORD);
// 8808: using guessed type int __fastcall nna_net_load_data(_DWORD);

//----- (00000200) --------------------------------------------------------
int __fastcall nna_net_hd_post(char *a1, char *a2)
{
  char *v2; // r4
  int v3; // r12
  int v4; // r1
  int v5; // r0
  int v6; // r1

  v2 = a2;
  v3 = *(_DWORD *)((char *)&unk_998 + (_DWORD)(off_8720 + 1024));
  v4 = v3 + 7;
  if ( v3 + 7 < 0 )
    v4 = v3 + 14;
  xramcpy(
    a1,
    (signed int)a1 >> 31,
    *(_DWORD *)((char *)&unk_984 + (_DWORD)(off_8720 + 1024)),
    0,
    *(_DWORD *)((char *)&unk_994 + (_DWORD)(off_8720 + 1024))
  * *(_DWORD *)((char *)&unk_990 + (_DWORD)(off_8720 + 1024))
  * (v4 & 0xFFFFFFF8),
    2);
  v5 = *(_DWORD *)((char *)&unk_AB4 + (_DWORD)(off_8720 + 1024));
  v6 = v5 + 7;
  if ( v5 + 7 < 0 )
    v6 = v5 + 14;
  return xramcpy(
           v2,
           (signed int)v2 >> 31,
           *(_DWORD *)((char *)&unk_AA0 + (_DWORD)(off_8720 + 1024)),
           0,
           *(_DWORD *)((char *)&unk_AB0 + (_DWORD)(off_8720 + 1024))
         * *(_DWORD *)((char *)&unk_AAC + (_DWORD)(off_8720 + 1024))
         * (v6 & 0xFFFFFFF8),
           2);
}
// 8720: using guessed type int *off_8720;
// 87F8: using guessed type int __fastcall xramcpy(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (000002C0) --------------------------------------------------------
unsigned int nna_net_hd_get_score_size(void)
{
  int v0; // r0
  int v1; // r3

  v0 = *(_DWORD *)((char *)&unk_998 + (_DWORD)(off_8720 + 1024));
  v1 = v0 + 7;
  if ( v0 + 7 < 0 )
    v1 = v0 + 14;
  return *(_DWORD *)((char *)&unk_994 + (_DWORD)(off_8720 + 1024))
       * *(_DWORD *)((char *)&unk_990 + (_DWORD)(off_8720 + 1024))
       * (v1 & 0xFFFFFFF8);
}
// 8720: using guessed type int *off_8720;

//----- (00000310) --------------------------------------------------------
unsigned int nna_net_hd_get_location_size(void)
{
  int v0; // r0
  int v1; // r3

  v0 = *(_DWORD *)((char *)&unk_AB4 + (_DWORD)(off_8720 + 1024));
  v1 = v0 + 7;
  if ( v0 + 7 < 0 )
    v1 = v0 + 14;
  return *(_DWORD *)((char *)&unk_AB0 + (_DWORD)(off_8720 + 1024))
       * *(_DWORD *)((char *)&unk_AAC + (_DWORD)(off_8720 + 1024))
       * (v1 & 0xFFFFFFF8);
}
// 8720: using guessed type int *off_8720;

//----- (00000360) --------------------------------------------------------
int nna_net_hd_get_score_w(void)
{
  return *(_DWORD *)((char *)&unk_990 + (_DWORD)(off_8720 + 1024));
}
// 8720: using guessed type int *off_8720;

//----- (00000394) --------------------------------------------------------
int nna_net_hd_get_score_h(void)
{
  return *(_DWORD *)((char *)&unk_994 + (_DWORD)(off_8720 + 1024));
}
// 8720: using guessed type int *off_8720;

//----- (000003C8) --------------------------------------------------------
int nna_net_hd_get_score_c(void)
{
  return *(_DWORD *)((char *)&unk_998 + (_DWORD)(off_8720 + 1024));
}
// 8720: using guessed type int *off_8720;

//----- (000003FC) --------------------------------------------------------
int nna_net_hd_get_score_fixpoint(void)
{
  return nna_net_get_quant(&hd_info, 0, 23);
}
// 8700: using guessed type void *hd_info;
// 8810: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (0000043C) --------------------------------------------------------
int nna_net_hd_get_location_fixpoint(void)
{
  return nna_net_get_quant(&hd_info, 0, 24);
}
// 8700: using guessed type void *hd_info;
// 8810: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (0000047C) --------------------------------------------------------
int nna_net_hd_case(void)
{
  nna_load_ram(dword_8718, off_8720 + 7);
  printf("\n# hd_info. w=%d", *(_DWORD *)((char *)&loc_4C + (_DWORD)off_8728));
  printf("\n# hd_info. h=%d", *(_DWORD *)((char *)&loc_50 + (_DWORD)off_8728));
  printf("\n# hd_info. c=%d", *(_DWORD *)((char *)&loc_54 + (_DWORD)off_8728));
  nna_net_init(&hd_info);
  nna_net_load_hyper(&hd_info);
  nna_net_load_data(&hd_info);
  nna_net_load_quant(&hd_info);
  nna_net_forward(&hd_info);
  return nna_net_dump(&hd_info);
}
// 8700: using guessed type void *hd_info;
// 8718: using guessed type int dword_8718;
// 8720: using guessed type int *off_8720;
// 8728: using guessed type void *off_8728;
// 87F0: using guessed type int __fastcall nna_net_init(_DWORD);
// 87F4: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// 8800: using guessed type int __fastcall nna_net_forward(_DWORD);
// 8808: using guessed type int __fastcall nna_net_load_data(_DWORD);
// 8814: using guessed type int __fastcall nna_load_ram(_DWORD, _DWORD);
// 8818: using guessed type int __fastcall nna_net_load_quant(_DWORD);
// 881C: using guessed type int __fastcall nna_net_dump(_DWORD);

//----- (00000530) --------------------------------------------------------
int __fastcall nna_hd_ddr_run(unsigned int a1, unsigned int a2, int a3, int a4, unsigned int a5)
{
  unsigned int v5; // r9
  __int64 v6; // r6
  void *v7; // r1
  int v8; // r11
  unsigned int v9; // r0
  unsigned int v10; // r0
  int v11; // r4
  unsigned int v12; // r0
  unsigned int v13; // r4
  unsigned int v14; // r0
  char v16; // [sp+8h] [bp-4028h]

  v5 = a1;
  v6 = (signed int)&v16;
  v7 = off_8728;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)off_8728) = a4;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)v7) = a3;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v7) = 1;
  dword_8718 = a5;
  nna_net_init(&hd_info);
  nna_net_load_hyper(&hd_info);
  nna_net_load_data(&hd_info);
  nna_net_load_quant(&hd_info);
  nna_net_forward(&hd_info);
  v8 = *(_DWORD *)((char *)&unk_984 + (_DWORD)(off_8720 + 1024));
  v9 = nna_net_hd_get_score_size();
  xramcpy(v6, HIDWORD(v6), v8, 0, v9, 2);
  v10 = nna_net_hd_get_score_size();
  xramcpy(v5, 0, v6, HIDWORD(v6), v10, 1);
  v11 = *(_DWORD *)((char *)&unk_AA0 + (_DWORD)(off_8720 + 1024));
  v12 = nna_net_hd_get_location_size();
  xramcpy(v6, HIDWORD(v6), v11, 0, v12, 2);
  v13 = nna_net_hd_get_score_size();
  v14 = nna_net_hd_get_location_size();
  return xramcpy(v13 + v5, 0, v6, HIDWORD(v6), v14, 1);
}
// 8700: using guessed type void *hd_info;
// 8718: using guessed type int dword_8718;
// 8720: using guessed type int *off_8720;
// 8728: using guessed type void *off_8728;
// 87F0: using guessed type int __fastcall nna_net_init(_DWORD);
// 87F4: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// 87F8: using guessed type int __fastcall xramcpy(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 8800: using guessed type int __fastcall nna_net_forward(_DWORD);
// 8808: using guessed type int __fastcall nna_net_load_data(_DWORD);
// 8818: using guessed type int __fastcall nna_net_load_quant(_DWORD);

//----- (00000664) --------------------------------------------------------
int GLOBAL__sub_I_nna_hd_cpp()
{
  std::ios_base::Init::Init((std::ios_base::Init *)&std::__ioinit);
  return _aeabi_atexit(&std::__ioinit, &std::ios_base::Init::~Init, &_dso_handle);
}
// 8824: using guessed type int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD);
// 8828: using guessed type _DWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this);

// ALL OK, 14 function(s) have been successfully decompiled
