/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall nna_pool_data_stride(unsigned int a1, int a2, int a3, int a4);
int __fastcall nna_pool_get_output_h(int a1, int a2, int a3, int a4);
_DWORD __fastcall nna_pool_get_output_w(int, int, int, int); // idb
int __fastcall nna_pool_hw(unsigned int a1, unsigned int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13);
int __fastcall nna_pool(unsigned int a1, unsigned int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11);
// _DWORD __cdecl xregw(unsigned int, unsigned int); idb
// _DWORD __cdecl nna_pdp_set_producer(int, int); idb
// _DWORD __cdecl nna_pdp_enable(int, int); idb
// _DWORD __cdecl nna_wait_done(int, int); idb


//----- (00000004) --------------------------------------------------------
int __fastcall nna_pool_data_stride(unsigned int a1, int a2, int a3, int a4)
{
  int v4; // r4
  unsigned int v5; // r5
  int v6; // r7
  int v7; // r6

  v4 = a2;
  v5 = a1;
  v6 = a3;
  v7 = a4;
  xregw(0xA024u, a1);
  xregw(0xA028u, v4);
  xregw(0xB068u, v5);
  xregw(0xB06Cu, v4);
  xregw(0xB078u, v6);
  return xregw(0xB07Cu, v7);
}

//----- (00000070) --------------------------------------------------------
int __fastcall nna_pool_get_output_h(int a1, int a2, int a3, int a4)
{
  return (a1 + 2 * a4 - a2 + a3 - 1) / a3 + 1;
}

//----- (000000B0) --------------------------------------------------------
int __fastcall nna_pool_hw(unsigned int a1, unsigned int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13)
{
  unsigned int v13; // r9
  int v14; // r10
  signed int v15; // r7
  unsigned int v16; // r3
  int v17; // r8
  unsigned int v18; // r10
  int v19; // r4
  unsigned int v20; // r6
  unsigned int v21; // r5
  unsigned int v22; // r8
  int v24; // [sp+4h] [bp-5Ch]
  int v25; // [sp+8h] [bp-58h]
  int v26; // [sp+Ch] [bp-54h]
  int v27; // [sp+10h] [bp-50h]
  int v28; // [sp+18h] [bp-48h]
  int v29; // [sp+20h] [bp-40h]
  int v30; // [sp+28h] [bp-38h]
  unsigned int v31; // [sp+2Ch] [bp-34h]

  v15 = a2;
  v27 = a4;
  v26 = a3;
  v16 = (unsigned int)a11 >> 8;
  if ( (unsigned int)a11 >> 8 )
  {
    v16 = (unsigned __int8)a11;
    v25 = (unsigned __int8)a11;
  }
  else
  {
    v25 = a11;
  }
  if ( (unsigned int)a11 >> 8 )
    v16 = ((unsigned int)a11 >> 16) & 0xFF;
  else
    v14 = a11;
  if ( (unsigned int)a11 >> 8 )
    v24 = v16;
  else
    v13 = a11;
  if ( (unsigned int)a11 >> 8 )
    v14 = (unsigned __int16)a11 >> 8;
  v17 = a5 + v25 + v14 - a9;
  v31 = a1;
  if ( (unsigned int)a11 >> 8 )
    v13 = (unsigned int)a11 >> 24;
  else
    v24 = a11;
  v28 = (a10 + v17 - 1) / a10;
  v29 = v17 % a10 + v14;
  v18 = a6 - 1;
  v19 = a10 - 1;
  v20 = 8 * nna_pool_get_output_w(a3, a9, a10, a11);
  v21 = a9 - 1;
  v30 = v20 * nna_pool_get_output_h(v27, a9, a10, a11);
  v22 = a7 - 1;
  if ( v15 )
  {
    xregw(0xA00Cu, a5 - 1);
    xregw(0xA010u, v18);
    xregw(0xA014u, v22);
    xregw(0xA01Cu, v15);
    xregw(0xA024u, 8 * v26);
    xregw(0xA028u, 8 * v26 * v27);
    xregw(0xA02Cu, 1u);
    xregw(0xA038u, v21 | 16 * v19);
    xregw(0xA03Cu, v25);
    xregw(0xB068u, 8 * v26);
    v15 = 1;
    xregw(0xB06Cu, 8 * v26 * v27);
  }
  else
  {
    xregw(0xA018u, 0);
  }
  xregw(0xB00Cu, a5 - 1);
  xregw(0xB010u, v18);
  xregw(0xB014u, v22);
  xregw(0xB018u, v28);
  xregw(0xB01Cu, (signed int)(v13 + a6 + v24 - a9 + a10 - 1) / a10);
  xregw(0xB020u, v22);
  xregw(0xB024u, a8 | 16 * v15);
  xregw(0xB034u, (v19 << 16) | (v19 << 20) | v21 | (v21 << 8));
  xregw(0xB038u, v21);
  xregw(0xB03Cu, v21);
  xregw(0xB040u, v25 | 16 * v24 | ((v13 + (signed int)(v24 + a6 + v13 - a9) % a10) << 12) | (v29 << 8));
  xregw(0xB044u, 0);
  xregw(0xB048u, 0);
  xregw(0xB04Cu, 0);
  xregw(0xB050u, 0);
  xregw(0xB054u, 0);
  xregw(0xB058u, 0);
  xregw(0xB05Cu, 0);
  xregw(0xB028u, 0);
  xregw(0xB070u, v31);
  xregw(0xB078u, v20);
  xregw(0xB07Cu, v30);
  xregw(0xB080u, 1u);
  return xregw(0xB084u, 0);
}

//----- (00000400) --------------------------------------------------------
int __fastcall nna_pool(unsigned int a1, unsigned int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11)
{
  int v11; // r5
  unsigned int v12; // r7
  unsigned int v13; // r6
  int v14; // r4

  v11 = a4;
  v12 = a2;
  v13 = a1;
  v14 = a3;
  nna_pdp_set_producer(0, 0);
  nna_pool_hw(v13, v12, v14, v11, v14, v11, a5, a6, a7, a8, a9, a10, a11);
  nna_pdp_enable(0, 0);
  return nna_wait_done(16, 16);
}

// ALL OK, 4 function(s) have been successfully decompiled
