/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall dump_bdma(_DWORD *a1);
int __fastcall dump_blob(_DWORD *a1);
int __fastcall dump_cvt(_DWORD *a1);
int __fastcall dump_sdp_op(_DWORD *a1);
int __fastcall dump_conv_param(_DWORD *a1);
int __fastcall dump_conv(_DWORD *a1);
int __fastcall dump_sdp_param(_DWORD *a1);
int __fastcall dump_sdp(_DWORD *a1);
int __fastcall dump_pdp_param(_DWORD *a1);
int __fastcall dump_pdp(_DWORD *a1);
int __fastcall dump_cdp(_DWORD *a1);
int __fastcall dump_nms(_DWORD *a1);
int __fastcall dump_lsc_param(_DWORD *a1);
int __fastcall dump_lsc(_DWORD *a1);
int __fastcall dump_nna_op(_DWORD *a1);
signed int __fastcall nna_reg_dump(unsigned int a1);
// int printf(const char *format, ...);
// int putchar(int c);
// int sprintf(char *s, const char *format, ...);
// FILE *fopen(const char *filename, const char *modes);
// _DWORD __cdecl nna_reg_read(unsigned int); idb
// int fprintf(FILE *stream, const char *format, ...);
// int fclose(FILE *stream);


//----- (00000004) --------------------------------------------------------
int __fastcall dump_bdma(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n BDMA :");
  printf("\n enable               :%d", *v1);
  printf("\n cmd_type             :%d", v1[19]);
  return putchar(10);
}

//----- (0000005C) --------------------------------------------------------
int __fastcall dump_blob(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n BLOB :");
  printf("\n type                 :%d", *v1);
  printf("\n address              :%08x", v1[1]);
  printf("\n bin_file             :%d", v1[2]);
  printf("\n size                 :%d", v1[3]);
  printf("\n width                :%d", v1[4]);
  printf("\n height               :%d", v1[5]);
  printf("\n channel              :%d", v1[6]);
  printf("\n line_stride          :%d", v1[7]);
  printf("\n surf_stride          :%d", v1[8]);
  return putchar(10);
}

//----- (00000140) --------------------------------------------------------
int __fastcall dump_cvt(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n CVT :");
  printf("\n enable               :%d", *v1);
  printf("\n scale                :%d", v1[1]);
  printf("\n truncate             :%d", v1[2]);
  printf("\n offset               :%d", v1[3]);
  return putchar(10);
}

//----- (000001C0) --------------------------------------------------------
int __fastcall dump_sdp_op(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n SDP_OP :");
  printf("\n enable               :%d", *v1);
  printf("\n alu_type             :%d", v1[1]);
  printf("\n alu_src              :%d", v1[2]);
  printf("\n mul_src              :%d", v1[3]);
  printf("\n mode                 :%d", v1[4]);
  printf("\n act                  :%d", v1[5]);
  printf("\n shift_value          :%d", v1[6]);
  printf("\n truncate             :%d", v1[7]);
  printf("\n precision            :%d", v1[8]);
  printf("\n alu_operand          :%d", v1[9]);
  printf("\n mul_operand          :%d", v1[10]);
  dump_cvt(v1 + 11);
  dump_cvt(v1 + 15);
  return putchar(10);
}

//----- (000002DC) --------------------------------------------------------
int __fastcall dump_conv_param(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n CONV_PARAM :");
  printf("\n num_output           :%d", *v1);
  printf("\n kernel_w             :%d", v1[1]);
  printf("\n kernel_h             :%d", v1[2]);
  printf("\n dilation_w           :%d", v1[3]);
  printf("\n dilation_h           :%d", v1[4]);
  printf("\n stride_w             :%d", v1[5]);
  printf("\n stride_h             :%d", v1[6]);
  printf("\n pad_left             :%d", v1[7]);
  printf("\n pad_right            :%d", v1[8]);
  printf("\n pad_top              :%d", v1[9]);
  printf("\n pad_bottom           :%d", v1[10]);
  printf("\n bias_en              :%d", v1[11]);
  printf("\n bias_term            :%d", v1[12]);
  printf("\n img_mode             :%d", v1[13]);
  printf("\n pix_format           :%d", v1[14]);
  printf("\n lsc_rom_enable       :%d", v1[15]);
  printf("\n lsc_net_type         :%d", v1[16]);
  printf("\n lsc_layer_start      :%d", v1[17]);
  printf("\n reuse_slices         :%d", v1[18]);
  printf("\n bank_wt              :%d", v1[19]);
  printf("\n bank_dt              :%d", v1[20]);
  printf("\n data_reuse           :%d", v1[21]);
  printf("\n weight_reuse         :%d", v1[22]);
  printf("\n skip_data_rls        :%d", v1[23]);
  printf("\n skip_weight_rls      :%d", v1[24]);
  printf("\n rls_slices           :%d", v1[25]);
  printf("\n mean_format          :%d", v1[26]);
  printf("\n mean_rygu            :%d", v1[27]);
  printf("\n mean_bvax            :%d", v1[28]);
  printf("\n entry_per_slice      :%d", v1[29]);
  return putchar(10);
}

//----- (00000564) --------------------------------------------------------
int __fastcall dump_conv(_DWORD *a1)
{
  _DWORD *v1; // r4
  _DWORD *v2; // r5

  v1 = a1;
  v2 = a1;
  printf("\n CONV :");
  printf("\n enable               :%d", *v2);
  dump_blob(v2 + 1);
  dump_blob(v1 + 10);
  dump_blob(v1 + 19);
  dump_conv_param(v1 + 28);
  return putchar(10);
}

//----- (000005CC) --------------------------------------------------------
int __fastcall dump_sdp_param(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n SDP_PARAM :");
  printf("\n src_precision        :%d", *v1);
  printf("\n dst_precision        :%d", v1[1]);
  printf("\n lut_index            :%d", v1[2]);
  printf("\n conv_mode            :%d", v1[3]);
  printf("\n batch_num            :%d", v1[4]);
  printf("\n reserved0            :%d", v1[5]);
  printf("\n batch_stride         :%d", v1[6]);
  dump_sdp_op(v1 + 7);
  dump_sdp_op(v1 + 26);
  dump_sdp_op(v1 + 45);
  dump_cvt(v1 + 64);
  return putchar(10);
}

//----- (000006A8) --------------------------------------------------------
int __fastcall dump_sdp(_DWORD *a1)
{
  _DWORD *v1; // r4
  _DWORD *v2; // r5

  v1 = a1;
  v2 = a1;
  printf("\n SDP :");
  printf("\n enable               :%d", *v2);
  dump_blob(v2 + 1);
  dump_blob(v1 + 10);
  dump_blob(v1 + 19);
  dump_blob(v1 + 28);
  dump_blob(v1 + 37);
  dump_sdp_param(v1 + 46);
  return putchar(10);
}

//----- (00000720) --------------------------------------------------------
int __fastcall dump_pdp_param(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n PDP_PARAM :");
  printf("\n pool_type            :%d", *v1);
  printf("\n kernel_w             :%d", v1[1]);
  printf("\n kernel_h             :%d", v1[2]);
  printf("\n stride_w             :%d", v1[3]);
  printf("\n stride_h             :%d", v1[4]);
  printf("\n pad_left             :%d", v1[5]);
  printf("\n pad_right            :%d", v1[6]);
  printf("\n pad_top              :%d", v1[7]);
  printf("\n pad_bottom           :%d", v1[8]);
  printf("\n pad_value            :%d", v1[9]);
  printf("\n pad_mode             :%d", v1[10]);
  return putchar(10);
}

//----- (0000082C) --------------------------------------------------------
int __fastcall dump_pdp(_DWORD *a1)
{
  _DWORD *v1; // r4
  _DWORD *v2; // r5

  v1 = a1;
  v2 = a1;
  printf("\n PDP :");
  printf("\n enable               :%d", *v2);
  dump_blob(v2 + 1);
  dump_blob(v1 + 10);
  dump_pdp_param(v1 + 19);
  return putchar(10);
}

//----- (0000088C) --------------------------------------------------------
int __fastcall dump_cdp(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n CDP :");
  printf("\n enable               :%d", *v1);
  return putchar(10);
}

//----- (000008D0) --------------------------------------------------------
int __fastcall dump_nms(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n NMS :");
  printf("\n enable               :%d", *v1);
  return putchar(10);
}

//----- (00000914) --------------------------------------------------------
int __fastcall dump_lsc_param(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n LSC_PARAM :");
  printf("\n net_type             :%d", v1[2]);
  printf("\n layer_start          :%d", v1[3]);
  printf("\n layer_end            :%d", v1[4]);
  printf("\n layer_width          :%d", v1[5]);
  printf("\n layer_height         :%d", v1[6]);
  printf("\n cvt_en               :%d", v1[7]);
  printf("\n mean                 :%d", v1[8]);
  printf("\n scale                :%d", v1[9]);
  return putchar(10);
}

//----- (000009E4) --------------------------------------------------------
int __fastcall dump_lsc(_DWORD *a1)
{
  _DWORD *v1; // r4

  v1 = a1;
  printf("\n LSC :");
  printf("\n enable               :%d", *v1);
  dump_lsc_param(v1 + 28);
  return putchar(10);
}

//----- (00000A30) --------------------------------------------------------
int __fastcall dump_nna_op(_DWORD *a1)
{
  _DWORD *v1; // r4
  _DWORD *v2; // r5

  v1 = a1;
  v2 = a1;
  printf("\n NNA_OP :");
  printf("\n type                 :%d", *v2);
  dump_bdma(v2 + 1);
  dump_conv(v1 + 22);
  dump_sdp(v1 + 80);
  dump_pdp(v1 + 194);
  dump_cdp(v1 + 225);
  dump_nms(v1 + 226);
  dump_lsc(v1 + 249);
  return putchar(10);
}

//----- (00000AB0) --------------------------------------------------------
signed int __fastcall nna_reg_dump(unsigned int a1)
{
  FILE *v1; // r5
  signed int result; // r0
  int v3; // r0
  int v4; // r0
  int v5; // r0
  int v6; // r0
  int v7; // r0
  int v8; // r0
  int v9; // r0
  int v10; // r0
  int v11; // r0
  int v12; // r0
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int v16; // r0
  int v17; // r0
  int v18; // r0
  int v19; // r0
  int v20; // r0
  int v21; // r0
  int v22; // r0
  int v23; // r0
  int v24; // r0
  int v25; // r0
  int v26; // r0
  int v27; // r0
  int v28; // r0
  int v29; // r0
  int v30; // r0
  int v31; // r0
  int v32; // r0
  int v33; // r0
  int v34; // r0
  int v35; // r0
  int v36; // r0
  int v37; // r0
  int v38; // r0
  int v39; // r0
  int v40; // r0
  int v41; // r0
  int v42; // r0
  int v43; // r0
  int v44; // r0
  int v45; // r0
  int v46; // r0
  int v47; // r0
  int v48; // r0
  int v49; // r0
  int v50; // r0
  int v51; // r0
  int v52; // r0
  int v53; // r0
  int v54; // r0
  int v55; // r0
  int v56; // r0
  int v57; // r0
  int v58; // r0
  int v59; // r0
  int v60; // r0
  int v61; // r0
  int v62; // r0
  int v63; // r0
  int v64; // r0
  int v65; // r0
  int v66; // r0
  int v67; // r0
  int v68; // r0
  int v69; // r0
  int v70; // r0
  int v71; // r0
  int v72; // r0
  int v73; // r0
  int v74; // r0
  int v75; // r0
  int v76; // r0
  int v77; // r0
  int v78; // r0
  int v79; // r0
  int v80; // r0
  int v81; // r0
  int v82; // r0
  int v83; // r0
  int v84; // r0
  int v85; // r0
  int v86; // r0
  int v87; // r0
  int v88; // r0
  int v89; // r0
  int v90; // r0
  int v91; // r0
  int v92; // r0
  int v93; // r0
  int v94; // r0
  int v95; // r0
  int v96; // r0
  int v97; // r0
  int v98; // r0
  int v99; // r0
  int v100; // r0
  int v101; // r0
  int v102; // r0
  int v103; // r0
  int v104; // r0
  int v105; // r0
  int v106; // r0
  int v107; // r0
  int v108; // r0
  int v109; // r0
  int v110; // r0
  int v111; // r0
  int v112; // r0
  int v113; // r0
  int v114; // r0
  int v115; // r0
  int v116; // r0
  int v117; // r0
  int v118; // r0
  int v119; // r0
  int v120; // r0
  int v121; // r0
  int v122; // r0
  int v123; // r0
  int v124; // r0
  int v125; // r0
  int v126; // r0
  int v127; // r0
  int v128; // r0
  int v129; // r0
  int v130; // r0
  int v131; // r0
  int v132; // r0
  int v133; // r0
  int v134; // r0
  int v135; // r0
  int v136; // r0
  int v137; // r0
  int v138; // r0
  int v139; // r0
  int v140; // r0
  int v141; // r0
  int v142; // r0
  int v143; // r0
  int v144; // r0
  int v145; // r0
  int v146; // r0
  int v147; // r0
  int v148; // r0
  int v149; // r0
  int v150; // r0
  int v151; // r0
  int v152; // r0
  int v153; // r0
  int v154; // r0
  int v155; // r0
  int v156; // r0
  int v157; // r0
  int v158; // r0
  int v159; // r0
  int v160; // r0
  int v161; // r0
  int v162; // r0
  int v163; // r0
  int v164; // r0
  int v165; // r0
  int v166; // r0
  int v167; // r0
  int v168; // r0
  int v169; // r0
  int v170; // r0
  int v171; // r0
  int v172; // r0
  int v173; // r0
  int v174; // r0
  int v175; // r0
  int v176; // r0
  int v177; // r0
  int v178; // r0
  int v179; // r0
  int v180; // r0
  int v181; // r0
  int v182; // r0
  int v183; // r0
  int v184; // r0
  int v185; // r0
  int v186; // r0
  int v187; // r0
  int v188; // r0
  int v189; // r0
  int v190; // r0
  int v191; // r0
  int v192; // r0
  int v193; // r0
  int v194; // r0
  int v195; // r0
  int v196; // r0
  int v197; // r0
  int v198; // r0
  int v199; // r0
  int v200; // r0
  int v201; // r0
  int v202; // r0
  int v203; // r0
  int v204; // r0
  int v205; // r0
  int v206; // r0
  int v207; // r0
  int v208; // r0
  int v209; // r0
  int v210; // r0
  int v211; // r0
  int v212; // r0
  int v213; // r0
  int v214; // r0
  int v215; // r0
  int v216; // r0
  int v217; // r0
  int v218; // r0
  int v219; // r0
  int v220; // r0
  int v221; // r0
  int v222; // r0
  int v223; // r0
  int v224; // r0
  int v225; // r0
  int v226; // r0
  int v227; // r0
  int v228; // r0
  int v229; // r0
  int v230; // r0
  int v231; // r0
  int v232; // r0
  int v233; // r0
  int v234; // r0
  int v235; // r0
  int v236; // r0
  int v237; // r0
  int v238; // r0
  int v239; // r0
  int v240; // r0
  int v241; // r0
  int v242; // r0
  int v243; // r0
  int v244; // r0
  int v245; // r0
  int v246; // r0
  int v247; // r0
  int v248; // r0
  int v249; // r0
  int v250; // r0
  int v251; // r0
  int v252; // r0
  int v253; // r0
  int v254; // r0
  int v255; // r0
  int v256; // r0
  int v257; // r0
  int v258; // r0
  int v259; // r0
  int v260; // r0
  int v261; // r0
  int v262; // r0
  int v263; // r0
  int v264; // r0
  int v265; // r0
  int v266; // r0
  int v267; // r0
  int v268; // r0
  int v269; // r0
  int v270; // r0
  int v271; // r0
  int v272; // r0
  int v273; // r0
  int v274; // r0
  int v275; // r0
  int v276; // r0
  int v277; // r0
  int v278; // r0
  int v279; // r0
  int v280; // r0
  int v281; // r0
  int v282; // r0
  int v283; // r0
  int v284; // r0
  int v285; // r0
  int v286; // r0
  int v287; // r0
  int v288; // r0
  int v289; // r0
  int v290; // r0
  int v291; // r0
  int v292; // r0
  int v293; // r0
  int v294; // r0
  int v295; // r0
  int v296; // r0
  int v297; // r0
  int v298; // r0
  int v299; // r0
  int v300; // r0
  int v301; // r0
  int v302; // r0
  int v303; // r0
  int v304; // r0
  int v305; // r0
  int v306; // r0
  int v307; // r0
  int v308; // r0
  int v309; // r0
  int v310; // r0
  int v311; // r0
  int v312; // r0
  int v313; // r0
  int v314; // r0
  int v315; // r0
  int v316; // r0
  int v317; // r0
  int v318; // r0
  int v319; // r0
  int v320; // r0
  int v321; // r0
  int v322; // r0
  int v323; // r0
  int v324; // r0
  int v325; // r0
  int v326; // r0
  int v327; // r0
  int v328; // r0
  int v329; // r0
  int v330; // r0
  int v331; // r0
  int v332; // r0
  int v333; // r0
  int v334; // r0
  int v335; // r0
  int v336; // r0
  int v337; // r0
  int v338; // r0
  int v339; // r0
  int v340; // r0
  int v341; // r0
  int v342; // r0
  int v343; // r0
  int v344; // r0
  int v345; // r0
  int v346; // r0
  int v347; // r0
  int v348; // r0
  int v349; // r0
  int v350; // r0
  int v351; // r0
  int v352; // r0
  int v353; // r0
  int v354; // r0
  int v355; // r0
  int v356; // r0
  int v357; // r0
  int v358; // r0
  int v359; // r0
  int v360; // r0
  int v361; // r0
  int v362; // r0
  int v363; // r0
  int v364; // r0
  int v365; // r0
  int v366; // r0
  int v367; // r0
  int v368; // r0
  int v369; // r0
  int v370; // r0
  int v371; // r0
  int v372; // r0
  int v373; // r0
  int v374; // r0
  int v375; // r0
  int v376; // r0
  int v377; // r0
  int v378; // r0
  int v379; // r0
  int v380; // r0
  int v381; // r0
  char s; // [sp+8h] [bp-110h]

  sprintf(&s, "DEBUG_reg_dump_%04d.txt", a1);
  v1 = fopen(&s, "w");
  if ( v1 )
  {
    v3 = nna_reg_read(0x1000u);
    fprintf(v1, "%05x,%08x,%s", 4096, v3, "GLB_S_NVDLA_HW_VERSION_0 --READ_ONLY --");
    v4 = nna_reg_read(0x1004u);
    fprintf(v1, "%05x,%08x,%s", 4100, v4, "GLB_S_INTR_MASK_0");
    v5 = nna_reg_read(0x1008u);
    fprintf(v1, "%05x,%08x,%s", 4104, v5, "GLB_S_INTR_SET_0");
    v6 = nna_reg_read(0x100Cu);
    fprintf(v1, "%05x,%08x,%s", 4108, v6, "GLB_S_INTR_STATUS_0");
    v7 = nna_reg_read(0x1010u);
    fprintf(v1, "%05x,%08x,%s", 4112, v7, "LSC_S_OP_EN_0");
    v8 = nna_reg_read(0x1014u);
    fprintf(v1, "%05x,%08x,%s", 4116, v8, "LSC_S_CTRL_0");
    v9 = nna_reg_read(0x1018u);
    fprintf(v1, "%05x,%08x,%s", 4120, v9, "LSC_S_NET_SEL_0");
    v10 = nna_reg_read(0x101Cu);
    fprintf(v1, "%05x,%08x,%s", 4124, v10, "LSC_S_BUFFER_ADDR_0");
    v11 = nna_reg_read(0x1020u);
    fprintf(v1, "%05x,%08x,%s", 4128, v11, "LSC_S_DATAIN_ADDR_0");
    v12 = nna_reg_read(0x1024u);
    fprintf(v1, "%05x,%08x,%s", 4132, v12, "LSC_S_DATAOUT_ADDR_0");
    v13 = nna_reg_read(0x1028u);
    fprintf(v1, "%05x,%08x,%s", 4136, v13, "LSC_S_DATAIN_STRIDE_0");
    v14 = nna_reg_read(0x1030u);
    fprintf(v1, "%05x,%08x,%s", 4144, v14, "LSC_S_DATAIN_SIZE_0");
    v15 = nna_reg_read(0x1034u);
    fprintf(v1, "%05x,%08x,%s", 4148, v15, "LSC_S_OFFSET0_0");
    v16 = nna_reg_read(0x1038u);
    fprintf(v1, "%05x,%08x,%s", 4152, v16, "LSC_S_OFFSET1_0");
    v17 = nna_reg_read(0x103Cu);
    fprintf(v1, "%05x,%08x,%s", 4156, v17, "LSC_S_OFFSET2_0");
    v18 = nna_reg_read(0x1040u);
    fprintf(v1, "%05x,%08x,%s", 4160, v18, "NMS_S_OP_EN_0");
    v19 = nna_reg_read(0x1044u);
    fprintf(v1, "%05x,%08x,%s", 4164, v19, "NMS_S_MODE_0");
    v20 = nna_reg_read(0x1048u);
    fprintf(v1, "%05x,%08x,%s", 4168, v20, "NMS_S_THRES_0");
    v21 = nna_reg_read(0x104Cu);
    fprintf(v1, "%05x,%08x,%s", 4172, v21, "NMS_S_DATAIN_SIZE_0");
    v22 = nna_reg_read(0x1050u);
    fprintf(v1, "%05x,%08x,%s", 4176, v22, "NMS_S_DATAOUT_SIZE_0");
    v23 = nna_reg_read(0x2000u);
    fprintf(v1, "%05x,%08x,%s", 0x2000, v23, "MCIF_CFG_RD_WEIGHT_0_0");
    v24 = nna_reg_read(0x2004u);
    fprintf(v1, "%05x,%08x,%s", 8196, v24, "MCIF_CFG_RD_WEIGHT_1_0");
    v25 = nna_reg_read(0x2008u);
    fprintf(v1, "%05x,%08x,%s", 8200, v25, "MCIF_CFG_RD_WEIGHT_2_0");
    v26 = nna_reg_read(0x200Cu);
    fprintf(v1, "%05x,%08x,%s", 8204, v26, "MCIF_CFG_WR_WEIGHT_0_0");
    v27 = nna_reg_read(0x2010u);
    fprintf(v1, "%05x,%08x,%s", 8208, v27, "MCIF_CFG_WR_WEIGHT_1_0");
    v28 = nna_reg_read(0x2014u);
    fprintf(v1, "%05x,%08x,%s", 8212, v28, "MCIF_CFG_OUTSTANDING_CNT_0");
    v29 = nna_reg_read(0x2018u);
    fprintf(v1, "%05x,%08x,%s", 8216, v29, "MCIF_STATUS_0 --READ_ONLY --");
    v30 = nna_reg_read(0x3000u);
    fprintf(v1, "%05x,%08x,%s", 12288, v30, "CDMA_S_STATUS_0 --READ_ONLY --");
    v31 = nna_reg_read(0x3004u);
    fprintf(v1, "%05x,%08x,%s", 12292, v31, "CDMA_S_POINTER_0 --DONT_CARE --");
    v32 = nna_reg_read(0x3008u);
    fprintf(v1, "%05x,%08x,%s", 12296, v32, "CDMA_S_ARBITER_0");
    v33 = nna_reg_read(0x300Cu);
    fprintf(v1, "%05x,%08x,%s", 12300, v33, "CDMA_S_CBUF_FLUSH_STATUS_0 --READ_ONLY --");
    v34 = nna_reg_read(0x3010u);
    fprintf(v1, "%05x,%08x,%s", 12304, v34, "CDMA_D_OP_ENABLE_0");
    v35 = nna_reg_read(0x3014u);
    fprintf(v1, "%05x,%08x,%s", 12308, v35, "CDMA_D_MISC_CFG_0");
    v36 = nna_reg_read(0x3018u);
    fprintf(v1, "%05x,%08x,%s", 12312, v36, "CDMA_D_DATAIN_FORMAT_0");
    v37 = nna_reg_read(0x301Cu);
    fprintf(v1, "%05x,%08x,%s", 12316, v37, "CDMA_D_DATAIN_SIZE_0_0");
    v38 = nna_reg_read(0x3020u);
    fprintf(v1, "%05x,%08x,%s", 12320, v38, "CDMA_D_DATAIN_SIZE_1_0");
    v39 = nna_reg_read(0x3024u);
    fprintf(v1, "%05x,%08x,%s", 12324, v39, "CDMA_D_DATAIN_SIZE_EXT_0_0");
    v40 = nna_reg_read(0x3028u);
    fprintf(v1, "%05x,%08x,%s", 12328, v40, "CDMA_D_PIXEL_OFFSET_0");
    v41 = nna_reg_read(0x302Cu);
    fprintf(v1, "%05x,%08x,%s", 12332, v41, "CDMA_D_DAIN_RAM_TYPE_0");
    v42 = nna_reg_read(0x3030u);
    fprintf(v1, "%05x,%08x,%s", 12336, v42, "CDMA_D_DAIN_ADDR_HIGH_0_0");
    v43 = nna_reg_read(0x3034u);
    fprintf(v1, "%05x,%08x,%s", 12340, v43, "CDMA_D_DAIN_ADDR_LOW_0_0");
    v44 = nna_reg_read(0x3038u);
    fprintf(v1, "%05x,%08x,%s", 12344, v44, "CDMA_D_DAIN_ADDR_HIGH_1_0");
    v45 = nna_reg_read(0x303Cu);
    fprintf(v1, "%05x,%08x,%s", 12348, v45, "CDMA_D_DAIN_ADDR_LOW_1_0");
    v46 = nna_reg_read(0x3040u);
    fprintf(v1, "%05x,%08x,%s", 12352, v46, "CDMA_D_LINE_STRIDE_0");
    v47 = nna_reg_read(0x3044u);
    fprintf(v1, "%05x,%08x,%s", 12356, v47, "CDMA_D_LINE_UV_STRIDE_0");
    v48 = nna_reg_read(0x3048u);
    fprintf(v1, "%05x,%08x,%s", 12360, v48, "CDMA_D_SURF_STRIDE_0");
    v49 = nna_reg_read(0x304Cu);
    fprintf(v1, "%05x,%08x,%s", 12364, v49, "CDMA_D_DAIN_MAP_0");
    v50 = nna_reg_read(0x3050u);
    fprintf(v1, "%05x,%08x,%s", 12368, v50, "CDMA_D_RESERVED_X_CFG_0");
    v51 = nna_reg_read(0x3054u);
    fprintf(v1, "%05x,%08x,%s", 12372, v51, "CDMA_D_RESERVED_Y_CFG_0");
    v52 = nna_reg_read(0x3058u);
    fprintf(v1, "%05x,%08x,%s", 12376, v52, "CDMA_D_BATCH_NUMBER_0");
    v53 = nna_reg_read(0x305Cu);
    fprintf(v1, "%05x,%08x,%s", 12380, v53, "CDMA_D_BATCH_STRIDE_0");
    v54 = nna_reg_read(0x3060u);
    fprintf(v1, "%05x,%08x,%s", 12384, v54, "CDMA_D_ENTRY_PER_SLICE_0");
    v55 = nna_reg_read(0x3064u);
    fprintf(v1, "%05x,%08x,%s", 12388, v55, "CDMA_D_FETCH_GRAIN_0");
    v56 = nna_reg_read(0x3068u);
    fprintf(v1, "%05x,%08x,%s", 12392, v56, "CDMA_D_WEIGHT_FORMAT_0");
    v57 = nna_reg_read(0x306Cu);
    fprintf(v1, "%05x,%08x,%s", 12396, v57, "CDMA_D_WEIGHT_SIZE_0_0");
    v58 = nna_reg_read(0x3070u);
    fprintf(v1, "%05x,%08x,%s", 12400, v58, "CDMA_D_WEIGHT_SIZE_1_0");
    v59 = nna_reg_read(0x3074u);
    fprintf(v1, "%05x,%08x,%s", 12404, v59, "CDMA_D_WEIGHT_RAM_TYPE_0");
    v60 = nna_reg_read(0x3078u);
    fprintf(v1, "%05x,%08x,%s", 12408, v60, "CDMA_D_WEIGHT_ADDR_HIGH_0");
    v61 = nna_reg_read(0x307Cu);
    fprintf(v1, "%05x,%08x,%s", 12412, v61, "CDMA_D_WEIGHT_ADDR_LOW_0");
    v62 = nna_reg_read(0x3080u);
    fprintf(v1, "%05x,%08x,%s", 12416, v62, "CDMA_D_WEIGHT_BYTES_0");
    v63 = nna_reg_read(0x3084u);
    fprintf(v1, "%05x,%08x,%s", 12420, v63, "CDMA_D_WGS_ADDR_HIGH_0");
    v64 = nna_reg_read(0x3088u);
    fprintf(v1, "%05x,%08x,%s", 12424, v64, "CDMA_D_WGS_ADDR_LOW_0");
    v65 = nna_reg_read(0x308Cu);
    fprintf(v1, "%05x,%08x,%s", 12428, v65, "CDMA_D_WMB_ADDR_HIGH_0");
    v66 = nna_reg_read(0x3090u);
    fprintf(v1, "%05x,%08x,%s", 12432, v66, "CDMA_D_WMB_ADDR_LOW_0");
    v67 = nna_reg_read(0x3094u);
    fprintf(v1, "%05x,%08x,%s", 12436, v67, "CDMA_D_WMB_BYTES_0");
    v68 = nna_reg_read(0x3098u);
    fprintf(v1, "%05x,%08x,%s", 12440, v68, "CDMA_D_MEAN_FORMAT_0");
    v69 = nna_reg_read(0x309Cu);
    fprintf(v1, "%05x,%08x,%s", 12444, v69, "CDMA_D_MEAN_GLOBAL_0_0");
    v70 = nna_reg_read(0x30A0u);
    fprintf(v1, "%05x,%08x,%s", 12448, v70, "CDMA_D_MEAN_GLOBAL_1_0");
    v71 = nna_reg_read(0x30A4u);
    fprintf(v1, "%05x,%08x,%s", 12452, v71, "CDMA_D_CVT_CFG_0");
    v72 = nna_reg_read(0x30A8u);
    fprintf(v1, "%05x,%08x,%s", 12456, v72, "CDMA_D_CVT_OFFSET_0");
    v73 = nna_reg_read(0x30ACu);
    fprintf(v1, "%05x,%08x,%s", 12460, v73, "CDMA_D_CVT_SCALE_0");
    v74 = nna_reg_read(0x30B0u);
    fprintf(v1, "%05x,%08x,%s", 12464, v74, "CDMA_D_CONV_STRIDE_0");
    v75 = nna_reg_read(0x30B4u);
    fprintf(v1, "%05x,%08x,%s", 12468, v75, "CDMA_D_ZERO_PADDING_0");
    v76 = nna_reg_read(0x30B8u);
    fprintf(v1, "%05x,%08x,%s", 12472, v76, "CDMA_D_ZERO_PADDING_VALUE_0");
    v77 = nna_reg_read(0x30BCu);
    fprintf(v1, "%05x,%08x,%s", 12476, v77, "CDMA_D_BANK_0");
    v78 = nna_reg_read(0x30C0u);
    fprintf(v1, "%05x,%08x,%s", 12480, v78, "CDMA_D_NAN_FLUSH_TO_ZERO_0");
    v79 = nna_reg_read(0x30C4u);
    fprintf(v1, "%05x,%08x,%s", 12484, v79, "CDMA_D_NAN_INPUT_DATA_NUM_0 --READ_ONLY --");
    v80 = nna_reg_read(0x30C8u);
    fprintf(v1, "%05x,%08x,%s", 12488, v80, "CDMA_D_NAN_INPUT_WEIGHT_NUM_0 --READ_ONLY --");
    v81 = nna_reg_read(0x30CCu);
    fprintf(v1, "%05x,%08x,%s", 12492, v81, "CDMA_D_INF_INPUT_DATA_NUM_0 --READ_ONLY --");
    v82 = nna_reg_read(0x30D0u);
    fprintf(v1, "%05x,%08x,%s", 12496, v82, "CDMA_D_INF_INPUT_WEIGHT_NUM_0 --READ_ONLY --");
    v83 = nna_reg_read(0x30D4u);
    fprintf(v1, "%05x,%08x,%s", 12500, v83, "CDMA_D_PERF_ENABLE_0");
    v84 = nna_reg_read(0x30D8u);
    fprintf(v1, "%05x,%08x,%s", 12504, v84, "CDMA_D_PERF_DAT_READ_STALL_0 --READ_ONLY --");
    v85 = nna_reg_read(0x30DCu);
    fprintf(v1, "%05x,%08x,%s", 12508, v85, "CDMA_D_PERF_WT_READ_STALL_0 --READ_ONLY --");
    v86 = nna_reg_read(0x30E0u);
    fprintf(v1, "%05x,%08x,%s", 12512, v86, "CDMA_D_PERF_DAT_READ_LATENCY_0 --READ_ONLY --");
    v87 = nna_reg_read(0x30E4u);
    fprintf(v1, "%05x,%08x,%s", 12516, v87, "CDMA_D_PERF_WT_READ_LATENCY_0 --READ_ONLY --");
    v88 = nna_reg_read(0x30E8u);
    fprintf(v1, "%05x,%08x,%s", 12520, v88, "CDMA_D_CYA_0");
    v89 = nna_reg_read(0x4000u);
    fprintf(v1, "%05x,%08x,%s", 0x4000, v89, "CSC_S_STATUS_0 --READ_ONLY --");
    v90 = nna_reg_read(0x4004u);
    fprintf(v1, "%05x,%08x,%s", 16388, v90, "CSC_S_POINTER_0 --DONT_CARE --");
    v91 = nna_reg_read(0x4008u);
    fprintf(v1, "%05x,%08x,%s", 16392, v91, "CSC_D_OP_ENABLE_0");
    v92 = nna_reg_read(0x400Cu);
    fprintf(v1, "%05x,%08x,%s", 16396, v92, "CSC_D_MISC_CFG_0");
    v93 = nna_reg_read(0x4010u);
    fprintf(v1, "%05x,%08x,%s", 16400, v93, "CSC_D_DATAIN_FORMAT_0");
    v94 = nna_reg_read(0x4014u);
    fprintf(v1, "%05x,%08x,%s", 16404, v94, "CSC_D_DATAIN_SIZE_EXT_0_0");
    v95 = nna_reg_read(0x4018u);
    fprintf(v1, "%05x,%08x,%s", 16408, v95, "CSC_D_DATAIN_SIZE_EXT_1_0");
    v96 = nna_reg_read(0x401Cu);
    fprintf(v1, "%05x,%08x,%s", 16412, v96, "CSC_D_BATCH_NUMBER_0");
    v97 = nna_reg_read(0x4020u);
    fprintf(v1, "%05x,%08x,%s", 16416, v97, "CSC_D_POST_Y_EXTENSION_0");
    v98 = nna_reg_read(0x4024u);
    fprintf(v1, "%05x,%08x,%s", 16420, v98, "CSC_D_ENTRY_PER_SLICE_0");
    v99 = nna_reg_read(0x4028u);
    fprintf(v1, "%05x,%08x,%s", 16424, v99, "CSC_D_WEIGHT_FORMAT_0");
    v100 = nna_reg_read(0x402Cu);
    fprintf(v1, "%05x,%08x,%s", 16428, v100, "CSC_D_WEIGHT_SIZE_EXT_0_0");
    v101 = nna_reg_read(0x4030u);
    fprintf(v1, "%05x,%08x,%s", 16432, v101, "CSC_D_WEIGHT_SIZE_EXT_1_0");
    v102 = nna_reg_read(0x4034u);
    fprintf(v1, "%05x,%08x,%s", 16436, v102, "CSC_D_WEIGHT_BYTES_0");
    v103 = nna_reg_read(0x4038u);
    fprintf(v1, "%05x,%08x,%s", 16440, v103, "CSC_D_WMB_BYTES_0");
    v104 = nna_reg_read(0x403Cu);
    fprintf(v1, "%05x,%08x,%s", 16444, v104, "CSC_D_DATAOUT_SIZE_0_0");
    v105 = nna_reg_read(0x4040u);
    fprintf(v1, "%05x,%08x,%s", 16448, v105, "CSC_D_DATAOUT_SIZE_1_0");
    v106 = nna_reg_read(0x4044u);
    fprintf(v1, "%05x,%08x,%s", 16452, v106, "CSC_D_ATOMICS_0");
    v107 = nna_reg_read(0x4048u);
    fprintf(v1, "%05x,%08x,%s", 16456, v107, "CSC_D_RELEASE_0");
    v108 = nna_reg_read(0x404Cu);
    fprintf(v1, "%05x,%08x,%s", 16460, v108, "CSC_D_CONV_STRIDE_EXT_0");
    v109 = nna_reg_read(0x4050u);
    fprintf(v1, "%05x,%08x,%s", 16464, v109, "CSC_D_DILATION_EXT_0");
    v110 = nna_reg_read(0x4054u);
    fprintf(v1, "%05x,%08x,%s", 16468, v110, "CSC_D_ZERO_PADDING_0");
    v111 = nna_reg_read(0x4058u);
    fprintf(v1, "%05x,%08x,%s", 16472, v111, "CSC_D_ZERO_PADDING_VALUE_0");
    v112 = nna_reg_read(0x405Cu);
    fprintf(v1, "%05x,%08x,%s", 16476, v112, "CSC_D_BANK_0");
    v113 = nna_reg_read(0x4060u);
    fprintf(v1, "%05x,%08x,%s", 16480, v113, "CSC_D_PRA_CFG_0");
    v114 = nna_reg_read(0x4064u);
    fprintf(v1, "%05x,%08x,%s", 16484, v114, "CSC_D_CYA_0");
    v115 = nna_reg_read(0x5000u);
    fprintf(v1, "%05x,%08x,%s", 20480, v115, "CMAC_A_S_STATUS_0 --READ_ONLY --");
    v116 = nna_reg_read(0x5004u);
    fprintf(v1, "%05x,%08x,%s", 20484, v116, "CMAC_A_S_POINTER_0 --DONT_CARE --");
    v117 = nna_reg_read(0x5008u);
    fprintf(v1, "%05x,%08x,%s", 20488, v117, "CMAC_A_D_OP_ENABLE_0");
    v118 = nna_reg_read(0x500Cu);
    fprintf(v1, "%05x,%08x,%s", 20492, v118, "CMAC_A_D_MISC_CFG_0");
    v119 = nna_reg_read(0x6000u);
    fprintf(v1, "%05x,%08x,%s", 24576, v119, "CMAC_B_S_STATUS_0 --READ_ONLY --");
    v120 = nna_reg_read(0x6004u);
    fprintf(v1, "%05x,%08x,%s", 24580, v120, "CMAC_B_S_POINTER_0 --DONT_CARE --");
    v121 = nna_reg_read(0x6008u);
    fprintf(v1, "%05x,%08x,%s", 24584, v121, "CMAC_B_D_OP_ENABLE_0");
    v122 = nna_reg_read(0x600Cu);
    fprintf(v1, "%05x,%08x,%s", 24588, v122, "CMAC_B_D_MISC_CFG_0");
    v123 = nna_reg_read(0x7000u);
    fprintf(v1, "%05x,%08x,%s", 28672, v123, "CACC_S_STATUS_0 --READ_ONLY --");
    v124 = nna_reg_read(0x7004u);
    fprintf(v1, "%05x,%08x,%s", 28676, v124, "CACC_S_POINTER_0 --DONT_CARE --");
    v125 = nna_reg_read(0x7008u);
    fprintf(v1, "%05x,%08x,%s", 28680, v125, "CACC_D_OP_ENABLE_0");
    v126 = nna_reg_read(0x700Cu);
    fprintf(v1, "%05x,%08x,%s", 28684, v126, "CACC_D_MISC_CFG_0");
    v127 = nna_reg_read(0x7010u);
    fprintf(v1, "%05x,%08x,%s", 28688, v127, "CACC_D_DATAOUT_SIZE_0_0");
    v128 = nna_reg_read(0x7014u);
    fprintf(v1, "%05x,%08x,%s", 28692, v128, "CACC_D_DATAOUT_SIZE_1_0");
    v129 = nna_reg_read(0x7018u);
    fprintf(v1, "%05x,%08x,%s", 28696, v129, "CACC_D_DATAOUT_ADDR_0");
    v130 = nna_reg_read(0x701Cu);
    fprintf(v1, "%05x,%08x,%s", 28700, v130, "CACC_D_BATCH_NUMBER_0");
    v131 = nna_reg_read(0x7020u);
    fprintf(v1, "%05x,%08x,%s", 28704, v131, "CACC_D_LINE_STRIDE_0");
    v132 = nna_reg_read(0x7024u);
    fprintf(v1, "%05x,%08x,%s", 28708, v132, "CACC_D_SURF_STRIDE_0");
    v133 = nna_reg_read(0x7028u);
    fprintf(v1, "%05x,%08x,%s", 28712, v133, "CACC_D_DATAOUT_MAP_0");
    v134 = nna_reg_read(0x702Cu);
    fprintf(v1, "%05x,%08x,%s", 28716, v134, "CACC_D_CLIP_CFG_0");
    v135 = nna_reg_read(0x7030u);
    fprintf(v1, "%05x,%08x,%s", 28720, v135, "CACC_D_OUT_SATURATION_0");
    v136 = nna_reg_read(0x7034u);
    fprintf(v1, "%05x,%08x,%s", 28724, v136, "CACC_D_CYA_0");
    v137 = nna_reg_read(0x8000u);
    fprintf(v1, "%05x,%08x,%s", 0x8000, v137, "SDP_RDMA_S_STATUS_0 --READ_ONLY --");
    v138 = nna_reg_read(0x8004u);
    fprintf(v1, "%05x,%08x,%s", 32772, v138, "SDP_RDMA_S_POINTER_0 --DONT_CARE --");
    v139 = nna_reg_read(0x8008u);
    fprintf(v1, "%05x,%08x,%s", 32776, v139, "SDP_RDMA_D_OP_ENABLE_0");
    v140 = nna_reg_read(0x800Cu);
    fprintf(v1, "%05x,%08x,%s", 32780, v140, "SDP_RDMA_D_DATA_CUBE_WIDTH_0");
    v141 = nna_reg_read(0x8010u);
    fprintf(v1, "%05x,%08x,%s", 32784, v141, "SDP_RDMA_D_DATA_CUBE_HEIGHT_0");
    v142 = nna_reg_read(0x8014u);
    fprintf(v1, "%05x,%08x,%s", 32788, v142, "SDP_RDMA_D_DATA_CUBE_CHANNEL_0");
    v143 = nna_reg_read(0x8018u);
    fprintf(v1, "%05x,%08x,%s", 32792, v143, "SDP_RDMA_D_SRC_BASE_ADDR_LOW_0");
    v144 = nna_reg_read(0x801Cu);
    fprintf(v1, "%05x,%08x,%s", 32796, v144, "SDP_RDMA_D_SRC_BASE_ADDR_HIGH_0");
    v145 = nna_reg_read(0x8020u);
    fprintf(v1, "%05x,%08x,%s", 32800, v145, "SDP_RDMA_D_SRC_LINE_STRIDE_0");
    v146 = nna_reg_read(0x8024u);
    fprintf(v1, "%05x,%08x,%s", 32804, v146, "SDP_RDMA_D_SRC_SURFACE_STRIDE_0");
    v147 = nna_reg_read(0x8028u);
    fprintf(v1, "%05x,%08x,%s", 32808, v147, "SDP_RDMA_D_BRDMA_CFG_0");
    v148 = nna_reg_read(0x802Cu);
    fprintf(v1, "%05x,%08x,%s", 32812, v148, "SDP_RDMA_D_BS_BASE_ADDR_LOW_0");
    v149 = nna_reg_read(0x8030u);
    fprintf(v1, "%05x,%08x,%s", 32816, v149, "SDP_RDMA_D_BS_BASE_ADDR_HIGH_0");
    v150 = nna_reg_read(0x8034u);
    fprintf(v1, "%05x,%08x,%s", 32820, v150, "SDP_RDMA_D_BS_LINE_STRIDE_0");
    v151 = nna_reg_read(0x8038u);
    fprintf(v1, "%05x,%08x,%s", 32824, v151, "SDP_RDMA_D_BS_SURFACE_STRIDE_0");
    v152 = nna_reg_read(0x803Cu);
    fprintf(v1, "%05x,%08x,%s", 32828, v152, "SDP_RDMA_D_BS_BATCH_STRIDE_0");
    v153 = nna_reg_read(0x8040u);
    fprintf(v1, "%05x,%08x,%s", 32832, v153, "SDP_RDMA_D_NRDMA_CFG_0");
    v154 = nna_reg_read(0x8044u);
    fprintf(v1, "%05x,%08x,%s", 32836, v154, "SDP_RDMA_D_BN_BASE_ADDR_LOW_0");
    v155 = nna_reg_read(0x8048u);
    fprintf(v1, "%05x,%08x,%s", 32840, v155, "SDP_RDMA_D_BN_BASE_ADDR_HIGH_0");
    v156 = nna_reg_read(0x804Cu);
    fprintf(v1, "%05x,%08x,%s", 32844, v156, "SDP_RDMA_D_BN_LINE_STRIDE_0");
    v157 = nna_reg_read(0x8050u);
    fprintf(v1, "%05x,%08x,%s", 32848, v157, "SDP_RDMA_D_BN_SURFACE_STRIDE_0");
    v158 = nna_reg_read(0x8054u);
    fprintf(v1, "%05x,%08x,%s", 32852, v158, "SDP_RDMA_D_BN_BATCH_STRIDE_0");
    v159 = nna_reg_read(0x8058u);
    fprintf(v1, "%05x,%08x,%s", 32856, v159, "SDP_RDMA_D_ERDMA_CFG_0");
    v160 = nna_reg_read(0x805Cu);
    fprintf(v1, "%05x,%08x,%s", 32860, v160, "SDP_RDMA_D_EW_BASE_ADDR_LOW_0");
    v161 = nna_reg_read(0x8060u);
    fprintf(v1, "%05x,%08x,%s", 32864, v161, "SDP_RDMA_D_EW_BASE_ADDR_HIGH_0");
    v162 = nna_reg_read(0x8064u);
    fprintf(v1, "%05x,%08x,%s", 32868, v162, "SDP_RDMA_D_EW_LINE_STRIDE_0");
    v163 = nna_reg_read(0x8068u);
    fprintf(v1, "%05x,%08x,%s", 32872, v163, "SDP_RDMA_D_EW_SURFACE_STRIDE_0");
    v164 = nna_reg_read(0x806Cu);
    fprintf(v1, "%05x,%08x,%s", 32876, v164, "SDP_RDMA_D_EW_BATCH_STRIDE_0");
    v165 = nna_reg_read(0x8070u);
    fprintf(v1, "%05x,%08x,%s", 32880, v165, "SDP_RDMA_D_FEATURE_MODE_CFG_0");
    v166 = nna_reg_read(0x8074u);
    fprintf(v1, "%05x,%08x,%s", 32884, v166, "SDP_RDMA_D_SRC_DMA_CFG_0");
    v167 = nna_reg_read(0x8078u);
    fprintf(v1, "%05x,%08x,%s", 32888, v167, "SDP_RDMA_D_STATUS_NAN_INPUT_NUM_0 --READ_ONLY --");
    v168 = nna_reg_read(0x807Cu);
    fprintf(v1, "%05x,%08x,%s", 32892, v168, "SDP_RDMA_D_STATUS_INF_INPUT_NUM_0 --READ_ONLY --");
    v169 = nna_reg_read(0x8080u);
    fprintf(v1, "%05x,%08x,%s", 32896, v169, "SDP_RDMA_D_PERF_ENABLE_0 --DONT_CARE --");
    v170 = nna_reg_read(0x8084u);
    fprintf(v1, "%05x,%08x,%s", 32900, v170, "SDP_RDMA_D_PERF_MRDMA_READ_STALL_0 --READ_ONLY --");
    v171 = nna_reg_read(0x8088u);
    fprintf(v1, "%05x,%08x,%s", 32904, v171, "SDP_RDMA_D_PERF_BRDMA_READ_STALL_0 --READ_ONLY --");
    v172 = nna_reg_read(0x808Cu);
    fprintf(v1, "%05x,%08x,%s", 32908, v172, "SDP_RDMA_D_PERF_NRDMA_READ_STALL_0 --READ_ONLY --");
    v173 = nna_reg_read(0x8090u);
    fprintf(v1, "%05x,%08x,%s", 32912, v173, "SDP_RDMA_D_PERF_ERDMA_READ_STALL_0 --READ_ONLY --");
    v174 = nna_reg_read(0x9000u);
    fprintf(v1, "%05x,%08x,%s", 36864, v174, "SDP_S_STATUS_0 --READ_ONLY --");
    v175 = nna_reg_read(0x9004u);
    fprintf(v1, "%05x,%08x,%s", 36868, v175, "SDP_S_POINTER_0 --DONT_CARE --");
    v176 = nna_reg_read(0x9008u);
    fprintf(v1, "%05x,%08x,%s", 36872, v176, "SDP_S_LUT_ACCESS_CFG_0");
    v177 = nna_reg_read(0x900Cu);
    fprintf(v1, "%05x,%08x,%s", 36876, v177, "SDP_S_LUT_ACCESS_DATA_0");
    v178 = nna_reg_read(0x9010u);
    fprintf(v1, "%05x,%08x,%s", 36880, v178, "SDP_S_LUT_CFG_0");
    v179 = nna_reg_read(0x9014u);
    fprintf(v1, "%05x,%08x,%s", 36884, v179, "SDP_S_LUT_INFO_0");
    v180 = nna_reg_read(0x9018u);
    fprintf(v1, "%05x,%08x,%s", 36888, v180, "SDP_S_LUT_LE_START_0");
    v181 = nna_reg_read(0x901Cu);
    fprintf(v1, "%05x,%08x,%s", 36892, v181, "SDP_S_LUT_LE_END_0");
    v182 = nna_reg_read(0x9020u);
    fprintf(v1, "%05x,%08x,%s", 36896, v182, "SDP_S_LUT_LO_START_0");
    v183 = nna_reg_read(0x9024u);
    fprintf(v1, "%05x,%08x,%s", 36900, v183, "SDP_S_LUT_LO_END_0");
    v184 = nna_reg_read(0x9028u);
    fprintf(v1, "%05x,%08x,%s", 36904, v184, "SDP_S_LUT_LE_SLOPE_SCALE_0");
    v185 = nna_reg_read(0x902Cu);
    fprintf(v1, "%05x,%08x,%s", 36908, v185, "SDP_S_LUT_LE_SLOPE_SHIFT_0");
    v186 = nna_reg_read(0x9030u);
    fprintf(v1, "%05x,%08x,%s", 36912, v186, "SDP_S_LUT_LO_SLOPE_SCALE_0");
    v187 = nna_reg_read(0x9034u);
    fprintf(v1, "%05x,%08x,%s", 36916, v187, "SDP_S_LUT_LO_SLOPE_SHIFT_0");
    v188 = nna_reg_read(0x9038u);
    fprintf(v1, "%05x,%08x,%s", 36920, v188, "SDP_D_OP_ENABLE_0");
    v189 = nna_reg_read(0x903Cu);
    fprintf(v1, "%05x,%08x,%s", 36924, v189, "SDP_D_DATA_CUBE_WIDTH_0");
    v190 = nna_reg_read(0x9040u);
    fprintf(v1, "%05x,%08x,%s", 36928, v190, "SDP_D_DATA_CUBE_HEIGHT_0");
    v191 = nna_reg_read(0x9044u);
    fprintf(v1, "%05x,%08x,%s", 36932, v191, "SDP_D_DATA_CUBE_CHANNEL_0");
    v192 = nna_reg_read(0x9048u);
    fprintf(v1, "%05x,%08x,%s", 36936, v192, "SDP_D_DST_BASE_ADDR_LOW_0");
    v193 = nna_reg_read(0x904Cu);
    fprintf(v1, "%05x,%08x,%s", 36940, v193, "SDP_D_DST_BASE_ADDR_HIGH_0");
    v194 = nna_reg_read(0x9050u);
    fprintf(v1, "%05x,%08x,%s", 36944, v194, "SDP_D_DST_LINE_STRIDE_0");
    v195 = nna_reg_read(0x9054u);
    fprintf(v1, "%05x,%08x,%s", 36948, v195, "SDP_D_DST_SURFACE_STRIDE_0");
    v196 = nna_reg_read(0x9058u);
    fprintf(v1, "%05x,%08x,%s", 36952, v196, "SDP_D_DP_BS_CFG_0");
    v197 = nna_reg_read(0x905Cu);
    fprintf(v1, "%05x,%08x,%s", 36956, v197, "SDP_D_DP_BS_ALU_CFG_0");
    v198 = nna_reg_read(0x9060u);
    fprintf(v1, "%05x,%08x,%s", 36960, v198, "SDP_D_DP_BS_ALU_SRC_VALUE_0");
    v199 = nna_reg_read(0x9064u);
    fprintf(v1, "%05x,%08x,%s", 36964, v199, "SDP_D_DP_BS_MUL_CFG_0");
    v200 = nna_reg_read(0x9068u);
    fprintf(v1, "%05x,%08x,%s", 36968, v200, "SDP_D_DP_BS_MUL_SRC_VALUE_0");
    v201 = nna_reg_read(0x906Cu);
    fprintf(v1, "%05x,%08x,%s", 36972, v201, "SDP_D_DP_BN_CFG_0");
    v202 = nna_reg_read(0x9070u);
    fprintf(v1, "%05x,%08x,%s", 36976, v202, "SDP_D_DP_BN_ALU_CFG_0");
    v203 = nna_reg_read(0x9074u);
    fprintf(v1, "%05x,%08x,%s", 36980, v203, "SDP_D_DP_BN_ALU_SRC_VALUE_0");
    v204 = nna_reg_read(0x9078u);
    fprintf(v1, "%05x,%08x,%s", 36984, v204, "SDP_D_DP_BN_MUL_CFG_0");
    v205 = nna_reg_read(0x907Cu);
    fprintf(v1, "%05x,%08x,%s", 36988, v205, "SDP_D_DP_BN_MUL_SRC_VALUE_0");
    v206 = nna_reg_read(0x9080u);
    fprintf(v1, "%05x,%08x,%s", 36992, v206, "SDP_D_DP_EW_CFG_0");
    v207 = nna_reg_read(0x9084u);
    fprintf(v1, "%05x,%08x,%s", 36996, v207, "SDP_D_DP_EW_ALU_CFG_0");
    v208 = nna_reg_read(0x9088u);
    fprintf(v1, "%05x,%08x,%s", 37000, v208, "SDP_D_DP_EW_ALU_SRC_VALUE_0");
    v209 = nna_reg_read(0x908Cu);
    fprintf(v1, "%05x,%08x,%s", 37004, v209, "SDP_D_DP_EW_ALU_CVT_OFFSET_VALUE_0");
    v210 = nna_reg_read(0x9090u);
    fprintf(v1, "%05x,%08x,%s", 37008, v210, "SDP_D_DP_EW_ALU_CVT_SCALE_VALUE_0");
    v211 = nna_reg_read(0x9094u);
    fprintf(v1, "%05x,%08x,%s", 37012, v211, "SDP_D_DP_EW_ALU_CVT_TRUNCATE_VALUE_0");
    v212 = nna_reg_read(0x9098u);
    fprintf(v1, "%05x,%08x,%s", 37016, v212, "SDP_D_DP_EW_MUL_CFG_0");
    v213 = nna_reg_read(0x909Cu);
    fprintf(v1, "%05x,%08x,%s", 37020, v213, "SDP_D_DP_EW_MUL_SRC_VALUE_0");
    v214 = nna_reg_read(0x90A0u);
    fprintf(v1, "%05x,%08x,%s", 37024, v214, "SDP_D_DP_EW_MUL_CVT_OFFSET_VALUE_0");
    v215 = nna_reg_read(0x90A4u);
    fprintf(v1, "%05x,%08x,%s", 37028, v215, "SDP_D_DP_EW_MUL_CVT_SCALE_VALUE_0");
    v216 = nna_reg_read(0x90A8u);
    fprintf(v1, "%05x,%08x,%s", 37032, v216, "SDP_D_DP_EW_MUL_CVT_TRUNCATE_VALUE_0");
    v217 = nna_reg_read(0x90ACu);
    fprintf(v1, "%05x,%08x,%s", 37036, v217, "SDP_D_DP_EW_TRUNCATE_VALUE_0");
    v218 = nna_reg_read(0x90B0u);
    fprintf(v1, "%05x,%08x,%s", 37040, v218, "SDP_D_FEATURE_MODE_CFG_0");
    v219 = nna_reg_read(0x90B4u);
    fprintf(v1, "%05x,%08x,%s", 37044, v219, "SDP_D_DST_DMA_CFG_0");
    v220 = nna_reg_read(0x90B8u);
    fprintf(v1, "%05x,%08x,%s", 37048, v220, "SDP_D_DST_BATCH_STRIDE_0");
    v221 = nna_reg_read(0x90BCu);
    fprintf(v1, "%05x,%08x,%s", 37052, v221, "SDP_D_DATA_FORMAT_0");
    v222 = nna_reg_read(0x90C0u);
    fprintf(v1, "%05x,%08x,%s", 37056, v222, "SDP_D_CVT_OFFSET_0");
    v223 = nna_reg_read(0x90C4u);
    fprintf(v1, "%05x,%08x,%s", 37060, v223, "SDP_D_CVT_SCALE_0");
    v224 = nna_reg_read(0x90C8u);
    fprintf(v1, "%05x,%08x,%s", 37064, v224, "SDP_D_CVT_SHIFT_0");
    v225 = nna_reg_read(0x90CCu);
    fprintf(v1, "%05x,%08x,%s", 37068, v225, "SDP_D_STATUS_0 --READ_ONLY --");
    v226 = nna_reg_read(0x90D0u);
    fprintf(v1, "%05x,%08x,%s", 37072, v226, "SDP_D_STATUS_NAN_INPUT_NUM_0 --READ_ONLY --");
    v227 = nna_reg_read(0x90D4u);
    fprintf(v1, "%05x,%08x,%s", 37076, v227, "SDP_D_STATUS_INF_INPUT_NUM_0 --READ_ONLY --");
    v228 = nna_reg_read(0x90D8u);
    fprintf(v1, "%05x,%08x,%s", 37080, v228, "SDP_D_STATUS_NAN_OUTPUT_NUM_0 --READ_ONLY --");
    v229 = nna_reg_read(0x90DCu);
    fprintf(v1, "%05x,%08x,%s", 37084, v229, "SDP_D_PERF_ENABLE_0");
    v230 = nna_reg_read(0x90E0u);
    fprintf(v1, "%05x,%08x,%s", 37088, v230, "SDP_D_PERF_WDMA_WRITE_STALL_0");
    v231 = nna_reg_read(0x90E4u);
    fprintf(v1, "%05x,%08x,%s", 37092, v231, "SDP_D_PERF_LUT_UFLOW_0");
    v232 = nna_reg_read(0x90E8u);
    fprintf(v1, "%05x,%08x,%s", 37096, v232, "SDP_D_PERF_LUT_OFLOW_0");
    v233 = nna_reg_read(0x90ECu);
    fprintf(v1, "%05x,%08x,%s", 37100, v233, "SDP_D_PERF_OUT_SATURATION_0");
    v234 = nna_reg_read(0x90F0u);
    fprintf(v1, "%05x,%08x,%s", 37104, v234, "SDP_D_PERF_LUT_HYBRID_0");
    v235 = nna_reg_read(0x90F4u);
    fprintf(v1, "%05x,%08x,%s", 37108, v235, "SDP_D_PERF_LUT_LE_HIT_0");
    v236 = nna_reg_read(0x90F8u);
    fprintf(v1, "%05x,%08x,%s", 37112, v236, "SDP_D_PERF_LUT_LO_HIT_0");
    v237 = nna_reg_read(0xA000u);
    fprintf(v1, "%05x,%08x,%s", 40960, v237, "PDP_RDMA_S_STATUS_0 --READ_ONLY --");
    v238 = nna_reg_read(0xA004u);
    fprintf(v1, "%05x,%08x,%s", 40964, v238, "PDP_RDMA_S_POINTER_0 --DONT_CARE --");
    v239 = nna_reg_read(0xA008u);
    fprintf(v1, "%05x,%08x,%s", 40968, v239, "PDP_RDMA_D_OP_ENABLE_0");
    v240 = nna_reg_read(0xA00Cu);
    fprintf(v1, "%05x,%08x,%s", 40972, v240, "PDP_RDMA_D_DATA_CUBE_IN_WIDTH_0");
    v241 = nna_reg_read(0xA010u);
    fprintf(v1, "%05x,%08x,%s", 40976, v241, "PDP_RDMA_D_DATA_CUBE_IN_HEIGHT_0");
    v242 = nna_reg_read(0xA014u);
    fprintf(v1, "%05x,%08x,%s", 40980, v242, "PDP_RDMA_D_DATA_CUBE_IN_CHANNEL_0");
    v243 = nna_reg_read(0xA018u);
    fprintf(v1, "%05x,%08x,%s", 40984, v243, "PDP_RDMA_D_FLYING_MODE_0");
    v244 = nna_reg_read(0xA01Cu);
    fprintf(v1, "%05x,%08x,%s", 40988, v244, "PDP_RDMA_D_SRC_BASE_ADDR_LOW_0");
    v245 = nna_reg_read(0xA020u);
    fprintf(v1, "%05x,%08x,%s", 40992, v245, "PDP_RDMA_D_SRC_BASE_ADDR_HIGH_0");
    v246 = nna_reg_read(0xA024u);
    fprintf(v1, "%05x,%08x,%s", 40996, v246, "PDP_RDMA_D_SRC_LINE_STRIDE_0");
    v247 = nna_reg_read(0xA028u);
    fprintf(v1, "%05x,%08x,%s", 41000, v247, "PDP_RDMA_D_SRC_SURFACE_STRIDE_0");
    v248 = nna_reg_read(0xA02Cu);
    fprintf(v1, "%05x,%08x,%s", 41004, v248, "PDP_RDMA_D_SRC_RAM_CFG_0");
    v249 = nna_reg_read(0xA030u);
    fprintf(v1, "%05x,%08x,%s", 41008, v249, "PDP_RDMA_D_DATA_FORMAT_0");
    v250 = nna_reg_read(0xA034u);
    fprintf(v1, "%05x,%08x,%s", 41012, v250, "PDP_RDMA_D_OPERATION_MODE_CFG_0");
    v251 = nna_reg_read(0xA038u);
    fprintf(v1, "%05x,%08x,%s", 41016, v251, "PDP_RDMA_D_POOLING_KERNEL_CFG_0");
    v252 = nna_reg_read(0xA03Cu);
    fprintf(v1, "%05x,%08x,%s", 41020, v252, "PDP_RDMA_D_POOLING_PADDING_CFG_0");
    v253 = nna_reg_read(0xA040u);
    fprintf(v1, "%05x,%08x,%s", 41024, v253, "PDP_RDMA_D_PARTIAL_WIDTH_IN_0");
    v254 = nna_reg_read(0xA044u);
    fprintf(v1, "%05x,%08x,%s", 41028, v254, "PDP_RDMA_D_PERF_ENABLE_0");
    v255 = nna_reg_read(0xA048u);
    fprintf(v1, "%05x,%08x,%s", 41032, v255, "PDP_RDMA_D_PERF_READ_STALL_0");
    v256 = nna_reg_read(0xA04Cu);
    fprintf(v1, "%05x,%08x,%s", 41036, v256, "PDP_RDMA_D_CYA_0");
    v257 = nna_reg_read(0xB000u);
    fprintf(v1, "%05x,%08x,%s", 45056, v257, "PDP_S_STATUS_0 --READ_ONLY --");
    v258 = nna_reg_read(0xB004u);
    fprintf(v1, "%05x,%08x,%s", 45060, v258, "PDP_S_POINTER_0 --DONT_CARE --");
    v259 = nna_reg_read(0xB008u);
    fprintf(v1, "%05x,%08x,%s", 45064, v259, "PDP_D_OP_ENABLE_0");
    v260 = nna_reg_read(0xB00Cu);
    fprintf(v1, "%05x,%08x,%s", 45068, v260, "PDP_D_DATA_CUBE_IN_WIDTH_0");
    v261 = nna_reg_read(0xB010u);
    fprintf(v1, "%05x,%08x,%s", 45072, v261, "PDP_D_DATA_CUBE_IN_HEIGHT_0");
    v262 = nna_reg_read(0xB014u);
    fprintf(v1, "%05x,%08x,%s", 45076, v262, "PDP_D_DATA_CUBE_IN_CHANNEL_0");
    v263 = nna_reg_read(0xB018u);
    fprintf(v1, "%05x,%08x,%s", 45080, v263, "PDP_D_DATA_CUBE_OUT_WIDTH_0");
    v264 = nna_reg_read(0xB01Cu);
    fprintf(v1, "%05x,%08x,%s", 45084, v264, "PDP_D_DATA_CUBE_OUT_HEIGHT_0");
    v265 = nna_reg_read(0xB020u);
    fprintf(v1, "%05x,%08x,%s", 45088, v265, "PDP_D_DATA_CUBE_OUT_CHANNEL_0");
    v266 = nna_reg_read(0xB024u);
    fprintf(v1, "%05x,%08x,%s", 45092, v266, "PDP_D_OPERATION_MODE_CFG_0");
    v267 = nna_reg_read(0xB028u);
    fprintf(v1, "%05x,%08x,%s", 45096, v267, "PDP_D_NAN_FLUSH_TO_ZERO_0");
    v268 = nna_reg_read(0xB02Cu);
    fprintf(v1, "%05x,%08x,%s", 45100, v268, "PDP_D_PARTIAL_WIDTH_IN_0");
    v269 = nna_reg_read(0xB030u);
    fprintf(v1, "%05x,%08x,%s", 45104, v269, "PDP_D_PARTIAL_WIDTH_OUT_0");
    v270 = nna_reg_read(0xB034u);
    fprintf(v1, "%05x,%08x,%s", 45108, v270, "PDP_D_POOLING_KERNEL_CFG_0");
    v271 = nna_reg_read(0xB038u);
    fprintf(v1, "%05x,%08x,%s", 45112, v271, "PDP_D_RECIP_KERNEL_WIDTH_0");
    v272 = nna_reg_read(0xB03Cu);
    fprintf(v1, "%05x,%08x,%s", 45116, v272, "PDP_D_RECIP_KERNEL_HEIGHT_0");
    v273 = nna_reg_read(0xB040u);
    fprintf(v1, "%05x,%08x,%s", 45120, v273, "PDP_D_POOLING_PADDING_CFG_0");
    v274 = nna_reg_read(0xB044u);
    fprintf(v1, "%05x,%08x,%s", 45124, v274, "PDP_D_POOLING_PADDING_VALUE_1_CFG_0");
    v275 = nna_reg_read(0xB048u);
    fprintf(v1, "%05x,%08x,%s", 45128, v275, "PDP_D_POOLING_PADDING_VALUE_2_CFG_0");
    v276 = nna_reg_read(0xB04Cu);
    fprintf(v1, "%05x,%08x,%s", 45132, v276, "PDP_D_POOLING_PADDING_VALUE_3_CFG_0");
    v277 = nna_reg_read(0xB050u);
    fprintf(v1, "%05x,%08x,%s", 45136, v277, "PDP_D_POOLING_PADDING_VALUE_4_CFG_0");
    v278 = nna_reg_read(0xB054u);
    fprintf(v1, "%05x,%08x,%s", 45140, v278, "PDP_D_POOLING_PADDING_VALUE_5_CFG_0");
    v279 = nna_reg_read(0xB058u);
    fprintf(v1, "%05x,%08x,%s", 45144, v279, "PDP_D_POOLING_PADDING_VALUE_6_CFG_0");
    v280 = nna_reg_read(0xB05Cu);
    fprintf(v1, "%05x,%08x,%s", 45148, v280, "PDP_D_POOLING_PADDING_VALUE_7_CFG_0");
    v281 = nna_reg_read(0xB060u);
    fprintf(v1, "%05x,%08x,%s", 45152, v281, "PDP_D_SRC_BASE_ADDR_LOW_0");
    v282 = nna_reg_read(0xB064u);
    fprintf(v1, "%05x,%08x,%s", 45156, v282, "PDP_D_SRC_BASE_ADDR_HIGH_0");
    v283 = nna_reg_read(0xB068u);
    fprintf(v1, "%05x,%08x,%s", 45160, v283, "PDP_D_SRC_LINE_STRIDE_0");
    v284 = nna_reg_read(0xB06Cu);
    fprintf(v1, "%05x,%08x,%s", 45164, v284, "PDP_D_SRC_SURFACE_STRIDE_0");
    v285 = nna_reg_read(0xB070u);
    fprintf(v1, "%05x,%08x,%s", 45168, v285, "PDP_D_DST_BASE_ADDR_LOW_0");
    v286 = nna_reg_read(0xB074u);
    fprintf(v1, "%05x,%08x,%s", 45172, v286, "PDP_D_DST_BASE_ADDR_HIGH_0");
    v287 = nna_reg_read(0xB078u);
    fprintf(v1, "%05x,%08x,%s", 45176, v287, "PDP_D_DST_LINE_STRIDE_0");
    v288 = nna_reg_read(0xB07Cu);
    fprintf(v1, "%05x,%08x,%s", 45180, v288, "PDP_D_DST_SURFACE_STRIDE_0");
    v289 = nna_reg_read(0xB080u);
    fprintf(v1, "%05x,%08x,%s", 45184, v289, "PDP_D_DST_RAM_CFG_0");
    v290 = nna_reg_read(0xB084u);
    fprintf(v1, "%05x,%08x,%s", 45188, v290, "PDP_D_DATA_FORMAT_0");
    v291 = nna_reg_read(0xB088u);
    fprintf(v1, "%05x,%08x,%s", 45192, v291, "PDP_D_INF_INPUT_NUM_0");
    v292 = nna_reg_read(0xB08Cu);
    fprintf(v1, "%05x,%08x,%s", 45196, v292, "PDP_D_NAN_INPUT_NUM_0");
    v293 = nna_reg_read(0xB090u);
    fprintf(v1, "%05x,%08x,%s", 45200, v293, "PDP_D_NAN_OUTPUT_NUM_0");
    v294 = nna_reg_read(0xB094u);
    fprintf(v1, "%05x,%08x,%s", 45204, v294, "PDP_D_PERF_ENABLE_0");
    v295 = nna_reg_read(0xB098u);
    fprintf(v1, "%05x,%08x,%s", 45208, v295, "PDP_D_PERF_WRITE_STALL_0");
    v296 = nna_reg_read(0xB09Cu);
    fprintf(v1, "%05x,%08x,%s", 45212, v296, "PDP_D_CYA_0");
    v297 = nna_reg_read(0xC000u);
    fprintf(v1, "%05x,%08x,%s", 49152, v297, "CDP_RDMA_S_STATUS_0 --READ_ONLY --");
    v298 = nna_reg_read(0xC004u);
    fprintf(v1, "%05x,%08x,%s", 49156, v298, "CDP_RDMA_S_POINTER_0 --DONT_CARE --");
    v299 = nna_reg_read(0xC008u);
    fprintf(v1, "%05x,%08x,%s", 49160, v299, "CDP_RDMA_D_OP_ENABLE_0");
    v300 = nna_reg_read(0xC00Cu);
    fprintf(v1, "%05x,%08x,%s", 49164, v300, "CDP_RDMA_D_DATA_CUBE_WIDTH_0");
    v301 = nna_reg_read(0xC010u);
    fprintf(v1, "%05x,%08x,%s", 49168, v301, "CDP_RDMA_D_DATA_CUBE_HEIGHT_0");
    v302 = nna_reg_read(0xC014u);
    fprintf(v1, "%05x,%08x,%s", 49172, v302, "CDP_RDMA_D_DATA_CUBE_CHANNEL_0");
    v303 = nna_reg_read(0xC018u);
    fprintf(v1, "%05x,%08x,%s", 49176, v303, "CDP_RDMA_D_SRC_BASE_ADDR_LOW_0");
    v304 = nna_reg_read(0xC01Cu);
    fprintf(v1, "%05x,%08x,%s", 49180, v304, "CDP_RDMA_D_SRC_BASE_ADDR_HIGH_0");
    v305 = nna_reg_read(0xC020u);
    fprintf(v1, "%05x,%08x,%s", 49184, v305, "CDP_RDMA_D_SRC_LINE_STRIDE_0");
    v306 = nna_reg_read(0xC024u);
    fprintf(v1, "%05x,%08x,%s", 49188, v306, "CDP_RDMA_D_SRC_SURFACE_STRIDE_0");
    v307 = nna_reg_read(0xC028u);
    fprintf(v1, "%05x,%08x,%s", 49192, v307, "CDP_RDMA_D_SRC_DMA_CFG_0");
    v308 = nna_reg_read(0xC02Cu);
    fprintf(v1, "%05x,%08x,%s", 49196, v308, "CDP_RDMA_D_SRC_COMPRESSION_EN_0");
    v309 = nna_reg_read(0xC030u);
    fprintf(v1, "%05x,%08x,%s", 49200, v309, "CDP_RDMA_D_OPERATION_MODE_0");
    v310 = nna_reg_read(0xC034u);
    fprintf(v1, "%05x,%08x,%s", 49204, v310, "CDP_RDMA_D_DATA_FORMAT_0");
    v311 = nna_reg_read(0xC038u);
    fprintf(v1, "%05x,%08x,%s", 49208, v311, "CDP_RDMA_D_PERF_ENABLE_0");
    v312 = nna_reg_read(0xC03Cu);
    fprintf(v1, "%05x,%08x,%s", 49212, v312, "CDP_RDMA_D_PERF_READ_STALL_0");
    v313 = nna_reg_read(0xC040u);
    fprintf(v1, "%05x,%08x,%s", 49216, v313, "CDP_RDMA_D_CYA_0");
    v314 = nna_reg_read(0xD000u);
    fprintf(v1, "%05x,%08x,%s", 53248, v314, "CDP_S_STATUS_0 --READ_ONLY --");
    v315 = nna_reg_read(0xD004u);
    fprintf(v1, "%05x,%08x,%s", 53252, v315, "CDP_S_POINTER_0 --DONT_CARE --");
    v316 = nna_reg_read(0xD008u);
    fprintf(v1, "%05x,%08x,%s", 53256, v316, "CDP_S_LUT_ACCESS_CFG_0");
    v317 = nna_reg_read(0xD00Cu);
    fprintf(v1, "%05x,%08x,%s", 53260, v317, "CDP_S_LUT_ACCESS_DATA_0");
    v318 = nna_reg_read(0xD010u);
    fprintf(v1, "%05x,%08x,%s", 53264, v318, "CDP_S_LUT_CFG_0");
    v319 = nna_reg_read(0xD014u);
    fprintf(v1, "%05x,%08x,%s", 53268, v319, "CDP_S_LUT_INFO_0");
    v320 = nna_reg_read(0xD018u);
    fprintf(v1, "%05x,%08x,%s", 53272, v320, "CDP_S_LUT_LE_START_LOW_0");
    v321 = nna_reg_read(0xD01Cu);
    fprintf(v1, "%05x,%08x,%s", 53276, v321, "CDP_S_LUT_LE_START_HIGH_0");
    v322 = nna_reg_read(0xD020u);
    fprintf(v1, "%05x,%08x,%s", 53280, v322, "CDP_S_LUT_LE_END_LOW_0");
    v323 = nna_reg_read(0xD024u);
    fprintf(v1, "%05x,%08x,%s", 53284, v323, "CDP_S_LUT_LE_END_HIGH_0");
    v324 = nna_reg_read(0xD028u);
    fprintf(v1, "%05x,%08x,%s", 53288, v324, "CDP_S_LUT_LO_START_LOW_0");
    v325 = nna_reg_read(0xD02Cu);
    fprintf(v1, "%05x,%08x,%s", 53292, v325, "CDP_S_LUT_LO_START_HIGH_0");
    v326 = nna_reg_read(0xD030u);
    fprintf(v1, "%05x,%08x,%s", 53296, v326, "CDP_S_LUT_LO_END_LOW_0");
    v327 = nna_reg_read(0xD034u);
    fprintf(v1, "%05x,%08x,%s", 53300, v327, "CDP_S_LUT_LO_END_HIGH_0");
    v328 = nna_reg_read(0xD038u);
    fprintf(v1, "%05x,%08x,%s", 53304, v328, "CDP_S_LUT_LE_SLOPE_SCALE_0");
    v329 = nna_reg_read(0xD03Cu);
    fprintf(v1, "%05x,%08x,%s", 53308, v329, "CDP_S_LUT_LE_SLOPE_SHIFT_0");
    v330 = nna_reg_read(0xD040u);
    fprintf(v1, "%05x,%08x,%s", 53312, v330, "CDP_S_LUT_LO_SLOPE_SCALE_0");
    v331 = nna_reg_read(0xD044u);
    fprintf(v1, "%05x,%08x,%s", 53316, v331, "CDP_S_LUT_LO_SLOPE_SHIFT_0");
    v332 = nna_reg_read(0xD048u);
    fprintf(v1, "%05x,%08x,%s", 53320, v332, "CDP_D_OP_ENABLE_0");
    v333 = nna_reg_read(0xD04Cu);
    fprintf(v1, "%05x,%08x,%s", 53324, v333, "CDP_D_FUNC_BYPASS_0");
    v334 = nna_reg_read(0xD050u);
    fprintf(v1, "%05x,%08x,%s", 53328, v334, "CDP_D_DST_BASE_ADDR_LOW_0");
    v335 = nna_reg_read(0xD054u);
    fprintf(v1, "%05x,%08x,%s", 53332, v335, "CDP_D_DST_BASE_ADDR_HIGH_0");
    v336 = nna_reg_read(0xD058u);
    fprintf(v1, "%05x,%08x,%s", 53336, v336, "CDP_D_DST_LINE_STRIDE_0");
    v337 = nna_reg_read(0xD05Cu);
    fprintf(v1, "%05x,%08x,%s", 53340, v337, "CDP_D_DST_SURFACE_STRIDE_0");
    v338 = nna_reg_read(0xD060u);
    fprintf(v1, "%05x,%08x,%s", 53344, v338, "CDP_D_DST_DMA_CFG_0");
    v339 = nna_reg_read(0xD064u);
    fprintf(v1, "%05x,%08x,%s", 53348, v339, "CDP_D_DST_COMPRESSION_EN_0");
    v340 = nna_reg_read(0xD068u);
    fprintf(v1, "%05x,%08x,%s", 53352, v340, "CDP_D_DATA_FORMAT_0");
    v341 = nna_reg_read(0xD06Cu);
    fprintf(v1, "%05x,%08x,%s", 53356, v341, "CDP_D_NAN_FLUSH_TO_ZERO_0");
    v342 = nna_reg_read(0xD070u);
    fprintf(v1, "%05x,%08x,%s", 53360, v342, "CDP_D_LRN_CFG_0");
    v343 = nna_reg_read(0xD074u);
    fprintf(v1, "%05x,%08x,%s", 53364, v343, "CDP_D_DATIN_OFFSET_0");
    v344 = nna_reg_read(0xD078u);
    fprintf(v1, "%05x,%08x,%s", 53368, v344, "CDP_D_DATIN_SCALE_0");
    v345 = nna_reg_read(0xD07Cu);
    fprintf(v1, "%05x,%08x,%s", 53372, v345, "CDP_D_DATIN_SHIFTER_0");
    v346 = nna_reg_read(0xD080u);
    fprintf(v1, "%05x,%08x,%s", 53376, v346, "CDP_D_DATOUT_OFFSET_0");
    v347 = nna_reg_read(0xD084u);
    fprintf(v1, "%05x,%08x,%s", 53380, v347, "CDP_D_DATOUT_SCALE_0");
    v348 = nna_reg_read(0xD088u);
    fprintf(v1, "%05x,%08x,%s", 53384, v348, "CDP_D_DATOUT_SHIFTER_0");
    v349 = nna_reg_read(0xD08Cu);
    fprintf(v1, "%05x,%08x,%s", 53388, v349, "CDP_D_NAN_INPUT_NUM_0");
    v350 = nna_reg_read(0xD090u);
    fprintf(v1, "%05x,%08x,%s", 53392, v350, "CDP_D_INF_INPUT_NUM_0");
    v351 = nna_reg_read(0xD094u);
    fprintf(v1, "%05x,%08x,%s", 53396, v351, "CDP_D_NAN_OUTPUT_NUM_0");
    v352 = nna_reg_read(0xD098u);
    fprintf(v1, "%05x,%08x,%s", 53400, v352, "CDP_D_OUT_SATURATION_0");
    v353 = nna_reg_read(0xD09Cu);
    fprintf(v1, "%05x,%08x,%s", 53404, v353, "CDP_D_PERF_ENABLE_0");
    v354 = nna_reg_read(0xD0A0u);
    fprintf(v1, "%05x,%08x,%s", 53408, v354, "CDP_D_PERF_WRITE_STALL_0");
    v355 = nna_reg_read(0xD0A4u);
    fprintf(v1, "%05x,%08x,%s", 53412, v355, "CDP_D_PERF_LUT_UFLOW_0");
    v356 = nna_reg_read(0xD0A8u);
    fprintf(v1, "%05x,%08x,%s", 53416, v356, "CDP_D_PERF_LUT_OFLOW_0");
    v357 = nna_reg_read(0xD0ACu);
    fprintf(v1, "%05x,%08x,%s", 53420, v357, "CDP_D_PERF_LUT_HYBRID_0");
    v358 = nna_reg_read(0xD0B0u);
    fprintf(v1, "%05x,%08x,%s", 53424, v358, "CDP_D_PERF_LUT_LE_HIT_0");
    v359 = nna_reg_read(0xD0B4u);
    fprintf(v1, "%05x,%08x,%s", 53428, v359, "CDP_D_PERF_LUT_LO_HIT_0");
    v360 = nna_reg_read(0xD0B8u);
    fprintf(v1, "%05x,%08x,%s", 53432, v360, "CDP_D_CYA_0");
    v361 = nna_reg_read(0x10000u);
    fprintf(v1, "%05x,%08x,%s", 0x10000, v361, "BDMA_CFG_SRC_ADDR_LOW_0");
    v362 = nna_reg_read(0x10004u);
    fprintf(v1, "%05x,%08x,%s", 65540, v362, "BDMA_CFG_SRC_ADDR_HIGH_0");
    v363 = nna_reg_read(0x10008u);
    fprintf(v1, "%05x,%08x,%s", 65544, v363, "BDMA_CFG_DST_ADDR_LOW_0");
    v364 = nna_reg_read(0x1000Cu);
    fprintf(v1, "%05x,%08x,%s", 65548, v364, "BDMA_CFG_DST_ADDR_HIGH_0");
    v365 = nna_reg_read(0x10010u);
    fprintf(v1, "%05x,%08x,%s", 65552, v365, "BDMA_CFG_LINE_0");
    v366 = nna_reg_read(0x10014u);
    fprintf(v1, "%05x,%08x,%s", 65556, v366, "BDMA_CFG_CMD_0");
    v367 = nna_reg_read(0x10018u);
    fprintf(v1, "%05x,%08x,%s", 65560, v367, "BDMA_CFG_LINE_REPEAT_0");
    v368 = nna_reg_read(0x1001Cu);
    fprintf(v1, "%05x,%08x,%s", 65564, v368, "BDMA_CFG_SRC_LINE_0");
    v369 = nna_reg_read(0x10020u);
    fprintf(v1, "%05x,%08x,%s", 65568, v369, "BDMA_CFG_DST_LINE_0");
    v370 = nna_reg_read(0x10024u);
    fprintf(v1, "%05x,%08x,%s", 65572, v370, "BDMA_CFG_SURF_REPEAT_0");
    v371 = nna_reg_read(0x10028u);
    fprintf(v1, "%05x,%08x,%s", 65576, v371, "BDMA_CFG_SRC_SURF_0");
    v372 = nna_reg_read(0x1002Cu);
    fprintf(v1, "%05x,%08x,%s", 65580, v372, "BDMA_CFG_DST_SURF_0");
    v373 = nna_reg_read(0x10030u);
    fprintf(v1, "%05x,%08x,%s", 65584, v373, "BDMA_CFG_OP_0");
    v374 = nna_reg_read(0x10034u);
    fprintf(v1, "%05x,%08x,%s", 65588, v374, "BDMA_CFG_LAUNCH0_0");
    v375 = nna_reg_read(0x10038u);
    fprintf(v1, "%05x,%08x,%s", 65592, v375, "BDMA_CFG_LAUNCH1_0");
    v376 = nna_reg_read(0x1003Cu);
    fprintf(v1, "%05x,%08x,%s", 65596, v376, "BDMA_CFG_STATUS_0 --READ_ONLY --");
    v377 = nna_reg_read(0x10040u);
    fprintf(v1, "%05x,%08x,%s", 65600, v377, "BDMA_STATUS_0 --READ_ONLY --");
    v378 = nna_reg_read(0x10044u);
    fprintf(v1, "%05x,%08x,%s", 65604, v378, "BDMA_STATUS_GRP0_READ_STALL_0 --READ_ONLY --");
    v379 = nna_reg_read(0x10048u);
    fprintf(v1, "%05x,%08x,%s", 65608, v379, "BDMA_STATUS_GRP0_WRITE_STALL_0 --READ_ONLY --");
    v380 = nna_reg_read(0x1004Cu);
    fprintf(v1, "%05x,%08x,%s", 65612, v380, "BDMA_STATUS_GRP1_READ_STALL_0 --READ_ONLY --");
    v381 = nna_reg_read(0x10050u);
    fprintf(v1, "%05x,%08x,%s", 65616, v381, "BDMA_STATUS_GRP1_WRITE_STALL_0 --READ_ONLY --");
    fclose(v1);
    result = 0;
  }
  else
  {
    printf("%s open failed.", &s);
    result = -1;
  }
  return result;
}

// ALL OK, 16 function(s) have been successfully decompiled
