/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall nna_poll_reg_equal(int a1, int a2);
int __fastcall setPointer(int a1);
int __fastcall setCdmaPointer(int a1);
int __fastcall setCdmaNextPointer(int a1);
int __fastcall setNextPointer(int a1);
// int __fastcall xregr(_DWORD); weak
// int __fastcall xregw(_DWORD, _DWORD); weak


//----- (00000004) --------------------------------------------------------
int __fastcall nna_poll_reg_equal(int a1, int a2)
{
  int v2; // r5
  int v3; // r4
  int result; // r0
  signed int v5; // r3

  v2 = a1;
  v3 = a2;
  while ( 1 )
  {
    result = xregr(v2);
    if ( result == v3 )
      break;
    v5 = 0x10000;
    do
      --v5;
    while ( v5 );
  }
  return result;
}
// 26830: using guessed type int __fastcall xregr(_DWORD);

//----- (0000002C) --------------------------------------------------------
int __fastcall setPointer(int a1)
{
  int v1; // r4
  unsigned int v2; // r0

  v1 = a1;
  v2 = xregr(a1);
  return xregw(v1, v2 >> 16);
}
// 26830: using guessed type int __fastcall xregr(_DWORD);
// 26838: using guessed type int __fastcall xregw(_DWORD, _DWORD);

//----- (0000004C) --------------------------------------------------------
int __fastcall setCdmaPointer(int a1)
{
  int v1; // r4
  unsigned int v2; // r0

  v1 = a1;
  v2 = xregr(16388);
  return xregw(v1, v2 >> 16);
}
// 26830: using guessed type int __fastcall xregr(_DWORD);
// 26838: using guessed type int __fastcall xregw(_DWORD, _DWORD);

//----- (00000070) --------------------------------------------------------
int __fastcall setCdmaNextPointer(int a1)
{
  int v1; // r4
  unsigned int v2; // r0

  v1 = a1;
  v2 = xregr(16388);
  return xregw(v1, ((v2 >> 16) + 1) & 1);
}
// 26830: using guessed type int __fastcall xregr(_DWORD);
// 26838: using guessed type int __fastcall xregw(_DWORD, _DWORD);

//----- (00000098) --------------------------------------------------------
int __fastcall setNextPointer(int a1)
{
  int v1; // r4
  unsigned int v2; // r0

  v1 = a1;
  v2 = xregr(a1);
  return xregw(v1, ((v2 >> 16) + 1) & 1);
}
// 26830: using guessed type int __fastcall xregr(_DWORD);
// 26838: using guessed type int __fastcall xregw(_DWORD, _DWORD);

//----- (000000BC) --------------------------------------------------------
#error "BC: too big function (funcsize=0)"

#error "There were 1 decompilation failure(s) on 6 function(s)"
