/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall nna_bisa_cfg(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13);
int __fastcall nna_x1_cfg(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17);
int __fastcall nna_x2_cfg(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17);
int __fastcall nna_y_cfg(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24);
int __fastcall nna_lut_updata_table_x_le(__int16 *a1);
int __fastcall nna_lut_updata_table_y_lo(__int16 *a1);
int __fastcall nna_lut_cfg(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, unsigned int a6, unsigned int a7, unsigned int a8, unsigned int a9, unsigned int a10, unsigned int a11);
int __fastcall nna_swish_cfg(int a1);
int __fastcall nna_act(int, int, int, int, int, int, int, int); // idb
int __fastcall nna_eltwise(int, unsigned int, unsigned int, int, int, int, int, int, int, int); // idb
// _DWORD __cdecl xregw(unsigned int, unsigned int); idb
// int printf(const char *format, ...);
// int __fastcall nna_build_swish_table(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak


//----- (00000004) --------------------------------------------------------
int __fastcall nna_bisa_cfg(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13)
{
  unsigned int v13; // r10
  unsigned int v14; // r4
  _BOOL4 v15; // r11
  unsigned int v16; // r7
  unsigned int v17; // r9
  unsigned int v18; // r1
  unsigned int v19; // r0
  _BOOL4 v21; // [sp+4h] [bp-4Ch]
  unsigned int v22; // [sp+8h] [bp-48h]
  unsigned int v23; // [sp+Ch] [bp-44h]

  v13 = a2;
  v23 = a4;
  v14 = a3;
  v15 = a2 == 0;
  v22 = a1;
  v16 = 8 * a8;
  v17 = a9 * 8 * a8;
  v21 = a1 == 0;
  xregw(0x8070u, v15);
  xregw(0x8074u, 1u);
  xregw(0x800Cu, a8 - 1);
  xregw(0x8010u, a9 - 1);
  xregw(0x8014u, a10 - 1);
  if ( v13 )
  {
    xregw(0x8018u, v13);
    xregw(0x8020u, v16);
    xregw(0x8024u, v17);
  }
  if ( v22 )
  {
    xregw(0x9048u, v22);
    xregw(0x9050u, 8 * a6);
    xregw(0x9054u, a7 * 8 * a6);
    xregw(0x90B4u, 1u);
  }
  if ( v14 )
  {
    if ( v14 == 1 )
      v14 = 0;
    xregw(0x802Cu, v14);
    if ( v14 >= 0x8000 )
    {
      xregw(0x8034u, v16);
      xregw(0x8038u, v17);
      v18 = 0;
      v19 = 32828;
    }
    else
    {
      v18 = 12;
      v19 = 32808;
    }
    xregw(v19, v18);
  }
  if ( v23 )
  {
    xregw(0x8044u, v23);
    xregw(0x804Cu, v16);
    xregw(0x8050u, v17);
    xregw(0x8054u, 0);
  }
  if ( a5 )
  {
    xregw(0x805Cu, a5);
    xregw(0x8064u, v16);
    xregw(0x8068u, v17);
    xregw(0x806Cu, 0);
  }
  xregw(0x903Cu, a8 - 1);
  xregw(0x9040u, a9 - 1);
  xregw(0x9044u, a10 - 1);
  xregw(0x90B0u, v15 | 2 * v21);
  xregw(0x90BCu, 0);
  xregw(0x90C0u, a11);
  xregw(0x90C4u, a12);
  return xregw(0x90C8u, a13);
}

//----- (00000270) --------------------------------------------------------
int __fastcall nna_x1_cfg(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17)
{
  int v17; // r4
  int v18; // r7
  int v19; // r11
  int result; // r0
  int v21; // [sp+0h] [bp-40h]

  v17 = a2;
  v18 = a1;
  v21 = a4;
  v19 = a3;
  result = xregw(0x9058u, a1 | 2 * a7 | 4 * a9 | 16 * a12 | 32 * a17 | (a16 << 6));
  if ( !v18 )
  {
    xregw(0x8028u, v17 | 2 * a6 | 8 * a5 | 16 * v21 | 32 * v19);
    if ( !a7 )
    {
      xregw(0x905Cu, (unsigned __int16)((_WORD)a10 << 8) | a8);
      xregw(0x9060u, (unsigned int)a11 >> 16);
    }
    if ( !a12 )
      xregw(0x9064u, (unsigned __int16)((_WORD)a15 << 8) | a13);
    result = xregw(0x9068u, a14);
  }
  return result;
}

//----- (00000390) --------------------------------------------------------
int __fastcall nna_x2_cfg(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17)
{
  int v17; // r4
  int v18; // r7
  int v19; // r11
  int result; // r0
  int v21; // [sp+0h] [bp-40h]

  v17 = a2;
  v18 = a1;
  v21 = a4;
  v19 = a3;
  result = xregw(0x906Cu, a1 | 2 * a7 | 4 * a9 | 16 * a12 | 32 * a17 | (a16 << 6));
  if ( !v18 )
  {
    xregw(0x8040u, v17 | 2 * a6 | 8 * a5 | 16 * v21 | 32 * v19);
    if ( !a7 )
    {
      xregw(0x9070u, (unsigned __int16)((_WORD)a10 << 8) | a8);
      xregw(0x9074u, (unsigned int)a11 >> 16);
    }
    if ( !a12 )
      xregw(0x9078u, (unsigned __int16)((_WORD)a15 << 8) | a13);
    result = xregw(0x907Cu, a14);
  }
  return result;
}

//----- (000004B0) --------------------------------------------------------
int __fastcall nna_y_cfg(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24)
{
  int v24; // r4
  int v25; // r9
  int result; // r0
  int v27; // [sp+4h] [bp-5Ch]
  int v28; // [sp+8h] [bp-58h]

  v24 = a2;
  v25 = a1;
  v27 = a3;
  v28 = a4;
  result = xregw(0x9080u, a1 | 2 * a7 | 4 * a9 | 16 * a15 | 32 * a24 | (a23 << 6));
  if ( !v25 )
  {
    xregw(0x8058u, v24 | 2 * a6 | 8 * a5 | 16 * v28 | 32 * v27);
    if ( !a15 )
    {
      xregw(0x9098u, a16 | 2 * a17);
      xregw(0x909Cu, (unsigned __int16)a21);
      if ( !a17 )
      {
        xregw(0x90A0u, a18);
        xregw(0x90A4u, a19);
        xregw(0x90A8u, a20);
      }
    }
    result = xregw(0x90ACu, a22);
    if ( !a7 )
    {
      xregw(0x9084u, a8 | 2 * a10);
      result = xregw(0x9088u, (unsigned int)a14 >> 16);
      if ( !a10 )
      {
        xregw(0x908Cu, a11);
        xregw(0x9090u, (unsigned __int16)a12);
        result = xregw(0x9094u, a13);
      }
    }
  }
  return result;
}

//----- (00000658) --------------------------------------------------------
int __fastcall nna_lut_updata_table_x_le(__int16 *a1)
{
  __int16 *v1; // r4
  __int16 *v2; // r5
  unsigned int v3; // t1
  int result; // r0

  v1 = a1;
  v2 = a1 + 65;
  printf("\n# nna_lut_updata_table_x_le");
  xregw(0x9008u, 0x20000u);
  do
  {
    v3 = *v1;
    ++v1;
    result = xregw(0x900Cu, v3);
  }
  while ( v1 != v2 );
  return result;
}

//----- (000006A4) --------------------------------------------------------
int __fastcall nna_lut_updata_table_y_lo(__int16 *a1)
{
  __int16 *v1; // r4
  __int16 *v2; // r5
  unsigned int v3; // t1
  int result; // r0

  v1 = a1;
  v2 = a1 + 257;
  printf("\n# nna_lut_updata_table_y_lo");
  xregw(0x9008u, 0x30000u);
  do
  {
    v3 = *v1;
    ++v1;
    result = xregw(0x900Cu, v3);
  }
  while ( v1 != v2 );
  return result;
}

//----- (000006F4) --------------------------------------------------------
int __fastcall nna_lut_cfg(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, unsigned int a6, unsigned int a7, unsigned int a8, unsigned int a9, unsigned int a10, unsigned int a11)
{
  unsigned int v11; // r4
  unsigned int v12; // r9
  unsigned int v13; // r10
  unsigned int v14; // r11

  v11 = a4;
  v12 = a1;
  v13 = a2;
  v14 = a3;
  printf("\n# nna_lut_cfg");
  printf(
    "\n"
    " hybrid_priority_lo:%x \n"
    " oflow_priority_lo :%x \n"
    " uflow_priority_lo :%x \n"
    " le_function_linear:%x \n"
    " le_index_offset   :%x \n"
    " le_index_select   :%x \n"
    " lo_index_select   :%x \n"
    " le_start          :%x \n"
    " le_end            :%x \n"
    " lo_start          :%x \n"
    " lo_end            :%x ",
    v12,
    v13,
    v14,
    v11,
    a5,
    a6,
    a7,
    a8,
    a9,
    a10,
    a11);
  xregw(0x9010u, v11 | 16 * v14 | 32 * v13 | (v12 << 6));
  xregw(0x9014u, a5 | (a6 << 8) | (a7 << 16));
  xregw(0x9018u, a8);
  xregw(0x901Cu, a9);
  xregw(0x9020u, a10);
  return xregw(0x9024u, a11);
}

//----- (00000800) --------------------------------------------------------
int __fastcall nna_swish_cfg(int a1)
{
  int v1; // r4
  char v3; // [sp+20h] [bp-200h]

  v1 = a1;
  printf("\n# nna_swish_cfg:%d", a1);
  nna_build_swish_table(&v3, -16, 16, 11, 65);
  nna_lut_updata_table_x_le((__int16 *)&v3);
  nna_build_swish_table(&v3, -1, 1, 11, 257);
  nna_lut_updata_table_y_lo((__int16 *)&v3);
  return nna_lut_cfg(1u, 0, 0, 1u, 0, v1 - 1, v1 - 7, -(1 << (v1 + 4)), 1 << (v1 + 4), -(1 << v1), 1 << v1);
}
// D34: using guessed type int __fastcall nna_build_swish_table(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (000008CC) --------------------------------------------------------
int __fastcall nna_act(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
  nna_bisa_cfg(a1, a2, 0, 0, 0, a4, a5, a4, a5, a6, 0, 1, (unsigned __int8)a3);
  nna_x1_cfg(0, 1, 1, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, a8 >> 8, (unsigned __int8)a8, 1, a7 == 2);
  nna_x2_cfg(1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0);
  return nna_y_cfg(1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0);
}

//----- (00000A34) --------------------------------------------------------
int __fastcall nna_eltwise(int a1, unsigned int a2, unsigned int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10)
{
  signed int v10; // r6
  int v11; // r3
  int v12; // r2

  v10 = a8;
  nna_bisa_cfg(a1, a3, a2, 0, 0, a5, a6, a5, a6, a7, 0, 1, 0);
  nna_x1_cfg(0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, a10, 0, 0, 1, 0);
  if ( !a8 )
  {
    v11 = 1;
    goto LABEL_4;
  }
  v11 = 0;
  v10 = 1;
  if ( a8 != 2 )
  {
LABEL_4:
    v12 = 2;
    goto LABEL_5;
  }
  v12 = 0;
LABEL_5:
  nna_x2_cfg(0, 1, 0, 1, 0, 0, v11, 1, v12, 0, 0, v10, 1, 0, 0, 1, 0);
  return nna_y_cfg(1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0);
}

// ALL OK, 10 function(s) have been successfully decompiled
