/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall nna_net_ypr_run(int a1, int a2, int a3);
int __fastcall nna_net_ypr_init(int a1, int a2, int a3);
int __fastcall nna_net_ypr(unsigned __int8 *a1, int a2, int a3, int a4);
int __fastcall nna_net_ypr_post(char *a1, char *a2);
unsigned int nna_net_ypr_get_score_size(void);
unsigned int nna_net_ypr_get_location_size(void);
int nna_net_ypr_get_score_w(void);
int nna_net_ypr_get_score_h(void);
int nna_net_ypr_get_score_c(void);
int nna_net_ypr_case(void);
int GLOBAL__sub_I_ypr_layer();
// int __fastcall nna_net_init(_DWORD); weak
// int __fastcall nna_net_load_hyper(_DWORD); weak
// int __fastcall xramcpy(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int printf(const char *format, ...);
// int __fastcall nna_net_forward(_DWORD); weak
// int __fastcall nna_net_dump(_DWORD); weak
// _DWORD std::ios_base::Init::Init(std::ios_base::Init *__hidden this); idb
// _DWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this); weak
// int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_8; // weak
_UNKNOWN loc_C; // weak
_UNKNOWN loc_10; // weak
_UNKNOWN loc_18; // weak
_UNKNOWN loc_4C; // weak
_UNKNOWN loc_50; // weak
_UNKNOWN loc_54; // weak
_UNKNOWN unk_1984; // weak
_UNKNOWN ypr_info; // weak
int *off_5AE4 = &ypr_io_data; // weak
void *off_5AEC = &ypr_layer; // weak
_UNKNOWN std::__ioinit; // weak
// extern _UNKNOWN _dso_handle; weak


//----- (00000004) --------------------------------------------------------
int __fastcall nna_net_ypr_run(int a1, int a2, int a3)
{
  int v3; // r9
  int v4; // r5
  int v5; // r6
  void *v6; // r3
  int v7; // r8
  int v8; // r10

  v3 = a1;
  v4 = a2;
  v5 = a3;
  v6 = off_5AEC;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)off_5AEC) = a2;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)v6) = a3;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v6) = 1;
  nna_net_init(&ypr_info);
  nna_net_load_hyper(&ypr_info);
  *(_DWORD *)((char *)&loc_8 + (_DWORD)off_5AE4) = v5 * v4;
  v7 = *off_5AE4;
  v8 = *(_DWORD *)((char *)&loc_8 + (_DWORD)off_5AE4);
  xramcpy(*off_5AE4, v3, *(_DWORD *)((char *)&loc_8 + (_DWORD)off_5AE4), 1);
  printf("\n### +++nna_net_ypr_run[%3d %3d %3d] target:%x target2:%x file_sz:%d\n", v4, v5, 1, v7, v3, v8);
  return nna_net_forward(&ypr_info);
}
// 5AE4: using guessed type int *off_5AE4;
// 5AEC: using guessed type void *off_5AEC;
// 87E8: using guessed type int __fastcall nna_net_init(_DWORD);
// 87EC: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// 87F0: using guessed type int __fastcall xramcpy(_DWORD, _DWORD, _DWORD, _DWORD);
// 87F8: using guessed type int __fastcall nna_net_forward(_DWORD);

//----- (00000078) --------------------------------------------------------
int __fastcall nna_net_ypr_init(int a1, int a2, int a3)
{
  void *v3; // r4

  v3 = off_5AEC;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)off_5AEC) = a1;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)v3) = a2;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v3) = a3;
  return nna_net_init(&ypr_info);
}
// 5AEC: using guessed type void *off_5AEC;
// 87E8: using guessed type int __fastcall nna_net_init(_DWORD);

//----- (00000094) --------------------------------------------------------
int __fastcall nna_net_ypr(unsigned __int8 *a1, int a2, int a3, int a4)
{
  unsigned __int8 *v4; // r8
  int v5; // r5
  int v6; // r6
  int v7; // r10
  void *v8; // r3
  int v9; // r7
  int v10; // r11

  v4 = a1;
  v5 = a2;
  v6 = a3;
  v7 = a4;
  v8 = off_5AEC;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)off_5AEC) = a2;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)v8) = a3;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v8) = 1;
  nna_net_init(&ypr_info);
  nna_net_load_hyper(&ypr_info);
  *(_DWORD *)((char *)&loc_8 + (_DWORD)off_5AE4) = v6 * v5;
  v9 = *off_5AE4;
  v10 = *(_DWORD *)((char *)&loc_8 + (_DWORD)off_5AE4);
  xramcpy(*off_5AE4, v4, *(_DWORD *)((char *)&loc_8 + (_DWORD)off_5AE4), 1);
  printf("\n### +++nna_net_ypr[%3d %3d %3d] target:%x target2:%x file_sz:%d\n", v5, v6, v7, v9, v4, v10);
  return nna_net_forward(&ypr_info);
}
// 5AE4: using guessed type int *off_5AE4;
// 5AEC: using guessed type void *off_5AEC;
// 87E8: using guessed type int __fastcall nna_net_init(_DWORD);
// 87EC: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// 87F0: using guessed type int __fastcall xramcpy(_DWORD, _DWORD, _DWORD, _DWORD);
// 87F8: using guessed type int __fastcall nna_net_forward(_DWORD);

//----- (00000108) --------------------------------------------------------
int __fastcall nna_net_ypr_post(char *a1, char *a2)
{
  char *v2; // r4
  int v3; // r2
  int v4; // r1
  int v5; // r2
  int v6; // r2
  int v7; // r0
  int v8; // r2

  v2 = a2;
  v3 = *(_DWORD *)((char *)&unk_1984 + (_DWORD)off_5AE4 + (unsigned int)&loc_10 + 4);
  v4 = v3 + 14;
  v5 = v3 + 7;
  if ( v5 >= 0 )
    v4 = v5;
  xramcpy(
    a1,
    *(_DWORD *)((char *)&unk_1984 + (_DWORD)off_5AE4),
    *(_DWORD *)((char *)&unk_1984 + (_DWORD)off_5AE4 + (unsigned int)&loc_10)
  * *(_DWORD *)((char *)&unk_1984 + (_DWORD)off_5AE4 + (unsigned int)&loc_C)
  * (v4 & 0xFFFFFFF8),
    2);
  v6 = *(_DWORD *)((char *)&loc_10 + (_DWORD)(off_5AE4 + 1704) + 4);
  v7 = v6 + 14;
  v8 = v6 + 7;
  if ( v8 >= 0 )
    v7 = v8;
  return xramcpy(
           v2,
           off_5AE4[1704],
           *(_DWORD *)((char *)&loc_10 + (_DWORD)(off_5AE4 + 1704))
         * *(_DWORD *)((char *)&loc_C + (_DWORD)(off_5AE4 + 1704))
         * (v7 & 0xFFFFFFF8),
           2);
}
// 5AE4: using guessed type int *off_5AE4;
// 87F0: using guessed type int __fastcall xramcpy(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00000170) --------------------------------------------------------
unsigned int nna_net_ypr_get_score_size(void)
{
  int v0; // r0
  int v1; // r2
  int v2; // r0

  v0 = *(_DWORD *)((char *)&loc_18 + (_DWORD)(off_5AE4 + 1632));
  v1 = v0 + 14;
  v2 = v0 + 7;
  if ( v2 >= 0 )
    v1 = v2;
  return *(_DWORD *)((char *)&loc_10 + (_DWORD)(off_5AE4 + 1632) + 4)
       * *(_DWORD *)((char *)&loc_10 + (_DWORD)(off_5AE4 + 1632))
       * (v1 & 0xFFFFFFF8);
}
// 5AE4: using guessed type int *off_5AE4;

//----- (0000019C) --------------------------------------------------------
unsigned int nna_net_ypr_get_location_size(void)
{
  int v0; // r0
  int v1; // r3
  int v2; // r0

  v0 = *(_DWORD *)((char *)&loc_10 + (_DWORD)(off_5AE4 + 1704) + 4);
  v1 = v0 + 14;
  v2 = v0 + 7;
  if ( v2 >= 0 )
    v1 = v2;
  return *(_DWORD *)((char *)&loc_10 + (_DWORD)(off_5AE4 + 1704))
       * *(_DWORD *)((char *)&loc_C + (_DWORD)(off_5AE4 + 1704))
       * (v1 & 0xFFFFFFF8);
}
// 5AE4: using guessed type int *off_5AE4;

//----- (000001C8) --------------------------------------------------------
int nna_net_ypr_get_score_w(void)
{
  return *(_DWORD *)((char *)&loc_10 + (_DWORD)(off_5AE4 + 1632));
}
// 5AE4: using guessed type int *off_5AE4;

//----- (000001DC) --------------------------------------------------------
int nna_net_ypr_get_score_h(void)
{
  return *(_DWORD *)((char *)&loc_10 + (_DWORD)(off_5AE4 + 1632) + 4);
}
// 5AE4: using guessed type int *off_5AE4;

//----- (000001F0) --------------------------------------------------------
int nna_net_ypr_get_score_c(void)
{
  return *(_DWORD *)((char *)&loc_18 + (_DWORD)(off_5AE4 + 1632));
}
// 5AE4: using guessed type int *off_5AE4;

//----- (00000204) --------------------------------------------------------
int nna_net_ypr_case(void)
{
  nna_net_init(&ypr_info);
  nna_net_load_hyper(&ypr_info);
  nna_net_forward(&ypr_info);
  return nna_net_dump(&ypr_info);
}
// 87E8: using guessed type int __fastcall nna_net_init(_DWORD);
// 87EC: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// 87F8: using guessed type int __fastcall nna_net_forward(_DWORD);
// 87FC: using guessed type int __fastcall nna_net_dump(_DWORD);

//----- (00000228) --------------------------------------------------------
int GLOBAL__sub_I_ypr_layer()
{
  std::ios_base::Init::Init((std::ios_base::Init *)&std::__ioinit);
  return _aeabi_atexit(&std::__ioinit, &std::ios_base::Init::~Init, &_dso_handle);
}
// 8808: using guessed type _DWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this);
// 880C: using guessed type int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD);

// ALL OK, 11 function(s) have been successfully decompiled
