/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

signed int __fastcall nna_api_pool_max_output_w(int a1, int a2, int a3, int a4, int a5, int a6);
signed int __fastcall nna_api_conv_max_output_w(int a1, int a2, int a3, int a4, int a5);
int __fastcall nna_api_pool_get_input_w(int a1, int a2, int a3, int a4, int a5);
int __fastcall nna_api_pool_get_input_h(int a1, int a2, int a3, int a4, int a5);
int __fastcall nna_api_pool_get_output_w(int a1, int a2, int a3, int a4, int a5);
int __fastcall nna_api_pool_get_output_h(int a1, int a2, int a3, int a4, int a5);
int __fastcall nna_api_conv_get_input_w(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall nna_api_conv_get_output_w(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall nna_api_conv_get_output_h(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall nna_api_conv_get_entry_per_slice(int a1, int a2, int a3, int a4);
int __fastcall nna_api_conv_get_data_bank(int a1, int a2, int a3, int a4);
int __fastcall nna_api_conv_get_weight_bank(int a1, int a2, int a3, int a4, int a5, int a6);
unsigned int __fastcall nna_api_conv_get_weight_bytes(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall nna_api_conv_get_input_bytes(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall nna_api_set_split_pad(int result, int *a2, int a3, int a4, int a5);
int __fastcall nna_fill_bdma(_DWORD *a1, int a2, int a3);
int __fastcall nna_fill_lsc(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14);
int __fastcall nna_fill_nms(_DWORD *a1, int a2, int a3, int a4, int a5, int a6);
unsigned int __fastcall nna_fill_conv(_DWORD *a1, int a2, int a3, int a4, signed int a5, int a6, int a7, unsigned int a8, int a9, int a10, int a11, int a12, int a13);
unsigned int __fastcall nna_fill_conv_sub(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17);
signed int __fastcall nna_fill_sdp(_DWORD *a1, int a2, int a3, int a4, signed int a5, int a6, unsigned __int8 a7, signed int a8, int a9, int a10, int a11, int a12, int a13, signed int a14, int a15, int a16, int a17);
_DWORD *__fastcall nna_fill_sdp_sub(_DWORD *result, int a2, int a3, int a4, int a5);
int __fastcall nna_fill_pdp(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10);
int __fastcall nna_fill_pdp_sub(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
int __fastcall nna_api_conv_act_pool(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23);
int __fastcall nna_api_conv_act_pool_big(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23);
int __fastcall nna_api_conv_act(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19);
int __fastcall nna_api_conv_act_big(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19);
int __fastcall nna_api_conv_act_eltwise(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23);
int __fastcall nna_api_inner_product(unsigned int a1, unsigned int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11);
int __fastcall nna_api_lsc(unsigned int a1, unsigned int a2, unsigned int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13);
int __fastcall nna_api_nms(unsigned int a1, unsigned int a2, int a3, int a4, int a5);
// _DWORD nna_get_engine(void); idb
// void *memset(void *s, int c, size_t n);
// int printf(const char *format, ...);
// int __fastcall nna_play(_DWORD); weak
// int __fastcall dump_nna_op(_DWORD); weak


//----- (00000004) --------------------------------------------------------
signed int __fastcall nna_api_pool_max_output_w(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return 16;
}

//----- (00000018) --------------------------------------------------------
signed int __fastcall nna_api_conv_max_output_w(int a1, int a2, int a3, int a4, int a5)
{
  return 128;
}

//----- (0000002C) --------------------------------------------------------
int __fastcall nna_api_pool_get_input_w(int a1, int a2, int a3, int a4, int a5)
{
  return a3 * (a1 - 1) - (a4 + a5 - a2 + a3 - 1);
}

//----- (0000005C) --------------------------------------------------------
int __fastcall nna_api_pool_get_input_h(int a1, int a2, int a3, int a4, int a5)
{
  return a3 * (a1 - 1) - (a4 + a5 - a2 + a3 - 1);
}

//----- (0000008C) --------------------------------------------------------
int __fastcall nna_api_pool_get_output_w(int a1, int a2, int a3, int a4, int a5)
{
  return (a1 + a4 + a5 - a2 + a3 - 1) / a3 + 1;
}

//----- (000000C4) --------------------------------------------------------
int __fastcall nna_api_pool_get_output_h(int a1, int a2, int a3, int a4, int a5)
{
  return (a1 + a5 + a4 - a2 + a3 - 1) / a3 + 1;
}

//----- (000000FC) --------------------------------------------------------
int __fastcall nna_api_conv_get_input_w(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return (unsigned __int8)a3 * ((unsigned __int8)a2 - 1) + 1 + a4 * (a1 - 1) - (a5 + a6);
}

//----- (00000134) --------------------------------------------------------
int __fastcall nna_api_conv_get_output_w(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return (a1 - ((unsigned __int8)a3 * ((unsigned __int8)a2 - 1) + 1) + a5 + a6) / a4 + 1;
}

//----- (0000017C) --------------------------------------------------------
int __fastcall nna_api_conv_get_output_h(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return (a1 - ((unsigned __int16)a3 * ((unsigned __int16)a2 - 1) + 1) + a5 + a6) / a4 + 1;
}

//----- (000001C4) --------------------------------------------------------
int __fastcall nna_api_conv_get_entry_per_slice(int a1, int a2, int a3, int a4)
{
  int v4; // r1
  int v5; // r2
  unsigned int v6; // r2
  unsigned int v7; // r0
  int v8; // r2
  int result; // r0
  int v10; // r1
  int v11; // r1
  int v12; // r0
  int v13; // r1

  v4 = a1;
  if ( a4 )
  {
    v11 = a1 * a3;
    v12 = a1 * a3 + 31;
    if ( v12 >= 0 )
      v13 = v12;
    else
      v13 = v11 + 62;
    result = v13 >> 5;
  }
  else
  {
    if ( a3 + 7 >= 0 )
      v5 = a3 + 7;
    else
      v5 = a3 + 14;
    v6 = v5 >> 3;
    v7 = v6 >> 2;
    v8 = v6 & 3;
    result = v4 * v7;
    switch ( v8 )
    {
      case 3:
        result += v4;
        break;
      case 2:
        result += (v4 + 1) / 2;
        break;
      case 1:
        if ( v4 + 3 >= 0 )
          v10 = v4 + 3;
        else
          v10 = v4 + 6;
        result += v10 >> 2;
        break;
    }
  }
  return result;
}

//----- (00000254) --------------------------------------------------------
int __fastcall nna_api_conv_get_data_bank(int a1, int a2, int a3, int a4)
{
  return (nna_api_conv_get_entry_per_slice(a1, a2, a3, a4) * a2 + 511) / 512;
}

//----- (00000288) --------------------------------------------------------
int __fastcall nna_api_conv_get_weight_bank(int a1, int a2, int a3, int a4, int a5, int a6)
{
  int v6; // r6
  int v7; // r4
  int v8; // r3
  int v9; // r0

  v6 = a3;
  v7 = a4;
  nna_api_conv_get_entry_per_slice(a1, a2, a3, a6);
  v8 = v7 * (unsigned __int16)a5 * v6 * (unsigned __int16)a5;
  v9 = v8 + 31;
  if ( v8 + 31 < 0 )
    v9 = v8 + 62;
  return (signed int)((v9 & 0xFFFFFFE0) + 0x3FFF) / 0x4000;
}

//----- (000002E0) --------------------------------------------------------
unsigned int __fastcall nna_api_conv_get_weight_bytes(int a1, int a2, int a3, int a4, int a5, int a6)
{
  int v6; // r6
  int v7; // r4
  int v8; // r3
  int v9; // r0

  v6 = a3;
  v7 = a4;
  nna_api_conv_get_entry_per_slice(a1, a2, a3, a6);
  v8 = v7 * (unsigned __int16)a5 * v6 * (unsigned __int16)a5;
  v9 = v8 + 31;
  if ( v8 + 31 < 0 )
    v9 = v8 + 62;
  return v9 & 0xFFFFFFE0;
}

//----- (00000320) --------------------------------------------------------
int __fastcall nna_api_conv_get_input_bytes(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return (nna_api_conv_get_entry_per_slice(a1, a2, a3, a6) * a2 + 511) / 512;
}

//----- (00000358) --------------------------------------------------------
int __fastcall nna_api_set_split_pad(int result, int *a2, int a3, int a4, int a5)
{
  bool v5; // zf
  int v6; // lr

  v5 = a5 == a3;
  if ( a5 == a3 )
    v5 = a5 == a4;
  v6 = v5 != 0;
  if ( !v5 )
  {
    if ( a5 == a3 )
    {
      *a2 = v6;
    }
    else
    {
      if ( a5 != a4 )
        *a2 = v6;
      *(_DWORD *)result = v6;
    }
  }
  return result;
}

//----- (000003A0) --------------------------------------------------------
int __fastcall nna_fill_bdma(_DWORD *a1, int a2, int a3)
{
  _DWORD *v3; // r4
  int v4; // r6
  int v5; // r5
  int result; // r0
  int v7; // r2

  v3 = a1;
  v4 = a3;
  v5 = a2;
  result = nna_get_engine();
  v7 = *(_DWORD *)(result + 12);
  *v3 = 1;
  v3[2] = v4 - v7;
  v3[11] = v5 - v7;
  v3[19] = 1;
  return result;
}

//----- (000003E4) --------------------------------------------------------
int __fastcall nna_fill_lsc(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14)
{
  _DWORD *v14; // r4
  int v15; // r5
  int v16; // r7
  int v17; // r6
  int result; // r0
  int v19; // r2

  v14 = a1;
  v15 = a3;
  v16 = a4;
  v17 = a2;
  result = nna_get_engine();
  v19 = *(_DWORD *)(result + 12);
  *v14 = 1;
  v14[28] = a5;
  v14[29] = a6;
  v14[30] = a7;
  v14[2] = v16 - v19;
  v14[31] = a8;
  v14[11] = v17 - v19;
  v14[32] = a9;
  v14[20] = v15 - v19;
  v14[33] = a10;
  v14[34] = a11;
  v14[35] = a12;
  v14[36] = a13;
  v14[37] = a14;
  return result;
}

//----- (00000480) --------------------------------------------------------
int __fastcall nna_fill_nms(_DWORD *a1, int a2, int a3, int a4, int a5, int a6)
{
  _DWORD *v6; // r4
  int v7; // r7
  int v8; // r5
  int v9; // r6
  int result; // r0
  int v11; // r3

  v6 = a1;
  v7 = a4;
  v8 = a2;
  v9 = a3;
  result = nna_get_engine();
  *v6 = 1;
  v11 = *(_DWORD *)(result + 12);
  v6[19] = v7;
  v6[2] = v9 - v11;
  v6[20] = a5;
  v6[11] = v8 - v11;
  v6[21] = a6;
  return result;
}

//----- (000004D8) --------------------------------------------------------
unsigned int __fastcall nna_fill_conv(_DWORD *a1, int a2, int a3, int a4, signed int a5, int a6, int a7, unsigned int a8, int a9, int a10, int a11, int a12, int a13)
{
  _DWORD *v13; // r4
  int v14; // r9
  int v15; // r10
  int v16; // r11
  int v17; // r7
  int v18; // r0
  signed int v19; // r2
  int v20; // r2
  int v21; // r2
  int v22; // r1
  int v23; // r12
  int v24; // r7
  int v25; // r7
  unsigned int result; // r0
  unsigned int v27; // r5
  unsigned int v28; // r3
  unsigned int v29; // r7
  int v30; // [sp+8h] [bp-30h]
  int v31; // [sp+Ch] [bp-2Ch]

  v13 = a1;
  v14 = a4;
  v15 = (unsigned __int8)a13;
  v30 = a2;
  v31 = a3;
  v16 = nna_get_engine();
  v17 = nna_api_conv_get_output_w(a6, a10, a11, a12, v15, v15);
  v18 = nna_api_conv_get_output_h(a7, a10, a11, a12, v15, v15);
  v19 = a5;
  *v13 = 1;
  if ( a5 )
    v19 = 1;
  v13[54] = v19;
  v13[53] = 1;
  v20 = (unsigned __int16)a5 | (a5 << 16);
  v13[55] = v20;
  v13[56] = v20;
  v13[52] = 0;
  v13[49] = 0;
  v13[50] = 0;
  v13[1] = 1;
  v13[31] = a11;
  v13[32] = a11;
  v13[33] = a12;
  v13[34] = a12;
  v21 = v30 - *(_DWORD *)(v16 + 12);
  v13[29] = a10;
  v13[30] = a10;
  v13[2] = v21;
  v13[41] = (unsigned __int8)v14;
  v13[42] = v14 >> 8;
  v13[37] = a13;
  v13[35] = a13;
  v13[38] = a13;
  v13[36] = a13;
  v13[5] = a6;
  v13[6] = a7;
  if ( (_BYTE)v14 )
    v13[8] = a6;
  v13[7] = a8;
  if ( !(_BYTE)v14 )
    v13[8] = 8 * a6;
  v22 = a7 * v13[8];
  v23 = *(_DWORD *)(v16 + 16);
  v13[23] = v17;
  v24 = 8 * v17;
  v13[20] = v21;
  v13[24] = v18;
  v13[26] = v24;
  v25 = v24 * v18;
  result = a8;
  v13[25] = a9;
  v13[9] = v22;
  v13[11] = v31 - v23;
  v13[10] = 1;
  v27 = (a10 * a10 * a9 * a8 + 31) & 0xFFFFFFE0;
  v13[19] = 2;
  v13[27] = v25;
  v13[13] = v27;
  if ( (_BYTE)v14 )
  {
    v13[57] = (a8 * (a6 + 2 * a13) + 31) >> 5;
  }
  else
  {
    v28 = ((a8 + 7) >> 3) & 3;
    v29 = a6 * ((a8 + 7) >> 5);
    if ( v28 )
    {
      result = ((1 << (3 - v28)) - 1 + a6) / (unsigned int)(1 << (3 - v28)) + v29;
      v13[57] = result;
    }
    else
    {
      v13[57] = v29;
    }
  }
  v13[48] = (unsigned int)(v13[57] * a7 + 511) >> 9;
  v13[47] = (v27 + 0x3FFF) >> 14;
  return result;
}

//----- (00000704) --------------------------------------------------------
unsigned int __fastcall nna_fill_conv_sub(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17)
{
  _DWORD *v17; // r4
  int v18; // r2
  int v19; // r0
  unsigned int v20; // r1
  unsigned int v21; // r0
  int v22; // r3
  unsigned int result; // r0

  v17 = a1;
  a1[5] = a4;
  a1[20] = a3;
  v18 = a1[29] - 1;
  a1[35] = a6;
  v19 = a1[31];
  v17[36] = a8;
  v17[2] = a2;
  v17[6] = a5;
  v20 = v17[33];
  v17[37] = a7;
  v17[38] = a9;
  v21 = (a4 - 1 + a8 + a6 - v19 * v18) / v20;
  v22 = v17[30];
  v17[23] = v21 + 1;
  result = (unsigned int)(a5 - 1 + a9 + a7 - v17[32] * (v22 - 1)) / v17[34] + 1;
  v17[24] = result;
  v17[46] = a10;
  v17[49] = a13;
  v17[50] = a14;
  v17[51] = a15;
  v17[52] = a16;
  v17[53] = a17;
  return result;
}

//----- (000007D4) --------------------------------------------------------
signed int __fastcall nna_fill_sdp(_DWORD *a1, int a2, int a3, int a4, signed int a5, int a6, unsigned __int8 a7, signed int a8, int a9, int a10, int a11, int a12, int a13, signed int a14, int a15, int a16, int a17)
{
  signed int v17; // lr
  int v18; // r7
  _DWORD *v19; // r4
  int v20; // r6
  int v21; // r11
  int v22; // r0
  signed int v23; // r3
  signed int v24; // r2
  int v25; // r2
  int v26; // r12
  int v27; // r1
  int v28; // r7
  int v29; // r0
  int v30; // r6
  int v31; // r2
  signed int v32; // r1
  signed int v33; // r2
  unsigned int v34; // r5
  signed int result; // r0
  int v36; // r2
  int v37; // [sp+0h] [bp-38h]
  int v38; // [sp+4h] [bp-34h]
  int v39; // [sp+8h] [bp-30h]
  int v40; // [sp+Ch] [bp-2Ch]
  char v41[40]; // [sp+10h] [bp-28h]

  v18 = a3;
  v19 = a1;
  v20 = a2;
  v21 = a4;
  v22 = nna_get_engine();
  v23 = 1;
  *v19 = 1;
  if ( v18 == -1 )
    v24 = 2;
  else
    v24 = 1;
  v19[1] = v24;
  v25 = *(_DWORD *)(v22 + 12);
  if ( v20 != -1 )
    v17 = 1;
  v19[7] = a13;
  if ( v20 == -1 )
    v17 = 2;
  v26 = 8 * a11 * a12;
  v19[8] = 8 * a11;
  v19[44] = 8 * a11;
  v27 = *(_DWORD *)(v22 + 20);
  v28 = v18 - v25;
  v29 = v21 - v27;
  v19[11] = v21 - v27;
  if ( v21 != -1 )
    v29 = 1;
  v30 = v20 - v25;
  if ( v21 == -1 )
    v29 = 2;
  v19[10] = v29;
  v31 = a6 - v25;
  v19[20] = a5 - v27;
  v32 = a5;
  v19[29] = v31;
  if ( a5 != -1 )
    v32 = 1;
  v19[37] = v17;
  if ( a5 == -1 )
    v32 = 2;
  v19[2] = v28;
  if ( a6 != -1 )
    v31 = 1;
  v19[5] = a11;
  if ( a6 == -1 )
    v31 = 2;
  v19[28] = v31;
  v33 = a14;
  v19[6] = a12;
  v19[9] = v26;
  if ( a14 <= 0 )
    v23 = 0;
  else
    v19[53] = 1;
  if ( a14 <= 0 )
    v19[53] = v23;
  else
    v33 = a8;
  if ( a14 > 0 )
  {
    v33 >>= 8;
    v19[61] = v23;
    v19[57] = v23;
  }
  v19[38] = v30;
  v19[41] = a11;
  v19[42] = a12;
  v19[43] = a13;
  v19[45] = v26;
  v19[19] = v32;
  if ( a14 > 0 )
  {
    v19[59] = v33;
    v33 = 2;
    v19[63] = v23;
  }
  if ( a14 > 0 )
    v19[54] = v33;
  if ( !a15 )
  {
    v19[72] = 0;
    v19[77] = 0;
  }
  if ( (unsigned int)(a15 - 1) <= 1 )
  {
    v19[72] = 1;
    v19[73] = 2;
    if ( a15 == 1 )
    {
      v19[77] = 1;
    }
    else
    {
      v19[77] = 3;
      v19[82] = a16 >> 8;
      v19[79] = (unsigned __int8)a16;
    }
  }
  v34 = a15 - 3;
  if ( (unsigned int)(a15 - 3) > 1 )
  {
    v19[91] = 0;
  }
  else
  {
    v19[48] = v34;
    v19[91] = 1;
  }
  if ( v34 <= 1 )
    v19[96] = 2;
  result = 255;
  v37 = 255;
  v38 = 2;
  v39 = 0;
  v40 = 255;
  if ( a6 != -1 )
  {
    v19[95] = 2;
    v19[91] = 1;
    v19[97] = a10 >> 8;
    v19[99] = 1;
    v19[101] = 1;
    v36 = *(_DWORD *)&v41[4 * a17 - 16];
    v19[102] = 1;
    v19[103] = 1;
    v19[92] = v36;
    v19[104] = 0;
    v19[105] = 0;
  }
  v19[110] = 1;
  v19[111] = 1;
  v19[112] = a7;
  v19[113] = 0;
  return result;
}
// 7D4: using guessed type char var_28[40];

//----- (00000A0C) --------------------------------------------------------
_DWORD *__fastcall nna_fill_sdp_sub(_DWORD *result, int a2, int a3, int a4, int a5)
{
  result[2] = a2;
  result[5] = a4;
  result[6] = a5;
  result[38] = a3;
  result[41] = a4;
  result[42] = a5;
  return result;
}

//----- (00000A38) --------------------------------------------------------
int __fastcall nna_fill_pdp(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10)
{
  _DWORD *v10; // r4
  int v11; // r7
  int v12; // r8
  int v13; // r0
  int v14; // r5
  int v15; // r6
  int v16; // r0
  int v17; // r5
  signed int v18; // r3
  int v19; // r2
  int v20; // r6
  int v21; // r6
  int v22; // r0
  int v23; // r3
  int v24; // r6
  unsigned int v25; // r8
  unsigned int v26; // r1
  unsigned int v27; // r0
  int result; // r0
  int v29; // r1
  int v30; // t0
  int v31; // [sp+8h] [bp-30h]
  int v32; // [sp+Ch] [bp-2Ch]

  v10 = a1;
  v11 = a4;
  v12 = a3;
  v32 = a2;
  v13 = nna_get_engine();
  v10[26] = a10;
  v10[24] = a10;
  v10[25] = a10;
  v10[27] = a10;
  v14 = (unsigned __int8)a10;
  v31 = v13;
  v10[28] = 0;
  *v10 = 1;
  v10[19] = 1;
  v10[20] = a8;
  v10[21] = a8;
  v10[22] = a9;
  v10[23] = a9;
  v15 = nna_api_pool_get_output_w(v11, a8, a9, (unsigned __int8)v14, (unsigned __int8)v14);
  v16 = nna_api_pool_get_output_h(a5, a8, a9, v14, v14);
  v17 = v10[27];
  if ( v12 == -1 )
    v18 = 2;
  else
    v18 = 1;
  v10[1] = v18;
  v19 = *(_DWORD *)(v31 + 12);
  v10[14] = v15;
  v10[6] = a5;
  v20 = 8 * v15;
  v10[7] = a6;
  v10[8] = 8 * v11;
  v10[15] = v16;
  v10[9] = 8 * v11 * a5;
  v10[17] = v20;
  v10[11] = v32 - v19;
  v21 = v20 * v16;
  v22 = v10[26];
  v10[16] = a6;
  v23 = v10[21];
  v10[2] = v12 - v19;
  v10[5] = v11;
  v10[18] = v21;
  v10[10] = 1;
  v24 = v10[25];
  v25 = (unsigned int)(v17 + v22 + a5 - v23) % v10[23];
  v26 = v10[22];
  v27 = v24 + v10[24] + v11 - v10[20];
  v30 = v27 / v26;
  v29 = v27 % v26;
  result = v30;
  v10[25] = v29 + v24;
  v10[27] = v17 + v25;
  return result;
}

//----- (00000BB0) --------------------------------------------------------
int __fastcall nna_fill_pdp_sub(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9)
{
  int v9; // r9
  _DWORD *v10; // r4
  int v11; // r2
  int v12; // r3
  unsigned int v13; // r8
  int v14; // r11
  unsigned int v15; // r7
  int v16; // r10
  unsigned int v17; // r0
  int result; // r0
  int v19; // r1

  v9 = a4;
  v10 = a1;
  v11 = a1[2] + a3;
  a1[6] = a5;
  v12 = a1[11];
  v13 = a1[22];
  v14 = a1[20];
  a1[2] = v11;
  a1[11] = v12 + a2;
  a1[5] = v9;
  a1[14] = (v9 + a6 + a8 + v13 - 1 - v14) / v13 + 1;
  v15 = a1[23];
  v16 = a1[21];
  a1[15] = (a5 + a9 + a7 - 1 + v15 - v16) / a1[23] + 1;
  a1[26] = a7;
  a1[24] = a6;
  a1[25] = (a6 + a8 + v9 - v14) % v13 + a8;
  v17 = a7 + a9 + a5 - v16;
  v19 = v17 % v15;
  result = v17 / v15;
  v10[27] = v19 + a9;
  return result;
}

//----- (00000CB0) --------------------------------------------------------
int __fastcall nna_api_conv_act_pool(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23)
{
  int v23; // ST4C_4
  int v24; // ST44_4
  int v25; // ST48_4
  int v26; // r5
  int v27; // ST40_4
  int v28; // r0
  _DWORD *v29; // r4
  int v30; // r10
  int v31; // r5

  v23 = a4;
  v24 = a2;
  v25 = a3;
  v26 = (unsigned __int8)a16;
  v27 = a1;
  v28 = nna_get_engine();
  v29 = *(_DWORD **)(v28 + 32 * *(_DWORD *)(v28 + 4) + 56);
  memset(v29, 0, 0x47Cu);
  printf("\n# %s:memset", "nna_api_conv_act_pool");
  v30 = nna_api_conv_get_output_w(a9, a13, a14, a15, v26, v26);
  v31 = nna_api_conv_get_output_h(a10, a13, a14, a15, v26, v26);
  nna_fill_conv(v29 + 22, v24, v25, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16);
  nna_fill_sdp(v29 + 80, -1, -1, v23, -1, -1, a5, a6, 0, 0, v30, v31, a12, a17, a18, a19, 0);
  nna_fill_pdp(v29 + 194, v27, -1, v30, v31, a12, a20, a21, a22, a23);
  return nna_play(v29);
}
// 1E28: using guessed type int __fastcall nna_play(_DWORD);

//----- (00000EC4) --------------------------------------------------------
int __fastcall nna_api_conv_act_pool_big(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23)
{
  int v23; // r9
  int v24; // r0
  int *v25; // r6
  int *v26; // r3
  char *v27; // r2
  int v28; // r0
  int v29; // r1
  _DWORD *v30; // r12
  int v31; // r0
  char *v32; // r2
  int *v33; // r3
  int v34; // r0
  int v35; // r1
  int *v36; // r12
  unsigned int v37; // r10
  unsigned int v38; // r11
  int v39; // r3
  unsigned int v40; // r5
  int v41; // r4
  int v42; // r4
  int v43; // r4
  int v44; // r1
  int v45; // r3
  unsigned int v46; // r0
  unsigned int v47; // r7
  int result; // r0
  unsigned int v49; // r4
  int v50; // r8
  int v51; // r7
  int v52; // r3
  int v53; // r2
  int v54; // r9
  signed int v55; // r3
  int v56; // [sp+38h] [bp-C8h]
  int v57; // [sp+3Ch] [bp-C4h]
  unsigned int v58; // [sp+40h] [bp-C0h]
  unsigned int v59; // [sp+44h] [bp-BCh]
  int v60; // [sp+48h] [bp-B8h]
  int v61; // [sp+4Ch] [bp-B4h]
  int v62; // [sp+50h] [bp-B0h]
  int v63; // [sp+54h] [bp-ACh]
  int v64; // [sp+5Ch] [bp-A4h]
  unsigned int v65; // [sp+64h] [bp-9Ch]
  int v66; // [sp+68h] [bp-98h]
  unsigned int v67; // [sp+6Ch] [bp-94h]
  int v68; // [sp+74h] [bp-8Ch]
  int v69; // [sp+78h] [bp-88h]
  int v70; // [sp+80h] [bp-80h]
  int v71; // [sp+84h] [bp-7Ch]
  int v72; // [sp+88h] [bp-78h]
  int v73; // [sp+8Ch] [bp-74h]
  char v74; // [sp+90h] [bp-70h]
  char v75; // [sp+B4h] [bp-4Ch]
  unsigned int v76; // [sp+C4h] [bp-3Ch]
  unsigned int v77; // [sp+C8h] [bp-38h]

  v23 = a3;
  v63 = a2;
  v67 = a1;
  v24 = nna_get_engine();
  v25 = *(int **)(v24 + 32 * *(_DWORD *)(v24 + 4) + 56);
  memset(v25, 0, 0x47Cu);
  nna_fill_conv(v25 + 22, v63, v23, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16);
  v26 = v25 + 23;
  v27 = &v74;
  do
  {
    v28 = *v26;
    v26 += 2;
    v29 = *(v26 - 1);
    *(_DWORD *)v27 = v28;
    *((_DWORD *)v27 + 1) = v29;
    v30 = v27 + 8;
    v27 += 8;
  }
  while ( v26 != v25 + 31 );
  v31 = *v26;
  v32 = &v75;
  v33 = v25 + 41;
  *v30 = v31;
  do
  {
    v34 = *v33;
    v33 += 2;
    v35 = *(v33 - 1);
    *(_DWORD *)v32 = v34;
    *((_DWORD *)v32 + 1) = v35;
    v36 = (int *)(v32 + 8);
    v32 += 8;
  }
  while ( v33 != v25 + 49 );
  *v36 = *v33;
  v37 = v25[70];
  v38 = v77;
  v61 = a14 * (a13 - 1) + 1 - a15;
  v39 = a11 * a13 * a13;
  v40 = v76;
  v41 = v39 * a12 + 31;
  if ( v41 < 0 )
    v41 = v39 * a12 + 62;
  v57 = (signed int)((v41 & 0xFFFFFFE0) + 0x3FFF) / 0x4000;
  if ( v37 + v57 <= 0x10 )
    goto LABEL_37;
  v42 = 16 * v39 + 31;
  if ( v42 < 0 )
    v42 = 16 * v39 + 62;
  v43 = (signed int)((v42 & 0xFFFFFFE0) + 0x3FFF) / 0x4000;
  if ( v37 + v43 <= 0x10 )
    goto LABEL_37;
  v44 = 8 * v39;
  v45 = 8 * v39 + 31;
  if ( v45 < 0 )
    v45 = v44 + 62;
  if ( v37 + (signed int)((v45 & 0xFFFFFFE0) + 0x3FFF) / 0x4000 <= 0x10 )
  {
    v57 = 16 - v37;
LABEL_37:
    result = 1;
    v47 = 1;
    goto LABEL_21;
  }
  v40 = 0 / v37;
  if ( 0 / v37 >= a9 )
  {
    v40 = 0;
    v38 = 0 / v37 / a9 - v61;
  }
  else
  {
    v38 = 1;
  }
  v37 = 16 - v43;
  v46 = nna_api_pool_max_output_w(a21, a22, a23, a23, a23, a23);
  if ( v46 < v40 )
    v40 = v46;
  v47 = (v40 - 1) / v40;
  result = (v38 - 1) / v38;
  v57 = v43;
LABEL_21:
  v49 = 0;
  v59 = v47 - 1;
  v50 = 0;
  v60 = 0;
  v65 = result - 1;
  v51 = 0;
  v56 = 0;
  while ( v59 >= v49 )
  {
    v73 = (unsigned __int8)a16;
    v72 = (unsigned __int8)a16;
    v71 = (unsigned __int8)a16;
    v70 = (unsigned __int8)a16;
    result = nna_api_set_split_pad((int)&v70, &v71, 0, v59, v49);
    v62 = v67 + 8 * v60;
    v58 = 0;
    while ( v65 >= v58 )
    {
      nna_api_set_split_pad((int)&v72, &v73, 0, v65, v58);
      if ( !v49 )
      {
        v50 = 0;
        v51 = 0;
      }
      if ( a7 )
      {
        v52 = v56;
        v53 = v63;
      }
      else
      {
        v52 = v63;
        v53 = v56;
      }
      if ( a7 )
        v54 = v52 + v53;
      else
        v54 = v52 + 8 * v53;
      v68 = v50 + v62;
      v69 = v25[30] * v64;
      v50 += v25[48] * v38;
      v66 = nna_api_conv_get_input_w(v40, a13, a14, a15, v70, v71);
      v64 = nna_api_conv_get_input_w(v38, a13, a14, a15, v72, v73);
      v56 += v66 - v61;
      v60 += v40;
      if ( v49 )
        v55 = -1;
      else
        v55 = ~v61;
      nna_fill_conv_sub(v25 + 22, v54 + v51, v68, v66, v64, v70, v72, v71, v73, 0, v57, v37, 0, 0, 0, 0, v55);
      nna_fill_sdp_sub(v25 + 80, v67 + v50, v67 + v50, v40, v38);
      v51 += v69;
      nna_api_conv_get_input_w(0, a13, a14, a15, v70, v71);
      v25[194] = 0;
      result = dump_nna_op(v25);
      ++v58;
      v62 += 8 * v40;
    }
    ++v49;
  }
  return result;
}
// 1E2C: using guessed type int __fastcall dump_nna_op(_DWORD);

//----- (000013A4) --------------------------------------------------------
int __fastcall nna_api_conv_act(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19)
{
  int v19; // ST4C_4
  int v20; // r5
  int v21; // ST44_4
  int v22; // ST48_4
  int v23; // ST40_4
  int v24; // r0
  _DWORD *v25; // r4
  int v26; // ST3C_4
  int v27; // r5

  v19 = a4;
  v20 = (unsigned __int8)a16;
  v21 = a2;
  v22 = a3;
  v23 = a1;
  v24 = nna_get_engine();
  v25 = *(_DWORD **)(v24 + 32 * *(_DWORD *)(v24 + 4) + 56);
  memset(v25, 0, 0x47Cu);
  v26 = nna_api_conv_get_output_w(a9, a13, a14, a15, v20, v20);
  v27 = nna_api_conv_get_output_h(a10, a13, a14, a15, v20, v20);
  nna_fill_conv(v25 + 22, v21, v22, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16);
  nna_fill_sdp(v25 + 80, v23, -1, v19, -1, -1, a5, a6, 0, 0, v26, v27, a12, a17, a18, a19, 0);
  v25[194] = 0;
  return nna_play(v25);
}
// 1E28: using guessed type int __fastcall nna_play(_DWORD);

//----- (00001540) --------------------------------------------------------
int __fastcall nna_api_conv_act_big(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19)
{
  int v19; // r8
  int v20; // r0
  int *v21; // r5
  int *v22; // r3
  char *v23; // r2
  int v24; // r0
  int v25; // r1
  _DWORD *v26; // r12
  int v27; // r0
  char *v28; // r2
  int *v29; // r3
  int v30; // r0
  int v31; // r1
  int *v32; // r12
  unsigned int v33; // r10
  unsigned int v34; // r11
  int v35; // r3
  unsigned int v36; // r6
  int v37; // r4
  int v38; // r4
  int v39; // r4
  int v40; // r1
  int v41; // r3
  unsigned int v42; // r7
  int result; // r0
  unsigned int v44; // r4
  int v45; // r8
  int v46; // r7
  int v47; // r3
  int v48; // r2
  int v49; // r9
  signed int v50; // r3
  int v51; // [sp+38h] [bp-C8h]
  int v52; // [sp+3Ch] [bp-C4h]
  unsigned int v53; // [sp+40h] [bp-C0h]
  unsigned int v54; // [sp+44h] [bp-BCh]
  int v55; // [sp+48h] [bp-B8h]
  int v56; // [sp+4Ch] [bp-B4h]
  int v57; // [sp+50h] [bp-B0h]
  int v58; // [sp+54h] [bp-ACh]
  int v59; // [sp+5Ch] [bp-A4h]
  unsigned int v60; // [sp+64h] [bp-9Ch]
  int v61; // [sp+68h] [bp-98h]
  unsigned int v62; // [sp+6Ch] [bp-94h]
  int v63; // [sp+74h] [bp-8Ch]
  int v64; // [sp+78h] [bp-88h]
  int v65; // [sp+80h] [bp-80h]
  int v66; // [sp+84h] [bp-7Ch]
  int v67; // [sp+88h] [bp-78h]
  int v68; // [sp+8Ch] [bp-74h]
  char v69; // [sp+90h] [bp-70h]
  char v70; // [sp+B4h] [bp-4Ch]
  unsigned int v71; // [sp+C4h] [bp-3Ch]
  unsigned int v72; // [sp+C8h] [bp-38h]

  v19 = a3;
  v58 = a2;
  v62 = a1;
  v20 = nna_get_engine();
  v21 = *(int **)(v20 + 32 * *(_DWORD *)(v20 + 4) + 56);
  memset(v21, 0, 0x47Cu);
  nna_fill_conv(v21 + 22, v58, v19, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16);
  v22 = v21 + 23;
  v23 = &v69;
  do
  {
    v24 = *v22;
    v22 += 2;
    v25 = *(v22 - 1);
    *(_DWORD *)v23 = v24;
    *((_DWORD *)v23 + 1) = v25;
    v26 = v23 + 8;
    v23 += 8;
  }
  while ( v22 != v21 + 31 );
  v27 = *v22;
  v28 = &v70;
  v29 = v21 + 41;
  *v26 = v27;
  do
  {
    v30 = *v29;
    v29 += 2;
    v31 = *(v29 - 1);
    *(_DWORD *)v28 = v30;
    *((_DWORD *)v28 + 1) = v31;
    v32 = (int *)(v28 + 8);
    v28 += 8;
  }
  while ( v29 != v21 + 49 );
  *v32 = *v29;
  v33 = v21[70];
  v34 = v72;
  v56 = a14 * (a13 - 1) + 1 - a15;
  v35 = a11 * a13 * a13;
  v36 = v71;
  v37 = v35 * a12 + 31;
  if ( v37 < 0 )
    v37 = v35 * a12 + 62;
  v52 = (signed int)((v37 & 0xFFFFFFE0) + 0x3FFF) / 0x4000;
  if ( v33 + v52 > 0x10 )
  {
    v38 = 16 * v35 + 31;
    if ( v38 < 0 )
      v38 = 16 * v35 + 62;
    v39 = (signed int)((v38 & 0xFFFFFFE0) + 0x3FFF) / 0x4000;
    if ( v33 + v39 > 0x10 )
    {
      v40 = 8 * v35;
      v41 = 8 * v35 + 31;
      if ( v41 < 0 )
        v41 = v40 + 62;
      if ( v33 + (signed int)((v41 & 0xFFFFFFE0) + 0x3FFF) / 0x4000 > 0x10 )
      {
        v36 = 0 / v33;
        if ( 0 / v33 >= a9 )
        {
          v36 = 0;
          v34 = 0 / v33 / a9 - v56;
        }
        else
        {
          v34 = 1;
        }
        v33 = 16 - v39;
        v42 = (v36 - 1) / v36;
        result = (v34 - 1) / v34;
        v52 = v39;
        goto LABEL_19;
      }
      v52 = 16 - v33;
    }
  }
  result = 1;
  v42 = 1;
LABEL_19:
  v44 = 0;
  v54 = v42 - 1;
  v45 = 0;
  v55 = 0;
  v60 = result - 1;
  v46 = 0;
  v51 = 0;
  while ( v54 >= v44 )
  {
    v68 = (unsigned __int8)a16;
    v67 = (unsigned __int8)a16;
    v66 = (unsigned __int8)a16;
    v65 = (unsigned __int8)a16;
    result = nna_api_set_split_pad((int)&v65, &v66, 0, v54, v44);
    v57 = v62 + 8 * v55;
    v53 = 0;
    while ( v60 >= v53 )
    {
      nna_api_set_split_pad((int)&v67, &v68, 0, v60, v53);
      if ( !v44 )
      {
        v45 = 0;
        v46 = 0;
      }
      if ( a7 )
      {
        v47 = v51;
        v48 = v58;
      }
      else
      {
        v47 = v58;
        v48 = v51;
      }
      if ( a7 )
        v49 = v47 + v48;
      else
        v49 = v47 + 8 * v48;
      v63 = v45 + v57;
      v64 = v21[30] * v59;
      v45 += v21[48] * v34;
      v61 = nna_api_conv_get_input_w(v36, a13, a14, a15, v65, v66);
      v59 = nna_api_conv_get_input_w(v34, a13, a14, a15, v67, v68);
      v51 += v61 - v56;
      v55 += v36;
      if ( v44 )
        v50 = -1;
      else
        v50 = ~v56;
      nna_fill_conv_sub(v21 + 22, v49 + v46, v63, v61, v59, v65, v67, v66, v68, 0, v52, v33, 0, 0, 0, 0, v50);
      nna_fill_sdp_sub(v21 + 80, v62 + v45, v62 + v45, v36, v34);
      v46 += v64;
      nna_api_conv_get_input_w(0, a13, a14, a15, v65, v66);
      v21[194] = 0;
      result = dump_nna_op(v21);
      ++v53;
      v57 += 8 * v36;
    }
    ++v44;
  }
  return result;
}
// 1E2C: using guessed type int __fastcall dump_nna_op(_DWORD);

//----- (000019F8) --------------------------------------------------------
int __fastcall nna_api_conv_act_eltwise(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23)
{
  int v23; // ST54_4
  int v24; // r5
  int v25; // ST4C_4
  signed int v26; // r4
  int v27; // r0
  int v28; // r6
  int v29; // r5
  unsigned int v30; // r3
  int v32; // [sp+44h] [bp-64h]
  int v33; // [sp+48h] [bp-60h]
  int v34; // [sp+50h] [bp-58h]

  v23 = a4;
  v24 = (unsigned __int8)a17;
  v25 = a2;
  v34 = a3;
  v33 = a1;
  v26 = a21;
  v27 = nna_get_engine();
  v28 = *(_DWORD *)(v27 + 32 * *(_DWORD *)(v27 + 4) + 56);
  v32 = nna_api_conv_get_output_w(a10, a14, a15, a16, v24, v24);
  v29 = nna_api_conv_get_output_h(a11, a14, a15, a16, v24, v24);
  nna_fill_conv((_DWORD *)(v28 + 88), v25, v23, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17);
  if ( a21 == 1 )
    v30 = (unsigned int)a23 >> 31;
  else
    v30 = 0;
  if ( v30 )
    v26 = 3;
  nna_fill_sdp((_DWORD *)(v28 + 320), v33, -1, a5, -1, v34, a6, a7, 0, 0, v32, v29, a13, a18, a19, a20, v26);
  return nna_play(v28);
}
// 1E28: using guessed type int __fastcall nna_play(_DWORD);

//----- (00001BBC) --------------------------------------------------------
int __fastcall nna_api_inner_product(unsigned int a1, unsigned int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11)
{
  int v11; // r9
  unsigned int v12; // ST40_4
  int v13; // r10
  int v14; // r0
  int v15; // r5
  int v16; // r3
  int v18; // [sp+3Ch] [bp-3Ch]

  v11 = a2;
  v12 = a4;
  v13 = a3;
  v18 = a1;
  v14 = nna_get_engine();
  v15 = *(_DWORD *)(v14 + 32 * *(_DWORD *)(v14 + 4) + 56);
  nna_fill_conv((_DWORD *)(v15 + 88), v11, v13, 0, 0, a7, a8, a9, a10, a7, 1, 1, 0);
  v16 = v12;
  if ( a11 <= 0 )
    v16 = -1;
  nna_fill_sdp((_DWORD *)(v15 + 320), v18, -1, v16, -1, -1, a5, a6, 0, 0, a7, a8, a10, 0, 0, 0, 0);
  return nna_play(v15);
}
// 1E28: using guessed type int __fastcall nna_play(_DWORD);

//----- (00001CB4) --------------------------------------------------------
int __fastcall nna_api_lsc(unsigned int a1, unsigned int a2, unsigned int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13)
{
  int v13; // r6
  int v14; // ST28_4
  int v15; // r7
  int v16; // r5
  int v17; // r0
  int v18; // r4

  v13 = a2;
  v14 = a4;
  v15 = a3;
  v16 = a1;
  v17 = nna_get_engine();
  v18 = *(_DWORD *)(v17 + 32 * *(_DWORD *)(v17 + 4) + 56);
  nna_fill_lsc((_DWORD *)(v18 + 996), v16, v13, v15, v14, a5, a6, a7, a8, a9, a10, a11, a12, a13);
  return nna_play(v18);
}
// 1E28: using guessed type int __fastcall nna_play(_DWORD);

//----- (00001D7C) --------------------------------------------------------
int __fastcall nna_api_nms(unsigned int a1, unsigned int a2, int a3, int a4, int a5)
{
  int v5; // r6
  int v6; // r7
  int v7; // r8
  int v8; // r5
  int v9; // r0
  int v10; // r4

  v5 = a2;
  v6 = a3;
  v7 = a4;
  v8 = a1;
  v9 = nna_get_engine();
  v10 = *(_DWORD *)(v9 + 32 * *(_DWORD *)(v9 + 4) + 56);
  nna_fill_nms((_DWORD *)(v10 + 904), v8, v5, v6, v7, a5);
  return nna_play(v10);
}
// 1E28: using guessed type int __fastcall nna_play(_DWORD);

// ALL OK, 32 function(s) have been successfully decompiled
