/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall nna_reg_open(unsigned int a1, __off_t a2);
int __fastcall nna_reg_close(int a1, int a2, int a3);
int __fastcall nna_reg_read(unsigned int a1);
int __fastcall nna_reg_wait_done(int a1, int a2);
// int open(const char *file, int oflag, ...);
// int printf(const char *format, ...);
// void *mmap(void *addr, size_t len, int prot, int flags, int fd, __off_t offset);
// int munmap(void *addr, size_t len);
// int *_errno_location(void);
// char *strerror(int errnum);
// int fprintf(FILE *stream, const char *format, ...);
// void exit(int status);
// int close(int fd);
// int usleep(__useconds_t useconds);

//-------------------------------------------------------------------------
// Data declarations

int nna_reg_base; // weak
int dev_fd; // weak
// extern struct _IO_FILE *stderr;


//----- (00000004) --------------------------------------------------------
int __fastcall nna_reg_open(unsigned int a1, __off_t a2)
{
  unsigned int v2; // r4
  int fd; // r0
  __off_t v5; // [sp+4h] [bp-14h]

  v5 = a2;
  v2 = a1;
  fd = open("/dev/mem", 2050);
  dev_fd = fd;
  if ( fd < 0 )
    return printf("open(/dev/mem) failed.");
  nna_reg_base = (int)mmap(0, 0x20000u, 3, 1, fd, v5);
  return printf("\n nna_reg_open: %08X %08X ", v2, nna_reg_base);
}
// 218: using guessed type int nna_reg_base;
// 21C: using guessed type int dev_fd;

//----- (000000B0) --------------------------------------------------------
int __fastcall nna_reg_close(int a1, int a2, int a3)
{
  FILE *stream; // ST0C_4
  int v4; // r4
  int *v5; // r0
  char *v6; // r0
  int result; // r0
  int v8; // [sp+8h] [bp-10h]

  v8 = a3;
  if ( munmap((void *)nna_reg_base, 0x20000u) == -1 )
  {
    stream = (FILE *)stderr;
    v4 = *_errno_location();
    v5 = _errno_location();
    v6 = strerror(*v5);
    fprintf(stream, "Error at line %d, file %s (%d) [%s]\n", 54, "nna_hw.cpp", v4, v6, v8);
    exit(1);
  }
  result = dev_fd;
  if ( dev_fd )
    result = close(dev_fd);
  return result;
}
// 218: using guessed type int nna_reg_base;
// 21C: using guessed type int dev_fd;

//----- (0000016C) --------------------------------------------------------
int __fastcall nna_reg_read(unsigned int a1)
{
  return *(unsigned __int8 *)(nna_reg_base + a1);
}
// 218: using guessed type int nna_reg_base;

//----- (00000190) --------------------------------------------------------
int __fastcall nna_reg_wait_done(int a1, int a2)
{
  int v2; // r6
  int v3; // r4
  int v4; // r7
  int v5; // r5

  v2 = a1;
  v3 = 0;
  v4 = a2;
  nna_reg_read(0x100Cu);
  while ( 1 )
  {
    ++v3;
    v5 = nna_reg_read(0x100Cu);
    if ( (v2 & v5) == v4 )
      break;
    usleep(0x28u);
    if ( v3 == 899 )
    {
      printf("\n# NNA wait timeout status:%08X mask:%08X loop:%d us:%d", v5, v2, v4, 899, 35960);
      return 0;
    }
  }
  return 0;
}

// ALL OK, 4 function(s) have been successfully decompiled
