/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int nna_net_fd1_get_scre_fixpoint(void);
int nna_net_fd1_get_location_fixpoint(void);
unsigned int nna_net_fd1_get_score_size(void);
unsigned int nna_net_fd1_get_location_size(void);
int nna_net_fd1_get_score_w(void);
int nna_net_fd1_get_score_h(void);
int nna_net_fd1_get_score_c(void);
int __fastcall nna_net_fd1_post(char *a1, char *a2);
int __fastcall nna_net_fd2_get_quant(int *a1, int *a2);
int nna_net_fd2_get_scre_fixpoint(void);
int nna_net_fd2_get_location_fixpoint(void);
int __fastcall nna_net_fd2_post(char *a1, char *a2);
int __fastcall nna_net_fd2_get_quant(int *a1, int *a2, int *a3);
int nna_net_fd3_get_scre_fixpoint(void);
int nna_net_fd3_get_box_fixpoint(void);
int nna_net_fd3_get_keypoint_fixpoint(void);
int __fastcall nna_net_fd3_post(char *a1, char *a2, char *a3);
int __fastcall nna_net_fd1_init(int a1, int a2, int a3);
int __fastcall nna_net_fd1(unsigned __int8 *a1, int a2, int a3, int a4);
int __fastcall nna_net_fd2(unsigned __int8 *a1);
int __fastcall nna_net_fd3(unsigned __int8 *a1);
int nna_net_fd1_case(void);
int nna_net_fd2_case(void);
int nna_net_fd3_case(void);
int __fastcall nna_net_fd1_run(unsigned int a1, unsigned int a2, int a3, int a4, unsigned int a5);
int __fastcall nna_net_fd2_run(unsigned int a1, unsigned int a2, int a3, unsigned int a4);
int __fastcall nna_net_fd3_run(unsigned int a1, unsigned int a2, int a3, unsigned int a4);
int GLOBAL__sub_I_nna_fdnet_cpp();
// int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD); weak
// int __cdecl xramcpy(_DWORD, _DWORD, _DWORD); weak
// int __fastcall nna_net_init(_DWORD); weak
// int __fastcall nna_net_load_hyper(_DWORD); weak
// int __fastcall nna_net_forward(_DWORD); weak
// int __fastcall nna_load_ram(_DWORD, _DWORD); weak
// int __fastcall nna_net_load_data(_DWORD); weak
// int printf(const char *format, ...);
// int __fastcall nna_net_load_quant(_DWORD); weak
// int __fastcall nna_net_dump(_DWORD); weak
// _DWORD std::ios_base::Init::Init(std::ios_base::Init *__hidden this); idb
// int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD); weak
// _DWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_8; // weak
_UNKNOWN loc_4C; // weak
_UNKNOWN loc_50; // weak
_UNKNOWN loc_54; // weak
void *off_25C = (void *)0x7FFFFF50; // weak
_UNKNOWN loc_470; // weak
_UNKNOWN loc_478; // weak
_UNKNOWN loc_47C; // weak
int *off_480 = &unk_A818; // weak
char **off_484 = &loc_C; // weak
_UNKNOWN loc_58C; // weak
_UNKNOWN loc_594; // weak
_UNKNOWN loc_598; // weak
_UNKNOWN loc_59C; // weak
_UNKNOWN loc_5A0; // weak
_UNKNOWN loc_6A8; // weak
_UNKNOWN loc_6B0; // weak
_UNKNOWN loc_6B4; // weak
_UNKNOWN loc_6B8; // weak
_UNKNOWN loc_6BC; // weak
_UNKNOWN loc_7C4; // weak
_UNKNOWN loc_7CC; // weak
void *off_8E0 = (void *)0x7FFFFF9C; // weak
_UNKNOWN std::__ioinit; // weak
char fdnet1_info[7] = "fdnet1"; // weak
int dword_ABAC = 1610612736; // weak  //0x60000000
int *off_ABB4 = &fdnet1_io_data; // weak
void *off_ABBC = &fdnet1_layer; // weak
char fdnet2_info[7] = "fdnet2"; // weak
int dword_ABE0 = 1610612736; // weak
int *off_ABE8 = &fdnet2_io_data; // weak
char fdnet3_info[7] = "fdnet3"; // weak
int dword_AC14 = 1610612736; // weak
int *off_AC1C = &fdnet3_io_data; // weak
// extern _UNKNOWN _dso_handle; weak


//----- (00000004) --------------------------------------------------------
int nna_net_fd1_get_scre_fixpoint(void)
{
  return nna_net_get_quant(fdnet1_info, 0, 4);
}
// AC44: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (00000044) --------------------------------------------------------
int nna_net_fd1_get_location_fixpoint(void)
{
  return nna_net_get_quant(fdnet1_info, 0, 5);
}
// AC44: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (00000084) --------------------------------------------------------
unsigned int nna_net_fd1_get_score_size(void)
{
  int v0; // r0
  int v1; // r3

  v0 = *(int *)((char *)&off_484 + (_DWORD)off_ABB4);
  v1 = v0 + 7;
  if ( v0 + 7 < 0 )
    v1 = v0 + 14;
  return *(_DWORD *)((char *)&off_480 + (_DWORD)off_ABB4)
       * *(_DWORD *)((char *)&loc_47C + (_DWORD)off_ABB4)
       * (v1 & 0xFFFFFFF8);
}
// 480: using guessed type int *off_480;
// 484: using guessed type char **off_484;
// ABB4: using guessed type int *off_ABB4;

//----- (000000D0) --------------------------------------------------------
unsigned int nna_net_fd1_get_location_size(void)
{
  int v0; // r0
  int v1; // r3

  v0 = *(_DWORD *)((char *)&loc_5A0 + (_DWORD)off_ABB4);
  v1 = v0 + 7;
  if ( v0 + 7 < 0 )
    v1 = v0 + 14;
  return *(_DWORD *)((char *)&loc_59C + (_DWORD)off_ABB4)
       * *(_DWORD *)((char *)&loc_598 + (_DWORD)off_ABB4)
       * (v1 & 0xFFFFFFF8);
}
// ABB4: using guessed type int *off_ABB4;

//----- (0000011C) --------------------------------------------------------
int nna_net_fd1_get_score_w(void)
{
  return *(_DWORD *)((char *)&loc_47C + (_DWORD)off_ABB4);
}
// ABB4: using guessed type int *off_ABB4;

//----- (0000014C) --------------------------------------------------------
int nna_net_fd1_get_score_h(void)
{
  return *(int *)((char *)&off_480 + (_DWORD)off_ABB4);
}
// 480: using guessed type int *off_480;
// ABB4: using guessed type int *off_ABB4;

//----- (0000017C) --------------------------------------------------------
int nna_net_fd1_get_score_c(void)
{
  return *(int *)((char *)&off_484 + (_DWORD)off_ABB4);
}
// 484: using guessed type char **off_484;
// ABB4: using guessed type int *off_ABB4;

//----- (000001AC) --------------------------------------------------------
int __fastcall nna_net_fd1_post(char *a1, char *a2)
{
  char *v2; // r5
  int v3; // r1
  int v4; // r3
  unsigned int v5; // ST00_4
  int v6; // r1
  int v7; // r3
  unsigned int v8; // ST00_4

  v2 = a2;
  v3 = *(int *)((char *)&off_484 + (_DWORD)off_ABB4);
  v4 = v3 + 7;
  if ( v3 + 7 < 0 )
    v4 = v3 + 14;
  v5 = *(_DWORD *)((char *)&off_480 + (_DWORD)off_ABB4)
     * *(_DWORD *)((char *)&loc_47C + (_DWORD)off_ABB4)
     * (v4 & 0xFFFFFFF8);
  xramcpy(a1, (signed int)a1 >> 31, *(_DWORD *)((char *)&loc_470 + (_DWORD)off_ABB4));
  v6 = *(_DWORD *)((char *)&loc_5A0 + (_DWORD)off_ABB4);
  v7 = v6 + 7;
  if ( v6 + 7 < 0 )
    v7 = v6 + 14;
  v8 = *(_DWORD *)((char *)&loc_59C + (_DWORD)off_ABB4)
     * *(_DWORD *)((char *)&loc_598 + (_DWORD)off_ABB4)
     * (v7 & 0xFFFFFFF8);
  return xramcpy(v2, (signed int)v2 >> 31, *(_DWORD *)((char *)&loc_58C + (_DWORD)off_ABB4));
}
// 480: using guessed type int *off_480;
// 484: using guessed type char **off_484;
// ABB4: using guessed type int *off_ABB4;
// AC48: using guessed type int __cdecl xramcpy(_DWORD, _DWORD, _DWORD);

//----- (00000264) --------------------------------------------------------
int __fastcall nna_net_fd2_get_quant(int *a1, int *a2)
{
  nna_net_get_quant(fdnet2_info, 0, 5);
  return nna_net_get_quant(fdnet2_info, 0, 6);
}
// AC44: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (000002B8) --------------------------------------------------------
int nna_net_fd2_get_scre_fixpoint(void)
{
  return nna_net_get_quant(fdnet2_info, 0, 5);
}
// AC44: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (000002F8) --------------------------------------------------------
int nna_net_fd2_get_location_fixpoint(void)
{
  return nna_net_get_quant(fdnet2_info, 0, 6);
}
// AC44: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (00000338) --------------------------------------------------------
int __fastcall nna_net_fd2_post(char *a1, char *a2)
{
  char *v2; // r5
  int v3; // r1
  int v4; // r3
  unsigned int v5; // ST00_4
  int v6; // r1
  int v7; // r3
  unsigned int v8; // ST00_4

  v2 = a2;
  v3 = *(_DWORD *)((char *)&loc_5A0 + (_DWORD)off_ABE8);
  v4 = v3 + 7;
  if ( v3 + 7 < 0 )
    v4 = v3 + 14;
  v5 = *(_DWORD *)((char *)&loc_59C + (_DWORD)off_ABE8)
     * *(_DWORD *)((char *)&loc_598 + (_DWORD)off_ABE8)
     * (v4 & 0xFFFFFFF8);
  xramcpy(a1, (signed int)a1 >> 31, *(_DWORD *)((char *)&loc_58C + (_DWORD)off_ABE8));
  v6 = *(_DWORD *)((char *)&loc_6BC + (_DWORD)off_ABE8);
  v7 = v6 + 7;
  if ( v6 + 7 < 0 )
    v7 = v6 + 14;
  v8 = *(_DWORD *)((char *)&loc_6B8 + (_DWORD)off_ABE8)
     * *(_DWORD *)((char *)&loc_6B4 + (_DWORD)off_ABE8)
     * (v7 & 0xFFFFFFF8);
  return xramcpy(v2, (signed int)v2 >> 31, *(_DWORD *)((char *)&loc_6A8 + (_DWORD)off_ABE8));
}
// ABE8: using guessed type int *off_ABE8;
// AC48: using guessed type int __cdecl xramcpy(_DWORD, _DWORD, _DWORD);

//----- (000003F0) --------------------------------------------------------
int __fastcall nna_net_fd2_get_quant(int *a1, int *a2, int *a3)
{
  nna_net_get_quant(fdnet3_info, 0, 6);
  nna_net_get_quant(fdnet3_info, 0, 7);
  return nna_net_get_quant(fdnet3_info, 0, 8);
}
// AC44: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (00000454) --------------------------------------------------------
int nna_net_fd3_get_scre_fixpoint(void)
{
  return nna_net_get_quant(fdnet3_info, 0, 6);
}
// 480: using guessed type int *off_480;
// 484: using guessed type char **off_484;
// AC44: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (00000494) --------------------------------------------------------
int nna_net_fd3_get_box_fixpoint(void)
{
  return nna_net_get_quant(fdnet3_info, 0, 7);
}
// AC44: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (000004D4) --------------------------------------------------------
int nna_net_fd3_get_keypoint_fixpoint(void)
{
  return nna_net_get_quant(fdnet3_info, 0, 8);
}
// AC44: using guessed type int __fastcall nna_net_get_quant(_DWORD, _DWORD, _DWORD);

//----- (00000514) --------------------------------------------------------
int __fastcall nna_net_fd3_post(char *a1, char *a2, char *a3)
{
  char *v3; // r7
  char *v4; // r8
  int v5; // ST00_4
  int v6; // ST00_4
  int v7; // ST00_4

  v3 = a3;
  v4 = a2;
  v5 = *(_DWORD *)((char *)&loc_6B0 + (_DWORD)off_AC1C);
  xramcpy(a1, (signed int)a1 >> 31, *(_DWORD *)((char *)&loc_6A8 + (_DWORD)off_AC1C));
  v6 = *(_DWORD *)((char *)&loc_7CC + (_DWORD)off_AC1C);
  xramcpy(v4, (signed int)v4 >> 31, *(_DWORD *)((char *)&loc_7C4 + (_DWORD)off_AC1C));
  v7 = *(_DWORD *)((char *)nna_net_fd1_run + (_DWORD)off_AC1C);
  return xramcpy(v3, (signed int)v3 >> 31, *(void **)((char *)&off_8E0 + (_DWORD)off_AC1C));
}
// 8E0: using guessed type void *off_8E0;
// AC1C: using guessed type int *off_AC1C;
// AC48: using guessed type int __cdecl xramcpy(_DWORD, _DWORD, _DWORD);

//----- (000005BC) --------------------------------------------------------
int __fastcall nna_net_fd1_init(int a1, int a2, int a3)
{
  void *v3; // r3

  v3 = off_ABBC;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)off_ABBC) = a1;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)v3) = a2;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v3) = a3;
  return nna_net_init(fdnet1_info);
}
// ABBC: using guessed type void *off_ABBC;
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);

//----- (000005F8) --------------------------------------------------------
int __fastcall nna_net_fd1(unsigned __int8 *a1, int a2, int a3, int a4)
{
  int v4; // r5
  unsigned __int8 *v5; // r7
  void *v6; // r3
  int v7; // r6
  int *v8; // r3

  v4 = a4;
  v5 = a1;
  v6 = off_ABBC;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)off_ABBC) = a2;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)v6) = a3;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v6) = v4;
  v7 = a3 * a2;
  nna_net_init(fdnet1_info);
  nna_net_load_hyper(fdnet1_info);
  v8 = off_ABB4;
  *(_DWORD *)((char *)&loc_8 + (_DWORD)off_ABB4) = v4 * v7;
  xramcpy(*v8, 0, v5);
  return nna_net_forward(fdnet1_info);
}
// ABB4: using guessed type int *off_ABB4;
// ABBC: using guessed type void *off_ABBC;
// AC48: using guessed type int __cdecl xramcpy(_DWORD, _DWORD, _DWORD);
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);
// AC54: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// AC58: using guessed type int __fastcall nna_net_forward(_DWORD);

//----- (00000690) --------------------------------------------------------
int __fastcall nna_net_fd2(unsigned __int8 *a1)
{
  unsigned __int8 *v1; // r5
  int *v2; // r2

  v1 = a1;
  nna_net_init(fdnet2_info);
  nna_net_load_hyper(fdnet2_info);
  v2 = off_ABE8;
  *(_DWORD *)((char *)&loc_8 + (_DWORD)off_ABE8) = 576;
  xramcpy(*v2, 0, v1);
  return nna_net_forward(fdnet2_info);
}
// ABE8: using guessed type int *off_ABE8;
// AC48: using guessed type int __cdecl xramcpy(_DWORD, _DWORD, _DWORD);
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);
// AC54: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// AC58: using guessed type int __fastcall nna_net_forward(_DWORD);

//----- (00000708) --------------------------------------------------------
int __fastcall nna_net_fd3(unsigned __int8 *a1)
{
  unsigned __int8 *v1; // r5

  v1 = a1;
  nna_net_init(fdnet3_info);
  nna_net_load_hyper(fdnet3_info);
  xramcpy(*off_AC1C, 0, v1);
  return nna_net_forward(fdnet3_info);
}
// AC1C: using guessed type int *off_AC1C;
// AC48: using guessed type int __cdecl xramcpy(_DWORD, _DWORD, _DWORD);
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);
// AC54: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// AC58: using guessed type int __fastcall nna_net_forward(_DWORD);

//----- (00000778) --------------------------------------------------------
int nna_net_fd1_case(void)
{
  nna_load_ram(dword_ABAC, off_ABB4 + 7);
  nna_net_init(fdnet1_info);
  nna_net_load_hyper(fdnet1_info);
  nna_net_load_data(fdnet1_info);
  printf("\n# data_pram[0] :%d", *(void **)((char *)&off_25C + (_DWORD)off_ABBC));
  nna_net_load_quant(fdnet1_info);
  printf("\n# data_pram[0] :%d", *(void **)((char *)&off_25C + (_DWORD)off_ABBC));
  nna_net_forward(fdnet1_info);
  return nna_net_dump(fdnet1_info);
}
// 25C: using guessed type void *;
// ABAC: using guessed type int dword_ABAC;
// ABB4: using guessed type int *off_ABB4;
// ABBC: using guessed type void *off_ABBC;
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);
// AC54: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// AC58: using guessed type int __fastcall nna_net_forward(_DWORD);
// AC5C: using guessed type int __fastcall nna_load_ram(_DWORD, _DWORD);
// AC60: using guessed type int __fastcall nna_net_load_data(_DWORD);
// AC68: using guessed type int __fastcall nna_net_load_quant(_DWORD);
// AC6C: using guessed type int __fastcall nna_net_dump(_DWORD);

//----- (00000810) --------------------------------------------------------
int nna_net_fd2_case(void)
{
  nna_load_ram(dword_ABE0, off_ABE8 + 7);
  nna_net_init(fdnet2_info);
  nna_net_load_hyper(fdnet2_info);
  nna_net_load_data(fdnet2_info);
  nna_net_load_quant(fdnet2_info);
  nna_net_forward(fdnet2_info);
  return nna_net_dump(fdnet2_info);
}
// ABE0: using guessed type int dword_ABE0;
// ABE8: using guessed type int *off_ABE8;
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);
// AC54: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// AC58: using guessed type int __fastcall nna_net_forward(_DWORD);
// AC5C: using guessed type int __fastcall nna_load_ram(_DWORD, _DWORD);
// AC60: using guessed type int __fastcall nna_net_load_data(_DWORD);
// AC68: using guessed type int __fastcall nna_net_load_quant(_DWORD);
// AC6C: using guessed type int __fastcall nna_net_dump(_DWORD);

//----- (0000087C) --------------------------------------------------------
int nna_net_fd3_case(void)
{
  nna_load_ram(dword_AC14, off_AC1C + 7);
  nna_net_init(fdnet3_info);
  nna_net_load_hyper(fdnet3_info);
  nna_net_load_data(fdnet3_info);
  nna_net_load_quant(fdnet3_info);
  nna_net_forward(fdnet3_info);
  return nna_net_dump(fdnet3_info);
}
// AC14: using guessed type int dword_AC14;
// AC1C: using guessed type int *off_AC1C;
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);
// AC54: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// AC58: using guessed type int __fastcall nna_net_forward(_DWORD);
// AC5C: using guessed type int __fastcall nna_load_ram(_DWORD, _DWORD);
// AC60: using guessed type int __fastcall nna_net_load_data(_DWORD);
// AC68: using guessed type int __fastcall nna_net_load_quant(_DWORD);
// AC6C: using guessed type int __fastcall nna_net_dump(_DWORD);

//----- (000008E8) --------------------------------------------------------
int __fastcall nna_net_fd1_run(unsigned int a1, unsigned int a2, int a3, int a4, unsigned int a5)
{
  int v5; // r5
  unsigned int v6; // r9
  void *v7; // r3
  int v8; // r5
  int v9; // ST00_4
  int v10; // ST00_4
  int v11; // ST00_4
  int v12; // ST00_4
  char v14; // [sp+8h] [bp-80020h]

  v5 = a4;
  v6 = a1;
  v7 = off_ABBC;
  *(_DWORD *)((char *)&loc_4C + (_DWORD)off_ABBC) = a3;
  *(_DWORD *)((char *)&loc_50 + (_DWORD)v7) = v5;
  *(_DWORD *)((char *)&loc_54 + (_DWORD)v7) = 1;
  v8 = v5 * a3;
  dword_ABAC = a5;
  nna_net_init(fdnet1_info);
  nna_net_load_hyper(fdnet1_info);
  nna_net_load_data(fdnet1_info);
  nna_net_load_quant(fdnet1_info);
  *(_DWORD *)((char *)&loc_8 + (_DWORD)off_ABB4) = v8;
  nna_net_forward(fdnet1_info);
  v9 = *(_DWORD *)((char *)&loc_478 + (_DWORD)off_ABB4);
  xramcpy(&v14, (signed int)&v14 >> 31, *(_DWORD *)((char *)&loc_470 + (_DWORD)off_ABB4));
  v10 = *(_DWORD *)((char *)&loc_478 + (_DWORD)off_ABB4);
  xramcpy(v6, 0, &v14);
  v11 = *(_DWORD *)((char *)&loc_594 + (_DWORD)off_ABB4);
  xramcpy(&v14, (signed int)&v14 >> 31, *(_DWORD *)((char *)&loc_58C + (_DWORD)off_ABB4));
  v12 = *(_DWORD *)((char *)&loc_594 + (_DWORD)off_ABB4);
  return xramcpy(v6 + *(_DWORD *)((char *)&loc_478 + (_DWORD)off_ABB4), 0, &v14);
}
// ABAC: using guessed type int dword_ABAC;
// ABB4: using guessed type int *off_ABB4;
// ABBC: using guessed type void *off_ABBC;
// AC48: using guessed type int __cdecl xramcpy(_DWORD, _DWORD, _DWORD);
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);
// AC54: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// AC58: using guessed type int __fastcall nna_net_forward(_DWORD);
// AC60: using guessed type int __fastcall nna_net_load_data(_DWORD);
// AC68: using guessed type int __fastcall nna_net_load_quant(_DWORD);

//----- (00000A34) --------------------------------------------------------
int __fastcall nna_net_fd2_run(unsigned int a1, unsigned int a2, int a3, unsigned int a4)
{
  unsigned int v4; // r10
  int v5; // r11
  unsigned int v6; // r5
  int v7; // r6
  int result; // r0
  signed __int64 v9; // d8
  int v10; // r0
  char v11; // [sp+8h] [bp-1030h]

  v4 = a4;
  v5 = a3;
  v6 = a1;
  v7 = 0;
  dword_ABE0 = a4;
  nna_net_init(fdnet2_info);
  nna_net_load_hyper(fdnet2_info);
  nna_net_load_data(fdnet2_info);
  result = nna_net_load_quant(fdnet2_info);
  v9 = vshrd_n_s64(vdup_n_s32((unsigned int)&v11).n64_i64[0], 0x20u);
  while ( v7 < v5 )
  {
    dword_ABE0 = v4 + 576 * v7;
    nna_net_load_data(fdnet2_info);
    ++v7;
    nna_net_forward(fdnet2_info);
    xramcpy(v9, HIDWORD(v9), *(_DWORD *)((char *)&loc_58C + (_DWORD)off_ABE8));
    xramcpy(v6, 0, v9);
    xramcpy(v9, HIDWORD(v9), *(_DWORD *)((char *)&loc_6A8 + (_DWORD)off_ABE8));
    v10 = v6 + 8;
    v6 += 16;
    result = xramcpy(v10, 0, v9);
  }
  return result;
}
// ABE0: using guessed type int dword_ABE0;
// ABE8: using guessed type int *off_ABE8;
// AC48: using guessed type int __cdecl xramcpy(_DWORD, _DWORD, _DWORD);
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);
// AC54: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// AC58: using guessed type int __fastcall nna_net_forward(_DWORD);
// AC60: using guessed type int __fastcall nna_net_load_data(_DWORD);
// AC68: using guessed type int __fastcall nna_net_load_quant(_DWORD);

//----- (00000B54) --------------------------------------------------------
int __fastcall nna_net_fd3_run(unsigned int a1, unsigned int a2, int a3, unsigned int a4)
{
  unsigned int v4; // r11
  unsigned int v5; // r5
  int v6; // r6
  signed __int64 v7; // d8
  int result; // r0
  int v9; // r0
  int v10; // [sp+Ch] [bp-1034h]
  char v11; // [sp+10h] [bp-1030h]
  __int64 v12; // [sp+18h] [bp-1028h]
  __int64 v13; // [sp+20h] [bp-1020h]
  __int64 v14; // [sp+28h] [bp-1018h]

  v4 = a4;
  v5 = a1;
  v10 = a3;
  v6 = 0;
  dword_AC14 = a4;
  nna_net_init(fdnet3_info);
  v7 = vshrd_n_s64(vdup_n_s32((unsigned int)&v11).n64_i64[0], 0x20u);
  nna_net_load_data(fdnet3_info);
  nna_net_load_hyper(fdnet3_info);
  result = nna_net_load_quant(fdnet3_info);
  while ( v6 < v10 )
  {
    dword_AC14 = v4 + 2304 * v6;
    nna_net_load_data(fdnet3_info);
    ++v6;
    nna_net_forward(fdnet3_info);
    *(_QWORD *)&v11 = 0LL;
    v12 = 0LL;
    v13 = 0LL;
    v14 = 0LL;
    xramcpy(v7, HIDWORD(v7), *(_DWORD *)((char *)&loc_6A8 + (_DWORD)off_AC1C));
    xramcpy(v5, 0, v7);
    xramcpy(v7, HIDWORD(v7), *(_DWORD *)((char *)&loc_7C4 + (_DWORD)off_AC1C));
    xramcpy(v5 + 8, 0, v7);
    xramcpy(v7, HIDWORD(v7), *(void **)((char *)&off_8E0 + (_DWORD)off_AC1C));
    v9 = v5 + 16;
    v5 += 32;
    result = xramcpy(v9, 0, v7);
  }
  return result;
}
// 8E0: using guessed type void *off_8E0;
// AC14: using guessed type int dword_AC14;
// AC1C: using guessed type int *off_AC1C;
// AC48: using guessed type int __cdecl xramcpy(_DWORD, _DWORD, _DWORD);
// AC50: using guessed type int __fastcall nna_net_init(_DWORD);
// AC54: using guessed type int __fastcall nna_net_load_hyper(_DWORD);
// AC58: using guessed type int __fastcall nna_net_forward(_DWORD);
// AC60: using guessed type int __fastcall nna_net_load_data(_DWORD);
// AC68: using guessed type int __fastcall nna_net_load_quant(_DWORD);

//----- (00000CBC) --------------------------------------------------------
int GLOBAL__sub_I_nna_fdnet_cpp()
{
  std::ios_base::Init::Init((std::ios_base::Init *)&std::__ioinit);
  return _aeabi_atexit(&std::__ioinit, &std::ios_base::Init::~Init, &_dso_handle);
}
// AC78: using guessed type int __fastcall _aeabi_atexit(_DWORD, _DWORD, _DWORD);
// AC7C: using guessed type _DWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this);

// ALL OK, 28 function(s) have been successfully decompiled
