/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall nna_conv_get_output_w(int a1, int a2, int a3, int a4, int a5);
int __fastcall nna_conv_get_output_h(int a1, int a2, int a3, int a4, int a5);
int __fastcall nna_conv_get_max_input_h(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
int __fastcall nna_convolution_hw(unsigned int a1, unsigned int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15);
int __fastcall nna_conv_act_hw(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22);
int __fastcall nna_conv_act_eltwise_hw(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24, int a25, int a26);
int __fastcall nna_conv_get_entry_per_slice(int a1, int a2, int a3, int a4);
int __fastcall nna_conv_get_data_bank(int a1, int a2, int a3, int a4);
int __fastcall nna_conv_get_weight_bank(int a1, int a2, int a3, int a4, int a5, int a6);
unsigned int __fastcall nna_conv_get_weight_bytes(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall nna_conv_get_input_bytes(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall nna_inner_product(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11);
int __fastcall nna_conv_act(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, unsigned int a16, int a17, int a18, int a19);
signed int __fastcall nna_conv_pool_get_max_input_w(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12);
int __fastcall nna_conv_act_pool(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, signed int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23);
int __fastcall nna_conv_act_eltwise(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23);
// _DWORD __cdecl xregw(unsigned int, unsigned int); idb
// int printf(const char *format, ...);
// _DWORD __cdecl nna_bisa_cfg(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, int, int, int, int, int, int, int, int); idb
// _DWORD __cdecl nna_x1_cfg(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int); idb
// _DWORD __cdecl nna_x2_cfg(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int); idb
// _DWORD __cdecl nna_swish_cfg(int); idb
// _DWORD __cdecl nna_y_cfg(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int); idb
// _DWORD __cdecl nna_conv_set_producer(int, int); idb
// _DWORD __cdecl nna_sdp_set_producer(int, int); idb
// _DWORD __cdecl nna_sdp_enable(int, int); idb
// _DWORD __cdecl nna_conv_enable(int, int); idb
// _DWORD __cdecl nna_wait_done(int, int); idb
// _DWORD __cdecl nna_pool_get_output_w(int, int, int, int); idb
// _DWORD __cdecl nna_pdp_set_producer(int, int); idb
// _DWORD __cdecl nna_pool_hw(unsigned int, unsigned int, int, int, int, int, int, int, int, int, int, int, int); idb
// _DWORD __cdecl nna_pdp_enable(int, int); idb

//-------------------------------------------------------------------------
// Data declarations

_DWORD map_grid_type_to_misc[16] =
{
  0,
  268435456,
  1114112,
  16777216,
  65536,
  17891328,
  16842752,
  16777216,
  17891328,
  16842752,
  1114112,
  17891328,
  17891328,
  16842752,
  17891328,
  17891328
}; // idb
int map_grid_type_to_pad_zero[16] =
{
  4294967295,
  16777215,
  4278255615,
  4294902015,
  4294967040,
  65535,
  4294901760,
  16711935,
  4278190335,
  16776960,
  4278255360,
  255,
  65280,
  16711680,
  4278190080,
  0
}; // idb
_DWORD map_grid_type_to_releas_op[16] =
{
  0,
  4294967295,
  1,
  1,
  0,
  0,
  0,
  4294967295,
  1,
  4294967295,
  0,
  0,
  0,
  4294967295,
  1,
  0
}; // idb


//----- (00000004) --------------------------------------------------------
int __fastcall nna_conv_get_output_w(int a1, int a2, int a3, int a4, int a5)
{
  int v5; // r0
  int v6; // r12

  v5 = a1 - ((unsigned __int8)a3 * ((unsigned __int8)a2 - 1) + 1);
  if ( (unsigned int)a5 >> 8 )
    v6 = (unsigned __int16)a5 >> 8;
  else
    v6 = (unsigned __int8)a5;
  return (v5 + (unsigned __int8)a5 + v6) / a4 + 1;
}

//----- (00000058) --------------------------------------------------------
int __fastcall nna_conv_get_output_h(int a1, int a2, int a3, int a4, int a5)
{
  unsigned int v5; // r12
  int v6; // r2
  unsigned int v7; // lr
  int v8; // r0

  v5 = a5;
  v6 = (unsigned __int16)a3 * ((unsigned __int16)a2 - 1);
  v7 = (unsigned int)a5 >> 8;
  if ( (unsigned int)a5 >> 8 )
    v7 = ((unsigned int)a5 >> 16) & 0xFF;
  v8 = a1 - (v6 + 1);
  if ( (unsigned int)a5 >> 8 )
    v5 = (unsigned int)a5 >> 24;
  else
    v7 = (unsigned __int8)a5;
  if ( !((unsigned int)a5 >> 8) )
    v5 = v7;
  return (signed int)(v8 + v7 + v5) / a4 + 1;
}

//----- (000000B0) --------------------------------------------------------
int __fastcall nna_conv_get_max_input_h(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9)
{
  int v9; // r4
  int v10; // r9
  int v11; // r5
  int v12; // r6
  int v13; // r8
  int v14; // r3
  unsigned int v15; // r3
  unsigned int v16; // r2
  int v17; // r3
  int v18; // r2
  int v19; // r4
  int v20; // r6
  unsigned int v21; // r2
  int v22; // r3
  int v24; // r4
  int v25; // r2

  v9 = a2;
  v10 = a1;
  v11 = a3;
  v12 = a4;
  nna_conv_get_output_w(a2, a6, a7, a8, a9);
  nna_conv_get_output_h(v11, a6, a7, a8, a9);
  if ( (unsigned int)a9 >> 8 )
    v13 = (unsigned __int16)a9 >> 8;
  else
    v13 = (unsigned __int8)a9;
  if ( v10 )
  {
    v24 = v12 * ((unsigned __int8)a9 + v9 + v13);
    v25 = v24 + 31;
    if ( v24 + 31 < 0 )
      v25 = v24 + 62;
    v18 = v25 >> 5;
  }
  else
  {
    v14 = v12 + 7;
    if ( v12 + 7 < 0 )
      v14 = v12 + 14;
    v15 = v14 >> 3;
    v16 = v15 >> 2;
    v17 = v15 & 3;
    v18 = v9 * v16;
    switch ( v17 )
    {
      case 3:
        v18 += v9;
        break;
      case 2:
        v18 += (v9 + 1) / 2;
        break;
      case 1:
        if ( v9 + 3 >= 0 )
          v19 = v9 + 3;
        else
          v19 = v9 + 6;
        v18 += v19 >> 2;
        break;
    }
  }
  v20 = a5 * (unsigned __int8)a6 * v12 * (unsigned __int8)a6;
  v21 = (unsigned int)(v18 * v11 + 511) >> 9;
  v22 = v20 + 31;
  if ( v20 + 31 < 0 )
    v22 = v20 + 62;
  if ( v21 + (((v22 & 0xFFFFFFE0) + 0x3FFF) >> 14) > 0x10 )
    v11 /= 2;
  return v11;
}

//----- (000001D0) --------------------------------------------------------
int __fastcall nna_convolution_hw(unsigned int a1, unsigned int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15)
{
  int v15; // r5
  unsigned int v16; // r4
  int v17; // r2
  unsigned int v18; // r3
  unsigned int v19; // r3
  int v20; // r3
  int v21; // r3
  unsigned int v22; // r3
  unsigned int v23; // r4
  int v24; // r3
  int v25; // r4
  int v26; // r3
  int v27; // r8
  int v28; // r3
  int v29; // r4
  int v30; // r3
  int v31; // r3
  unsigned int v32; // r1
  unsigned int v33; // r1
  unsigned int v34; // r0
  int v35; // r1
  int v36; // r10
  int v37; // r1
  unsigned int v38; // r1
  unsigned int v39; // r0
  unsigned int v40; // r1
  unsigned int v41; // r1
  unsigned int v43; // [sp+8h] [bp-80h]
  unsigned int v44; // [sp+Ch] [bp-7Ch]
  unsigned int v45; // [sp+1Ch] [bp-6Ch]
  unsigned int v46; // [sp+24h] [bp-64h]
  int v47; // [sp+2Ch] [bp-5Ch]
  int v48; // [sp+34h] [bp-54h]
  int v49; // [sp+38h] [bp-50h]
  unsigned int v50; // [sp+3Ch] [bp-4Ch]
  unsigned int v51; // [sp+44h] [bp-44h]
  unsigned int v52; // [sp+4Ch] [bp-3Ch]
  int v53; // [sp+50h] [bp-38h]
  unsigned int v54; // [sp+58h] [bp-30h]

  v15 = a3;
  v44 = a4;
  v16 = a15;
  v46 = a1;
  v45 = a2;
  nna_conv_get_output_w(a5, a12, a13, a14, a15);
  nna_conv_get_output_h(a6, a12, a13, a14, a15);
  if ( (unsigned int)a15 >> 8 )
    v18 = ((unsigned int)a15 >> 16) & 0xFF;
  else
    v18 = (unsigned __int8)a15;
  if ( (unsigned int)a15 >> 8 )
    v17 = (unsigned __int16)a15 >> 8;
  else
    v16 = (unsigned __int8)a15;
  if ( (unsigned int)a15 >> 8 )
    v16 >>= 24;
  else
    v17 = (unsigned __int8)a15;
  v19 = ((v18 << 16) | (v16 << 24) | (unsigned __int8)a15 | (v17 << 8)) & map_grid_type_to_pad_zero[a7];
  v43 = v19;
  v47 = (unsigned __int8)v19;
  v52 = v19 >> 16;
  v20 = (unsigned __int8)a12 - a14;
  if ( (unsigned int)a7 <= 1 )
    v20 = 0;
  v51 = v20;
  v53 = map_grid_type_to_releas_op[a7];
  v48 = nna_conv_get_output_w(a8, a12, a13, a14, v43);
  v49 = nna_conv_get_output_h(a9, a12, a13, a14, v43);
  if ( v15 )
  {
    v28 = a10 * (((unsigned __int16)v43 >> 8) + v47 + a8);
    v27 = (unsigned __int16)v15 >> 8;
    v15 = 1;
    v29 = v28 + 31;
    if ( v28 + 31 < 0 )
      v29 = v28 + 62;
    v25 = v29 >> 5;
  }
  else
  {
    v21 = a10 + 7;
    if ( a10 + 7 < 0 )
      v21 = a10 + 14;
    v22 = v21 >> 3;
    v23 = v22 >> 2;
    v24 = v22 & 3;
    v25 = a8 * v23;
    switch ( v24 )
    {
      case 3:
        v25 += a8;
        break;
      case 2:
        v25 += (a8 + 1) / 2;
        break;
      case 1:
        v26 = a8 + 3;
        if ( a8 + 3 < 0 )
          v26 = a8 + 6;
        v25 += v26 >> 2;
        break;
    }
    v27 = 0;
  }
  v30 = a11 * a10 * (unsigned __int8)a12 * (unsigned __int8)a12;
  if ( v30 + 31 >= 0 )
    v31 = v30 + 31;
  else
    v31 = v30 + 62;
  v50 = v31 & 0xFFFFFFE0;
  v54 = ((v31 & 0xFFFFFFE0) + 0x3FFF) >> 14;
  xregw(0x500Cu, 0);
  xregw(0x600Cu, 0);
  xregw(0x400Cu, map_grid_type_to_misc[a7] >> 16 << 16);
  xregw(0x4010u, v15);
  xregw(0x4014u, (a8 - 1) | ((v51 + a9 - 1) << 16));
  xregw(0x4018u, a10 - 1);
  xregw(0x401Cu, 0);
  if ( v15 )
    v32 = 2;
  else
    v32 = 0;
  xregw(0x4020u, v32);
  xregw(0x4024u, v25 - 1);
  if ( v45 <= 0x7FFFF )
  {
    xregw(0x4028u, 1u);
    v33 = v45;
    v34 = 16440;
  }
  else
  {
    v33 = 0;
    v34 = 16424;
  }
  xregw(v34, v33);
  if ( v15 )
  {
    xregw(0x402Cu, ((unsigned __int8)a12 - 1) << 16);
    v35 = (a10 * (unsigned __int8)a12 - 1) | ((a11 - 1) << 16);
  }
  else
  {
    xregw(0x402Cu, ((unsigned __int8)a12 - 1) | (((unsigned __int8)a12 - 1) << 16));
    v35 = (a10 - 1) | ((a11 - 1) << 16);
  }
  xregw(0x4030u, v35);
  v36 = a10 * (unsigned __int8)a12 * (unsigned __int8)a12;
  v37 = v36 * a11 + 31;
  if ( v37 < 0 )
    v37 = v36 * a11 + 62;
  xregw(0x4034u, v37 & 0xFFFFFFE0);
  xregw(0x403Cu, (v48 - 1) | ((v49 - 1) << 16));
  xregw(0x4040u, a11 - 1);
  xregw(0x4044u, v49 * v48 - 1);
  if ( a7 )
    v38 = a9 + v53 * ((unsigned __int8)a12 - a14) - 1;
  else
    v38 = 0;
  xregw(0x4048u, v38);
  xregw(0x404Cu, (a14 - 1) | ((a14 - 1) << 16));
  xregw(0x4050u, ((unsigned __int16)a13 - 1) | (((unsigned __int16)a13 - 1) << 16));
  xregw(0x4054u, (v52 << 16) & 0xFF0000 | v47);
  xregw(0x4058u, 0);
  xregw(0x405Cu, (((unsigned int)(v25 * a9 + 511) >> 9) - 1) | ((v54 - 1) << 16));
  xregw(0x4060u, 0);
  xregw(0x3008u, 0x10001u);
  xregw(0x3014u, map_grid_type_to_misc[a7] & 0xFFFF0000);
  if ( v15 )
  {
    xregw(0x3018u, (v27 << 8) | 1);
    if ( v44 )
    {
      xregw(0x3098u, 1u);
      xregw(0x309Cu, (v44 << 8) & 0xFF0000 | (unsigned __int8)v44);
      xregw(0x30A0u, 0xFFFF * ((v44 >> 16) & 0xFF) | (v44 >> 24 << 16));
      xregw(0x30ACu, 1u);
      v40 = 1;
      v39 = 12452;
    }
    else
    {
      printf("\n# mean OFF");
      v40 = 0;
      v39 = 12440;
    }
  }
  else
  {
    v39 = 12312;
    v40 = 1052672;
  }
  xregw(v39, v40);
  xregw(0x304Cu, 1u);
  xregw(0x301Cu, (a8 - 1) | ((a9 - 1) << 16));
  xregw(0x3020u, a10 - 1);
  xregw(0x3024u, (a8 - 1) | ((a9 - 1) << 16));
  xregw(0x302Cu, 1u);
  xregw(0x3030u, 0);
  if ( v15 )
  {
    xregw(0x3034u, v46);
    xregw(0x3040u, a5);
    v41 = a6 * a5;
  }
  else
  {
    xregw(0x3034u, v46 & 0xFFFFFFF8);
    xregw(0x3028u, v46 & 7);
    xregw(0x3040u, 8 * a5);
    v41 = 8 * a5 * a6;
  }
  xregw(0x3048u, v41);
  xregw(0x304Cu, 1u);
  xregw(0x3058u, 0);
  xregw(0x3060u, v25 - 1);
  xregw(0x3068u, 0);
  xregw(0x306Cu, v36 - 1);
  xregw(0x3070u, a11 - 1);
  xregw(0x3074u, v45 > 0x7FFFF);
  xregw(0x3078u, 0);
  xregw(0x307Cu, v45);
  xregw(0x3080u, v50);
  xregw(0x30B0u, (a14 - 1) | ((a14 - 1) << 16));
  xregw(0x30B4u, v43);
  xregw(0x30B8u, 0);
  return xregw(0x30BCu, (((unsigned int)(v25 * a9 + 511) >> 9) - 1) | ((v54 - 1) << 16));
}

//----- (000008C0) --------------------------------------------------------
int __fastcall nna_conv_act_hw(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22)
{
  int v22; // r5
  int v23; // r1
  unsigned int v24; // r3
  unsigned int v25; // r0
  unsigned int v26; // r3
  int v27; // r3
  int v28; // r9
  int v29; // r10
  int v30; // r11
  int v31; // r9
  int v32; // r0
  signed int v33; // r2
  int v34; // r0
  int v35; // r3
  int v36; // r2
  int v37; // r0
  int v38; // r1
  int v39; // r2
  unsigned int v40; // r3
  int v41; // r0
  int v43; // [sp+4h] [bp-7Ch]
  unsigned int v44; // [sp+50h] [bp-30h]
  unsigned int v45; // [sp+54h] [bp-2Ch]

  v44 = a4;
  v45 = a1;
  v22 = a20;
  nna_convolution_hw(a2, a3, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19);
  if ( (unsigned int)a19 >> 8 )
    v24 = ((unsigned int)a19 >> 16) & 0xFF;
  else
    v24 = (unsigned __int8)a19;
  if ( (unsigned int)a19 >> 8 )
    v25 = (unsigned int)a19 >> 24;
  else
    v25 = (unsigned __int8)a19;
  v26 = v24 << 16;
  if ( !((unsigned int)a19 >> 8) )
    v23 = (unsigned __int8)a19;
  v27 = v26 | (v25 << 24) | (unsigned __int8)a19;
  if ( (unsigned int)a19 >> 8 )
    v23 = (unsigned __int16)a19 >> 8;
  v28 = map_grid_type_to_pad_zero[a11] & (v27 | (v23 << 8));
  v29 = nna_conv_get_output_w(a12, a16, a17, a18, v28);
  v30 = nna_conv_get_output_h(a13, a16, a17, a18, v28);
  v31 = nna_conv_get_output_w(a9, a16, a17, a18, a19);
  v32 = nna_conv_get_output_h(a10, a16, a17, a18, a19);
  nna_bisa_cfg(v45, 0, v44, 0, 0, v31, v32, v29, v30, a15, 0, 1, (unsigned __int8)a5);
  if ( a20 )
  {
    if ( a20 == 1 )
    {
      v33 = 1;
      v34 = 0;
      goto LABEL_17;
    }
    v22 = 0;
    v34 = 0;
  }
  else
  {
    v34 = 1;
  }
  v33 = 2;
LABEL_17:
  v35 = a21 - 1;
  if ( a21 != 1 )
    v35 = 1;
  v43 = v33;
  v36 = v44;
  if ( v44 < 0x80000 )
    v36 = 0;
  if ( v44 >= 0x80000 )
    v36 = 1;
  v37 = nna_x1_cfg(
          v34,
          0,
          v36,
          0,
          1,
          v43,
          0,
          1,
          2,
          (unsigned __int16)a6 >> 8,
          0,
          v22,
          1,
          1,
          (unsigned __int8)a6,
          v35,
          0);
  v40 = a21;
  if ( a21 == 2 )
    v40 = a22;
  else
    v39 = 0;
  if ( a21 == 2 )
    v38 = (unsigned __int8)a22;
  else
    v40 = 1;
  if ( a21 == 2 )
  {
    v40 = (v40 >> 8) & 0xFFFF;
    v39 = 1;
  }
  else
  {
    v38 = v39;
  }
  if ( a21 != 2 )
    v37 = v40;
  if ( a21 == 2 )
    v37 = 0;
  nna_x2_cfg(v37, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, v40, v38, 1, v39);
  if ( a21 == 4 )
  {
    nna_swish_cfg(a22);
    v41 = 0;
  }
  else
  {
    v41 = 1;
  }
  return nna_y_cfg(v41, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, v41, 0);
}

//----- (00000BCC) --------------------------------------------------------
int __fastcall nna_conv_act_eltwise_hw(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24, int a25, int a26)
{
  int v26; // r6
  signed int v27; // r5
  int v28; // r1
  unsigned int v29; // r3
  unsigned int v30; // r0
  unsigned int v31; // r3
  int v32; // r3
  int v33; // r10
  int v34; // ST60_4
  int v35; // r11
  int v36; // r10
  int v37; // r0
  signed int v38; // r2
  int v39; // r0
  int v40; // r3
  int v41; // r2
  int v42; // r0
  int v43; // r2
  unsigned int v44; // r3
  int v45; // r1
  signed int v46; // r2
  int v47; // r0
  int v48; // r2
  int v50; // [sp+4h] [bp-94h]
  unsigned int v51; // [sp+44h] [bp-54h]
  unsigned int v52; // [sp+64h] [bp-34h]
  int v53; // [sp+A0h] [bp+8h]

  v52 = a1;
  v51 = a3;
  v26 = a21;
  v27 = a24;
  nna_convolution_hw(a2, a4, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20);
  if ( (unsigned int)a20 >> 8 )
    v29 = ((unsigned int)a20 >> 16) & 0xFF;
  else
    v29 = (unsigned __int8)a20;
  if ( (unsigned int)a20 >> 8 )
    v30 = (unsigned int)a20 >> 24;
  else
    v30 = (unsigned __int8)a20;
  v31 = v29 << 16;
  if ( !((unsigned int)a20 >> 8) )
    v28 = (unsigned __int8)a20;
  v32 = v31 | (v30 << 24) | (unsigned __int8)a20;
  if ( (unsigned int)a20 >> 8 )
    v28 = (unsigned __int16)a20 >> 8;
  v33 = map_grid_type_to_pad_zero[a12] & (v32 | (v28 << 8));
  v34 = nna_conv_get_output_w(a13, a17, a18, a19, v33);
  v35 = nna_conv_get_output_h(a14, a17, a18, a19, v33);
  v36 = nna_conv_get_output_w(a10, a17, a18, a19, a20);
  v37 = nna_conv_get_output_h(a11, a17, a18, a19, a20);
  nna_bisa_cfg(v52, 0, a5, 0, v51, v36, v37, v34, v35, a16, 0, 1, 1);
  if ( a21 )
  {
    if ( a21 == 1 )
    {
      v38 = 1;
      v39 = 0;
      goto LABEL_17;
    }
    v26 = 0;
    v39 = 0;
  }
  else
  {
    v39 = 1;
  }
  v38 = 2;
LABEL_17:
  v40 = a22 - 1;
  if ( a22 != 1 )
    v40 = 1;
  v50 = v38;
  v41 = a5;
  if ( a5 <= 0x7FFFF )
    v41 = 0;
  if ( a5 > 0x7FFFF )
    v41 = 1;
  v42 = nna_x1_cfg(
          v39,
          0,
          v41,
          0,
          1,
          v50,
          0,
          1,
          2,
          (unsigned __int16)a7 >> 8,
          0,
          v26,
          1,
          1,
          (unsigned __int8)a7,
          v40,
          0);
  if ( a22 == 2 )
  {
    v44 = a23;
  }
  else
  {
    v43 = 0;
    v44 = 1;
  }
  if ( a22 == 2 )
  {
    v45 = (unsigned __int8)a23;
    v43 = 1;
    v44 = (v44 >> 8) & 0xFFFF;
  }
  else
  {
    v45 = v43;
  }
  if ( a22 != 2 )
    v42 = v44;
  if ( a22 == 2 )
    v42 = 0;
  nna_x2_cfg(v42, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, v44, v45, 1, v43);
  if ( a22 == 4 )
    nna_swish_cfg(a23);
  if ( !a24 )
  {
    v46 = 1;
    goto LABEL_42;
  }
  v46 = 0;
  if ( a24 == 1 )
  {
LABEL_42:
    v47 = 2;
    goto LABEL_43;
  }
  if ( a24 == 2 )
  {
    v47 = 0;
    v27 = 1;
  }
  else
  {
    v47 = 2;
    v27 = 0;
  }
LABEL_43:
  v53 = v46;
  v48 = v51;
  if ( v51 <= 0x7FFFF )
    v48 = 0;
  if ( v51 > 0x7FFFF )
    v48 = 1;
  return nna_y_cfg(0, 0, v48, 1, 0, v27, v53, 1, v47, 1, 0, a26, 0, 0, 0, 0, 0, 0, 0, 0, 1, (unsigned __int8)a6, 1, 0);
}

//----- (00000F7C) --------------------------------------------------------
int __fastcall nna_conv_get_entry_per_slice(int a1, int a2, int a3, int a4)
{
  int v4; // r1
  int v5; // r2
  unsigned int v6; // r2
  unsigned int v7; // r0
  int v8; // r2
  int result; // r0
  int v10; // r1
  int v11; // r1
  int v12; // r0
  int v13; // r1

  v4 = a1;
  if ( a4 )
  {
    v11 = a1 * a3;
    v12 = a1 * a3 + 31;
    if ( v12 >= 0 )
      v13 = v12;
    else
      v13 = v11 + 62;
    result = v13 >> 5;
  }
  else
  {
    if ( a3 + 7 >= 0 )
      v5 = a3 + 7;
    else
      v5 = a3 + 14;
    v6 = v5 >> 3;
    v7 = v6 >> 2;
    v8 = v6 & 3;
    result = v4 * v7;
    switch ( v8 )
    {
      case 3:
        result += v4;
        break;
      case 2:
        result += (v4 + 1) / 2;
        break;
      case 1:
        if ( v4 + 3 >= 0 )
          v10 = v4 + 3;
        else
          v10 = v4 + 6;
        result += v10 >> 2;
        break;
    }
  }
  return result;
}

//----- (0000100C) --------------------------------------------------------
int __fastcall nna_conv_get_data_bank(int a1, int a2, int a3, int a4)
{
  return (nna_conv_get_entry_per_slice(a1, a2, a3, a4) * a2 + 511) / 512;
}

//----- (00001040) --------------------------------------------------------
int __fastcall nna_conv_get_weight_bank(int a1, int a2, int a3, int a4, int a5, int a6)
{
  int v6; // r6
  int v7; // r4
  int v8; // r3
  int v9; // r0

  v6 = a3;
  v7 = a4;
  nna_conv_get_entry_per_slice(a1, a2, a3, a6);
  v8 = v7 * (unsigned __int16)a5 * v6 * (unsigned __int16)a5;
  v9 = v8 + 31;
  if ( v8 + 31 < 0 )
    v9 = v8 + 62;
  return (signed int)((v9 & 0xFFFFFFE0) + 0x3FFF) / 0x4000;
}

//----- (00001098) --------------------------------------------------------
unsigned int __fastcall nna_conv_get_weight_bytes(int a1, int a2, int a3, int a4, int a5, int a6)
{
  int v6; // r6
  int v7; // r4
  int v8; // r3
  int v9; // r0

  v6 = a3;
  v7 = a4;
  nna_conv_get_entry_per_slice(a1, a2, a3, a6);
  v8 = v7 * (unsigned __int16)a5 * v6 * (unsigned __int16)a5;
  v9 = v8 + 31;
  if ( v8 + 31 < 0 )
    v9 = v8 + 62;
  return v9 & 0xFFFFFFE0;
}

//----- (000010D8) --------------------------------------------------------
int __fastcall nna_conv_get_input_bytes(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return (nna_conv_get_entry_per_slice(a1, a2, a3, a6) * a2 + 511) / 512;
}

//----- (00001110) --------------------------------------------------------
int __fastcall nna_inner_product(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11)
{
  unsigned int v11; // ST5C_4
  unsigned int v12; // ST54_4
  int v13; // r6
  int v14; // r7
  unsigned int v15; // ST58_4
  int v16; // r8
  int v17; // r9
  unsigned int v18; // r2
  unsigned int v20; // [sp+50h] [bp-40h]

  v11 = a4;
  v12 = a2;
  v20 = a1;
  v13 = a7;
  v14 = a8;
  v15 = a3;
  nna_conv_set_producer(0, 0);
  nna_sdp_set_producer(0, 0);
  v16 = nna_conv_get_output_w(v13, v13, 1, 1, 0);
  v17 = nna_conv_get_output_h(v14, v14, 1, 1, 0);
  nna_convolution_hw(v12, v15, 0, 0, v13, v14, 0, v13, v14, a9, a10, v13, 1, 1, 0);
  v18 = v11;
  if ( !a11 )
    v18 = 0;
  nna_bisa_cfg(v20, 0, v18, 0, 0, v16, v17, v16, v17, a10, 0, 1, a5);
  nna_x1_cfg(1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0);
  nna_x2_cfg(1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0);
  nna_y_cfg(1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0);
  nna_sdp_enable(0, 1);
  nna_conv_enable(0, 1);
  return nna_wait_done(1376257, 1376257);
}

//----- (00001340) --------------------------------------------------------
int __fastcall nna_conv_act(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, unsigned int a16, int a17, int a18, int a19)
{
  unsigned int v19; // r11
  int v20; // r0
  unsigned int v21; // r3
  int v22; // r7
  int v23; // r0
  int v24; // r11
  int v25; // r9
  int v26; // r7
  signed int v27; // r3
  signed int v28; // ST80_4
  int v29; // r1
  unsigned int v31; // [sp+58h] [bp-60h]
  unsigned int v32; // [sp+5Ch] [bp-5Ch]
  unsigned int v33; // [sp+60h] [bp-58h]
  unsigned int v34; // [sp+64h] [bp-54h]
  unsigned int v35; // [sp+80h] [bp-38h]
  unsigned int v36; // [sp+84h] [bp-34h]
  int v37; // [sp+8Ch] [bp-2Ch]

  v34 = a4;
  v31 = a1;
  v32 = a2;
  v33 = a3;
  v20 = nna_conv_get_max_input_h(a7, a9, a10, a11, a12, a13, a14, a15, a16);
  v21 = a16 >> 8;
  v22 = v20;
  if ( a16 >> 8 )
    v21 = (unsigned __int16)a16 >> 8;
  if ( a16 >> 8 )
    v35 = v21;
  if ( a16 >> 8 )
    v21 = (a16 >> 16) & 0xFF;
  if ( a16 >> 8 )
    v36 = v21;
  else
    v19 = (unsigned __int8)a16;
  if ( a16 >> 8 )
    v19 = a16 >> 24;
  if ( !(a16 >> 8) )
    v36 = (unsigned __int8)a16;
  if ( !(a16 >> 8) )
    v35 = (unsigned __int8)a16;
  v37 = nna_conv_get_output_w(a9, a13, a14, a15, a16);
  nna_conv_get_output_h(a10, a13, a14, a15, a16);
  if ( a10 <= v22 )
  {
    nna_conv_set_producer(0, 0);
    nna_sdp_set_producer(0, 0);
    nna_conv_act_hw(
      v31,
      v32,
      v33,
      v34,
      a5,
      a6,
      a7,
      a8,
      a9,
      a10,
      0,
      a9,
      a10,
      a11,
      a12,
      a13,
      a14,
      a15,
      a16,
      a17,
      a18,
      a19);
    nna_sdp_enable(0, 1);
    nna_conv_enable(0, 1);
    v29 = 1376257;
  }
  else
  {
    nna_conv_set_producer(0, 0);
    nna_sdp_set_producer(0, 0);
    nna_conv_act_hw(
      v31,
      v32,
      v33,
      v34,
      a5,
      a6,
      a7,
      a8,
      a9,
      a10,
      1,
      a9,
      v22,
      a11,
      a12,
      a13,
      a14,
      a15,
      a16,
      a17,
      a18,
      a19);
    nna_sdp_enable(0, 1);
    nna_conv_enable(0, 1);
    nna_wait_done(1376257, 1376257);
    v23 = nna_conv_get_output_h(
            v22,
            a13,
            a14,
            a15,
            ((v36 << 16) | (v19 << 24) | (unsigned __int8)a16 | (v35 << 8)) & 0xFFFFFF);
    v24 = v22 * a9;
    v25 = v23 * 8 * v37;
    v26 = a10 - v22;
    if ( a7 )
      v27 = 1;
    else
      v27 = 8;
    v28 = v27;
    nna_conv_set_producer(0, 0);
    nna_sdp_set_producer(0, 0);
    nna_conv_act_hw(
      v31 + v25,
      v32 + v24 * v28,
      v33,
      v34,
      a5,
      a6,
      a7,
      a8,
      a9,
      a10,
      2,
      a9,
      v26,
      a11,
      a12,
      a13,
      a14,
      a15,
      a16,
      a17,
      a18,
      a19);
    nna_sdp_enable(0, 1);
    nna_conv_enable(0, 1);
    v29 = 2752514;
  }
  return nna_wait_done(v29, v29);
}

//----- (00001720) --------------------------------------------------------
signed int __fastcall nna_conv_pool_get_max_input_w(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12)
{
  return 256;
}

//----- (00001734) --------------------------------------------------------
int __fastcall nna_conv_act_pool(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, int a5, int a6, int a7, int a8, signed int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23)
{
  int v23; // r4
  int v24; // ST90_4
  int v25; // ST94_4
  int v26; // ST90_4
  int v27; // r1
  int v29; // [sp+48h] [bp-78h]
  int v30; // [sp+58h] [bp-68h]
  unsigned int v31; // [sp+64h] [bp-5Ch]
  unsigned int v32; // [sp+68h] [bp-58h]
  unsigned int v33; // [sp+6Ch] [bp-54h]
  unsigned int v34; // [sp+70h] [bp-50h]

  v34 = a4;
  v31 = a1;
  v32 = a2;
  v33 = a3;
  v30 = nna_conv_get_output_w(a9, a13, a14, a15, a16);
  v29 = nna_conv_get_output_h(a10, a13, a14, a15, a16);
  if ( a9 <= nna_conv_pool_get_max_input_w(a9, a10, a11, a12, a13, a14, a15, a16, a20, a21, a22, a23) )
  {
    nna_conv_set_producer(0, 0);
    nna_sdp_set_producer(0, 0);
    nna_pdp_set_producer(0, 0);
    nna_conv_act_hw(0, v32, v33, v34, a5, a6, a7, a8, a9, a10, 0, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19);
    nna_pool_hw(v31, 0, v30, v29, v30, v29, a12, a20, a21, a22, a23, 0, 2);
    nna_pdp_enable(0, 0);
    nna_sdp_enable(0, 1);
    nna_conv_enable(0, 1);
    v27 = 1376273;
  }
  else
  {
    v23 = (unsigned __int8)((unsigned __int8)(a13 & 0xFE) / a15) + 256;
    v24 = nna_conv_get_output_w(v23, a13, a14, a15, a16);
    v25 = nna_pool_get_output_w(v24, a21, a22, a23);
    nna_conv_set_producer(0, 0);
    nna_sdp_set_producer(0, 0);
    nna_pdp_set_producer(0, 0);
    nna_conv_act_hw(0, v32, v33, v34, a5, a6, a7, a8, a9, a10, 0, v23, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19);
    nna_pool_hw(v31, 0, v30, v29, v24, v29, a12, a20, a21, a22, a23, 0, 2);
    nna_pdp_enable(0, 0);
    nna_sdp_enable(0, 1);
    nna_conv_enable(0, 1);
    nna_wait_done(1376257, 1376257);
    v26 = nna_conv_get_output_w(a9 - 256, a13, a14, a15, a16);
    nna_conv_set_producer(0, 0);
    nna_sdp_set_producer(0, 0);
    nna_pdp_set_producer(0, 0);
    nna_conv_act_hw(
      0,
      v32 + 256,
      v33,
      v34,
      a5,
      a6,
      a7,
      a8,
      a9,
      a10,
      0,
      a9 - 256,
      a10,
      a11,
      a12,
      a13,
      a14,
      a15,
      a16,
      a17,
      a18,
      a19);
    nna_pool_hw(v31 + 8 * v25, 0, v30, v29, v26, v29, a12, a20, a21, a22, a23, 0, 2);
    nna_pdp_enable(0, 0);
    nna_sdp_enable(0, 1);
    nna_conv_enable(0, 1);
    v27 = 2752514;
  }
  return nna_wait_done(v27, v27);
}

//----- (00001C38) --------------------------------------------------------
int __fastcall nna_conv_act_eltwise(unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23)
{
  unsigned int v23; // r6
  unsigned int v24; // ST64_4
  unsigned int v25; // ST5C_4
  unsigned int v26; // ST60_4

  v23 = a2;
  v24 = a4;
  v25 = a1;
  v26 = a3;
  nna_conv_set_producer(0, 0);
  nna_sdp_set_producer(0, 0);
  nna_conv_act_eltwise_hw(
    v25,
    v23,
    v26,
    v24,
    a5,
    a6,
    a7,
    a8,
    a9,
    a10,
    a11,
    0,
    a10,
    a11,
    a12,
    a13,
    a14,
    a15,
    a16,
    a17,
    a18,
    a19,
    a20,
    a21,
    a22,
    a23);
  nna_sdp_enable(0, 1);
  nna_conv_enable(0, 1);
  return nna_wait_done(1376257, 1376257);
}

// ALL OK, 16 function(s) have been successfully decompiled
