/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall nna_play_cfg_cvt(unsigned int a1, int a2);
int __fastcall nna_play_cfg_lut(int a1, _DWORD *a2);
int __fastcall nna_play_cfg_sdp(int a1, _DWORD *a2, int *a3);
int __fastcall nna_play_conv(unsigned int *a1);
int __fastcall nna_play_sdp(_DWORD *a1);
int __fastcall nna_play_pdp(_DWORD *a1);
int __fastcall nna_play_bdma(int a1);
int __fastcall nna_play_nms(unsigned int *a1);
int __fastcall nna_play_lsc(_DWORD *a1);
int __fastcall nna_play_clean_producer(unsigned int a1);
int __fastcall nna_play_set_producer(int a1);
int __fastcall nna_play_set_enable(int result);
int __fastcall nna_play_wait_done(int a1);
int __fastcall dump_group(unsigned __int8 *a1);
int __fastcall nna_play_run(int result);
int __fastcall nna_group_run(int a1);
int __fastcall nna_set_group_id(int a1);
int __fastcall nna_play(int a1);
// _DWORD __cdecl xregw(unsigned int, unsigned int); idb
// _DWORD __cdecl nna_get_bs_addr(unsigned int); idb
// _DWORD nna_get_engine(void); idb
// _DWORD __cdecl nna_get_fm_addr(unsigned int); idb
// _DWORD __cdecl nna_get_wt_addr(unsigned int); idb
// int printf(const char *format, ...);
// _DWORD __cdecl xreg_wait(unsigned int, unsigned int, unsigned int); idb
// _DWORD __cdecl xregr(unsigned int); idb
// _DWORD __cdecl nna_mean_cfg(int, int, int, int); idb
// _DWORD __cdecl nna_wait_done(int, int); weak

//-------------------------------------------------------------------------
// Data declarations

_DWORD hd_wt_bs_ew[63] =
{
  11634,
  3264,
  0,
  0,
  0,
  1,
  9,
  128,
  0,
  25,
  192,
  0,
  97,
  256,
  0,
  113,
  384,
  1,
  545,
  576,
  0,
  581,
  672,
  0,
  743,
  768,
  0,
  779,
  960,
  1,
  1643,
  1216,
  0,
  1707,
  1344,
  0,
  1995,
  1472,
  0,
  2059,
  1728,
  1,
  3787,
  2112,
  0,
  3931,
  2304,
  0,
  4579,
  2496,
  0,
  4723,
  2880,
  0,
  5107,
  3392,
  0,
  9715,
  3904,
  0,
  9759,
  3920,
  0
}; // idb
_DWORD recip_kernel_size[16] =
{
  65536,
  32768,
  21845,
  16384,
  13107,
  10922,
  9362,
  8192,
  31744,
  30720,
  30037,
  29696,
  29286,
  29013,
  28818,
  28672
}; // idb
_DWORD sdp_cfg_offset_map[3] = { 36952, 36972, 36992 }; // idb
_DWORD sdp_rdma_offset_map[3] = { 32808, 32832, 32856 }; // idb
_DWORD sdp_alu_cfg_offset_map[3] = { 36956, 36976, 36996 }; // idb
_DWORD sdp_alu_src_offset_map[3] = { 36960, 36980, 37000 }; // idb
_DWORD sdp_mul_cfg_offset_map[3] = { 36964, 36984, 37016 }; // idb
_DWORD sdp_mul_src_offset_map[3] = { 36968, 36988, 37020 }; // idb


//----- (00000004) --------------------------------------------------------
int __fastcall nna_play_cfg_cvt(unsigned int a1, int a2)
{
  int v2; // r4
  unsigned int v3; // r5

  v2 = a2;
  v3 = a1;
  xregw(a1, *(_DWORD *)(a2 + 12));
  xregw(v3 + 4, *(_DWORD *)(v2 + 4));
  return xregw(v3 + 8, *(_DWORD *)(v2 + 8));
}

//----- (00000040) --------------------------------------------------------
int __fastcall nna_play_cfg_lut(int a1, _DWORD *a2)
{
  _DWORD *v2; // r4
  int v3; // r5
  unsigned int v4; // r1
  int v5; // r5
  unsigned int v6; // r1
  int v8; // [sp+0h] [bp-420h]

  v2 = a2;
  v3 = 0;
  xregw(0x9008u, 0x20000u);
  nna_get_bs_addr((unsigned int)(v2 + 1));
  do
  {
    v4 = *(&v8 + v3++);
    xregw(0x900Cu, v4);
  }
  while ( v3 != 65 );
  v5 = 0;
  nna_get_bs_addr((unsigned int)(v2 + 10));
  xregw(0x9008u, 0x30000u);
  do
  {
    v6 = *(&v8 + v5++);
    xregw(0x900Cu, v6);
  }
  while ( v5 != 257 );
  xregw(0x9010u, 32 * v2[21] | (v2[19] << 6) | v2[22] | 16 * v2[20]);
  xregw(0x9014u, (v2[24] << 8) | (v2[26] << 16) | v2[23]);
  xregw(0x9018u, v2[27]);
  xregw(0x901Cu, v2[28]);
  xregw(0x9020u, v2[29]);
  return xregw(0x9024u, v2[30]);
}

//----- (00000150) --------------------------------------------------------
int __fastcall nna_play_cfg_sdp(int a1, _DWORD *a2, int *a3)
{
  int v3; // r6
  int v4; // r10
  _DWORD *v5; // r4
  int v6; // r5
  int v7; // r0
  int v8; // r11
  int v9; // r8
  bool v10; // zf
  int v11; // lr
  int v12; // r0
  int v13; // r7
  _BOOL4 v14; // r0
  signed int v15; // r9
  int result; // r0
  signed int v17; // r10
  int v18; // r9
  signed int v19; // r1
  _BOOL4 v20; // r6
  int v21; // [sp+0h] [bp-30h]
  int v22; // [sp+4h] [bp-2Ch]

  v3 = a1;
  v4 = *a2;
  v5 = a2;
  if ( *a2 )
  {
    v6 = a2[2];
    if ( v6 != 1 )
      v6 = a2[3] == 1;
  }
  else
  {
    v6 = 0;
  }
  v7 = a2[5];
  v8 = a2[3];
  v9 = a2[2];
  v11 = v7 - 1;
  v10 = v7 == 1;
  v21 = *a3;
  v12 = v7 - 3;
  if ( !v10 )
    v11 = 1;
  v22 = a2[8];
  v13 = a2[2] & 1;
  v14 = v12 == 0;
  v15 = a2[4];
  if ( v8 & 1 && v9 & 1 )
    v13 = 2;
  result = xregw(
             sdp_cfg_offset_map[v3],
             (v4 == 0) | 4 * a2[1] | (v11 << 6) | 32 * v14 | 16 * (v8 == 2) | 2 * (a2[2] == 2));
  if ( v4 )
  {
    v17 = v15;
    v10 = v15 == 0;
    v18 = v15 - 2;
    if ( !v10 )
      v17 = 1;
    xregw(sdp_rdma_offset_map[v3], 8 * v22 | 32 * v21 | 16 * (v18 == 0) | v6 & v17 ^ 1 | 2 * v13);
    if ( v3 == 2 )
    {
      if ( v5[11] )
        v19 = 0;
      else
        v19 = 2;
      result = xregw(0x9084u, v17 | v19);
      if ( v9 != 2 )
      {
        result = xregw(0x9088u, v5[9]);
        if ( v5[11] )
          result = nna_play_cfg_cvt(0x908Cu, (int)(v5 + 11));
      }
    }
    else
    {
      result = xregw(sdp_alu_cfg_offset_map[v3], (*((_WORD *)v5 + 12) << 8) & 0x3F00 | v17);
      if ( v9 != 2 )
        result = xregw(sdp_alu_src_offset_map[v3], v5[9]);
    }
    if ( !v5[3] )
    {
      xregw(sdp_mul_cfg_offset_map[v3], (*((_WORD *)v5 + 14) << 8) & 0xFF00);
      result = xregw(sdp_mul_src_offset_map[v3], v5[10]);
    }
    v20 = v3 == 2;
    if ( v8 == 2 )
      v20 = 0;
    if ( v20 )
    {
      if ( v5[15] )
        result = nna_play_cfg_cvt(0x90A0u, (int)(v5 + 15));
    }
  }
  return result;
}

//----- (00000398) --------------------------------------------------------
int __fastcall nna_play_conv(unsigned int *a1)
{
  unsigned int *v1; // r4
  int v2; // r6
  unsigned int v3; // r5
  unsigned int v4; // r1
  unsigned int v5; // r1
  unsigned int v6; // r0
  int v7; // r1
  int v8; // r3
  unsigned int v9; // r3
  unsigned int v10; // r1
  bool v11; // zf
  unsigned int v12; // r1

  v1 = a1;
  nna_get_engine();
  v2 = nna_get_fm_addr(v1[2]);
  nna_get_fm_addr(v1[20]);
  v3 = nna_get_wt_addr(v1[11]);
  xregw(0x500Cu, 0);
  xregw(0x600Cu, 0);
  xregw(0x400Cu, v1[49] << 16);
  xregw(0x4010u, v1[41]);
  xregw(0x4014u, (v1[5] - 1) | ((v1[6] + v1[46] - 1) << 16));
  xregw(0x4018u, v1[7] - 1);
  if ( v1[41] )
    v4 = 2;
  else
    v4 = 0;
  xregw(0x4020u, v4);
  xregw(0x4024u, v1[57] - 1);
  if ( v1[10] )
  {
    v5 = 0;
    v6 = 16424;
  }
  else
  {
    xregw(0x4028u, 1u);
    v5 = v3;
    v6 = 16440;
  }
  xregw(v6, v5);
  if ( v1[41] )
  {
    xregw(0x402Cu, (v1[30] - 1) << 16);
    v8 = v1[29] * v1[7] - 1;
    v7 = v1[25] - 1;
  }
  else
  {
    xregw(0x402Cu, (v1[29] - 1) | ((v1[30] - 1) << 16));
    v7 = v1[25] - 1;
    v8 = v1[7] - 1;
  }
  xregw(0x4030u, v8 | (v7 << 16));
  xregw(0x4034u, v1[13]);
  xregw(0x403Cu, (v1[23] - 1) | ((v1[24] - 1) << 16));
  xregw(0x4040u, v1[25] - 1);
  xregw(0x4044u, v1[23] * v1[24] - 1);
  xregw(0x4048u, v1[53]);
  xregw(0x404Cu, (v1[33] - 1) | ((v1[34] - 1) << 16));
  xregw(0x4050u, (v1[31] - 1) | ((v1[32] - 1) << 16));
  xregw(0x4054u, v1[35] | (v1[37] << 16));
  xregw(0x4058u, 0);
  xregw(0x405Cu, (v1[48] - 1) | ((v1[47] - 1) << 16));
  xregw(0x4060u, 0);
  xregw(0x3008u, 0x10001u);
  xregw(0x3014u, (v1[49] << 24) | (v1[52] << 28) | (v1[50] << 20) | (v1[49] << 16));
  v10 = v1[41];
  v11 = v10 == 0;
  if ( v10 )
    v9 = v1[42];
  else
    v10 = 1052672;
  if ( !v11 )
    v10 |= v9 << 8;
  xregw(0x3018u, v10);
  xregw(0x304Cu, 1u);
  xregw(0x301Cu, (v1[5] - 1) | ((v1[6] - 1) << 16));
  xregw(0x3020u, v1[7] - 1);
  xregw(0x3024u, (v1[5] - 1) | ((v1[6] - 1) << 16));
  xregw(0x302Cu, v1[1]);
  xregw(0x3034u, v2 & 0xFFFFFFF8);
  if ( !v1[41] )
    xregw(0x3028u, v2 & 7);
  xregw(0x3040u, v1[8]);
  xregw(0x3048u, v1[9]);
  xregw(0x304Cu, 1u);
  xregw(0x3058u, 0);
  xregw(0x3060u, v1[57] - 1);
  xregw(0x3068u, 0);
  xregw(0x306Cu, v1[7] * v1[29] * v1[30] - 1);
  xregw(0x3070u, v1[25] - 1);
  xregw(0x3074u, v1[10]);
  xregw(0x307Cu, v3);
  xregw(0x3080u, v1[13]);
  xregw(0x3098u, v1[54]);
  v12 = v1[54];
  if ( v12 )
  {
    xregw(0x309Cu, v1[55]);
    xregw(0x30A0u, v1[56]);
    xregw(0x30ACu, 1u);
    v12 = 1;
  }
  xregw(0x30A4u, v12);
  xregw(0x30B0u, (v1[33] - 1) | ((v1[34] - 1) << 16));
  xregw(0x30B4u, (v1[37] << 16) | (v1[38] << 24) | v1[35] | (v1[36] << 8));
  xregw(0x30B8u, 0);
  return xregw(0x30BCu, (v1[48] - 1) | ((v1[47] - 1) << 16));
}

//----- (00000804) --------------------------------------------------------
int __fastcall nna_play_sdp(_DWORD *a1)
{
  _DWORD *v1; // r4
  int *v2; // r10
  int *v3; // r8
  _DWORD *v4; // r11
  _DWORD *v5; // r9
  _DWORD *v6; // r7
  int v7; // r6
  _BOOL4 v8; // r5
  unsigned int v9; // r1
  unsigned int v10; // r0
  unsigned int v11; // r0
  unsigned int v12; // r0
  unsigned int v13; // r0
  unsigned int v14; // r0
  int *v16; // [sp+0h] [bp-30h]
  _BOOL4 v17; // [sp+4h] [bp-2Ch]

  v1 = a1;
  v2 = a1 + 19;
  v16 = a1 + 10;
  v3 = a1 + 28;
  v4 = a1 + 53;
  v5 = a1 + 72;
  v6 = a1 + 91;
  nna_get_engine();
  nna_get_fm_addr(v1[2]);
  nna_get_fm_addr(v1[38]);
  nna_get_bs_addr(v1[11]);
  nna_get_fm_addr(v1[20]);
  nna_get_fm_addr(v1[29]);
  v7 = v1[1];
  v8 = v1[1] == 2;
  v17 = v1[37] == 2;
  xregw(0x8070u, v8);
  v9 = v7 - 2;
  if ( v7 != 2 )
    v9 = 1;
  xregw(0x8074u, v9);
  xregw(0x800Cu, v1[5] - 1);
  xregw(0x8010u, v1[6] - 1);
  xregw(0x8014u, v1[7] - 1);
  if ( v1[1] == 1 )
  {
    v10 = nna_get_fm_addr(v1[2]);
    xregw(0x8018u, v10);
    xregw(0x8020u, v1[8]);
    xregw(0x8024u, v1[9]);
  }
  if ( v1[37] == 1 )
  {
    v11 = nna_get_fm_addr(v1[38]);
    xregw(0x9048u, v11);
    xregw(0x9050u, v1[44]);
    xregw(0x9054u, v1[45]);
    xregw(0x90B4u, 1u);
  }
  if ( v1[10] == 1 )
  {
    v12 = nna_get_bs_addr(v1[11]);
    xregw(0x802Cu, v12);
    xregw(0x8034u, v1[17]);
    xregw(0x8038u, v1[18]);
    xregw(0x803Cu, 0);
  }
  if ( v1[19] == 1 )
  {
    v13 = nna_get_fm_addr(v1[20]);
    xregw(0x8044u, v13);
    xregw(0x804Cu, v1[26]);
    xregw(0x8050u, v1[27]);
    xregw(0x8054u, 0);
  }
  if ( v1[28] == 1 )
  {
    v14 = nna_get_fm_addr(v1[29]);
    xregw(0x805Cu, v14);
    xregw(0x8064u, v1[35]);
    xregw(0x8068u, v1[36]);
    xregw(0x806Cu, 0);
  }
  xregw(0x903Cu, v1[5] - 1);
  xregw(0x9040u, v1[6] - 1);
  xregw(0x9044u, v1[7] - 1);
  xregw(0x90B0u, v8 | 2 * v17);
  xregw(0x90BCu, v1[47]);
  nna_play_cfg_cvt(0x90C0u, (int)(v1 + 110));
  nna_play_cfg_sdp(0, v4, v16);
  nna_play_cfg_sdp(1, v5, v2);
  return nna_play_cfg_sdp(2, v6, v3);
}

//----- (00000AA8) --------------------------------------------------------
int __fastcall nna_play_pdp(_DWORD *a1)
{
  _DWORD *v1; // r4
  unsigned int v2; // r7
  unsigned int v3; // r0
  int v4; // r6
  unsigned int v5; // r5

  v1 = a1;
  v2 = nna_get_fm_addr(a1[2]);
  v3 = nna_get_fm_addr(v1[11]);
  v4 = v1[1];
  v5 = v3;
  if ( v4 == 1 )
  {
    xregw(0xA00Cu, v1[5] - 1);
    xregw(0xA010u, v1[6] - 1);
    xregw(0xA014u, v1[7] - 1);
    xregw(0xA01Cu, v2);
    xregw(0xA024u, v1[8]);
    xregw(0xA028u, v1[9]);
    xregw(0xA02Cu, 1u);
    xregw(0xA038u, (v1[20] - 1) | 16 * (v1[22] - 1));
    xregw(0xA03Cu, v1[24]);
    xregw(0xB068u, v1[8]);
    xregw(0xB06Cu, v1[9]);
  }
  else
  {
    v4 = 0;
    xregw(0xA018u, 0);
  }
  xregw(0xB00Cu, v1[5] - 1);
  xregw(0xB010u, v1[6] - 1);
  xregw(0xB014u, v1[7] - 1);
  xregw(0xB018u, v1[14] - 1);
  xregw(0xB01Cu, v1[15] - 1);
  xregw(0xB020u, v1[16] - 1);
  xregw(0xB024u, v1[19] | 16 * v4);
  xregw(0xB034u, ((v1[22] - 1) << 16) | ((v1[23] - 1) << 20) | (v1[20] - 1) | ((v1[21] - 1) << 8));
  if ( !v1[19] )
  {
    xregw(0xB038u, recip_kernel_size[v1[20] - 1 + 8 * (v1[30] == 2)]);
    xregw(0xB03Cu, recip_kernel_size[v1[21] - 1 + 8 * (v1[30] == 2)]);
  }
  xregw(0xB040u, (v1[25] << 8) | (v1[27] << 12) | v1[24] | 16 * v1[26]);
  xregw(0xB044u, 0);
  xregw(0xB048u, 0);
  xregw(0xB04Cu, 0);
  xregw(0xB050u, 0);
  xregw(0xB054u, 0);
  xregw(0xB058u, 0);
  xregw(0xB05Cu, 0);
  xregw(0xB070u, v5);
  xregw(0xB078u, v1[17]);
  xregw(0xB07Cu, v1[18]);
  xregw(0xB080u, v1[10]);
  return xregw(0xB084u, 0);
}

//----- (00000D70) --------------------------------------------------------
int __fastcall nna_play_bdma(int a1)
{
  int v1; // r4
  unsigned int v2; // r6
  unsigned int v3; // r5

  v1 = a1;
  v2 = nna_get_fm_addr(*(_DWORD *)(a1 + 8));
  v3 = nna_get_fm_addr(*(_DWORD *)(v1 + 44));
  printf("\n# +++nna_bdmacpy %x<--%x\tsize:%d", v3, v2, *(_DWORD *)(v1 + 80));
  xregw(0x10000u, v2);
  xregw(0x10008u, v3);
  xregw(0x10010u, (*(_DWORD *)(v1 + 80) >> 3) - 1);
  xregw(0x10014u, 3u);
  xregw(0x10030u, 1u);
  xregw(0x10034u, 1u);
  xreg_wait(0x100Cu, 0x40u, 0x40u);
  xregw(0x100Cu, 0xFFFFFFFF);
  return printf("\n# ---nna_bdmacpy %x<--%x\tsize:%d", v3, v2, *(_DWORD *)(v1 + 80));
}

//----- (00000E58) --------------------------------------------------------
int __fastcall nna_play_nms(unsigned int *a1)
{
  unsigned int *v1; // r4
  unsigned int v2; // r5
  unsigned int v3; // r10
  unsigned int v4; // r3
  int v5; // r1
  unsigned int v6; // r3
  int v7; // r1

  v1 = a1;
  v2 = nna_get_fm_addr(a1[2]);
  v3 = nna_get_fm_addr(v1[11]);
  xreg_wait(0x300Cu, 1u, 1u);
  xregw(0x10000u, v2);
  xregw(0x10008u, 0);
  v4 = v1[19];
  v5 = v4 + 31;
  if ( (signed int)(v4 + 31) < 0 )
    v5 = v4 + 62;
  xregw(0x10010u, (v5 & 0xFFFFFFE0) - 1);
  xregw(0x10014u, 1u);
  xregw(0x10030u, 1u);
  xregw(0x10034u, 1u);
  xreg_wait(0x100Cu, 0x40u, 0x40u);
  xregw(0x100Cu, 0xFFFFFFFF);
  xregw(0x1044u, v1[20]);
  xregw(0x1048u, v1[21] | 0x640000);
  xregw(0x104Cu, v1[19]);
  xregw(0x1040u, 1u);
  xreg_wait(0x1040u, 1u, 0);
  v1[22] = xregr(0x1050u);
  xregw(0x10000u, 0);
  xregw(0x10008u, v3);
  v6 = v1[22];
  v7 = v6 + 31;
  if ( (signed int)(v6 + 31) < 0 )
    v7 = v6 + 62;
  xregw(0x10010u, (v7 & 0xFFFFFFE0) - 1);
  xregw(0x10014u, 2u);
  xregw(0x10030u, 1u);
  xregw(0x10034u, 1u);
  xreg_wait(0x100Cu, 0x40u, 0x40u);
  return xregw(0x100Cu, 0xFFFFFFFF);
}

//----- (00000FF8) --------------------------------------------------------
int __fastcall nna_play_lsc(_DWORD *a1)
{
  _DWORD *v1; // r4
  unsigned int v2; // r8
  unsigned int v3; // r7
  unsigned int v4; // r9

  v1 = a1;
  v2 = nna_get_fm_addr(a1[2]);
  v3 = nna_get_fm_addr(v1[11]);
  v4 = nna_get_fm_addr(v1[20]);
  if ( v1[35] )
  {
    xregw(0x3004u, 0);
    nna_mean_cfg(v1[36], 0, 0, 0);
    xregw(0x3004u, 1u);
    nna_mean_cfg(v1[36], 0, 0, 0);
  }
  if ( v1[31] )
  {
    xregw(0x1014u, 0x30000u);
    xregw(0x1018u, v1[30] | (hd_wt_bs_ew[3 * v1[31] + 1] << 16));
    xregw(0x1030u, v1[28] | (v1[29] << 16));
    xregw(0x1034u, 20 * v1[31] - 20);
    xregw(0x1038u, hd_wt_bs_ew[3 * v1[31]]);
    xregw(0x103Cu, hd_wt_bs_ew[3 * v1[31] + 1]);
    if ( hd_wt_bs_ew[3 * v1[31] + 2] )
      xregw(0x101Cu, v4);
  }
  xregw(0x1020u, v2);
  return xregw(0x1024u, v3);
}

//----- (00001150) --------------------------------------------------------
int __fastcall nna_play_clean_producer(unsigned int a1)
{
  unsigned int v1; // r5
  unsigned int v2; // r0
  unsigned __int16 v3; // r4

  v1 = a1;
  v2 = xregr(a1);
  v3 = v2;
  xregw(v1, v2 >> 16);
  return v3;
}

//----- (00001180) --------------------------------------------------------
int __fastcall nna_play_set_producer(int a1)
{
  int v1; // r4
  int result; // r0
  _DWORD *v3; // r4

  v1 = a1;
  result = nna_get_engine();
  v3 = *(_DWORD **)(v1 + 24);
  if ( v3[22] )
  {
    nna_play_clean_producer(0x7004u);
    nna_play_clean_producer(0x5004u);
    nna_play_clean_producer(0x6004u);
    nna_play_clean_producer(0x4004u);
    result = nna_play_clean_producer(0x3004u);
  }
  if ( v3[80] )
  {
    nna_play_clean_producer(0x9004u);
    result = nna_play_clean_producer(0x8004u);
  }
  if ( v3[194] )
  {
    nna_play_clean_producer(0xB004u);
    result = nna_play_clean_producer(0xA004u);
  }
  return result;
}

//----- (0000120C) --------------------------------------------------------
int __fastcall nna_play_set_enable(int result)
{
  _DWORD *v1; // r4

  v1 = *(_DWORD **)(result + 24);
  if ( v1[194] )
  {
    if ( v1[195] == 1 )
      xregw(0xA008u, 1u);
    result = xregw(0xB008u, 1u);
  }
  if ( v1[80] )
  {
    if ( v1[81] == 1 || v1[99] == 1 || v1[90] == 1 || v1[108] == 1 )
      xregw(0x8008u, 1u);
    result = xregw(0x9038u, 1u);
  }
  if ( v1[22] )
  {
    while ( !xregr(0x300Cu) )
      ;
    xregw(0x7008u, 1u);
    xregw(0x5008u, 1u);
    xregw(0x6008u, 1u);
    xregw(0x4008u, 1u);
    result = xregw(0x3010u, 1u);
  }
  return result;
}

//----- (000012FC) --------------------------------------------------------
int __fastcall nna_play_wait_done(int a1)
{
  _BYTE *v1; // r5
  _DWORD *v2; // r4
  signed int v3; // r1

  v1 = (_BYTE *)a1;
  v2 = *(_DWORD **)(a1 + 24);
  nna_get_engine();
  v3 = v2[194];
  if ( v3 )
    v3 = 16;
  if ( v2[80] )
    v3 |= 1u;
  if ( v2[22] )
    v3 |= 0x150000u;
  return nna_wait_done(v3 << *v1, v3 << *v1);
}
// 1844: using guessed type _DWORD __cdecl nna_wait_done(int, int);

//----- (00001350) --------------------------------------------------------
int __fastcall dump_group(unsigned __int8 *a1)
{
  unsigned __int8 *v1; // r4
  int v2; // r1

  v1 = a1;
  printf("\n GROUP ");
  printf("\n id                  :%d", *v1);
  printf("\n rdma_id             :%d", v1[1]);
  printf("\n active              :%d", v1[2]);
  printf("\n events              :%d", v1[3]);
  printf("\n roi_index           :%d", v1[4]);
  printf("\n is_rdma_needed      :%d", v1[5]);
  printf("\n pending             :%d", v1[6]);
  printf("\n lut_index           :%d", *((_DWORD *)v1 + 2));
  printf("\n programming         :%d", v1[12]);
  return printf("\n start_time          :%d", v2, *((_QWORD *)v1 + 2));
}

//----- (00001440) --------------------------------------------------------
int __fastcall nna_play_run(int result)
{
  int v1; // r4

  v1 = result;
  if ( *(_DWORD *)(result + 88) )
    result = nna_play_conv((unsigned int *)(result + 88));
  if ( *(_DWORD *)(v1 + 320) )
    result = nna_play_sdp((_DWORD *)(v1 + 320));
  if ( *(_DWORD *)(v1 + 776) )
    result = nna_play_pdp((_DWORD *)(v1 + 776));
  return result;
}

//----- (00001494) --------------------------------------------------------
int __fastcall nna_group_run(int a1)
{
  int v1; // r4
  int v2; // r5

  v1 = a1;
  v2 = *(_DWORD *)(a1 + 24);
  nna_play_set_producer(a1);
  nna_play_run(v2);
  nna_play_set_enable(v1);
  return nna_play_wait_done(v1);
}

//----- (000014CC) --------------------------------------------------------
int __fastcall nna_set_group_id(int a1)
{
  int v1; // r4
  int result; // r0

  v1 = a1;
  result = nna_get_engine();
  if ( v1 )
    *(_DWORD *)(result + 4) = 1;
  else
    *(_DWORD *)(result + 4) = 0;
  return result;
}

//----- (000014F8) --------------------------------------------------------
int __fastcall nna_play(int a1)
{
  int v1; // r5
  int v2; // r0
  int v3; // r4
  int v4; // r0
  int result; // r0

  v1 = a1;
  v2 = nna_get_engine();
  v3 = v2;
  v4 = *(_DWORD *)(v2 + 4);
  *(_DWORD *)(v3 + 32 * v4 + 56) = v1;
  result = nna_group_run(v3 + 32 * (v4 + 1));
  *(_DWORD *)(v3 + 4) = ((unsigned __int8)*(_DWORD *)(v3 + 4) + 1) & 1;
  return result;
}

// ALL OK, 18 function(s) have been successfully decompiled
